-- ===========================================================================
-- 0001 : one database, and the conventions every later migration follows
-- ---------------------------------------------------------------------------
-- MySQL has no schemas-inside-a-database: a schema *is* a database. The
-- per-service split that PostgreSQL would express as seven schemas was
-- originally expressed here as seven databases plus one for the shared read
-- views. Everything now lives in a single database instead, and the ownership
-- boundary is carried by a prefix on the table name:
--
--   identity_*    -> User Service      (login, profile, roles)
--   catalog_*     -> Course Service    (course + lesson structure)
--   content_*     -> Content Service   (articles, video URL metadata)
--   progress_*    -> Progress Service  (tracking what a learner has watched)
--   assessment_*  -> Quiz Service      (quizzes, questions, attempts)
--   search_*      -> Search Service    (denormalised, indexed search documents)
--   analytics_*   -> Analytics Service (raw behaviour events + rollups)
--   v_*           -> shared read views; owned by nobody
--   platform_*    -> the migration ledger
--
-- Each service is still the only writer to its own tables. Cross-service reads
-- go through the v_ views (migration 0009) or over HTTP. The rule is the same
-- one it always was; only its expression changed, from a database boundary the
-- server enforced to a naming convention it does not.
--
-- Why give that up: shared hosting. On cPanel every database name is prefixed
-- with the account name, so `catalog` becomes `noshadal_catalog` and eight
-- databases mean eight names to configure, eight sets of grants to click
-- through by hand, and eight entries against a plan's database quota. With one
-- database the name appears once, in the connection string, and every
-- statement below is written unqualified so it does not care what that name is.
--
-- What that costs is per-service GRANTs: the server can no longer stop the
-- Quiz Service writing to identity_users, because a grant covers a database or
-- a named table, and the services all connect as one user regardless. That
-- isolation was already notional here - see migrations/optional/ for the
-- per-service users, which stay available where the host allows them.
--
-- ---------------------------------------------------------------------------
-- Conventions used throughout, stated once here rather than repeated:
--
-- 1. IDS are CHAR(36) CHARACTER SET ascii, defaulted to (UUID()).
--    ascii rather than utf8mb4 because a utf8mb4 CHAR(36) reserves 144 bytes
--    per value; a uuid only ever contains hex and hyphens. Every foreign key
--    column repeats the same charset, because InnoDB refuses a foreign key
--    between columns whose character sets differ.
--
--    The cost of a random uuid primary key is index locality: inserts scatter
--    across the B-tree instead of appending. The append-heavy log tables
--    (analytics_events, search_query_log) use BIGINT AUTO_INCREMENT instead,
--    for exactly that reason.
--
-- 2. TIMESTAMPS are DATETIME(3) defaulted to (UTC_TIMESTAMP(3)), never
--    TIMESTAMP and never CURRENT_TIMESTAMP.
--
--    DATETIME because TIMESTAMP cannot represent a date past 2038-01-19.
--    UTC_TIMESTAMP because CURRENT_TIMESTAMP returns the *session* time zone -
--    so a client connected with time_zone='+05:30' would silently write local
--    time into a column every other client reads as UTC. UTC_TIMESTAMP is
--    immune to that. For the same reason updated_at is maintained by a trigger
--    rather than by ON UPDATE CURRENT_TIMESTAMP, which has the same session
--    dependency.
--
--    Clients should still connect with time_zone='+00:00'. The defaults above
--    mean forgetting is not corrupting.
--
-- 3. TEXT COLUMNS are utf8mb4 with the server default collation
--    (utf8mb4_0900_ai_ci), which is case- and accent-insensitive. That is what
--    makes identity_users.email behave like PostgreSQL's citext for free:
--    Ada@x.test and ada@x.test collide on the unique index.
--
--    Columns holding a digest or a token are the exception - they are declared
--    ascii/ascii_bin so comparison is exact and byte-for-byte.
--
-- 4. ENUMS are declared inline per column. MySQL has no CREATE TYPE, so the
--    same value set is repeated where it is used; the sets are listed in
--    docs/SCHEMA.md so a change can be applied everywhere it appears.
-- ===========================================================================

-- Nothing here creates a database. Every migration runs against whichever
-- database the connection already points at, which is what makes the schema
-- portable to hosting where you cannot issue CREATE DATABASE at all: on
-- cPanel the database is created through the control panel, arrives with an
-- account prefix (noshadal_learning), and the name only ever appears in the
-- connection string.
--
-- scripts/reset.sh creates it for local development.

-- The migration ledger. scripts/migrate.sh records a checksum per applied file
-- and refuses to run if a file that already ran has changed.
CREATE TABLE IF NOT EXISTS platform_schema_migrations (
  filename   VARCHAR(255) CHARACTER SET ascii NOT NULL PRIMARY KEY,
  checksum   CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  applied_at DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP(3))
) ENGINE=InnoDB;
