-- ===========================================================================
-- Seed 21 : quizzes for the Dart course
--
-- One per level. Unlike the other language courses there is no scratchpad on
-- these pages: the playground cannot run Dart, and an HTML scratchpad under a
-- Dart question would be worse than none. starter_for_course() in the website
-- returns null for this course for that reason.
--
-- Generated by scratchpad/gen/build_dart_quizzes.py, which also checks that
-- every single_choice has exactly one correct option and every
-- multiple_choice has at least two. A quiz that cannot be passed is not
-- obvious from the SQL.
-- ===========================================================================

INSERT INTO assessment_quizzes
  (id, course_id, lesson_id, title, description, pass_percent, time_limit_seconds,
   max_attempts, shuffle_questions, shuffle_options, show_answers, status)
VALUES
  ('f0000001-0000-4000-8000-000000000020',
   'c0000001-0000-4000-8000-00000000000b', 'e0000001-0000-4000-8000-00000000008d',
   'Level 1 Check: Types, Null Safety and Collections',
   'What the type system knows, what ? and ! actually do, and how Iterable behaves. Every one of these can be settled by running four lines of Dart.',
   60, 600, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000021',
   'c0000001-0000-4000-8000-00000000000b', 'e0000001-0000-4000-8000-00000000008e',
   'Level 2 Check: Classes, Generics and Failure',
   'Constructors, equality, mixins and class modifiers, and which failures are yours to catch.',
   60, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000022',
   'c0000001-0000-4000-8000-00000000000b', 'e0000001-0000-4000-8000-00000000008f',
   'Level 3 Check: Async, Streams and Patterns',
   'The event loop, what await really suspends, streams that close, and matching on shape.',
   70, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000023',
   'c0000001-0000-4000-8000-00000000000b', 'e0000001-0000-4000-8000-000000000090',
   'Expert Exam: Dart',
   'Isolates, where the time goes, and how an application is arranged.',
   70, 1500, 3, 1, 1, 1, 'published')
ON DUPLICATE KEY UPDATE
  title = VALUES(title), description = VALUES(description),
  pass_percent = VALUES(pass_percent), status = VALUES(status);

INSERT INTO assessment_questions
  (id, quiz_id, kind, prompt, explanation, points, `position`, correct_text)
VALUES
  -- Level 1 Check: Types, Null Safety and Collections
  ('a1000001-0000-4000-8000-000000000295', 'f0000001-0000-4000-8000-000000000020', 'single_choice',
   'What is the difference between `final` and `const` on a list?',
   '`final` fixes the binding: the variable cannot be reassigned, but a growable list behind it can still be added to. `const` fixes the value at compile time - the list itself is immutable, and two `const` literals with the same contents are the same object.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-000000000296', 'f0000001-0000-4000-8000-000000000020', 'single_choice',
   'What does the `!` in `scores[''ada'']!` do?',
   'It asserts that the value is not null, which changes the static type from `int?` to `int` and inserts a runtime check. It verifies nothing at compile time: if the value is null the program throws. Every `!` is a place the program can crash, and `?? 0` is usually both shorter and safer.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-000000000297', 'f0000001-0000-4000-8000-000000000020', 'multiple_choice',
   'Which statements about `Iterable` methods such as `map` and `where` are true? Select all that apply.',
   'They are lazy: calling `map` does no work, and the callback runs when something iterates the result. That also means iterating twice runs it twice, which matters when the callback has a side effect or costs money. `toList()` performs the work once and keeps the answer. `sort`, by contrast, is a `List` method that mutates in place and returns nothing.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-000000000298', 'f0000001-0000-4000-8000-000000000020', 'single_choice',
   'A map lookup `stock[''plums'']` where the key is absent returns what?',
   '`null`. `Map`''s `[]` operator is declared to return `V?` for exactly this reason, which is why the compiler makes you deal with the absence. `stock[''plums''] ?? 0` supplies a default; `putIfAbsent` and `update` are the safe ways to write.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-000000000299', 'f0000001-0000-4000-8000-000000000020', 'true_false',
   '`late` on a field means the field is allowed to be null.',
   'False. `late` keeps the type non-nullable and moves the check to first use: reading the field before it is assigned throws a LateInitializationError. It is for a value that is definitely there but cannot be built in the constructor - `late final x = expensive()` is the common case, and it runs once on first read.',
   2, 5, NULL),

  -- Level 2 Check: Classes, Generics and Failure
  ('a1000001-0000-4000-8000-00000000029a', 'f0000001-0000-4000-8000-000000000021', 'single_choice',
   'You override `==` on a value class and leave `hashCode` alone. What breaks?',
   'Sets and map keys. Two objects that are `==` but have different hash codes land in different buckets, so a set keeps both and a map lookup misses one that is ''equal'' to the key you passed. Override the pair together - `Object.hash(a, b)` builds one from the same fields `==` compares.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-00000000029b', 'f0000001-0000-4000-8000-000000000021', 'single_choice',
   'What can a `factory` constructor do that a generative constructor cannot?',
   'Return an object it did not just create: a cached instance, an instance of a subclass, or the result of parsing. It is the standard home for validation that should fail loudly, because it may also throw before anything is built.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-00000000029c', 'f0000001-0000-4000-8000-000000000021', 'multiple_choice',
   'Which statements about `extends`, `implements` and `with` are true? Select all that apply.',
   '`extends` inherits implementation and there can be only one superclass. `implements` takes the interface only - every member has to be written again - and any class can serve as an interface. `with` mixes in members from a mixin, and a class can have several. `on` in a mixin declaration restricts what it can be applied to and lets the mixin call that type''s members.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-00000000029d', 'f0000001-0000-4000-8000-000000000021', 'single_choice',
   'What does marking a class `sealed` buy you?',
   'The compiler knows the complete list of subtypes, because they must be declared in the same library. A `switch` over that type is then checked for exhaustiveness, so adding a new subclass turns every switch that has not been updated into a compile error - which is precisely when you want to be told.',
   3, 4, NULL),

  ('a1000001-0000-4000-8000-00000000029e', 'f0000001-0000-4000-8000-000000000021', 'single_choice',
   'Which of these should you catch in ordinary application code?',
   '`FormatException` - bad input is an expected condition and the caller can react to it. `RangeError`, `TypeError` and a failed assertion are all bugs in your own code: catching them hides the defect rather than handling a situation. Dart splits the hierarchy into Exception and Error for exactly this reason.',
   3, 5, NULL),

  -- Level 3 Check: Async, Streams and Patterns
  ('a1000001-0000-4000-8000-00000000029f', 'f0000001-0000-4000-8000-000000000022', 'multiple_choice',
   'Which statements about `async` and `await` in Dart are true? Select all that apply.',
   'An async function returns its future as soon as it hits the first await, and the rest runs later. Completed futures resume on the microtask queue, which is drained before the next event (timer or I/O), so a flood of microtasks can starve a timer. None of it is parallel: it is all one thread, so a synchronous loop with no await blocks everything regardless of how many async keywords surround it.',
   3, 1, NULL),

  ('a1000001-0000-4000-8000-0000000002a0', 'f0000001-0000-4000-8000-000000000022', 'single_choice',
   'Three independent calls each take about 60ms. What is the difference between awaiting them one at a time and `Future.wait`?',
   'Awaiting in sequence costs the sum, about 180ms, because each call only starts when the one before it finishes. `Future.wait` starts all three and waits for the slowest, about 60ms. The catch is that it fails as soon as any one fails - wrap each future with `catchError` if you need every result regardless.',
   3, 2, NULL),

  ('a1000001-0000-4000-8000-0000000002a1', 'f0000001-0000-4000-8000-000000000022', 'single_choice',
   'Your program using a StreamController never exits, and prints no error. What is the most likely cause?',
   'The controller was never closed, so the `await for` over its stream is still waiting for events that will never come. `close()` is what ends the stream and lets the loop finish - it is the most common stream bug, and it is silent.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-0000000002a2', 'f0000001-0000-4000-8000-000000000022', 'single_choice',
   'What does `if (response case {''status'': final int status, ''body'': final String body})` do?',
   'It tests the shape and binds in one step: the branch runs only when response is a map with both keys and with values of those types, and inside it `status` and `body` are already the right types. It replaces a chain of is-checks, casts and null tests with one readable line.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-0000000002a3', 'f0000001-0000-4000-8000-000000000022', 'true_false',
   'Two records with the same field names and equal values are equal to each other.',
   'True. Records have structural equality, so `(name: ''Ada'', age: 36) == (name: ''Ada'', age: 36)` is true with nothing to write - unlike a class, where `==` is identity until you override it. That is what makes a record a good fit for returning two or three values, and a class still the right answer when the thing has a name and behaviour.',
   2, 5, NULL),

  -- Expert Exam: Dart
  ('a1000001-0000-4000-8000-0000000002a4', 'f0000001-0000-4000-8000-000000000023', 'multiple_choice',
   'Which statements about isolates are true? Select all that apply.',
   'Isolates have separate memory and separate event loops, so there is nothing shared to lock. They talk by messages, and a message is copied - which makes a very large payload a real cost on both sides. They are worth it for CPU-bound work; for I/O they are pointless, because a network or file call already yields to the event loop.',
   3, 1, NULL),

  ('a1000001-0000-4000-8000-0000000002a5', 'f0000001-0000-4000-8000-000000000023', 'single_choice',
   'Why is `text += ''x''` inside a loop so much slower than a StringBuffer?',
   'Strings are immutable, so every `+=` allocates a new string and copies the whole thing so far - which makes the loop quadratic in the length. A StringBuffer writes into one buffer that grows geometrically, and `join` does the same in one step for a list you already have.',
   3, 2, NULL),

  ('a1000001-0000-4000-8000-0000000002a6', 'f0000001-0000-4000-8000-000000000023', 'single_choice',
   'When does an `assert` actually run?',
   'Only when asserts are enabled - `dart run --enable-asserts`, or Flutter''s debug mode. `dart run` on its own does not enable them, and every release build strips them entirely. So an assert states a belief about your own code; anything that validates input from outside needs a real check and a thrown ArgumentError.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-0000000002a7', 'f0000001-0000-4000-8000-000000000023', 'single_choice',
   'A lookup inside a loop uses `bannedList.contains(word)`. What is the fix and why?',
   'Build a `Set` once outside the loop. `List.contains` is a linear scan, so the loop is quadratic; `Set.contains` hashes and is constant time. Choosing the right structure is worth more than any amount of tuning inside the loop - and hoisting the construction out of the loop is half the point.',
   3, 4, NULL),

  ('a1000001-0000-4000-8000-0000000002a8', 'f0000001-0000-4000-8000-000000000023', 'multiple_choice',
   'Which of these describe an application that stays easy to change? Select all that apply.',
   'The rules live in plain Dart with no framework imports, so they can be tested with a constructor call. They declare what they need as an interface and the implementation is handed in, which keeps the arrows pointing inward. An expected outcome is a sealed result type the caller must handle, not an exception it may ignore. Naming classes after patterns describes the mechanism rather than the problem, and ages badly.',
   3, 5, NULL)
ON DUPLICATE KEY UPDATE
  prompt = VALUES(prompt), explanation = VALUES(explanation),
  points = VALUES(points), `position` = VALUES(`position`);

DELETE FROM assessment_question_options
 WHERE question_id IN (
   SELECT id FROM assessment_questions
    WHERE quiz_id IN ('f0000001-0000-4000-8000-000000000020',
                      'f0000001-0000-4000-8000-000000000021',
                      'f0000001-0000-4000-8000-000000000022',
                      'f0000001-0000-4000-8000-000000000023'));

INSERT INTO assessment_question_options (question_id, body, is_correct, `position`)
SELECT v.question_id, v.body, v.is_correct, v.pos
  FROM (
    SELECT 'a1000001-0000-4000-8000-000000000295' AS question_id, 'final stops reassignment; const also makes the value immutable and shared' AS body, 1 AS is_correct, 1 AS pos
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000295', 'They are the same, and const is just the older spelling', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000295', 'const stops reassignment; final also freezes the contents', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000295', 'final works on locals and const only on fields', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000296', 'Changes the type from int? to int and throws at runtime if it is null', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000296', 'Converts the value to an int, parsing it if necessary', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000296', 'Tells the compiler to skip the null check entirely, with no runtime cost', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000296', 'Returns a default value when the key is missing', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000297', 'map does no work until the result is iterated', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000297', 'Iterating the same lazy chain twice runs the callback twice', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000297', 'toList() performs the work once and stores the result', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000297', 'map sorts the collection as a side effect', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000298', 'null, because operator [] on a Map returns V?', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000298', 'It throws a StateError, like firstWhere does', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000298', 'Zero, because int is the value type', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000298', 'It inserts the key with a default value and returns that', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000299', 'True', 0, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000299', 'False', 1, 2

    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029a', 'Sets keep duplicates and map lookups miss, because the hash no longer agrees with ==', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029a', 'Nothing: Dart derives hashCode from == automatically', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029a', 'The class can no longer be used with const', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029a', '== stops working and falls back to identity', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029b', 'Return an existing or a subclass instance rather than building a new one', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029b', 'Assign final fields after the body has run', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029b', 'Be declared const while still running arbitrary code', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029b', 'Be called without the class name', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029c', 'extends inherits the implementation, and a class has at most one superclass', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029c', 'implements takes only the interface, so every member must be provided again', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029c', 'A class can mix in several mixins with `with`', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029c', 'implements is how you inherit a superclass''s method bodies', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029d', 'The compiler knows every subtype, so a switch over it is checked for exhaustiveness', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029d', 'It prevents the class from being instantiated, like abstract', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029d', 'It makes every field final automatically', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029d', 'It hides the class from other libraries in the same package', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029e', 'FormatException from parsing input that came from outside', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029e', 'RangeError from indexing past the end of a list', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029e', 'TypeError from a null assertion that failed', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029e', 'AssertionError from an assert you wrote', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029f', 'An async function returns a Future immediately and continues after the await', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029f', 'Microtasks run before events such as timers and I/O', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029f', 'A long synchronous loop blocks the event loop even inside an async function', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000029f', 'await runs the awaited work on a second thread', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a0', 'Sequential costs about 180ms, Future.wait about 60ms, and Future.wait fails fast', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a0', 'They take the same time; Future.wait is only tidier', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a0', 'Future.wait runs them on separate isolates, so it is genuinely parallel', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a0', 'Future.wait is slower, because it has to collect the results', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a1', 'close() was never called on the controller, so the stream never ends', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a1', 'The stream was single-subscription and something listened twice', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a1', 'An error was thrown and swallowed by cancelOnError', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a1', 'await for cannot be used on a controller''s stream', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a2', 'Runs the branch only if response matches that shape, binding status and body', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a2', 'Casts response to a map and throws if it is not one', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a2', 'Compares response for equality with that literal map', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a2', 'Declares a new map with those two keys', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a3', 'True', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a3', 'False', 0, 2

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a4', 'Each isolate has its own memory, so no locking is needed', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a4', 'Messages between isolates are copied, so large payloads cost time', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a4', 'They help with CPU-bound work, not with I/O', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a4', 'Isolates share their heap, so you must synchronise access to it', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a5', 'Strings are immutable, so each += allocates and copies the whole string so far', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a5', '+= acquires a lock on the string each time round', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a5', 'StringBuffer runs the concatenation on another isolate', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a5', '+= is interpreted while StringBuffer is compiled', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a6', 'Only when asserts are enabled; they are stripped from release builds entirely', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a6', 'Always, in every mode, which is why they are safe for validating input', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a6', 'Only in AOT builds produced by dart compile', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a6', 'Whenever the enclosing function is async', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a7', 'Build a Set once outside the loop: Set.contains is constant time, List.contains is a scan', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a7', 'Sort the list first, because contains then uses a binary search', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a7', 'Move the loop to another isolate', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a7', 'Mark the list const so the lookup is compiled away', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a8', 'The domain rules import nothing beyond dart:core', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a8', 'Dependencies are declared as interfaces and passed in', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a8', 'Expected outcomes are a sealed result type the caller must handle', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a8', 'Classes are named after the pattern used, so CourseServiceManagerImpl', 0, 4
  ) v;

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-00000000000b');
CALL search_reindex_all();
