-- ===========================================================================
-- Seed 23 : quizzes for the Java course
--
-- One per level. Like the Dart course there is no scratchpad on these pages:
-- the playground cannot run Java, and an HTML scratchpad under a Java question
-- would be worse than none. starter_for_course() in the website returns null
-- for this course for that reason.
--
-- Generated by scratchpad/gen/build_java_quizzes.py, which also checks that
-- every single_choice has exactly one correct option and every
-- multiple_choice has at least two. A quiz that cannot be passed is not
-- obvious from the SQL.
-- ===========================================================================

INSERT INTO assessment_quizzes
  (id, course_id, lesson_id, title, description, pass_percent, time_limit_seconds,
   max_attempts, shuffle_questions, shuffle_options, show_answers, status)
VALUES
  ('f0000001-0000-4000-8000-000000000024',
   'c0000001-0000-4000-8000-00000000000c', 'e0000001-0000-4000-8000-00000000009d',
   'Level 1 Check: Types, References and Collections',
   'Primitives against references, what == really compares, and the collections. Every one of these can be settled by compiling five lines.',
   60, 600, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000025',
   'c0000001-0000-4000-8000-00000000000c', 'e0000001-0000-4000-8000-00000000009e',
   'Level 2 Check: Records, Generics and Exceptions',
   'The equals contract, what erasure costs you, and which failures are yours to catch.',
   60, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000026',
   'c0000001-0000-4000-8000-00000000000c', 'e0000001-0000-4000-8000-00000000009f',
   'Level 3 Check: Streams, Threads and Patterns',
   'Lazy pipelines, data races, virtual threads, and switch that cannot miss a case.',
   70, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000027',
   'c0000001-0000-4000-8000-00000000000c', 'e0000001-0000-4000-8000-0000000000a0',
   'Expert Exam: Java',
   'Reachability and leaks, where the time goes, and how an application is arranged.',
   70, 1500, 3, 1, 1, 1, 'published')
ON DUPLICATE KEY UPDATE
  title = VALUES(title), description = VALUES(description),
  pass_percent = VALUES(pass_percent), status = VALUES(status);

INSERT INTO assessment_questions
  (id, quiz_id, kind, prompt, explanation, points, `position`, correct_text)
VALUES
  -- Level 1 Check: Types, References and Collections
  ('a1000001-0000-4000-8000-0000000002a9', 'f0000001-0000-4000-8000-000000000024', 'single_choice',
   'Why does `==` sometimes appear to work on `Integer` and then stop?',
   'Java caches boxed Integers from -128 to 127, so two boxes of 100 are the same object and `==` is true by accident. At 1000 they are two objects and it is false. `==` on a reference always asks whether it is the same object - compare values with `equals`, or unbox to `int` first.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-0000000002aa', 'f0000001-0000-4000-8000-000000000024', 'single_choice',
   'A method takes a `List<String>` and does `values = new ArrayList<>()`. What does the caller see?',
   'Nothing. Java passes everything by value, and for an object that means the reference is copied - so the method can change the object the caller handed it (`values.add(...)` is visible), but reassigning the parameter only repoints the method''s own copy.',
   3, 2, NULL),

  ('a1000001-0000-4000-8000-0000000002ab', 'f0000001-0000-4000-8000-000000000024', 'multiple_choice',
   'Which statements about `String` in Java are true? Select all that apply.',
   'A String cannot be modified after construction, which is what makes it safe to share between threads and safe as a map key - its hash can never go stale. Identical literals are interned to one pooled object, which is why `==` on literals looks like it works. Building text in a loop with `+=` allocates and copies each time; StringBuilder is the answer.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-0000000002ac', 'f0000001-0000-4000-8000-000000000024', 'single_choice',
   '`map.get("missing")` on a `HashMap<String, Integer>` returns what?',
   'null. A missing key is not an error, which is why the read hands back null and why `getOrDefault` exists. Assigning that result to an `int` unboxes null and throws NullPointerException - one of the most common ways Java programs fail.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-0000000002ad', 'f0000001-0000-4000-8000-000000000024', 'true_false',
   '`List.of("a", "b")` returns a list you can add to.',
   'False. The `of` factories return immutable collections - `add` throws UnsupportedOperationException. That is usually what you want for a constant; wrap it in `new ArrayList<>(...)` when you genuinely need to modify a copy.',
   2, 5, NULL),

  -- Level 2 Check: Records, Generics and Exceptions
  ('a1000001-0000-4000-8000-0000000002ae', 'f0000001-0000-4000-8000-000000000025', 'single_choice',
   'You override `equals` on a class and leave `hashCode` alone. What breaks?',
   'Hash collections. Two objects that are `equals` but hash differently land in different buckets, so a HashSet keeps both and a HashMap lookup misses an entry that is ''equal'' to your key. Override them together - `Objects.hash(...)` over the same fields `equals` compares.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-0000000002af', 'f0000001-0000-4000-8000-000000000025', 'multiple_choice',
   'Which are true of a `record`? Select all that apply.',
   'A record generates the canonical constructor, the accessors, and equals/hashCode/toString from its components, which is exactly why it is the right shape for a map key. A compact constructor lets you validate and normalise before assignment. Its components are final - a record is shallowly immutable, so a record holding a mutable List still needs List.copyOf to be genuinely safe.',
   3, 2, NULL),

  ('a1000001-0000-4000-8000-0000000002b0', 'f0000001-0000-4000-8000-000000000025', 'single_choice',
   'Java''s generics are erased. Which of these is a consequence?',
   'At runtime `List<String>` is just `List`, so the type argument is unavailable: you cannot create `new T[]`, cannot ask `x instanceof List<String>`, and an unchecked cast compiles with a warning and fails later at the point of use rather than at the assignment.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-0000000002b1', 'f0000001-0000-4000-8000-000000000025', 'single_choice',
   'What does PECS tell you to write for a method that only reads numbers out of a list?',
   '`List<? extends Number>` - Producer Extends. The list produces Numbers for you to read, and accepts List<Integer> or List<Double> at the call site. You cannot add to it, because the actual list may be of a narrower type. `? super` is the consumer side, for a list you write into.',
   3, 4, NULL),

  ('a1000001-0000-4000-8000-0000000002b2', 'f0000001-0000-4000-8000-000000000025', 'single_choice',
   'Which of these should application code normally catch?',
   'IOException - a file that is missing or a connection refused is an expected condition the caller can react to, and the compiler makes you deal with it. NullPointerException and ArrayIndexOutOfBoundsException are programming mistakes, and OutOfMemoryError is an Error: catching any of those hides a defect rather than handling a situation.',
   3, 5, NULL),

  -- Level 3 Check: Streams, Threads and Patterns
  ('a1000001-0000-4000-8000-0000000002b3', 'f0000001-0000-4000-8000-000000000026', 'multiple_choice',
   'Which statements about streams are true? Select all that apply.',
   'Intermediate operations such as filter and map are lazy - the pipeline is built and nothing runs until a terminal operation asks. Elements then flow one at a time through every stage, which is what lets findFirst stop early. A stream is single-use: a second terminal operation throws IllegalStateException. And writing to a shared collection from a lambda is a race the moment the stream goes parallel; let collect build the result.',
   3, 1, NULL),

  ('a1000001-0000-4000-8000-0000000002b4', 'f0000001-0000-4000-8000-000000000026', 'single_choice',
   'Two threads run `counter++` a hundred thousand times each on a shared int. What happens?',
   'The total is usually less than two hundred thousand. `counter++` is three operations - read, add, write - and the two threads interleave inside it, so increments are lost. Worse, without synchronisation there is no guarantee either thread ever sees the other''s writes at all. The fixes are synchronized, an AtomicInteger, or not sharing mutable state.',
   3, 2, NULL),

  ('a1000001-0000-4000-8000-0000000002b5', 'f0000001-0000-4000-8000-000000000026', 'single_choice',
   'What do virtual threads (Java 21) change?',
   'Blocking becomes cheap. A virtual thread is scheduled by the JVM onto a small pool of carrier threads, and blocking one on I/O parks it instead of holding an OS thread - so a million of them is reasonable where a million platform threads is not. They change the cost of blocking, not the rules of sharing: a data race is still a data race.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-0000000002b6', 'f0000001-0000-4000-8000-000000000026', 'single_choice',
   'What does a `switch` over a sealed interface give you that an if-else chain does not?',
   'Exhaustiveness. The compiler knows the permitted subtypes, so it can tell whether every case is handled - no default branch needed, and adding a new subtype makes every incomplete switch stop compiling. That is the point: the compiler carries the list of cases instead of you.',
   3, 4, NULL),

  ('a1000001-0000-4000-8000-0000000002b7', 'f0000001-0000-4000-8000-000000000026', 'true_false',
   '`if (value instanceof String s)` makes `s` available everywhere in the method.',
   'False. The pattern variable is in scope only where the test is known to have passed - inside that if, or after an early return in the negative branch. That is the feature: it cannot be used where the type is not established, which is what the old test-then-cast could not guarantee.',
   2, 5, NULL),

  -- Expert Exam: Java
  ('a1000001-0000-4000-8000-0000000002b8', 'f0000001-0000-4000-8000-000000000027', 'multiple_choice',
   'Which of these cause a memory leak in Java? Select all that apply.',
   'A leak in a collected language is an object that stays reachable after it stops being useful. A static collection that only grows, a listener that is registered and never removed, and a ThreadLocal set on a pooled thread and never cleared are the three classic sources. A local variable going out of scope is the opposite - that is exactly what makes an object collectable.',
   3, 1, NULL),

  ('a1000001-0000-4000-8000-0000000002b9', 'f0000001-0000-4000-8000-000000000027', 'single_choice',
   'Why should a nested class be `static` unless it needs otherwise?',
   'A non-static inner class holds a hidden reference to the instance that created it, so handing one to a long-lived collection keeps that whole enclosing object alive. Marking it static removes the reference, which is why it is the right default - and why it is a standard source of leaks when it is not.',
   3, 2, NULL),

  ('a1000001-0000-4000-8000-0000000002ba', 'f0000001-0000-4000-8000-000000000027', 'single_choice',
   'Your benchmark loop runs much faster on its fifth round than its first. Why?',
   'The JIT. Java starts by interpreting bytecode and compiles the hot paths as it runs, so early iterations measure the interpreter and the compiler rather than the code. Warm up first, use the later rounds, keep the result so nothing can be optimised away - or use JMH, which handles all three properly.',
   3, 3, NULL),

  ('a1000001-0000-4000-8000-0000000002bb', 'f0000001-0000-4000-8000-000000000027', 'single_choice',
   'A loop calls `list.contains(value)` twenty thousand times on a twenty-thousand-element list. What is the fix?',
   'Build a HashSet once, outside the loop. `List.contains` is a linear scan, so the pair of loops is quadratic; `HashSet.contains` hashes and is effectively constant time. Choosing the right structure is worth more than any amount of tuning inside the loop.',
   3, 4, NULL),

  ('a1000001-0000-4000-8000-0000000002bc', 'f0000001-0000-4000-8000-000000000027', 'multiple_choice',
   'Which describe an application that stays easy to change? Select all that apply.',
   'The domain is plain Java that can be tested with a constructor call. It owns the interfaces it needs and the implementations are passed in, which keeps the dependency arrows pointing inward. Expected outcomes are a sealed result type the caller must handle, not an exception it may ignore. Naming classes after the pattern describes the mechanism rather than the problem, and ages badly.',
   3, 5, NULL)
ON DUPLICATE KEY UPDATE
  prompt = VALUES(prompt), explanation = VALUES(explanation),
  points = VALUES(points), `position` = VALUES(`position`);

DELETE FROM assessment_question_options
 WHERE question_id IN (
   SELECT id FROM assessment_questions
    WHERE quiz_id IN ('f0000001-0000-4000-8000-000000000024',
                      'f0000001-0000-4000-8000-000000000025',
                      'f0000001-0000-4000-8000-000000000026',
                      'f0000001-0000-4000-8000-000000000027'));

INSERT INTO assessment_question_options (question_id, body, is_correct, `position`)
SELECT v.question_id, v.body, v.is_correct, v.pos
  FROM (
    SELECT 'a1000001-0000-4000-8000-0000000002a9' AS question_id, 'Integers from -128 to 127 are cached, so small values share one object' AS body, 1 AS is_correct, 1 AS pos
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a9', '== unboxes automatically below 128 and compares numerically', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a9', 'The JIT replaces == with equals once the code is hot', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002a9', 'Small Integers are primitives and large ones are objects', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002aa', 'No change: reassigning the parameter only repoints the method''s copy', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002aa', 'The caller''s variable now points at the new list, because objects are by reference', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002aa', 'A compile error - parameters are implicitly final in Java', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002aa', 'The caller''s list is emptied but keeps its identity', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ab', 'A String cannot be changed after it is created', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ab', 'Two identical literals refer to the same pooled object', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ab', 'Building a string in a loop with += is quadratic', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ab', 'String.toUpperCase() modifies the string in place', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ac', 'null, which will throw if you assign it straight to an int', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ac', '0, because Integer defaults to zero', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ac', 'It throws NoSuchElementException', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ac', 'It inserts the key with a default value and returns that', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ad', 'True', 0, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ad', 'False', 1, 2

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ae', 'HashSet keeps duplicates and HashMap lookups miss', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ae', 'Nothing - the JVM derives hashCode from equals', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ae', 'The class can no longer be used in a List', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ae', 'equals stops being called and identity is used instead', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002af', 'equals and hashCode are generated from the components', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002af', 'A compact constructor can validate and normalise before assignment', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002af', 'Its components are final, so the record is shallowly immutable', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002af', 'A record can extend another class to share fields', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b0', 'You cannot write new T[] or test instanceof List<String> at runtime', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b0', 'Generic code is slower because every call is reflective', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b0', 'A List<String> and a List<Integer> are different classes at runtime', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b0', 'Generic types cannot be used as map keys', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b1', 'List<? extends Number>, because the list produces values you read', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b1', 'List<? super Number>, because the method consumes the list', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b1', 'List<Number>, because wildcards are only for generic classes', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b1', 'List<?>, because the element type does not matter when reading', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b2', 'IOException when reading a file that may not be there', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b2', 'NullPointerException, to keep the program running', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b2', 'ArrayIndexOutOfBoundsException, to guard a loop', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b2', 'OutOfMemoryError, to free some caches and retry', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b3', 'filter and map do nothing until a terminal operation runs', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b3', 'A stream can only be consumed once', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b3', 'Elements flow one at a time, so findFirst can stop early', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b3', 'forEach on a parallel stream is a safe way to fill an ArrayList', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b4', 'The total is usually short, because ++ is read-add-write and they interleave', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b4', 'The total is always correct: int writes are atomic in Java', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b4', 'The JVM throws ConcurrentModificationException', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b4', 'One thread blocks until the other finishes the loop', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b5', 'Blocking I/O becomes cheap, so simple blocking code scales', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b5', 'Shared mutable state becomes safe without synchronisation', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b5', 'CPU-bound work runs faster by using more cores', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b5', 'They replace synchronized with an automatic lock-free mode', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b6', 'The compiler checks every permitted subtype is handled', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b6', 'It runs faster, because switch compiles to a jump table', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b6', 'It automatically casts the value to Object first', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b6', 'It catches exceptions thrown inside the branches', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b7', 'True', 0, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b7', 'False', 1, 2

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b8', 'A static Map that entries are added to and never removed from', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b8', 'A listener registered on a long-lived object and never unregistered', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b8', 'A ThreadLocal set on a pooled thread and never cleared', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b8', 'A local variable going out of scope at the end of a method', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b9', 'A non-static inner class holds a hidden reference to its enclosing instance', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b9', 'Static nested classes are allocated on the stack instead of the heap', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b9', 'Only static nested classes can be private', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002b9', 'Non-static inner classes cannot be garbage collected at all', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ba', 'The JIT compiles the hot path after the first rounds have run interpreted', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ba', 'The garbage collector has finished and stops interrupting', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ba', 'The CPU cache is full, so the loop no longer needs memory', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002ba', 'System.nanoTime() becomes more accurate as the process ages', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bb', 'Build a HashSet once outside the loop and use contains on that', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bb', 'Sort the list first so contains can binary-search', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bb', 'Convert the loop to a parallel stream', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bb', 'Mark the list final so the JIT can inline the lookup', 0, 4

    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bc', 'The domain classes import no framework and need no container to test', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bc', 'The domain declares the interfaces it needs and implementations are passed in', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bc', 'Expected outcomes are a sealed result type the caller must handle', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000002bc', 'Classes are named after the pattern used, so CourseServiceManagerImpl', 0, 4
  ) v;

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-00000000000c');
CALL search_reindex_all();
