-- ===========================================================================
-- Seed 24 : the C# course, basics -> intermediate -> advanced -> expert
--
-- These lessons carry ```csharp fences, and like the Dart and Java courses
-- there is no browser runner behind them: the playground cannot run
-- C#, so the front end renders these as plain code blocks with no Try
-- yourself button. CODE_FENCE_PATTERN in the website lists the runnable
-- languages, and csharp is deliberately not one of them.
--
-- That makes the examples' correctness this file's problem rather than the
-- learner's. Every fence below was compiled and executed against
-- the .NET SDK (8.0, C# 12), with that compiler's own warnings
-- treated as errors, by scratchpad/gen/checklang.py - before it was written
-- out, and again after being read back out of MySQL.
--
-- Generated by scratchpad/gen/build_batch5.py - the bodies are full of quotes,
-- backslashes and format specifiers, and escaping those by hand is how a seed
-- gets broken.
-- ===========================================================================

INSERT INTO catalog_tags (id, slug, name) VALUES
  ('bbbbbbb1-0000-4000-8000-000000000016', 'csharp', 'C#')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO catalog_courses
  (id, slug, title, subtitle, description, category_id, instructor_id, level, status,
   thumbnail_url, price_cents, learning_outcomes, requirements, published_at)
VALUES
  ('c0000001-0000-4000-8000-00000000000d',
   'csharp-from-basics-to-expert',
   'C#: From Basics to Expert',
   'Four levels, twelve lessons, every example compiled and run on .NET',
   'A complete path through C# in four levels, taught on .NET 8 and C# 12. Level 1, Basic, covers the split between value types and references, nullable reference types - the feature that turns a NullReferenceException into a compiler warning - and the collections with LINQ over them. Level 2, Intermediate, is classes, structs and records and when each is right, properties with init and required, interfaces and reified generics, variance, and the three shapes of failure. Level 3, Advanced, covers async and await and what they actually free, LINQ''s deferred execution with the pattern matching that has grown into its own language, and real parallelism with locks, Interlocked and channels. Level 4, Expert, finishes with the garbage collector and the leaks it cannot prevent, where the time and allocations go, and how to arrange an application so a change stays small.

Every example in this course was compiled and run on a real .NET SDK before publication, with the build''s own warnings treated as failures. There is no in-browser C# runner yet, so the code blocks are for reading and for running in your own editor.

There is no in-browser runner for this language on the site, so to follow along install the SDK from dotnet.microsoft.com and run each one with dotnet run, or paste it into a scratch project.',
   'aaaaaaa1-0000-4000-8000-000000000001',
   '55555555-5555-4555-8555-555555555555',
   'beginner', 'published',
   'https://images.example-cdn.test/courses/csharp-from-basics-to-expert.jpg', 0,
   JSON_ARRAY('Say what a variable holds, and why that decides so much',
              'Use nullable reference types deliberately, and ! almost never',
              'Choose between class, struct and record for a reason you can state',
              'Explain what await frees, and why async void is a trap',
              'Read a LINQ query and know when it has not run yet',
              'Find a leak by asking what still holds a reference'),
   JSON_ARRAY('No prior C#', 'Some experience of any programming language helps but is not required'),
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), subtitle = VALUES(subtitle), description = VALUES(description),
  learning_outcomes = VALUES(learning_outcomes), requirements = VALUES(requirements);

INSERT INTO catalog_course_tags (course_id, tag_id) VALUES
  ('c0000001-0000-4000-8000-00000000000d', 'bbbbbbb1-0000-4000-8000-000000000016'),
  ('c0000001-0000-4000-8000-00000000000d', 'bbbbbbb1-0000-4000-8000-000000000007')
ON DUPLICATE KEY UPDATE course_id = VALUES(course_id);

INSERT INTO catalog_modules (id, course_id, title, summary, `position`) VALUES
  ('d0000001-0000-4000-8000-00000000002c', 'c0000001-0000-4000-8000-00000000000d',
   'Level 1 - Basic', 'Value types against references, nullable reference types, and LINQ over the collections.', 1),
  ('d0000001-0000-4000-8000-00000000002d', 'c0000001-0000-4000-8000-00000000000d',
   'Level 2 - Intermediate', 'Classes, structs and records, interfaces and generics, and failing on purpose.', 2),
  ('d0000001-0000-4000-8000-00000000002e', 'c0000001-0000-4000-8000-00000000000d',
   'Level 3 - Advanced', 'async and await, LINQ in depth with pattern matching, and real parallelism.', 3),
  ('d0000001-0000-4000-8000-00000000002f', 'c0000001-0000-4000-8000-00000000000d',
   'Level 4 - Expert', 'The heap and disposal, where the time goes, and how to arrange an application.', 4)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary);

INSERT INTO catalog_lessons
  (id, module_id, course_id, slug, title, summary, kind, status, `position`,
   duration_seconds, is_free_preview)
VALUES
  ('e0000001-0000-4000-8000-0000000000a1', 'd0000001-0000-4000-8000-00000000002c', 'c0000001-0000-4000-8000-00000000000d',
   'cs-values-and-types', 'Values, Types and Nullable Reference Types',
   'Value types against references, what ! really does, and decimal for money.',
   'article', 'published', 1, 720, 1),
  ('e0000001-0000-4000-8000-0000000000a2', 'd0000001-0000-4000-8000-00000000002c', 'c0000001-0000-4000-8000-00000000000d',
   'cs-control-flow', 'Control Flow, Methods and Pattern Switches',
   'The switch expression with relational patterns, named arguments, and the Try shape.',
   'article', 'published', 2, 660, 1),
  ('e0000001-0000-4000-8000-0000000000a3', 'd0000001-0000-4000-8000-00000000002c', 'c0000001-0000-4000-8000-00000000000d',
   'cs-collections', 'Collections and LINQ',
   'Collection expressions, the dictionary that throws, and LINQ''s deferred execution.',
   'article', 'published', 3, 780, 0),
  ('e0000001-0000-4000-8000-0000000000a4', 'd0000001-0000-4000-8000-00000000002d', 'c0000001-0000-4000-8000-00000000000d',
   'cs-classes-and-records', 'Classes, Structs and Records',
   'class, struct or record; primary constructors, init, required, and the equality contract.',
   'article', 'published', 1, 840, 0),
  ('e0000001-0000-4000-8000-0000000000a5', 'd0000001-0000-4000-8000-00000000002d', 'c0000001-0000-4000-8000-00000000000d',
   'cs-interfaces-and-generics', 'Interfaces, Generics and Extension Methods',
   'Default implementations, reified generics, in and out variance, and extension methods.',
   'article', 'published', 2, 840, 0),
  ('e0000001-0000-4000-8000-0000000000a6', 'd0000001-0000-4000-8000-00000000002d', 'c0000001-0000-4000-8000-00000000000d',
   'cs-exceptions', 'Exceptions, Disposal and Failing on Purpose',
   'when filters, using, keeping the stack trace, and the TryParse shape.',
   'article', 'published', 3, 780, 0),
  ('e0000001-0000-4000-8000-0000000000a7', 'd0000001-0000-4000-8000-00000000002e', 'c0000001-0000-4000-8000-00000000000d',
   'cs-async', 'async, await and Tasks',
   'What await frees, WhenAll, cancellation tokens, and why async void is a trap.',
   'article', 'published', 1, 900, 0),
  ('e0000001-0000-4000-8000-0000000000a8', 'd0000001-0000-4000-8000-00000000002e', 'c0000001-0000-4000-8000-00000000000d',
   'cs-linq-and-patterns', 'LINQ in Depth and Pattern Matching',
   'Deferred execution, the collectors worth knowing, and property and positional patterns.',
   'article', 'published', 2, 840, 0),
  ('e0000001-0000-4000-8000-0000000000a9', 'd0000001-0000-4000-8000-00000000002e', 'c0000001-0000-4000-8000-00000000000d',
   'cs-parallel', 'Threads, Locks and Parallel Work',
   'Data races, lock and Interlocked, AsParallel, and Channels with backpressure.',
   'article', 'published', 3, 840, 0),
  ('e0000001-0000-4000-8000-0000000000aa', 'd0000001-0000-4000-8000-00000000002f', 'c0000001-0000-4000-8000-00000000000d',
   'cs-memory', 'Memory, the Heap and Disposal',
   'Generations, the leaks a collector cannot prevent, IDisposable, and Span.',
   'article', 'published', 1, 900, 0),
  ('e0000001-0000-4000-8000-0000000000ab', 'd0000001-0000-4000-8000-00000000002f', 'c0000001-0000-4000-8000-00000000000d',
   'cs-performance', 'Where C# Spends Its Time',
   'StringBuilder, boxing, the right collection, and why the first measurement is the JIT.',
   'article', 'published', 2, 840, 0),
  ('e0000001-0000-4000-8000-0000000000ac', 'd0000001-0000-4000-8000-00000000002f', 'c0000001-0000-4000-8000-00000000000d',
   'cs-architecture', 'Arranging a C# Application',
   'Plain-C# rules, interfaces the domain owns, internal by default, one composition root.',
   'article', 'published', 3, 900, 0),
  ('e0000001-0000-4000-8000-0000000000ad', 'd0000001-0000-4000-8000-00000000002c', 'c0000001-0000-4000-8000-00000000000d',
   'cs-level-1-check', 'Level 1 Check: Types, Nullability and Collections',
   'Five questions on nullability, the dictionary indexer, LINQ and const against readonly.',
   'quiz', 'published', 4, 420, 1),
  ('e0000001-0000-4000-8000-0000000000ae', 'd0000001-0000-4000-8000-00000000002d', 'c0000001-0000-4000-8000-00000000000d',
   'cs-level-2-check', 'Level 2 Check: Records, Interfaces and Failure',
   'Five questions on records and structs, variance, and preserving a stack trace.',
   'quiz', 'published', 4, 480, 0),
  ('e0000001-0000-4000-8000-0000000000af', 'd0000001-0000-4000-8000-00000000002e', 'c0000001-0000-4000-8000-00000000000d',
   'cs-level-3-check', 'Level 3 Check: async, LINQ and Patterns',
   'Five questions on what await frees, cancellation, data races and patterns.',
   'quiz', 'published', 4, 540, 0),
  ('e0000001-0000-4000-8000-0000000000b0', 'd0000001-0000-4000-8000-00000000002f', 'c0000001-0000-4000-8000-00000000000d',
   'cs-expert-exam', 'Expert Exam: C#',
   'Leaks, disposal, the JIT, and how an application is arranged.',
   'quiz', 'published', 4, 900, 0)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary), `position` = VALUES(`position`);

-- ---------------------------------------------------------------------------
-- Values, Types and Nullable Reference Types
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a1',
   'Values, Types and Nullable Reference Types',
   'markdown',
   '# Values, Types and Nullable Reference Types

C# has two families of type and the difference decides what a variable holds.
A **value type** - `int`, `double`, `bool`, `char`, a `struct`, an `enum` -
holds the value itself. A **reference type** - `string`, arrays, classes,
records - holds a reference to an object.

```csharp
int count = 42;                  // the variable IS the 42
string name = "Ada";             // the variable points AT the string

var total = 1_000_000;           // var infers the type; it is still an int
var ratio = 0.5;                 // double
var ready = true;                // bool

Console.WriteLine($"{count.GetType().Name} {name.GetType().Name} {ratio.GetType().Name}");
Console.WriteLine($"{total:N0} and ready={ready}");

// Assigning a value type copies the value.
int a = 1;
int b = a;
b++;
Console.WriteLine($"a={a} b={b}");

// Assigning a reference type copies the reference: one object, two names.
int[] first = [1, 2, 3];
int[] second = first;
second[0] = 99;
Console.WriteLine($"first[0]={first[0]}");
```

That file has no `class` and no `Main`. Since C# 9 a file may hold **top-level
statements**, and the compiler writes the entry point for you.

## Nullable reference types: the compiler took the billion-dollar mistake away

In a modern C# project (`<Nullable>enable</Nullable>`, on by default in new
projects), `string` means "never null" and `string?` means "may be null". The
compiler tracks which is which and warns when you get it wrong.

```csharp
string certain = "always here";
string? maybe = Lookup("missing");

Console.WriteLine(certain.Length);
// Console.WriteLine(maybe.Length);   // warning: may be null here

if (maybe is not null)
{
    Console.WriteLine(maybe.Length);  // narrowed: the compiler knows it is not null
}

Console.WriteLine(maybe?.Length);                    // null-conditional
Console.WriteLine(maybe ?? "fallback");              // null-coalescing
maybe ??= "assigned now";                            // assign only if null
Console.WriteLine(maybe);

static string? Lookup(string key) => key == "known" ? "found it" : null;
```

The `!` operator - `maybe!.Length` - silences the warning without checking
anything. It is a promise to the compiler, and every one is a place the program
can throw. Prefer the check, or `??`.

## Value types cannot be null, unless you say so

```csharp
int definite = 0;
int? optional = null;             // Nullable<int>

Console.WriteLine(optional.HasValue);
Console.WriteLine(optional ?? -1);

optional = 42;
Console.WriteLine(optional.Value);

// GetValueOrDefault is the one that never throws.
int? empty = null;
Console.WriteLine(empty.GetValueOrDefault(-1));
Console.WriteLine(definite);

try
{
    Console.WriteLine(empty!.Value);
}
catch (InvalidOperationException e)
{
    Console.WriteLine($"reading .Value on an empty int?: {e.Message}");
}
```

## Numbers

```csharp
int max = int.MaxValue;
Console.WriteLine(max);
Console.WriteLine(unchecked(max + 1));       // wraps, silently

try
{
    Console.WriteLine(checked(max + 1));     // throws instead
}
catch (OverflowException)
{
    Console.WriteLine("checked: OverflowException");
}

// Note those go through a variable. Written as literals, `checked(int.MaxValue
// + 1)` is a COMPILE error - the compiler evaluates constants itself and will
// not emit code it knows overflows.

Console.WriteLine(7 / 2);            // integer division truncates
Console.WriteLine(7 / 2.0);
Console.WriteLine(7 % 3);

Console.WriteLine(0.1 + 0.2);        // binary floating point, here as everywhere
Console.WriteLine(0.1 + 0.2 == 0.3);

// decimal is base ten, and is what money belongs in.
decimal price = 0.1m + 0.2m;
Console.WriteLine($"{price} {price == 0.3m}");
```

`decimal` is not a faster `double`: it is slower and has a smaller range, but it
represents 0.1 exactly. Money, invoices and anything a person will check by hand
belong in it.

## Strings

```csharp
const string name = "Ada";
const int version = 12;

Console.WriteLine($"{name} writes C# {version}");        // interpolation
Console.WriteLine($"{name,10} padded, {3.14159:F2} formatted");

// Verbatim strings ignore escapes, which is what paths and regexes want.
Console.WriteLine(@"C:\\temp\\new");
Console.WriteLine(@"\\d+ is not an escape here");

// A raw string literal (C# 11) needs no escaping at all.
string query = """
    SELECT title
      FROM courses
     WHERE published = 1
    """;
Console.WriteLine(query);

// Strings are immutable: every method returns a new one.
string padded = "  trim me  ";
Console.WriteLine($"[{padded.Trim()}] and the original is still [{padded}]");

// So build in a loop with StringBuilder, not +=.
var builder = new System.Text.StringBuilder();
for (int i = 1; i <= 5; i++) builder.Append(i).Append('','');
Console.WriteLine(builder);
```

## What to take away

- Value types hold the value; reference types hold a reference to an object.
- Top-level statements mean a program needs no class and no `Main`.
- With nullable reference types on, `string` cannot be null and `string?` can.
- `?.`, `??` and `??=` handle absence; `!` only silences the compiler.
- `int?` is `Nullable<int>`; `.Value` on an empty one throws.
- `decimal` for money, `double` for measurements, and `checked` when overflow matters.
',
   'Value types against references, what ! really does, and decimal for money.',
   4, 728,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Control Flow, Methods and Pattern Switches
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a2',
   'Control Flow, Methods and Pattern Switches',
   'markdown',
   '# Control Flow, Methods and Pattern Switches

The loops are conventional. What is worth your attention is `switch`, because C#
has two of them and the expression form is both shorter and safer.

```csharp
int[] scores = [88, 42, 95, 61];

foreach (int score in scores)
{
    if (score >= 90) Console.WriteLine($"{score}: excellent");
    else if (score >= 60) Console.WriteLine($"{score}: pass");
    else Console.WriteLine($"{score}: resit");
}

for (int i = 0; i < scores.Length; i++)
{
    if (scores[i] == 42) continue;
    if (scores[i] > 90) break;
}

int countdown = 3;
while (countdown > 0)
{
    Console.WriteLine($"t-minus {countdown--}");
}

do { Console.WriteLine("runs at least once"); } while (false);
```

## The switch statement, and why the expression replaced it

A C# `switch` statement does not fall through - the compiler insists every
section ends with `break` or `return`. But it is still a statement: it produces
nothing, so the variable has to be declared before it and assigned inside.

```csharp
Console.WriteLine(DescribeOld(404));
Console.WriteLine(DescribeNew(404));
Console.WriteLine(DescribeNew(500));
Console.WriteLine(Categorise(15));
Console.WriteLine(Categorise(-1));

static string DescribeOld(int code)
{
    string result;
    switch (code)
    {
        case 200:
            result = "ok";
            break;
        case 301:
        case 302:
            result = "redirected";
            break;
        default:
            result = "something else";
            break;
    }
    return result;
}

// The expression form: no break, no temporary, and it produces a value.
static string DescribeNew(int code) => code switch
{
    200 => "ok",
    301 or 302 => "redirected",
    404 => "not found",
    _ => "something else",
};

// Patterns, not just constants: relational and logical patterns read like the
// rule you would say out loud.
static string Categorise(int n) => n switch
{
    < 0 => "negative",
    0 => "zero",
    > 0 and < 10 => "small",
    >= 10 and < 100 => "medium",
    _ => "large",
};
```

`_` is the discard: the catch-all arm. A switch expression with no matching arm
throws `SwitchExpressionException`, which is a loud failure rather than a silent
`null` - and over an enum or a sealed hierarchy the compiler warns when you have
missed a case.

## Methods, optional arguments and named ones

```csharp
Console.WriteLine(Maths.Add(2, 3));
Console.WriteLine(Maths.Add(2.5, 3.5));             // overloaded by type

Console.WriteLine(Greet("Ada"));
Console.WriteLine(Greet("Ada", "Good morning"));
Console.WriteLine(Greet("Ada", punctuation: "?"));  // named: skip the middle one

Console.WriteLine(Join("-", "a", "b", "c"));
Console.WriteLine(Join("-"));

static string Greet(string name, string greeting = "Hello", string punctuation = "!")
    => $"{greeting}, {name}{punctuation}";

static string Join(string separator, params string[] parts)
    => string.Join(separator, parts);

// Overloads have to live in a type. The methods above are LOCAL functions -
// convenient, but a local function cannot be overloaded, which is the first
// thing top-level statements will teach you the hard way.
static class Maths
{
    public static int Add(int a, int b) => a + b;
    public static double Add(double a, double b) => a + b;
}
```

Named arguments are worth a habit: `Draw(shape, 10, 20, true, false)` tells a
reader nothing, and `Draw(shape, x: 10, y: 20, filled: true, dashed: false)`
tells them everything.

## ref, out and in

C# lets a parameter be passed by reference, which is occasionally exactly right
and usually not.

```csharp
int value = 1;
Increment(ref value);                 // the caller''s variable is changed
Console.WriteLine(value);

if (TryParseAge("36", out int age))   // out: an extra result, not an input
{
    Console.WriteLine($"parsed {age}");
}

if (!TryParseAge("thirty", out int bad))
{
    Console.WriteLine($"could not parse, got {bad}");
}

static void Increment(ref int n) => n++;

static bool TryParseAge(string text, out int result)
    => int.TryParse(text, out result);
```

The `Try...` shape - a `bool` return and an `out` result - is how the standard
library reports an expected failure without an exception, and it is worth
copying.

## Local functions and lambdas

```csharp
Console.WriteLine(ApplyTwice(n => n * 2, 3));
Console.WriteLine(ApplyTwice(Double, 3));

var counter = MakeCounter();
Console.WriteLine(counter());
Console.WriteLine(counter());

// A lambda''s type is Func<...> or Action<...>; a local function has a name and
// can be recursive without the ceremony.
static int Double(int n) => n * 2;
static int ApplyTwice(Func<int, int> f, int start) => f(f(start));

static Func<int> MakeCounter()
{
    int count = 0;             // captured by the closure, and kept alive
    return () => ++count;
}
```

## What to take away

- A `switch` statement cannot fall through, but produces nothing.
- A `switch` expression produces a value and supports relational and logical patterns.
- `_` is the discard arm; an unmatched switch expression throws rather than returning null.
- Optional parameters plus named arguments beat four unexplained positional ones.
- `out` with a `bool` return is how C# reports an expected failure without throwing.
- A closure captures the variable, so the counter keeps counting.
',
   'The switch expression with relational patterns, named arguments, and the Try shape.',
   4, 758,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Collections and LINQ
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a3',
   'Collections and LINQ',
   'markdown',
   '# Collections and LINQ

Three collections carry almost every C# program: `List<T>` for order,
`HashSet<T>` for membership, `Dictionary<K,V>` for lookup. All three are
generic, and unlike Java''s, C#''s generics are **not erased** - a `List<int>`
knows it holds `int` at runtime, and stores them unboxed.

```csharp
List<string> tasks = ["write", "review", "write"];      // collection expression
HashSet<string> tags = ["csharp", "basics", "csharp"];  // duplicates collapse
Dictionary<string, int> stock = new() { ["apples"] = 3, ["pears"] = 0 };

Console.WriteLine(string.Join(", ", tasks));
Console.WriteLine(tags.Count);
Console.WriteLine(stock["apples"]);

tasks.Add("publish");
tasks.Insert(0, "plan");
tasks.Remove("review");
Console.WriteLine($"{tasks.Count}: {string.Join(" -> ", tasks)}");

Console.WriteLine(tasks[0]);
Console.WriteLine(tasks[^1]);          // ^1 is "one from the end"
Console.WriteLine(string.Join(",", tasks[1..3]));   // a range, end exclusive
```

## Reading a dictionary without an exception

```csharp
var stock = new Dictionary<string, int> { ["apples"] = 3 };

// The indexer THROWS on a missing key - unlike Java''s map, which returns null.
try
{
    Console.WriteLine(stock["plums"]);
}
catch (KeyNotFoundException)
{
    Console.WriteLine("the indexer throws on a missing key");
}

// So read with TryGetValue or GetValueOrDefault.
if (stock.TryGetValue("apples", out int apples))
{
    Console.WriteLine($"apples: {apples}");
}
Console.WriteLine(stock.GetValueOrDefault("plums", 0));

stock["plums"] = 7;                     // the indexer inserts or overwrites
stock.TryAdd("apples", 99);             // only if missing, so no change
Console.WriteLine(string.Join(", ", stock.Select(e => $"{e.Key}={e.Value}")));

foreach ((string name, int count) in stock)   // deconstructed in the foreach
{
    Console.WriteLine($"{name}: {count}");
}
```

## Arrays, spans and the immutable ones

```csharp
int[] numbers = [5, 3, 9, 1];
Array.Sort(numbers);
Console.WriteLine(string.Join(",", numbers));

// A Span<T> is a view over memory with no copy - slicing it allocates nothing.
Span<int> middle = numbers.AsSpan(1, 2);
middle[0] = 100;
Console.WriteLine(string.Join(",", numbers));     // the array changed

// Immutable, when a collection must not change after construction.
System.Collections.Immutable.ImmutableArray<int> frozen = [1, 2, 3];
Console.WriteLine(string.Join(",", frozen.Add(4)));   // a NEW array
Console.WriteLine(string.Join(",", frozen));          // the original stands

// IReadOnlyList is the type to expose: callers can read, not add.
IReadOnlyList<int> exposed = numbers;
Console.WriteLine(exposed.Count);
```

## LINQ is the query language, and it is lazy

`Where`, `Select` and friends build a query. Nothing runs until something
enumerates it - a `foreach`, a `ToList`, a `Count`.

```csharp
var source = new[] { 1, 2, 3, 4, 5, 6 };

var query = source
    .Where(n => { Console.WriteLine($"  testing {n}"); return n % 2 == 0; })
    .Select(n => n * n);

Console.WriteLine("nothing has run yet");
Console.WriteLine(string.Join(",", query));

// And it runs AGAIN on every enumeration - which is the trap.
Console.WriteLine($"count: {query.Count()}");

// ToList() pays for the work once.
var materialised = query.ToList();
Console.WriteLine($"{materialised.Count} without re-running anything");
```

## The operations worth knowing by name

```csharp
// The record is declared at the BOTTOM of this file, not the top: in a file
// using top-level statements, every type declaration must come after the last
// statement.
Learner[] learners =
[
    new("Ada", "UK", 95),
    new("Grace", "US", 88),
    new("Alan", "UK", 72),
    new("Katherine", "US", 95),
];

Console.WriteLine(string.Join(", ", learners.Select(l => l.Name)));
Console.WriteLine(learners.Count(l => l.Score > 80));
Console.WriteLine(learners.Any(l => l.Score == 100));
Console.WriteLine(learners.All(l => l.Score > 50));
Console.WriteLine(learners.Max(l => l.Score));
Console.WriteLine(learners.Average(l => l.Score));

// OrderBy then ThenBy, which reads like the sort you meant.
foreach (var learner in learners.OrderByDescending(l => l.Score).ThenBy(l => l.Name))
{
    Console.WriteLine($"  {learner.Name} {learner.Score}");
}

// GroupBy, and the query syntax that is the same thing spelled differently.
foreach (var group in learners.GroupBy(l => l.Country))
{
    Console.WriteLine($"{group.Key}: {string.Join(", ", group.Select(l => l.Name))}");
}

var uk = from l in learners
         where l.Country == "UK"
         orderby l.Score descending
         select l.Name;
Console.WriteLine(string.Join(", ", uk));

// First throws when nothing matches; FirstOrDefault hands back null.
Console.WriteLine(learners.FirstOrDefault(l => l.Score > 99)?.Name ?? "nobody");

// ToDictionary throws on a duplicate key, which is better than silently dropping.
var byName = learners.ToDictionary(l => l.Name, l => l.Score);
Console.WriteLine(byName["Ada"]);

record Learner(string Name, string Country, int Score);
```

## What to take away

- `List<T>`, `HashSet<T>` and `Dictionary<K,V>`; generics are reified, so no boxing.
- Collection expressions (`[1, 2, 3]`) build any of them, and `^1` and `1..3` index from the end.
- A dictionary''s indexer throws on a missing key - `TryGetValue` or `GetValueOrDefault`.
- LINQ is lazy and re-runs on every enumeration; `ToList()` pays once.
- `OrderBy().ThenBy()`, `GroupBy`, `Any`, `All` and `Count` replace the loops.
- Expose `IReadOnlyList<T>`, and use `ImmutableArray<T>` when it truly must not change.
',
   'Collection expressions, the dictionary that throws, and LINQ''s deferred execution.',
   3, 694,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Classes, Structs and Records
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a4',
   'Classes, Structs and Records',
   'markdown',
   '# Classes, Structs and Records

C# gives you three ways to declare a type, and the choice is about identity and
copying rather than style.

- A **class** is a reference type. Two variables can name one object; equality
  is identity unless you say otherwise.
- A **struct** is a value type. Assigning copies it. Use one for a small,
  immutable value - a point, a money amount - and measure before anything bigger.
- A **record** is a class (or `record struct`) with value equality, a
  `ToString`, and `with` generated for you.

```csharp
var a = new PointClass(1, 2);
var b = new PointClass(1, 2);
Console.WriteLine($"class:  equal={a.Equals(b)}");        // false: identity

var c = new PointStruct(1, 2);
var d = new PointStruct(1, 2);
Console.WriteLine($"struct: equal={c.Equals(d)}");        // true: value equality

var e = new PointRecord(1, 2);
var f = new PointRecord(1, 2);
Console.WriteLine($"record: equal={e == f}, {e}");        // true, and prints itself

var moved = e with { Y = 99 };                            // a copy, one field changed
Console.WriteLine($"{e} -> {moved}");

class PointClass(int x, int y)
{
    public int X { get; } = x;
    public int Y { get; } = y;
}

readonly struct PointStruct(int x, int y)
{
    public int X { get; } = x;
    public int Y { get; } = y;
}

record PointRecord(int X, int Y);
```

Those `(int x, int y)` after the type names are **primary constructors** (C# 12):
the parameters are in scope for the whole body.

## Properties are the public surface

A field is storage; a property is the interface to it. C# makes the property so
cheap to write that a public field is almost never the right answer.

```csharp
var t = new Temperature(21);
Console.WriteLine($"{t.Celsius}C is {t.Fahrenheit:F1}F");

t.Celsius = -10;
Console.WriteLine(t.Celsius);

try
{
    t.Celsius = -300;
}
catch (ArgumentOutOfRangeException e)
{
    Console.WriteLine($"rejected: {e.ParamName}");
}

Console.WriteLine(Temperature.AbsoluteZero.Celsius);

class Temperature
{
    private double _celsius;

    public Temperature(double celsius) => Celsius = celsius;   // the setter validates

    public static Temperature AbsoluteZero { get; } = new(-273.15);

    public double Celsius
    {
        get => _celsius;
        set
        {
            if (value < -273.15)
            {
                throw new ArgumentOutOfRangeException(nameof(value), "below absolute zero");
            }
            _celsius = value;
        }
    }

    // A computed property: no storage, just a rule.
    public double Fahrenheit => _celsius * 9 / 5 + 32;
}
```

`init` instead of `set` makes a property settable only during construction,
which is how you get an object that is immutable but still readable as an object
initialiser:

```csharp
var course = new Course { Slug = "csharp", Title = "C#: From Basics to Expert" };
Console.WriteLine(course.Title);

// course.Title = "changed";        // will not compile: init-only

class Course
{
    public required string Slug { get; init; }      // required: the compiler insists
    public required string Title { get; init; }
}
```

## Equality, and the contract behind it

Override `Equals` and you must override `GetHashCode`, because every hash
collection uses the pair. A record does both for you, from its components -
which is the main reason to reach for one.

```csharp
var x = new Money(500, "GBP");
var y = new Money(500, "GBP");

Console.WriteLine(x == y);                                 // true
Console.WriteLine(new HashSet<Money> { x, y }.Count);      // 1
Console.WriteLine(x + new Money(250, "GBP"));

try
{
    _ = x + new Money(100, "USD");
}
catch (ArgumentException e)
{
    Console.WriteLine(e.Message);
}

readonly record struct Money(long Pence, string Currency)
{
    public static Money operator +(Money left, Money right)
        => left.Currency == right.Currency
            ? new Money(left.Pence + right.Pence, left.Currency)
            : throw new ArgumentException($"cannot add {right.Currency} to {left.Currency}");

    public override string ToString() => $"{Pence / 100.0:F2} {Currency}";
}
```

## Inheritance, and the keyword Java does not have

```csharp
Shape[] shapes = [new Rectangle(3, 4), new Circle(1)];
foreach (var shape in shapes) Console.WriteLine(shape.Describe());

abstract class Shape
{
    public abstract double Area { get; }

    // virtual: subclasses MAY replace it. Without this keyword they cannot -
    // C# methods are sealed by default, unlike Java''s.
    public virtual string Describe() => $"{GetType().Name} of area {Area:F2}";
}

sealed class Rectangle(double width, double height) : Shape
{
    public override double Area => width * height;
}

sealed class Circle(double radius) : Shape
{
    public override double Area => Math.PI * radius * radius;

    public override string Describe() => $"Circle r={radius}, {base.Describe()}";
}
```

`override` is compulsory, so you cannot accidentally hide a base method - and a
method you did not mark `virtual` cannot be overridden at all. That is the
opposite default from Java, and it is the safer one.

## What to take away

- class for identity, struct for a small copied value, record for a value with data.
- Primary constructors (C# 12) put the parameters in scope for the whole type.
- Properties, not public fields; `init` and `required` give immutability with initialisers.
- Override `Equals` and `GetHashCode` together - or use a record and get both.
- Methods are sealed unless marked `virtual`, and `override` is compulsory.
- `with` copies a record and changes named members, leaving the original alone.
',
   'class, struct or record; primary constructors, init, required, and the equality contract.',
   4, 830,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Interfaces, Generics and Extension Methods
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a5',
   'Interfaces, Generics and Extension Methods',
   'markdown',
   '# Interfaces, Generics and Extension Methods

An interface is a promise about behaviour. Programming against one is what lets
you hand a use case a real database in production and a dictionary in a test,
without the use case noticing.

```csharp
IRepository repository = new InMemoryRepository(new() { ["1"] = "Ada" });

Console.WriteLine(repository.Find("1") ?? "not found");
Console.WriteLine(repository.Find("2") ?? "not found");
Console.WriteLine(repository.FindOrDefault("2", "unknown"));

interface IRepository
{
    string? Find(string id);

    // A default implementation, so adding this does not break implementers.
    string FindOrDefault(string id, string fallback) => Find(id) ?? fallback;
}

sealed class InMemoryRepository(Dictionary<string, string> rows) : IRepository
{
    public string? Find(string id) => rows.GetValueOrDefault(id);
}
```

## Generics are reified, and that is a real difference

C#''s generics survive to runtime. `List<int>` stores unboxed ints, `typeof(T)`
works, and `new T()` is possible with a constraint.

```csharp
var boxed = new Box<int>(42);
Console.WriteLine(boxed);
Console.WriteLine(boxed.Map(n => n.ToString()).Map(s => s.Length));

Console.WriteLine(Largest([3, 9, 4]));
Console.WriteLine(Largest(["pear", "apple", "quince"]));

Console.WriteLine(Describe<int>());
Console.WriteLine(Describe<string>());

// The type argument is available at runtime - Java cannot do this.
static string Describe<T>() => $"T is {typeof(T).Name}";

// A constraint is what lets the body use anything beyond object.
static T Largest<T>(IEnumerable<T> values) where T : IComparable<T>
{
    T best = values.First();
    foreach (T value in values)
    {
        if (value.CompareTo(best) > 0) best = value;
    }
    return best;
}

record Box<T>(T Value)
{
    public Box<TResult> Map<TResult>(Func<T, TResult> f) => new(f(Value));
}
```

The constraints worth knowing: `where T : class` (a reference type),
`where T : struct` (a value type), `where T : new()` (has a parameterless
constructor), and `where T : ISomething` (implements an interface).

## in, out: which way a generic type may be substituted

```csharp
// IEnumerable<out T> is covariant: an IEnumerable<string> IS an IEnumerable<object>,
// because you can only take things out of it.
IEnumerable<string> strings = ["a", "b"];
IEnumerable<object> objects = strings;
Console.WriteLine(objects.Count());

// Action<in T> is contravariant: an Action<object> can stand in for an
// Action<string>, because anything you can do to an object you can do to a string.
Action<object> printAnything = o => Console.WriteLine($"got {o}");
Action<string> printString = printAnything;
printString("a string");

// List<T> is neither, and the reason is that you can both read and write it:
// if List<string> were a List<object>, you could add an int to it.
List<string> list = ["x"];
// List<object> broken = list;      // will not compile, and rightly
Console.WriteLine(list.Count);
```

## Extension methods: adding to a type you do not own

An extension method is a static method that reads like an instance method. The
entire LINQ library is built from them - `Where` and `Select` are extensions on
`IEnumerable<T>`, not members of it.

```csharp
Console.WriteLine("hello world".ToTitleCase());
Console.WriteLine(new[] { 1, 2, 3, 4 }.EverySecond().Sum());

// The one rule: an extension cannot see private state, so it is composition,
// not inheritance. That is a feature - it cannot break the type it extends.
static class StringExtensions
{
    public static string ToTitleCase(this string value)
        => string.Join('' '', value.Split('' '').Select(w => char.ToUpper(w[0]) + w[1..]));
}

static class EnumerableExtensions
{
    public static IEnumerable<T> EverySecond<T>(this IEnumerable<T> source)
        => source.Where((_, index) => index % 2 == 0);
}
```

## Enums, and what they do not protect you from

```csharp
Status status = Status.Published;
Console.WriteLine($"{status} = {(int)status}");

foreach (Status value in Enum.GetValues<Status>())
{
    Console.WriteLine($"  {value}: {Describe(value)}");
}

// An enum is an int in a hat: a cast can produce a value that is not a member,
// and nothing stops it. Enum.IsDefined is the check.
var smuggled = (Status)99;
Console.WriteLine($"{smuggled} is defined: {Enum.IsDefined(smuggled)}");
Console.WriteLine(Describe(smuggled));

static string Describe(Status status) => status switch
{
    Status.Draft => "not visible",
    Status.Published => "live",
    Status.Archived => "read only",
    _ => $"unknown status {(int)status}",
};

enum Status { Draft, Published, Archived }
```

That `_` arm is not optional ceremony: because any int can be cast to the enum,
the compiler is right to insist you handle a value that is not a member.

## What to take away

- An interface is a promise; a default implementation lets you add to one safely.
- C# generics are reified: `typeof(T)` works, and `List<int>` does not box.
- Constraints (`where T : IComparable<T>`) are what let the body do anything.
- `out` for covariance (read-only), `in` for contravariance (write-only), neither for both.
- Extension methods add behaviour without inheritance, and cannot see private state.
- An enum is an int: `Enum.IsDefined`, and always handle the unexpected value.
',
   'Default implementations, reified generics, in and out variance, and extension methods.',
   4, 727,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Exceptions, Disposal and Failing on Purpose
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a6',
   'Exceptions, Disposal and Failing on Purpose',
   'markdown',
   '# Exceptions, Disposal and Failing on Purpose

C# has no checked exceptions. Nothing in a signature tells a caller what might
be thrown, which makes what you throw - and what you document - a design
decision rather than a compiler-enforced one.

The distinction that matters is the same as everywhere: is this a condition the
caller could reasonably expect, or a mistake in the code?

```csharp
// Expected: the input was wrong, and the caller can react.
try
{
    int.Parse("twelve");
}
catch (FormatException e)
{
    Console.WriteLine($"expected: {e.Message}");
}

// A mistake: catching this hides a bug rather than handling a situation.
try
{
    int[] values = [1, 2, 3];
    Console.WriteLine(values[7]);
}
catch (IndexOutOfRangeException)
{
    Console.WriteLine("a bug, not a condition");
}

// The most common of all, and .NET names the expression that was null.
try
{
    string? nothing = null;
    Console.WriteLine(nothing!.Length);
}
catch (NullReferenceException e)
{
    Console.WriteLine($"NullReferenceException: {e.Message}");
}
```

## catch, when, and finally

```csharp
string[] keys = ["ok", "missing", ""];      // the collection expression needs a
                                            // target type, so foreach over a
foreach (string key in keys)                // bare [...] does not compile
{
    try
    {
        Console.WriteLine(Load(key));
    }
    catch (ArgumentException e) when (e.ParamName == "key")
    {
        // `when` filters WITHOUT unwinding the stack, so a filter that does not
        // match leaves the exception to travel on with its original context.
        Console.WriteLine($"  bad argument: {e.Message.Split(" (")[0]}");
    }
    catch (KeyNotFoundException)
    {
        Console.WriteLine("  no such record");
    }
    finally
    {
        Console.WriteLine($"  ...done with \\"{key}\\"");
    }
}

static string Load(string key) => key switch
{
    "" => throw new ArgumentException("must not be empty", nameof(key)),
    "missing" => throw new KeyNotFoundException(),
    _ => $"value for {key}",
};
```

Order matters: the first matching `catch` wins, so specific types go above
general ones. A bare `catch` at the end catches everything, including bugs.

## using, and the resources it closes for you

Anything implementing `IDisposable` belongs in a `using`. The compiler writes
the `try/finally` so the resource is released even when the body throws.

```csharp
using (var outer = new Connection("db"))
{
    outer.Use();
    try
    {
        using var inner = new Connection("cache");    // declaration form: closes
        inner.Use();                                  // at the end of the scope
        throw new InvalidOperationException("something went wrong");
    }
    catch (InvalidOperationException e)
    {
        Console.WriteLine($"caught: {e.Message}");
    }
}

sealed class Connection(string name) : IDisposable
{
    public void Use() => Console.WriteLine($"using {name}");
    public void Dispose() => Console.WriteLine($"closed {name}");
}
```

`using var` without braces is the modern form: it disposes at the end of the
enclosing scope, and saves a level of indentation.

## Your own exception types

```csharp
foreach ((string email, int age) in new[] { ("ada@example.com", 36), ("nope", 30) })
{
    try
    {
        Console.WriteLine($"{new Registration(email, age)} accepted");
    }
    catch (ValidationException e)
    {
        Console.WriteLine($"{email} rejected on {e.Field}: {e.Message}");
    }
}

sealed class ValidationException(string field, string reason)
    : Exception($"{field} {reason}")
{
    public string Field { get; } = field;
}

// A record has no "compact constructor": validation goes in the property
// initialisers, which run in declaration order before the object is usable.
record Registration(string Email, int Age)
{
    public string Email { get; } = Email.Contains(''@'')
        ? Email
        : throw new ValidationException(nameof(Email), "must contain @");

    public int Age { get; } = Age >= 13
        ? Age
        : throw new ValidationException(nameof(Age), "must be at least 13");
}
```

## Rethrow with `throw;`, never `throw e;`

```csharp
try
{
    Outer();
}
catch (InvalidOperationException e)
{
    Console.WriteLine(e.Message);
    Console.WriteLine($"  caused by: {e.InnerException?.Message}");
}

static void Outer()
{
    try
    {
        Inner();
    }
    catch (FormatException e)
    {
        // Wrapping: keep the original as InnerException so the trace survives.
        throw new InvalidOperationException("could not load the configuration", e);
    }
}

static void Inner() => int.Parse("not a number");
```

Inside a `catch`, bare `throw;` rethrows with the original stack trace intact.
`throw e;` resets it to this line - which discards the only evidence of where
the failure actually happened.

## Often the answer is not to throw

.NET''s own library shows both shapes: `int.Parse` throws, `int.TryParse` returns
a `bool`. An outcome the caller expects is a value.

```csharp
string[] inputs = ["10", "twelve", "30"];

int total = 0;
foreach (string input in inputs)
{
    if (int.TryParse(input, out int value)) total += value;
}
Console.WriteLine(total);

// The same thing in LINQ, and without an exception per bad row.
int sum = inputs
    .Select(text => (ok: int.TryParse(text, out int n), value: n))
    .Where(r => r.ok)
    .Sum(r => r.value);
Console.WriteLine(sum);
```

Exceptions are also expensive - constructing one captures a stack trace. One per
bad row in a large import is a measurable cost as well as a confusing design.

## What to take away

- No checked exceptions: what you throw is documentation, not a signature.
- `when` filters without unwinding, so the context survives a non-match.
- `using`/`using var` releases resources even when the body throws.
- Carry the data a caller needs on your exception type, not just in a message.
- `throw;` preserves the stack trace; `throw e;` destroys it.
- Prefer the `TryParse` shape for an outcome the caller expects.
',
   'when filters, using, keeping the stack trace, and the TryParse shape.',
   4, 832,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- async, await and Tasks
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a7',
   'async, await and Tasks',
   'markdown',
   '# async, await and Tasks

A `Task` is work that may not have finished. `async` marks a method that can
suspend; `await` is where it suspends. The thread is not blocked while it waits -
it is returned to the pool and picks up other work, which is the whole point.

```csharp
Console.WriteLine("before");
string name = await FetchNameAsync();
Console.WriteLine($"got {name}");
Console.WriteLine("after");

static async Task<string> FetchNameAsync()
{
    await Task.Delay(50);          // not Thread.Sleep: this does not hold a thread
    return "Ada";
}
```

`await` at the top level works because the compiler wraps the file in an async
entry point. In a library the rule is: a method that awaits must be `async`, and
an `async` method should return `Task` or `Task<T>` - never `void`, except for an
event handler, because nothing can await it and nothing can catch what it throws.

## Sequential await costs the sum; WhenAll costs the slowest

```csharp
var clock = System.Diagnostics.Stopwatch.StartNew();

await LoadAsync("a", 60);
await LoadAsync("b", 60);
await LoadAsync("c", 60);
Console.WriteLine($"sequential took at least 180ms: {clock.ElapsedMilliseconds >= 180}");

clock.Restart();

// Start all three, THEN await. The tasks are already running by the time
// WhenAll is reached - which is the part people get wrong.
Task<string>[] running = [LoadAsync("a", 60), LoadAsync("b", 60), LoadAsync("c", 60)];
string[] results = await Task.WhenAll(running);
Console.WriteLine($"concurrent: {string.Join(",", results)} in about 60ms: "
                  + $"{clock.ElapsedMilliseconds < 180}");

static async Task<string> LoadAsync(string name, int ms)
{
    await Task.Delay(ms);
    return name;
}
```

## Cancellation is a parameter, not an exception you invent

Every async API in .NET takes a `CancellationToken`. Pass it down; do not
swallow the `OperationCanceledException` it produces.

```csharp
using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(100));

try
{
    await SlowAsync(cts.Token);
}
catch (OperationCanceledException)
{
    Console.WriteLine("cancelled after 100ms, as asked");
}

// A timeout is the same mechanism with a clock attached.
using var timeout = new CancellationTokenSource(TimeSpan.FromMilliseconds(50));
string value = await FallbackAsync(timeout.Token);
Console.WriteLine(value);

static async Task SlowAsync(CancellationToken token)
{
    await Task.Delay(TimeSpan.FromSeconds(5), token);
}

static async Task<string> FallbackAsync(CancellationToken token)
{
    try
    {
        await Task.Delay(TimeSpan.FromSeconds(5), token);
        return "eventually";
    }
    catch (OperationCanceledException)
    {
        return "default, because it took too long";
    }
}
```

## Errors travel in the Task

An exception inside an `async` method is captured in the returned task and
rethrown at the `await`. That is what makes `try/catch` around an `await` work
the way it looks like it should.

```csharp
try
{
    await RiskyAsync(-1);
}
catch (ArgumentOutOfRangeException e)
{
    Console.WriteLine($"caught at the await: {e.ParamName}");
}

// WhenAll reports the FIRST exception at the await, but the task holds them all.
Task all = Task.WhenAll(RiskyAsync(-1), RiskyAsync(-2));
try
{
    await all;
}
catch (ArgumentOutOfRangeException)
{
    Console.WriteLine($"WhenAll collected {all.Exception?.InnerExceptions.Count} failures");
}

static async Task<int> RiskyAsync(int n)
{
    await Task.Yield();
    return n < 0 ? throw new ArgumentOutOfRangeException(nameof(n)) : n * 2;
}
```

## The two rules that prevent most async bugs

**Never block on async code.** `.Result` and `.Wait()` deadlock in any context
with a synchronisation context (classic ASP.NET, WinForms, WPF) and waste a
thread everywhere else. Await it, all the way up.

**Do not `async void`.** Nothing can await it, so nothing can observe the
failure: an exception from an `async void` method is thrown on the thread pool
and takes the process down.

```csharp
// Right: async all the way, returning Task.
await GoodAsync();

// A fire-and-forget that at least observes its own failure.
_ = Task.Run(async () =>
{
    try
    {
        await BackgroundAsync();
    }
    catch (Exception e)
    {
        Console.WriteLine($"background failed, and we know: {e.Message}");
    }
});

await Task.Delay(100);

static async Task GoodAsync()
{
    await Task.Delay(10);
    Console.WriteLine("finished properly");
}

static async Task BackgroundAsync()
{
    await Task.Delay(10);
    throw new InvalidOperationException("something went wrong out of sight");
}
```

## IAsyncEnumerable: results that arrive over time

```csharp
await foreach (int value in CountToAsync(3))
{
    Console.WriteLine($"got {value}");
}
Console.WriteLine("stream finished");

static async IAsyncEnumerable<int> CountToAsync(int n)
{
    for (int i = 1; i <= n; i++)
    {
        await Task.Delay(10);
        yield return i;               // one value at a time, as it is ready
    }
}
```

## What to take away

- `await` frees the thread; `Thread.Sleep` and `.Result` hold it.
- An async method returns `Task`/`Task<T>` - `async void` only for event handlers.
- Start tasks, then `await Task.WhenAll` - awaiting one at a time costs the sum.
- Pass the `CancellationToken` down; a timeout is a token with a clock.
- Exceptions are captured in the task and rethrown at the `await`.
- `await foreach` over an `IAsyncEnumerable<T>` for results that arrive over time.
',
   'What await frees, WhenAll, cancellation tokens, and why async void is a trap.',
   4, 737,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- LINQ in Depth and Pattern Matching
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a8',
   'LINQ in Depth and Pattern Matching',
   'markdown',
   '# LINQ in Depth and Pattern Matching

LINQ is two things at once: a set of extension methods over `IEnumerable<T>`,
and a query syntax that compiles to exactly those calls. Understanding the first
explains every surprise in the second.

```csharp
int[] source = [1, 2, 3, 4, 5, 6];

// Deferred: this builds a query object and runs nothing.
IEnumerable<int> query = source.Where(n => n % 2 == 0).Select(n => n * n);

Console.WriteLine("built, not run");
Console.WriteLine(string.Join(",", query));

// The source is captured, not copied. Change it and the query changes too.
var list = new List<int> { 1, 2, 3 };
IEnumerable<int> live = list.Where(n => n > 1);
list.Add(4);
Console.WriteLine(string.Join(",", live));     // 2,3,4 - the 4 was added after
```

## Deferred execution is the feature and the trap

```csharp
int calls = 0;

var numbers = Enumerable.Range(1, 5).Select(n =>
{
    calls++;
    return n * 2;
});

Console.WriteLine(numbers.Count());
Console.WriteLine(numbers.First());
Console.WriteLine(string.Join(",", numbers));
Console.WriteLine($"the projection ran {calls} times for 5 elements");

calls = 0;
var once = Enumerable.Range(1, 5).Select(n => { calls++; return n * 2; }).ToList();
Console.WriteLine($"{once.Count} elements, {calls} calls - ToList paid once");
```

If the projection touches a database or has a side effect, running it three
times is a bug. `ToList()` or `ToArray()` is where you decide to pay.

## The methods worth knowing

```csharp
Learner[] learners =
[
    new("Ada", "UK", 95), new("Grace", "US", 88),
    new("Alan", "UK", 72), new("Katherine", "US", 95),
];

// SelectMany flattens one level - the LINQ answer to a nested loop.
string[] lines = ["hello world", "goodbye moon"];
Console.WriteLine(string.Join(",", lines.SelectMany(l => l.Split('' ''))));

// Aggregate, when the fold is not one of the ready-made ones.
Console.WriteLine(learners.Select(l => l.Name).Aggregate((a, b) => $"{a} & {b}"));

// Join, which is the same shape as SQL''s.
(string Code, string Name)[] countries = [("UK", "United Kingdom"), ("US", "United States")];
var joined = learners.Join(countries, l => l.Country, c => c.Code,
                           (l, c) => $"{l.Name} ({c.Name})");
Console.WriteLine(string.Join("; ", joined));

// ToLookup: a one-to-many dictionary, built in one pass.
var byCountry = learners.ToLookup(l => l.Country, l => l.Name);
foreach (var group in byCountry)
{
    Console.WriteLine($"{group.Key}: {string.Join(", ", group)}");
}

// Chunk, DistinctBy, MinBy, MaxBy - all newer, all replace a hand-written loop.
Console.WriteLine(learners.MaxBy(l => l.Score)!.Name);
Console.WriteLine(string.Join(", ", learners.DistinctBy(l => l.Score).Select(l => l.Score)));
foreach (int[] chunk in Enumerable.Range(1, 7).Chunk(3))
{
    Console.WriteLine($"  chunk: {string.Join(",", chunk)}");
}

record Learner(string Name, string Country, int Score);
```

## Pattern matching has grown into its own language

```csharp
object[] values = ["hello", 42, 3.5, new[] { 1, 2 }, null!, new Point(1, 2)];

foreach (object value in values)
{
    Console.WriteLine(Describe(value));
}

static string Describe(object? value) => value switch
{
    null => "nothing at all",
    string { Length: > 3 } s => $"a long string: {s.ToUpper()}",
    string s => $"a short string: {s}",
    int and > 40 => "a big int",
    int i => $"an int: {i}",
    double d when d > 3 => $"a double over three: {d}",
    int[] { Length: 2 } pair => $"a pair adding to {pair[0] + pair[1]}",
    Point (var x, var y) => $"a point at {x},{y}",     // positional pattern
    _ => $"something else: {value}",
};

record Point(int X, int Y);
```

`{ Length: > 3 }` is a property pattern, `and`/`or`/`not` are logical patterns,
`when` adds a condition, and a record can be matched positionally because it has
a `Deconstruct`.

## Exhaustiveness, as far as C# offers it

C# has no `sealed` hierarchy like Java or Kotlin, so a `switch` over a class
hierarchy can never be proven complete. What it does have: a switch **expression**
with no matching arm throws rather than returning a default, and the compiler
warns when it can see a value you have not handled.

```csharp
Shape[] shapes = [new Square(2), new Circle(1)];
foreach (Shape shape in shapes)
{
    Console.WriteLine($"{shape.GetType().Name}: {Area(shape):F3}");
}

// A shape this does not know about throws loudly at the point of failure,
// rather than quietly returning zero.
try
{
    Console.WriteLine(Area(new Triangle(3, 4)));
}
catch (ArgumentException e)
{
    Console.WriteLine(e.Message);
}

static double Area(Shape shape) => shape switch
{
    Square s => s.Side * s.Side,
    Circle c => Math.PI * c.Radius * c.Radius,
    _ => throw new ArgumentException($"no area rule for {shape.GetType().Name}"),
};

abstract record Shape;
record Square(double Side) : Shape;
record Circle(double Radius) : Shape;
record Triangle(double Base, double Height) : Shape;
```

## What to take away

- LINQ is deferred: it captures the source, and re-runs on every enumeration.
- `ToList()`/`ToArray()` is where you choose to pay for the work once.
- `SelectMany`, `ToLookup`, `MaxBy`, `Chunk` and `DistinctBy` replace hand-written loops.
- Property, positional, relational and logical patterns compose into readable rules.
- `when` guards a pattern; order matters, and the compiler warns on unreachable arms.
- C# cannot prove a hierarchy switch complete - throw in the `_` arm rather than defaulting.
',
   'Deferred execution, the collectors worth knowing, and property and positional patterns.',
   4, 796,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Threads, Locks and Parallel Work
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000a9',
   'Threads, Locks and Parallel Work',
   'markdown',
   '# Threads, Locks and Parallel Work

`async` and parallelism are different problems. `async` is about not holding a
thread while waiting for something else; parallelism is about using several
cores at once. This lesson is the second one.

Two threads writing the same field with nothing arranged between them is a data
race, and the result is not merely a wrong number: without a memory barrier one
thread may never see the other''s write at all.

```csharp
int counter = 0;
var threads = new Thread[4];

for (int i = 0; i < threads.Length; i++)
{
    threads[i] = new Thread(() =>
    {
        for (int n = 0; n < 100_000; n++) counter++;    // read, add, write
    });
    threads[i].Start();
}
foreach (Thread thread in threads) thread.Join();

Console.WriteLine($"counter = {counter} (expected 400000)");
Console.WriteLine("usually short, and never reliably right");
```

## The three ways to make it correct

```csharp
int guarded = 0;
int atomic = 0;
object gate = new();

var threads = new Thread[4];
for (int i = 0; i < threads.Length; i++)
{
    threads[i] = new Thread(() =>
    {
        for (int n = 0; n < 50_000; n++)
        {
            lock (gate) { guarded++; }            // mutual exclusion + barriers
            Interlocked.Increment(ref atomic);    // one hardware instruction
        }
    });
    threads[i].Start();
}
foreach (Thread thread in threads) thread.Join();

Console.WriteLine($"lock:        {guarded}");
Console.WriteLine($"Interlocked: {atomic}");
Console.WriteLine("and the third way: share nothing that changes");
```

Lock on a `private readonly object`, never on `this` or on a type - anything
another piece of code can also lock is a deadlock waiting to be assembled.

## Do not create threads by hand

`Task.Run` queues work on the thread pool, which already knows how many cores
there are. `Parallel.ForEach` and `AsParallel` go further and split a collection
across them.

```csharp
var clock = System.Diagnostics.Stopwatch.StartNew();

int[] input = Enumerable.Range(1, 12).ToArray();

// Sequential.
long sequential = input.Select(Work).Sum();
long sequentialMs = clock.ElapsedMilliseconds;

clock.Restart();

// Parallel LINQ: the same query, spread across cores.
long parallel = input.AsParallel().Select(Work).Sum();

Console.WriteLine($"sequential {sequentialMs}ms -> {sequential}");
Console.WriteLine($"parallel   {clock.ElapsedMilliseconds}ms -> {parallel}");
Console.WriteLine($"same answer: {sequential == parallel}");

static long Work(int n)
{
    long total = 0;
    for (int i = 0; i < 3_000_000; i++) total += (i % 7) * n;
    return total;
}
```

Two rules for `AsParallel` and `Parallel.ForEach`: the work must be CPU-bound
(for I/O, use `async` - a parked thread is not a busy core), and the body must
not touch shared mutable state. The second is where people come unstuck.

```csharp
// Wrong: a List<T> is not thread-safe, and this silently loses or corrupts items.
var unsafeList = new List<int>();
Parallel.For(0, 1000, i => { lock (unsafeList) { unsafeList.Add(i); } });
Console.WriteLine($"with a lock around every add: {unsafeList.Count} (correct, and slow)");

// Right: let the query build the result, with no shared state at all.
List<int> collected = Enumerable.Range(0, 1000).AsParallel().Select(i => i).ToList();
Console.WriteLine($"no sharing: {collected.Count}");

// Or use a collection designed for it.
var bag = new System.Collections.Concurrent.ConcurrentBag<int>();
Parallel.For(0, 1000, bag.Add);
Console.WriteLine($"ConcurrentBag: {bag.Count}");
```

## Channels: a queue between producers and consumers

`System.Threading.Channels` is the modern way to hand work from one part of a
program to another without sharing a collection.

```csharp
using System.Threading.Channels;

Channel<int> channel = Channel.CreateBounded<int>(capacity: 4);

Task producer = Task.Run(async () =>
{
    for (int i = 1; i <= 10; i++)
    {
        await channel.Writer.WriteAsync(i);      // blocks when the buffer is full,
    }                                            // which is backpressure, free
    channel.Writer.Complete();                   // without this, the reader waits forever
});

int total = 0;
await foreach (int value in channel.Reader.ReadAllAsync())
{
    total += value;
}

await producer;
Console.WriteLine($"consumed, total {total}");
```

The bounded capacity is the part worth noticing: a producer faster than its
consumer will wait rather than filling memory.

## What to take away

- `async` is about not holding threads; parallelism is about using cores. Different problems.
- An unsynchronised shared field is a data race - wrong values, and stale reads.
- `lock` on a private readonly object; `Interlocked` for a single counter.
- Prefer `Task.Run`, `Parallel.ForEach` and `AsParallel` to creating threads.
- Parallel work must be CPU-bound and must not touch shared mutable state.
- A bounded `Channel<T>` gives you a producer/consumer queue with backpressure.
',
   'Data races, lock and Interlocked, AsParallel, and Channels with backpressure.',
   3, 687,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Memory, the Heap and Disposal
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000aa',
   'Memory, the Heap and Disposal',
   'markdown',
   '# Memory, the Heap and Disposal

.NET has two places values live. The **stack** holds a frame per call: its
locals, and for a reference-typed local the reference itself. The **heap** holds
every object, and is managed by a garbage collector. A value type declared as a
local lives in the frame; the same value type as a field lives wherever its
owner does.

```csharp
var owner = new Owner(new Point(1, 2));
Point copy = owner.Position;       // a struct: this is a COPY
copy = copy with { X = 99 };
Console.WriteLine($"{owner.Position} is unchanged; the copy is {copy}");

var shared = new Box(1);
Box alias = shared;                // a class: two names, one object
alias.Value = 99;
Console.WriteLine($"shared.Value is now {shared.Value}");

readonly record struct Point(int X, int Y);
sealed class Box(int value) { public int Value { get; set; } = value; }
sealed class Owner(Point position) { public Point Position { get; } = position; }
```

## The collector is generational

Most objects die young, and the collector is built around that. New objects go
in **gen 0**, collected often and cheaply; survivors are promoted to gen 1 and
then gen 2, which is collected rarely and expensively. Anything over about 85KB
goes straight to the **Large Object Heap**, which is not compacted by default.

```csharp
Console.WriteLine($"gen 0 collections so far: {GC.CollectionCount(0)}");

long before = GC.GetTotalMemory(false);
long checksum = 0;

for (int i = 0; i < 2_000_000; i++)
{
    var temporary = new Box(i);          // dies immediately: the cheap case
    checksum += temporary.Value;
}

Console.WriteLine($"checksum {checksum}");
Console.WriteLine($"gen 0 collections now:   {GC.CollectionCount(0)}");
Console.WriteLine($"gen 2 collections:       {GC.CollectionCount(2)}");
Console.WriteLine($"heap grew by about {(GC.GetTotalMemory(false) - before) / 1_000_000}MB");
Console.WriteLine("(indicative: the collector runs when it chooses)");

sealed class Box(int value) { public int Value { get; } = value; }
```

Two consequences. Short-lived garbage is nearly free, so contorting code to
avoid an allocation is usually not worth it. And an object that survives long
enough to reach gen 2 and then dies is the expensive case - which is exactly
what a cache with the wrong lifetime produces.

## What leaks in a language with a collector

An object is collectable when nothing can reach it. "Unreachable", not "unused",
is the rule - and every .NET leak is something still holding a reference.

```csharp
var publisher = new Publisher();

for (int i = 0; i < 3; i++)
{
    var subscriber = new Subscriber(i);
    publisher.Changed += subscriber.OnChanged;     // the publisher now holds it
}

publisher.Raise();
Console.WriteLine("three subscribers are unreachable from here - and still alive");
Console.WriteLine("because the event''s delegate list references them");

// The fix is to unsubscribe, which is what IDisposable is usually for.
var temporary = new Subscriber(99);
publisher.Changed += temporary.OnChanged;
publisher.Changed -= temporary.OnChanged;
publisher.Raise();

sealed class Publisher
{
    public event Action<string>? Changed;
    public void Raise() => Changed?.Invoke("event");
}

sealed class Subscriber(int id)
{
    public void OnChanged(string message) => Console.WriteLine($"  subscriber {id}: {message}");
}
```

The four classic sources: an event subscription never removed, a static
collection that only grows, a cached object with no eviction, and a `Timer` or
long-running task holding a closure over something large.

## IDisposable is for what the collector does not manage

The collector frees memory. It does not close a file handle, a socket, or a
database connection - those are operating-system resources with their own limits,
and the `IDisposable` pattern is how .NET releases them deterministically.

```csharp
using (var connection = new Connection("db"))
{
    connection.Use();
}
Console.WriteLine("closed at the end of the using block, not when the GC feels like it");

await using (var asyncConnection = new AsyncConnection("cache"))
{
    await asyncConnection.UseAsync();
}

sealed class Connection(string name) : IDisposable
{
    public void Use() => Console.WriteLine($"using {name}");
    public void Dispose() => Console.WriteLine($"disposed {name}");
}

sealed class AsyncConnection(string name) : IAsyncDisposable
{
    public async Task UseAsync()
    {
        await Task.Delay(1);
        Console.WriteLine($"using {name}");
    }

    public async ValueTask DisposeAsync()
    {
        await Task.Delay(1);
        Console.WriteLine($"disposed {name} asynchronously");
    }
}
```

A class that owns an `IDisposable` field should itself be `IDisposable` and
dispose it - the obligation travels up the ownership chain. And never write a
finaliser unless you own an unmanaged handle directly: it delays collection by a
whole generation and runs on a thread you do not control.

## Span<T>: working with memory without copying it

```csharp
string csv = "ada,36,uk";

// Substring allocates a new string each time. AsSpan does not.
ReadOnlySpan<char> span = csv.AsSpan();
int firstComma = span.IndexOf('','');
ReadOnlySpan<char> name = span[..firstComma];
Console.WriteLine($"name is {name} ({name.Length} chars, no allocation)");

// stackalloc puts a small buffer in the frame, so it is never collected at all.
Span<int> buffer = stackalloc int[8];
for (int i = 0; i < buffer.Length; i++) buffer[i] = i * i;
Console.WriteLine(string.Join(",", buffer.ToArray()));

// The restriction that makes it safe: a Span cannot be stored on the heap, so
// it cannot outlive the memory it points at. It cannot be a field of a class,
// and cannot be used across an await.
Console.WriteLine("Span is a stack-only type, and the compiler enforces it");
```

## What to take away

- Value types copy on assignment; reference types alias. That decides more than syntax does.
- The collector is generational: young garbage is cheap, promoted-then-dead is not.
- A leak is a reference you forgot: events, static collections, caches, timers.
- `IDisposable`/`using` is for OS resources - the collector does not close handles.
- Ownership of an `IDisposable` travels up: dispose what you own.
- `Span<T>` slices memory without allocating, and is stack-only so it cannot dangle.
',
   'Generations, the leaks a collector cannot prevent, IDisposable, and Span.',
   5, 917,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Where C# Spends Its Time
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000ab',
   'Where C# Spends Its Time',
   'markdown',
   '# Where C# Spends Its Time

Most .NET performance problems are one of four things: building strings in a
loop, allocating in a hot path, the wrong collection, and measuring the JIT''s
warm-up instead of the code.

```csharp
using System.Diagnostics;
using System.Text;

const int n = 40_000;
int checksum = 0;                      // used, so neither loop can be removed

var clock = Stopwatch.StartNew();
string concatenated = "";
for (int i = 0; i < n; i++) concatenated += ''x'';
long plusEquals = clock.ElapsedMilliseconds;
checksum += concatenated.Length;

clock.Restart();
var builder = new StringBuilder();
for (int i = 0; i < n; i++) builder.Append(''x'');
string built = builder.ToString();
long stringBuilder = clock.ElapsedMilliseconds;
checksum += built.Length;

Console.WriteLine($"+=            {plusEquals}ms");
Console.WriteLine($"StringBuilder {stringBuilder}ms");
Console.WriteLine($"builder is faster: {stringBuilder < plusEquals}");
Console.WriteLine($"both built {checksum / 2} characters");
```

A `string` is immutable, so `s += "x"` allocates a new one and copies everything
so far: the loop is quadratic. `StringBuilder` writes into one buffer that grows.
(A `+` in a single expression is compiled to `string.Concat` already - it is only
the *loop* that is the problem.)

## Allocation is the thing to watch

The collector is fast, but the cheapest allocation is the one that never
happens. Structs, spans and pooled buffers are how you avoid them.

```csharp
using System.Diagnostics;

const int n = 2_000_000;
var clock = Stopwatch.StartNew();

// Boxing: every int becomes an object on the heap.
long boxedTotal = 0;
for (int i = 0; i < n; i++)
{
    object boxed = i;                   // an allocation, every iteration
    boxedTotal += (int)boxed;
}
long boxedMs = clock.ElapsedMilliseconds;

clock.Restart();
long plainTotal = 0;
for (int i = 0; i < n; i++) plainTotal += i;
long plainMs = clock.ElapsedMilliseconds;

Console.WriteLine($"boxed  {boxedMs}ms -> {boxedTotal}");
Console.WriteLine($"plain  {plainMs}ms -> {plainTotal}");
Console.WriteLine($"same answer: {boxedTotal == plainTotal}");
Console.WriteLine($"gen 0 collections: {GC.CollectionCount(0)}");
```

The same effect hides in older APIs: a non-generic `ArrayList`, `string.Format`
with value types, and any interface call on a struct all box. Generic
collections do not, which is the main reason `List<int>` replaced `ArrayList`.

## The collection is the algorithm

```csharp
using System.Diagnostics;

const int n = 20_000;
List<int> haystack = Enumerable.Range(0, n).ToList();

var clock = Stopwatch.StartNew();
int foundByScan = 0;
for (int i = 0; i < n; i++) if (haystack.Contains(i)) foundByScan++;
long scan = clock.ElapsedMilliseconds;

var set = haystack.ToHashSet();
clock.Restart();
int foundByHash = 0;
for (int i = 0; i < n; i++) if (set.Contains(i)) foundByHash++;
long hash = clock.ElapsedMilliseconds;

Console.WriteLine($"List.Contains    {scan}ms");
Console.WriteLine($"HashSet.Contains {hash}ms");
Console.WriteLine($"same answer: {foundByScan == foundByHash}");

// And if the size is known, say so: a List that grows copies its array each
// time it doubles.
clock.Restart();
var grows = new List<int>();
for (int i = 0; i < 2_000_000; i++) grows.Add(i);
long growing = clock.ElapsedMilliseconds;

clock.Restart();
var sized = new List<int>(2_000_000);
for (int i = 0; i < 2_000_000; i++) sized.Add(i);
Console.WriteLine($"growing {growing}ms, presized {clock.ElapsedMilliseconds}ms");
```

## LINQ costs something, and it is usually worth it

Each LINQ stage is an iterator object and a delegate call per element. For a
hot inner loop over millions of items that shows up; for the other 99% of code
the readability is worth more than the nanoseconds.

```csharp
using System.Diagnostics;

int[] source = Enumerable.Range(1, 5_000_000).ToArray();

var clock = Stopwatch.StartNew();
long linq = source.Where(n => n % 2 == 0).Select(n => (long)n * 2).Sum();
long linqMs = clock.ElapsedMilliseconds;

clock.Restart();
long manual = 0;
foreach (int n in source)
{
    if (n % 2 == 0) manual += (long)n * 2;
}

Console.WriteLine($"LINQ  {linqMs}ms -> {linq}");
Console.WriteLine($"loop  {clock.ElapsedMilliseconds}ms -> {manual}");
Console.WriteLine($"same answer: {linq == manual}");
Console.WriteLine("measure before rewriting readable code into a loop");
```

## Why your first measurement is wrong

.NET compiles IL to machine code the first time a method runs, and tiered
compilation then recompiles the hot ones with better optimisation. Early
iterations measure the JIT, not the code.

```csharp
using System.Diagnostics;

for (int round = 1; round <= 5; round++)
{
    var clock = Stopwatch.StartNew();
    long total = 0;
    for (int i = 0; i < 5_000_000; i++) total += Work(i);
    Console.WriteLine($"round {round}: {clock.ElapsedMilliseconds}ms ({total})");
}

Console.WriteLine("the same loop five times - and the first is not like the last");

static long Work(int i) => (i % 7) * 3L;
```

Warm up before timing, run several rounds, keep the result so nothing can be
optimised away - or use **BenchmarkDotNet**, which handles warm-up, statistics
and the dead-code problem properly, and is the only thing worth quoting in an
argument.

## Measure the program, not your guess

Before optimising anything, find where the time goes: `dotnet-counters` for live
metrics, `dotnet-trace` for a profile, and the GC counters for allocation
pressure. Most "slow .NET" turns out to be an N+1 query, a lock everything
queues behind, a cache with no eviction, or an algorithm that is quadratic in
the input - none of them found by staring at the code.

## What to take away

- `StringBuilder` in a loop; `+=` on strings is quadratic.
- Boxing allocates: generics, structs and spans are how you avoid it.
- `HashSet`/`Dictionary` for membership; presize a `List<T>` when you know the size.
- LINQ costs a delegate call per element - worth it except in a hot inner loop.
- The JIT needs warm-up; use BenchmarkDotNet for anything you will act on.
- Profile first: it is usually a query, a lock, a cache, or the algorithm.
',
   'StringBuilder, boxing, the right collection, and why the first measurement is the JIT.',
   4, 893,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Arranging a C# Application
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000ac',
   'Arranging a C# Application',
   'markdown',
   '# Arranging a C# Application

An application that stays easy to change keeps its rules in one place, its I/O
at the edges, and its dependencies pointing inward: the domain knows nothing
about the database, ASP.NET, or the JSON serialiser.

## The domain is plain C#

No framework, no attributes, nothing that needs a host to test.

```csharp
var basket = new Basket([new Money(1999), new Money(2500), new Money(1200)]);
Console.WriteLine(basket.Total);
Console.WriteLine($"free delivery: {basket.QualifiesForFreeDelivery()}");

readonly record struct Money(long Pence)
{
    public static Money operator +(Money a, Money b) => new(a.Pence + b.Pence);
    public bool IsMoreThan(Money other) => Pence > other.Pence;
    public override string ToString() => $"{Pence / 100.0:F2}";
}

sealed class Basket
{
    private readonly IReadOnlyList<Money> _lines;

    // A defensive copy: without ToList() the caller keeps a handle on the list
    // inside this object and can change it afterwards.
    public Basket(IEnumerable<Money> lines) => _lines = lines.ToList();

    public Money Total => _lines.Aggregate(new Money(0), (sum, line) => sum + line);

    public bool QualifiesForFreeDelivery() => Total.IsMoreThan(new Money(5000));
}
```

Every rule there is testable with a constructor call and an assertion - no
database, no mocks, no `WebApplicationFactory`.

## Dependencies point inward

The domain declares what it needs as an interface it owns. The implementation
lives further out and is handed in through the constructor.

```csharp
ICourseRepository repository = new InMemoryCourses(new()
{
    ["csharp"] = new Course("csharp", "C#: From Basics to Expert"),
});

var useCase = new ViewCourse(repository);

foreach (string slug in new[] { "csharp", "cobol" })
{
    string message = useCase.Handle(slug) switch
    {
        Found(var course) => $"found {course.Title}",
        NotFound(var missing) => $"no course called {missing}",
        _ => "unreachable",
    };
    Console.WriteLine(message);
}

// --- domain ---------------------------------------------------------------
record Course(string Slug, string Title);

// The port: owned by the domain, implemented at the edge. The arrow points in.
interface ICourseRepository
{
    Course? FindBySlug(string slug);
}

abstract record Outcome;
sealed record Found(Course Course) : Outcome;
sealed record NotFound(string Slug) : Outcome;

sealed class ViewCourse(ICourseRepository courses)
{
    public Outcome Handle(string slug)
        => courses.FindBySlug(slug) is { } course ? new Found(course) : new NotFound(slug);
}

// --- edge -----------------------------------------------------------------
// In production this is EF Core or Dapper. In a test it is three lines.
sealed class InMemoryCourses(Dictionary<string, Course> rows) : ICourseRepository
{
    public Course? FindBySlug(string slug) => rows.GetValueOrDefault(slug);
}
```

Three things are doing work. The repository interface is declared *with the
rules*, so the database depends on the domain rather than the other way round.
The dependency arrives through the primary constructor, so a `ViewCourse` cannot
exist in an unusable state. And the result is a type the caller must inspect,
rather than a null or an exception it may ignore.

## Projects, namespaces and what to make public

In .NET the compilation boundary is the **project**, and `internal` - the
default for a type - means "visible inside this assembly". That makes the
project the real unit of design.

```text
src/
  Omniacad.Catalogue/              rules and ports. References nothing.
    Course.cs                      public
    ICourseRepository.cs           public
    ViewCourse.cs                  public
  Omniacad.Catalogue.Sql/          an adapter. References Catalogue.
    SqlCourseRepository.cs         internal, plus one public registration method
  Omniacad.Web/                    the host. References both.
    Program.cs                     the composition root
tests/
  Omniacad.Catalogue.Tests/        fast, no database
```

The dependency arrows are enforced by the project references: `Catalogue` cannot
accidentally use EF Core, because it does not reference it. That is worth more
than any amount of documentation about layering.

## One composition root, deliberately dull

```csharp
// In an ASP.NET application this is Program.cs and the container does the
// wiring; the shape is the same either way, and so is the rule: this is the
// only file that knows every concrete type.
var services = new Dictionary<Type, object>();

IClock clock = new FixedClock(1_700_000_000);
IMailer mailer = new ConsoleMailer();
services[typeof(Notifier)] = new Notifier(clock, mailer);

var notifier = (Notifier)services[typeof(Notifier)];
notifier.Welcome("ada@example.com");

interface IClock { long Now(); }
interface IMailer { void Send(string to, string subject); }

sealed class FixedClock(long now) : IClock { public long Now() => now; }
sealed class ConsoleMailer : IMailer
{
    public void Send(string to, string subject) => Console.WriteLine($"to {to}: {subject}");
}

sealed class Notifier(IClock clock, IMailer mailer)
{
    public void Welcome(string address) => mailer.Send(address, $"Welcome, at {clock.Now()}");
}
```

Anything clever in the composition root is something that cannot be tested.

## What the build should enforce

Turn on `<Nullable>enable</Nullable>`, `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`
and `<AnalysisLevel>latest</AnalysisLevel>` in `Directory.Build.props`, and add
an `.editorconfig`. A team that argues about style in review is spending review
on the wrong thing - and a nullable warning ignored today is a
`NullReferenceException` in production later.

```csharp
// A test against a plain domain needs no setup and runs in a millisecond.
// In a project this is xUnit; the assertions are the same shape.
AssertEqual(new Money(300), new Money(100) + new Money(200));
AssertEqual(new Money(0), new Money(0) + new Money(0));
Console.WriteLine("2 assertions passed");

static void AssertEqual<T>(T expected, T actual)
{
    if (!Equals(expected, actual))
    {
        throw new InvalidOperationException($"expected {expected} but was {actual}");
    }
}

readonly record struct Money(long Pence)
{
    public static Money operator +(Money a, Money b) => new(a.Pence + b.Pence);
}
```

## What to take away

- Domain rules in plain C#; I/O at the edges; dependencies pointing inward.
- The domain owns the interface; the adapter implements it and is handed in.
- Project references enforce the layering - the domain cannot use what it does not reference.
- Defensive copies keep a collection genuinely owned by the object that holds it.
- A result type makes the caller handle the outcome; `internal` is the right default.
- Nullable on, warnings as errors, and one composition root that stays boring.
',
   'Plain-C# rules, interfaces the domain owns, internal by default, one composition root.',
   5, 913,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-00000000000d');
CALL search_reindex_all();
