-- ===========================================================================
-- Seed 26 : the Go course, basics -> intermediate -> advanced -> expert
--
-- These lessons carry ```go fences, and like the Dart and Java courses
-- there is no browser runner behind them: the playground cannot run
-- Go, so the front end renders these as plain code blocks with no Try
-- yourself button. CODE_FENCE_PATTERN in the website lists the runnable
-- languages, and go is deliberately not one of them.
--
-- That makes the examples' correctness this file's problem rather than the
-- learner's. Every fence below was compiled and executed against
-- the Go toolchain (1.24), with that compiler's own warnings
-- treated as errors, by scratchpad/gen/checklang.py - before it was written
-- out, and again after being read back out of MySQL.
--
-- Generated by scratchpad/gen/build_batch5.py - the bodies are full of quotes,
-- backslashes and format specifiers, and escaping those by hand is how a seed
-- gets broken.
-- ===========================================================================

INSERT INTO catalog_tags (id, slug, name) VALUES
  ('bbbbbbb1-0000-4000-8000-000000000017', 'go', 'Go')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO catalog_courses
  (id, slug, title, subtitle, description, category_id, instructor_id, level, status,
   thumbnail_url, price_cents, learning_outcomes, requirements, published_at)
VALUES
  ('c0000001-0000-4000-8000-00000000000e',
   'go-from-basics-to-expert',
   'Go: From Basics to Expert',
   'Four levels, twelve lessons, every example vetted and run on a real toolchain',
   'A complete path through Go in four levels, taught on Go 1.24. Level 1, Basic, covers the zero value that is always usable, the absence of implicit conversions, one loop keyword, and the slice aliasing that surprises everyone exactly once. Level 2, Intermediate, is structs and methods with the receiver decision you make constantly, interfaces satisfied implicitly and declared by the code that consumes them, generics, and errors as ordinary values with wrapping, errors.Is and errors.As. Level 3, Advanced, covers goroutines and channels and the four deadlocks you will actually hit, context and worker pools and pipelines, and the parts of the standard library that turn up in every program. Level 4, Expert, finishes with escape analysis and the leaks a collector cannot prevent, where the time and allocations go, and how to arrange a module so a change stays small.

Every example in this course was run through go vet and executed on a real Go toolchain before publication. There is no in-browser Go runner yet, so the code blocks are for reading and for running in your own editor.

There is no in-browser runner for this language on the site, so to follow along install it from go.dev and run each one with go run main.go, or paste it into the Go playground.',
   'aaaaaaa1-0000-4000-8000-000000000001',
   '55555555-5555-4555-8555-555555555555',
   'beginner', 'published',
   'https://images.example-cdn.test/courses/go-from-basics-to-expert.jpg', 0,
   JSON_ARRAY('Rely on the zero value, and know why a nil map cannot be written',
              'Explain what append does to a shared backing array',
              'Choose a pointer or a value receiver for a reason you can state',
              'Wrap errors so the final message reads like a path to the cause',
              'Say who closes a channel, and how a goroutine is told to stop',
              'Arrange a module so the interface belongs to the code that uses it'),
   JSON_ARRAY('No prior Go', 'Some experience of any programming language helps but is not required'),
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), subtitle = VALUES(subtitle), description = VALUES(description),
  learning_outcomes = VALUES(learning_outcomes), requirements = VALUES(requirements);

INSERT INTO catalog_course_tags (course_id, tag_id) VALUES
  ('c0000001-0000-4000-8000-00000000000e', 'bbbbbbb1-0000-4000-8000-000000000017'),
  ('c0000001-0000-4000-8000-00000000000e', 'bbbbbbb1-0000-4000-8000-000000000007')
ON DUPLICATE KEY UPDATE course_id = VALUES(course_id);

INSERT INTO catalog_modules (id, course_id, title, summary, `position`) VALUES
  ('d0000001-0000-4000-8000-000000000030', 'c0000001-0000-4000-8000-00000000000e',
   'Level 1 - Basic', 'The zero value, no implicit conversions, and the slice aliasing that surprises everyone.', 1),
  ('d0000001-0000-4000-8000-000000000031', 'c0000001-0000-4000-8000-00000000000e',
   'Level 2 - Intermediate', 'Structs and methods, implicit interfaces and generics, and errors as values.', 2),
  ('d0000001-0000-4000-8000-000000000032', 'c0000001-0000-4000-8000-00000000000e',
   'Level 3 - Advanced', 'Goroutines and channels, context and worker pools, and the standard library.', 3),
  ('d0000001-0000-4000-8000-000000000033', 'c0000001-0000-4000-8000-00000000000e',
   'Level 4 - Expert', 'Escape analysis and leaks, where the time goes, and how a module is arranged.', 4)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary);

INSERT INTO catalog_lessons
  (id, module_id, course_id, slug, title, summary, kind, status, `position`,
   duration_seconds, is_free_preview)
VALUES
  ('e0000001-0000-4000-8000-0000000000b1', 'd0000001-0000-4000-8000-000000000030', 'c0000001-0000-4000-8000-00000000000e',
   'go-values-and-types', 'Values, Types and the Zero Value',
   'The zero value that is always usable, no implicit conversions, bytes against runes.',
   'article', 'published', 1, 720, 1),
  ('e0000001-0000-4000-8000-0000000000b2', 'd0000001-0000-4000-8000-000000000030', 'c0000001-0000-4000-8000-00000000000e',
   'go-control-flow', 'Control Flow, Functions and defer',
   'One loop keyword, if with a statement, multiple returns, and defer''s LIFO order.',
   'article', 'published', 2, 660, 1),
  ('e0000001-0000-4000-8000-0000000000b3', 'd0000001-0000-4000-8000-000000000030', 'c0000001-0000-4000-8000-00000000000e',
   'go-collections', 'Slices, Maps and the Aliasing That Surprises You',
   'Arrays copy and slices share, what append really does, and the comma-ok idiom.',
   'article', 'published', 3, 780, 0),
  ('e0000001-0000-4000-8000-0000000000b4', 'd0000001-0000-4000-8000-000000000031', 'c0000001-0000-4000-8000-00000000000e',
   'go-structs-and-methods', 'Structs, Methods and Composition',
   'Pointer against value receivers, embedding without inheritance, and exported fields.',
   'article', 'published', 1, 840, 0),
  ('e0000001-0000-4000-8000-0000000000b5', 'd0000001-0000-4000-8000-000000000031', 'c0000001-0000-4000-8000-00000000000e',
   'go-interfaces', 'Interfaces, Type Switches and Generics',
   'Implicit satisfaction, small consumer-declared interfaces, and the nil interface trap.',
   'article', 'published', 2, 840, 0),
  ('e0000001-0000-4000-8000-0000000000b6', 'd0000001-0000-4000-8000-000000000031', 'c0000001-0000-4000-8000-00000000000e',
   'go-errors', 'Errors Are Values',
   'Wrapping with %w, errors.Is and errors.As, and why panic is only for bugs.',
   'article', 'published', 3, 780, 0),
  ('e0000001-0000-4000-8000-0000000000b7', 'd0000001-0000-4000-8000-000000000032', 'c0000001-0000-4000-8000-00000000000e',
   'go-goroutines', 'Goroutines and Channels',
   'WaitGroups, unbuffered channels as synchronisation, select, and the four deadlocks.',
   'article', 'published', 1, 840, 0),
  ('e0000001-0000-4000-8000-0000000000b8', 'd0000001-0000-4000-8000-000000000032', 'c0000001-0000-4000-8000-00000000000e',
   'go-context-and-patterns', 'Context, Pipelines and Worker Pools',
   'ctx.Done(), worker pools, pipelines, and the goroutine leak that never gets collected.',
   'article', 'published', 2, 900, 0),
  ('e0000001-0000-4000-8000-0000000000b9', 'd0000001-0000-4000-8000-000000000032', 'c0000001-0000-4000-8000-00000000000e',
   'go-stdlib', 'The Standard Library You Will Actually Use',
   'encoding/json and its struct tags, time layouts by example, io composition, slices and maps.',
   'article', 'published', 3, 840, 0),
  ('e0000001-0000-4000-8000-0000000000ba', 'd0000001-0000-4000-8000-000000000033', 'c0000001-0000-4000-8000-00000000000e',
   'go-memory', 'Memory, Escape Analysis and the Collector',
   'Escape analysis, the slice that holds a megabyte alive, and when to use a pointer.',
   'article', 'published', 1, 840, 0),
  ('e0000001-0000-4000-8000-0000000000bb', 'd0000001-0000-4000-8000-000000000033', 'c0000001-0000-4000-8000-00000000000e',
   'go-performance', 'Where Go Spends Its Time',
   'strings.Builder, preallocation, map[T]struct{}, and benchmarks that mean something.',
   'article', 'published', 2, 840, 0),
  ('e0000001-0000-4000-8000-0000000000bc', 'd0000001-0000-4000-8000-000000000033', 'c0000001-0000-4000-8000-00000000000e',
   'go-architecture', 'Arranging a Go Application',
   'internal/ as real privacy, consumer-declared interfaces, and table-driven tests.',
   'article', 'published', 3, 900, 0),
  ('e0000001-0000-4000-8000-0000000000bd', 'd0000001-0000-4000-8000-000000000030', 'c0000001-0000-4000-8000-00000000000e',
   'go-level-1-check', 'Level 1 Check: Zero Values, Slices and Maps',
   'Five questions on the nil map, slice aliasing, conversions and defer.',
   'quiz', 'published', 4, 420, 1),
  ('e0000001-0000-4000-8000-0000000000be', 'd0000001-0000-4000-8000-000000000031', 'c0000001-0000-4000-8000-00000000000e',
   'go-level-2-check', 'Level 2 Check: Methods, Interfaces and Errors',
   'Five questions on receivers, implicit satisfaction, the nil interface and error wrapping.',
   'quiz', 'published', 4, 480, 0),
  ('e0000001-0000-4000-8000-0000000000bf', 'd0000001-0000-4000-8000-000000000032', 'c0000001-0000-4000-8000-00000000000e',
   'go-level-3-check', 'Level 3 Check: Goroutines, Channels and Context',
   'Five questions on who closes, what blocks, context and goroutine leaks.',
   'quiz', 'published', 4, 540, 0),
  ('e0000001-0000-4000-8000-0000000000c0', 'd0000001-0000-4000-8000-000000000033', 'c0000001-0000-4000-8000-00000000000e',
   'go-expert-exam', 'Expert Exam: Go',
   'Escape analysis, preallocation, internal/, and where an interface belongs.',
   'quiz', 'published', 4, 900, 0)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary), `position` = VALUES(`position`);

-- ---------------------------------------------------------------------------
-- Values, Types and the Zero Value
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b1',
   'Values, Types and the Zero Value',
   'markdown',
   '# Values, Types and the Zero Value

Go is statically typed with a deliberately small type system. There are no
classes, no inheritance, no exceptions and no implicit conversions - and the
language is smaller than the list of things it leaves out suggests.

```go
package main

import "fmt"

func main() {
	var count int = 42        // the full form
	var ratio = 0.5           // the type is inferred
	name := "Ada"             // short form: declare and assign, inside a function
	ready := true

	fmt.Printf("%T %T %T %T\\n", count, ratio, name, ready)
	fmt.Println(count, ratio, name, ready)

	// %v prints a value, %+v adds field names, %#v prints Go syntax.
	type point struct{ X, Y int }
	p := point{1, 2}
	fmt.Printf("%v %+v %#v\\n", p, p, p)
}
```

`:=` only works inside a function. At package level you need `var`.

## Every type has a zero value, and it is always usable

There is no uninitialised variable in Go. A declared variable starts at its
type''s zero value: `0`, `false`, `""`, and `nil` for pointers, slices, maps,
channels, functions and interfaces.

```go
package main

import "fmt"

type Config struct {
	Name    string
	Retries int
	Debug   bool
	Tags    []string
}

func main() {
	var i int
	var s string
	var b bool
	var p *int
	var slice []string
	var m map[string]int

	fmt.Printf("int=%d string=%q bool=%t pointer=%v\\n", i, s, b, p)
	fmt.Printf("slice=%v nil? %t len=%d\\n", slice, slice == nil, len(slice))
	fmt.Printf("map=%v nil? %t len=%d\\n", m, m == nil, len(m))

	// A nil slice is usable: append works on it, and so does range.
	slice = append(slice, "now it has something")
	fmt.Println(slice)

	// A nil map is readable but NOT writable - this is the one that catches people.
	fmt.Println(m["missing"])        // 0, no panic
	// m["key"] = 1                  // panic: assignment to entry in nil map

	// A struct''s zero value is every field''s zero value, and is often useful
	// as-is. Designing for that is idiomatic Go.
	var config Config
	fmt.Printf("%+v\\n", config)
}
```

## No implicit conversions, at all

```go
package main

import "fmt"

func main() {
	var i int = 42
	var f float64 = float64(i)      // explicit, always
	var u uint8 = uint8(i)

	fmt.Println(i, f, u)

	// var broken float64 = i       // will not compile: int is not float64

	// Which also means integer division truncates, and you convert first.
	a, b := 7, 2
	fmt.Println(a/b, float64(a)/float64(b))

	// Conversions can silently lose data, so the compiler makes you ask for it.
	big := 300
	fmt.Println(uint8(big))         // 44: wrapped, because you said to

	// Untyped constants are the exception: they take the type they are used at.
	const ratio = 1.5
	var scaled float64 = ratio * 2
	fmt.Println(scaled)
}
```

## Strings are bytes; runes are characters

A Go string is an immutable sequence of **bytes**, usually holding UTF-8.
`len()` counts bytes. Ranging over a string yields **runes** - Unicode code
points - along with the byte offset each one started at.

```go
package main

import (
	"fmt"
	"strings"
	"unicode/utf8"
)

func main() {
	s := "héllo"

	fmt.Println(len(s))                    // 6 bytes: é takes two
	fmt.Println(utf8.RuneCountInString(s)) // 5 characters

	for i, r := range s {
		fmt.Printf("  byte %d: %c (%d)\\n", i, r, r)
	}

	fmt.Println(s[0])                      // a byte: 104
	fmt.Printf("%c\\n", []rune(s)[1])       // a rune: é

	fmt.Println(strings.ToUpper(s), strings.Contains(s, "ll"))
	fmt.Println(strings.Split("a,b,c", ","))
	fmt.Println(strings.TrimSpace("  padded  "))

	// Strings are immutable, so build with a Builder rather than +=.
	var b strings.Builder
	for i := 0; i < 5; i++ {
		fmt.Fprintf(&b, "%d,", i)
	}
	fmt.Println(b.String())
}
```

## Pointers, without the arithmetic

Go has pointers and no pointer arithmetic. `&x` takes an address, `*p` reads
through one, and the dot operator dereferences automatically.

```go
package main

import "fmt"

type Counter struct{ n int }

func (c *Counter) Increment() { c.n++ }       // a pointer receiver can change it
func (c Counter) Value() int  { return c.n }  // a value receiver sees a copy

func main() {
	x := 1
	p := &x
	*p = 42
	fmt.Println(x, *p, p != nil)

	// Passing a pointer is how a function changes the caller''s value.
	double(&x)
	fmt.Println(x)

	c := Counter{}
	c.Increment()          // Go takes the address for you
	c.Increment()
	fmt.Println(c.Value())

	// new(T) allocates a zero T and returns a pointer to it.
	q := new(int)
	fmt.Println(*q)
}

func double(n *int) { *n *= 2 }
```

## What to take away

- `:=` inside functions, `var` at package level; types are inferred either way.
- Every type has a usable zero value - and a nil map can be read but not written.
- No implicit conversions, ever: `float64(i)`, and the compiler makes you mean it.
- A string is bytes; `len` counts bytes, `range` yields runes.
- Build strings with `strings.Builder`, not `+=` in a loop.
- Pointers, but no arithmetic; `.` dereferences for you.
',
   'The zero value that is always usable, no implicit conversions, bytes against runes.',
   4, 803,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Control Flow, Functions and defer
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b2',
   'Control Flow, Functions and defer',
   'markdown',
   '# Control Flow, Functions and defer

Go has one loop keyword, no parentheses around conditions, and compulsory
braces. The syntax is small enough to hold in your head, which is the point.

```go
package main

import "fmt"

func main() {
	scores := []int{88, 42, 95, 61}

	for i, score := range scores {          // range: index and value
		fmt.Printf("%d: %s\\n", i, grade(score))
	}

	for _, score := range scores {          // _ discards the index
		if score > 90 {
			break
		}
	}

	for i := 0; i < 3; i++ {                // the C-style form
		fmt.Println("i =", i)
	}

	countdown := 3
	for countdown > 0 {                     // this is Go''s "while"
		fmt.Println("t-minus", countdown)
		countdown--
	}

	n := 0
	for {                                   // and this is "forever"
		n++
		if n > 2 {
			break
		}
	}
	fmt.Println("looped", n, "times")
}

func grade(score int) string {
	if score >= 90 {
		return "excellent"
	} else if score >= 60 {
		return "pass"
	}
	return "resit"
}
```

## if with a statement, and why it shortens everything

An `if` may run a short statement first, and anything it declares is scoped to
the if and its else. That is the shape of almost every error check in Go.

```go
package main

import (
	"fmt"
	"strconv"
)

func main() {
	for _, text := range []string{"42", "not a number"} {
		// n and err exist only inside this if/else.
		if n, err := strconv.Atoi(text); err == nil {
			fmt.Println("parsed", n)
		} else {
			fmt.Println("failed:", err)
		}
	}

	// The same shape with a map lookup: the comma-ok idiom.
	stock := map[string]int{"apples": 3}
	if count, ok := stock["pears"]; ok {
		fmt.Println("pears:", count)
	} else {
		fmt.Println("no pears at all")
	}
}
```

## switch: no fallthrough, and no condition needed

```go
package main

import "fmt"

func main() {
	for _, code := range []int{200, 302, 404, 500} {
		fmt.Printf("%d -> %s\\n", code, describe(code))
	}
	fmt.Println(categorise(-1), categorise(5), categorise(500))
}

func describe(code int) string {
	switch code {
	case 200:
		return "ok"
	case 301, 302:            // several values, one case
		return "redirected"
	case 404:
		return "not found"
	default:
		return "something else"
	}
}

// A switch with no expression is a tidier if/else chain.
func categorise(n int) string {
	switch {
	case n < 0:
		return "negative"
	case n < 10:
		return "small"
	case n < 100:
		return "medium"
	default:
		return "large"
	}
}
```

Cases do not fall through - there is no `break` to forget. `fallthrough` exists
for the rare case where you want it, and saying so explicitly is the right way
round.

## Functions return more than one thing

This is how Go does errors, and it shapes the whole language.

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	lo, hi := minMax([]int{5, 2, 9, 1})
	fmt.Println(lo, hi)

	if value, err := lookup("known"); err == nil {
		fmt.Println(value)
	}

	if _, err := lookup("missing"); err != nil {
		fmt.Println("error:", err)
	}

	fmt.Println(join("-", "a", "b", "c"))
	fmt.Println(join("-"))

	// Named results document what comes back, and are occasionally useful with
	// defer. Do not use them just to save typing.
	fmt.Println(split(17))
}

func minMax(values []int) (int, int) {
	lo, hi := values[0], values[0]
	for _, v := range values {
		if v < lo {
			lo = v
		}
		if v > hi {
			hi = v
		}
	}
	return lo, hi
}

func lookup(key string) (string, error) {
	if key != "known" {
		return "", fmt.Errorf("no value for %q", key)
	}
	return "found it", nil
}

func join(sep string, parts ...string) string {   // variadic
	return strings.Join(parts, sep)
}

func split(sum int) (x, y int) {
	x = sum * 4 / 9
	y = sum - x
	return                                        // returns the named results
}
```

## defer runs on the way out

`defer` schedules a call for when the surrounding function returns - however it
returns. It is how Go closes files, unlocks mutexes, and undoes things without a
`finally`.

```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println(readAll("first\\nsecond\\n"))

	// Deferred calls run last-in, first-out.
	order()

	// Arguments are evaluated at the DEFER, not at the call. This catches
	// everyone once.
	x := 1
	defer fmt.Println("deferred saw x =", x)   // prints 1, not 2
	x = 2
	fmt.Println("at the end, x =", x)
}

func readAll(text string) int {
	reader := strings.NewReader(text)
	defer fmt.Println("  (reader released)")   // runs even on an early return

	count := 0
	for {
		var line string
		if _, err := fmt.Fscanln(reader, &line); err != nil {
			break
		}
		count++
	}
	return count
}

func order() {
	for i := 1; i <= 3; i++ {
		defer fmt.Println("  deferred", i)
	}
	fmt.Println("order() is returning")
}
```

## Closures capture the variable

```go
package main

import "fmt"

func main() {
	next := counter()
	fmt.Println(next(), next(), next())

	other := counter()
	fmt.Println(other())

	// Since Go 1.22 each iteration gets a fresh loop variable, so these three
	// closures capture three different values. In older Go they all saw 3.
	var fns []func()
	for i := 1; i <= 3; i++ {
		fns = append(fns, func() { fmt.Print(i, " ") })
	}
	for _, f := range fns {
		f()
	}
	fmt.Println()
}

func counter() func() int {
	count := 0                  // one variable, captured
	return func() int {
		count++
		return count
	}
}
```

## What to take away

- One loop keyword: `for` covers while, for-each and forever.
- `if err := f(); err != nil` scopes the error to the check - the commonest shape in Go.
- `switch` does not fall through, and needs no expression.
- Multiple return values are how Go reports errors, and why it needs no exceptions.
- `defer` runs on the way out, LIFO, with arguments evaluated at the defer.
- Since Go 1.22 a loop variable is fresh each iteration, which fixed a classic trap.
',
   'One loop keyword, if with a statement, multiple returns, and defer''s LIFO order.',
   5, 982,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Slices, Maps and the Aliasing That Surprises You
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b3',
   'Slices, Maps and the Aliasing That Surprises You',
   'markdown',
   '# Slices, Maps and the Aliasing That Surprises You

Go has arrays, slices and maps. You will use slices and maps; the array exists
mainly so that slices have something to point at, and understanding that is what
explains every slice surprise.

```go
package main

import "fmt"

func main() {
	// An array has a FIXED length, and the length is part of its type.
	var array [3]int
	array[0] = 1
	fmt.Printf("%T %v\\n", array, array)

	// A slice is a view onto an array: a pointer, a length and a capacity.
	slice := []int{1, 2, 3}
	fmt.Printf("%T len=%d cap=%d %v\\n", slice, len(slice), cap(slice), slice)

	// Assigning an array COPIES it. Assigning a slice shares the backing array.
	other := array
	other[0] = 99
	fmt.Println("array:", array, "other:", other)

	alias := slice
	alias[0] = 99
	fmt.Println("slice:", slice, "alias:", alias)
}
```

## append, and the copy you did not ask for

`append` returns a slice. If the backing array has spare capacity it writes in
place; if not, it allocates a bigger array and copies. Both behaviours are
correct, and the difference is visible when two slices share an array.

```go
package main

import "fmt"

func main() {
	base := make([]int, 3, 5)          // len 3, cap 5
	fmt.Printf("len=%d cap=%d %v\\n", len(base), cap(base), base)

	// Room to spare: append writes into the SAME array.
	grown := append(base, 4)
	grown[0] = 99
	fmt.Println("base:", base, "grown:", grown, "- they share an array")

	// No room: append allocates a new one, and they stop sharing.
	full := []int{1, 2, 3}
	fmt.Printf("before: len=%d cap=%d\\n", len(full), cap(full))
	extended := append(full, 4)
	extended[0] = 99
	fmt.Println("full:", full, "extended:", extended, "- separate arrays now")

	// Which is why you always assign the result back:
	full = append(full, 5)
	fmt.Println(full)

	// A slice of a slice shares memory too, and holds the WHOLE array alive.
	big := make([]byte, 1_000_000)
	small := big[:10]
	fmt.Println(len(small), cap(small), "- the megabyte cannot be collected")

	independent := make([]byte, 10)
	copy(independent, big[:10])         // copy is how you break the link
	fmt.Println(len(independent), cap(independent))
}
```

## Slicing, and the three-index form

```go
package main

import "fmt"

func main() {
	letters := []string{"a", "b", "c", "d", "e"}

	fmt.Println(letters[1:3])      // b c - the end is exclusive
	fmt.Println(letters[:2])
	fmt.Println(letters[3:])
	fmt.Println(letters[:])

	// The capacity of a slice runs to the end of the backing array, so an
	// append can overwrite what comes after.
	head := letters[:2]
	fmt.Printf("len=%d cap=%d\\n", len(head), cap(head))
	head = append(head, "OVERWRITTEN")
	fmt.Println(letters)

	// The three-index form caps it, so append must allocate instead.
	fresh := []string{"a", "b", "c", "d", "e"}
	safe := fresh[:2:2]
	safe = append(safe, "appended")
	fmt.Println(fresh, safe)
}
```

## Maps

```go
package main

import (
	"fmt"
	"sort"
)

func main() {
	stock := map[string]int{"apples": 3, "pears": 0}

	// Reading a missing key gives the zero value, not an error.
	fmt.Println(stock["apples"], stock["plums"])

	// The comma-ok idiom distinguishes "absent" from "present and zero".
	if count, ok := stock["pears"]; ok {
		fmt.Println("pears present, count", count)
	}
	if _, ok := stock["plums"]; !ok {
		fmt.Println("plums absent")
	}

	stock["plums"] = 7
	delete(stock, "pears")
	fmt.Println(len(stock))

	// Iteration order is RANDOMISED, deliberately - so nobody can depend on it.
	keys := make([]string, 0, len(stock))
	for key := range stock {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Printf("  %s=%d\\n", key, stock[key])
	}

	// A map value is not addressable: you cannot modify a struct field in place.
	type counter struct{ n int }
	counters := map[string]counter{"a": {1}}
	// counters["a"].n++            // will not compile
	c := counters["a"]
	c.n++
	counters["a"] = c
	fmt.Println(counters)

	// A map of pointers avoids that, at the cost of nil handling.
	pointers := map[string]*counter{"a": {1}}
	pointers["a"].n++
	fmt.Println(pointers["a"].n)
}
```

## Passing slices and maps to functions

A slice header is copied, but the array it points at is not - so a function can
change the elements but cannot change the caller''s length. A map is a reference,
so a function can add to it.

```go
package main

import "fmt"

func main() {
	numbers := []int{1, 2, 3}
	mutate(numbers)
	fmt.Println("after mutate:", numbers)      // changed

	appendTo(numbers)
	fmt.Println("after appendTo:", numbers)    // NOT changed

	numbers = appendAndReturn(numbers)
	fmt.Println("after returning:", numbers)   // changed, because it was returned

	stock := map[string]int{}
	addTo(stock)
	fmt.Println("map:", stock)                 // changed: maps are references
}

func mutate(values []int)  { values[0] = 99 }
func appendTo(values []int) { values = append(values, 4); _ = values }
func appendAndReturn(values []int) []int { return append(values, 4) }
func addTo(m map[string]int) { m["added"] = 1 }
```

## What to take away

- An array is a value and copies; a slice is a view and shares.
- `append` may write in place or reallocate - always assign the result back.
- A small slice of a big array keeps the whole array alive; `copy` breaks the link.
- `s[:2:2]` caps the capacity so an append cannot overwrite what follows.
- Reading a missing map key gives the zero value; `v, ok := m[k]` tells you which.
- Map iteration order is deliberately random - sort the keys when order matters.
',
   'Arrays copy and slices share, what append really does, and the comma-ok idiom.',
   4, 836,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Structs, Methods and Composition
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b4',
   'Structs, Methods and Composition',
   'markdown',
   '# Structs, Methods and Composition

Go has no classes and no inheritance. It has structs, methods on any named type,
and embedding - and between them they cover what inheritance was for, without
the fragile base class.

```go
package main

import "fmt"

type Temperature struct {
	celsius float64            // lower case: unexported, private to the package
}

// A constructor is just a function. Go has no special syntax for one, and
// returning (T, error) is how it reports invalid input.
func NewTemperature(celsius float64) (Temperature, error) {
	if celsius < -273.15 {
		return Temperature{}, fmt.Errorf("below absolute zero: %.2f", celsius)
	}
	return Temperature{celsius: celsius}, nil
}

// A method is a function with a receiver. This one takes a copy.
func (t Temperature) Celsius() float64    { return t.celsius }
func (t Temperature) Fahrenheit() float64 { return t.celsius*9/5 + 32 }

// The String() method is what fmt uses when it prints the value.
func (t Temperature) String() string { return fmt.Sprintf("%.1fC", t.celsius) }

func main() {
	t, err := NewTemperature(21)
	if err != nil {
		panic(err)
	}
	fmt.Println(t, t.Fahrenheit())

	if _, err := NewTemperature(-300); err != nil {
		fmt.Println("rejected:", err)
	}
}
```

## Value receivers copy; pointer receivers do not

This is the decision you make on every method, and the rule is simple: if the
method changes the receiver, or the struct is large, use a pointer. Then use a
pointer for *all* of that type''s methods, so the set is consistent.

```go
package main

import "fmt"

type Counter struct{ n int }

func (c Counter) IncrementByValue()   { c.n++ }        // changes a copy: useless
func (c *Counter) IncrementByPointer() { c.n++ }       // changes the original
func (c Counter) Value() int           { return c.n }

func main() {
	c := Counter{}

	c.IncrementByValue()
	fmt.Println("after value receiver:  ", c.Value())

	c.IncrementByPointer()             // Go takes &c for you
	c.IncrementByPointer()
	fmt.Println("after pointer receiver:", c.Value())

	// The copy is real: this is the bug the value receiver hides.
	counters := []Counter{{}, {}}
	for _, counter := range counters {
		counter.IncrementByPointer()   // ranges over COPIES
	}
	fmt.Println("range over values:", counters[0].Value())

	for i := range counters {
		counters[i].IncrementByPointer()   // index into the real elements
	}
	fmt.Println("range over indexes:", counters[0].Value())
}
```

## Struct literals, and why field names matter

```go
package main

import "fmt"

type Course struct {
	Slug     string
	Title    string
	Lessons  int
	Free     bool
}

func main() {
	// Named fields: readable, and survives a field being added.
	a := Course{Slug: "go", Title: "Go: From Basics to Expert", Lessons: 12}
	fmt.Printf("%+v\\n", a)

	// Positional: compiles today, breaks the day someone reorders the struct.
	b := Course{"go", "Go", 12, true}
	fmt.Printf("%+v\\n", b)

	// Zero values fill in whatever you leave out.
	c := Course{Slug: "minimal"}
	fmt.Printf("%+v\\n", c)

	// A pointer to a struct, which is what most constructors return.
	d := &Course{Slug: "pointer"}
	d.Lessons = 5                      // no (*d).Lessons needed
	fmt.Printf("%+v\\n", *d)

	// Structs compare with == when every field is comparable.
	fmt.Println(a == Course{Slug: "go", Title: "Go: From Basics to Expert", Lessons: 12})
}
```

## Embedding is composition with promotion

Embed a type and its fields and methods are promoted to the outer type. This is
not inheritance: there is no base class, no virtual dispatch, and the embedded
value is just a field with a convenient name.

```go
package main

import "fmt"

type Logger struct {
	prefix string
}

func (l Logger) Log(message string) {
	fmt.Printf("[%s] %s\\n", l.prefix, message)
}

type Job struct {
	Logger                       // embedded: no field name
	Name string
}

// The outer type can override by declaring its own method with the same name.
type QuietJob struct {
	Logger
	Name string
}

func (q QuietJob) Log(string) {}       // does nothing, deliberately

func main() {
	job := Job{Logger: Logger{prefix: "nightly"}, Name: "backup"}
	job.Log("started")                 // promoted from Logger
	job.Logger.Log("and reachable by name too")

	quiet := QuietJob{Logger: Logger{prefix: "quiet"}, Name: "silent"}
	quiet.Log("you will not see this")
	quiet.Logger.Log("but the embedded one still works")

	fmt.Println(job.Name, quiet.Name)
}
```

The important difference from inheritance: `Job` is not a `Logger` for the
purposes of dispatch. If `Logger` had a method that called `Log`, it would call
*its own* `Log`, not the outer type''s. Go has no virtual methods, and interfaces
(the next lesson) are how you get polymorphism.

## Struct tags, for the packages that read them

```go
package main

import (
	"encoding/json"
	"fmt"
)

type Course struct {
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Lessons int    `json:"lessons"`
	Notes   string `json:"notes,omitempty"`   // dropped when empty
	secret  string                            // unexported: never serialised
}

func main() {
	c := Course{Slug: "go", Title: "Go", Lessons: 12, secret: "hidden"}

	encoded, err := json.Marshal(c)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(encoded))

	var decoded Course
	if err := json.Unmarshal([]byte(`{"slug":"rust","title":"Rust","lessons":12}`), &decoded); err != nil {
		panic(err)
	}
	fmt.Printf("%+v\\n", decoded)

	pretty, _ := json.MarshalIndent(c, "", "  ")
	fmt.Println(string(pretty))
}
```

Only **exported** fields - those starting with a capital letter - are visible to
`encoding/json` and every other reflection-based package. That is the single
most common cause of "my JSON came out empty".

## What to take away

- No classes: a struct plus methods, and a constructor is an ordinary function.
- Pointer receiver to change the receiver or avoid a copy - and be consistent per type.
- `for _, v := range` gives copies; index into the slice when you need to modify.
- Use named fields in literals; positional ones break when the struct changes.
- Embedding promotes fields and methods, but there is no virtual dispatch.
- Only exported (capitalised) fields are serialised or seen by reflection.
',
   'Pointer against value receivers, embedding without inheritance, and exported fields.',
   5, 920,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Interfaces, Type Switches and Generics
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b5',
   'Interfaces, Type Switches and Generics',
   'markdown',
   '# Interfaces, Type Switches and Generics

A Go interface is a set of method signatures. A type satisfies it by having
those methods - there is no `implements` keyword, and the implementation does
not need to know the interface exists.

```go
package main

import (
	"fmt"
	"strings"
)

// The interface is declared where it is USED, not next to the implementations.
type Shape interface {
	Area() float64
	Name() string
}

type Rectangle struct{ Width, Height float64 }
type Circle struct{ Radius float64 }

func (r Rectangle) Area() float64 { return r.Width * r.Height }
func (r Rectangle) Name() string  { return "rectangle" }
func (c Circle) Area() float64    { return 3.141592653589793 * c.Radius * c.Radius }
func (c Circle) Name() string     { return "circle" }

func describe(shapes []Shape) string {
	var b strings.Builder
	for _, s := range shapes {
		fmt.Fprintf(&b, "%s: %.2f\\n", s.Name(), s.Area())
	}
	return b.String()
}

func main() {
	fmt.Print(describe([]Shape{Rectangle{3, 4}, Circle{1}}))
}
```

Neither `Rectangle` nor `Circle` mentions `Shape`. That is what makes it
possible to write an interface for a type you do not own - including one in the
standard library.

## Small interfaces, declared by the consumer

The convention is one or two methods. `io.Reader` and `io.Writer` have one each,
and half the standard library composes out of them.

```go
package main

import (
	"fmt"
	"io"
	"os"
	"strings"
)

// A function that takes io.Reader works with a file, a network connection, a
// string, or anything else anyone writes later.
func countLines(r io.Reader) (int, error) {
	data, err := io.ReadAll(r)
	if err != nil {
		return 0, err
	}
	return strings.Count(string(data), "\\n"), nil
}

func main() {
	n, err := countLines(strings.NewReader("first\\nsecond\\nthird\\n"))
	fmt.Println(n, err)

	// io.Writer, the other half. os.Stdout is one; so is strings.Builder.
	var b strings.Builder
	writeReport(&b, 3)
	writeReport(os.Stdout, 3)
	fmt.Print(b.String())
}

func writeReport(w io.Writer, count int) {
	fmt.Fprintf(w, "counted %d lines\\n", count)
}
```

## any, type assertions and type switches

`any` (an alias for `interface{}`) holds anything. Getting the concrete value
back out is a type assertion, and the comma-ok form is the safe one.

```go
package main

import "fmt"

func main() {
	values := []any{"hello", 42, 3.5, []int{1, 2}, nil, Point{1, 2}}

	for _, v := range values {
		fmt.Println(describe(v))
	}

	// A bare assertion panics when it is wrong; the comma-ok form does not.
	var value any = "text"
	s := value.(string)
	fmt.Println(s)

	if n, ok := value.(int); ok {
		fmt.Println("an int:", n)
	} else {
		fmt.Println("not an int, and no panic")
	}
}

type Point struct{ X, Y int }

func describe(v any) string {
	switch t := v.(type) {
	case nil:
		return "nothing at all"
	case string:
		return fmt.Sprintf("a string of %d: %s", len(t), t)
	case int:
		return fmt.Sprintf("an int, doubled: %d", t*2)
	case []int:
		return fmt.Sprintf("a slice of %d ints", len(t))
	case Point:
		return fmt.Sprintf("a point at %d,%d", t.X, t.Y)
	default:
		return fmt.Sprintf("something else: %T", t)
	}
}
```

## The nil interface trap

An interface value has two parts: a type and a value. It is `nil` only when
*both* are. A nil pointer stored in an interface is therefore not a nil
interface - and this is the most notorious gotcha in the language.

```go
package main

import "fmt"

type MyError struct{ msg string }

func (e *MyError) Error() string { return e.msg }

// Broken: returning a typed nil pointer as an error.
func broken() error {
	var e *MyError = nil
	return e                        // the interface holds (*MyError, nil)
}

// Correct: return the untyped nil.
func correct() error {
	return nil
}

func main() {
	if err := broken(); err != nil {
		fmt.Printf("broken() looks like a failure: %v (type %T)\\n", err, err)
	}

	if err := correct(); err == nil {
		fmt.Println("correct() is properly nil")
	}

	fmt.Println("the rule: never declare a typed nil and return it as an interface")
}
```

## Generics, since Go 1.18

```go
package main

import (
	"fmt"
	"strings"
)

// A type parameter with a constraint. `comparable` is built in.
func Keys[K comparable, V any](m map[K]V) []K {
	keys := make([]K, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	return keys
}

// A union constraint: any of these underlying types.
type Number interface {
	~int | ~int64 | ~float64
}

func Sum[T Number](values []T) T {
	var total T                    // the zero value of whatever T is
	for _, v := range values {
		total += v
	}
	return total
}

func Map[T, R any](values []T, f func(T) R) []R {
	out := make([]R, 0, len(values))
	for _, v := range values {
		out = append(out, f(v))
	}
	return out
}

func main() {
	fmt.Println(len(Keys(map[string]int{"a": 1, "b": 2})))
	fmt.Println(Sum([]int{1, 2, 3}), Sum([]float64{1.5, 2.5}))
	fmt.Println(Map([]int{1, 2, 3}, func(n int) string {
		return strings.Repeat("*", n)
	}))
}
```

The `~int` means "any type whose underlying type is int", so a `type Celsius
int` satisfies it too. Generics are worth reaching for when you would otherwise
write the same function three times - and not much sooner: an interface is
usually the more Go-like answer.

## What to take away

- Satisfaction is implicit: a type has the methods, so it satisfies the interface.
- Declare interfaces where they are consumed, and keep them to one or two methods.
- `io.Reader`/`io.Writer` are the model: small, composable, and everywhere.
- Use the comma-ok form of a type assertion; a bare one panics.
- An interface holding a typed nil pointer is not nil - never return one.
- Generics for genuine repetition; `comparable`, `any` and `~T` unions are the vocabulary.
',
   'Implicit satisfaction, small consumer-declared interfaces, and the nil interface trap.',
   5, 930,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Errors Are Values
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b6',
   'Errors Are Values',
   'markdown',
   '# Errors Are Values

Go has no exceptions. A function that can fail returns an `error` as its last
result, and the caller checks it. That is the whole mechanism, and everything
else in this lesson is a consequence.

```go
package main

import (
	"errors"
	"fmt"
	"strconv"
)

func main() {
	for _, text := range []string{"42", "not a number"} {
		n, err := strconv.Atoi(text)
		if err != nil {
			fmt.Println("failed:", err)
			continue
		}
		fmt.Println("parsed", n)
	}

	// error is an interface with one method. Anything with Error() string is one.
	var err error = errors.New("a plain error")
	fmt.Println(err.Error(), len(err.Error()))

	// fmt.Errorf builds one with context.
	err = fmt.Errorf("loading course %q: %w", "go", errors.New("not found"))
	fmt.Println(err)
}
```

The repetition is the trade. Every failure is visible at the point it can
happen, and no function can throw past you into a caller three frames up.

## Wrap with %w, and unwrap with errors.Is and errors.As

```go
package main

import (
	"errors"
	"fmt"
)

// A sentinel error: a package-level value callers can compare against.
var ErrNotFound = errors.New("not found")

// A typed error, when the caller needs detail rather than just identity.
type ValidationError struct {
	Field  string
	Reason string
}

func (e *ValidationError) Error() string {
	return fmt.Sprintf("%s %s", e.Field, e.Reason)
}

func findCourse(slug string) error {
	if slug == "" {
		return &ValidationError{Field: "slug", Reason: "must not be empty"}
	}
	if slug != "go" {
		// %w wraps: the message gains context and the original stays reachable.
		return fmt.Errorf("course %q: %w", slug, ErrNotFound)
	}
	return nil
}

func main() {
	for _, slug := range []string{"go", "cobol", ""} {
		err := findCourse(slug)

		switch {
		case err == nil:
			fmt.Printf("%-8q ok\\n", slug)

		// errors.Is walks the wrap chain looking for that exact error.
		case errors.Is(err, ErrNotFound):
			fmt.Printf("%-8q not found (full message: %v)\\n", slug, err)

		// errors.As walks it looking for a type, and fills in the target.
		default:
			var ve *ValidationError
			if errors.As(err, &ve) {
				fmt.Printf("%-8q invalid: field %s %s\\n", slug, ve.Field, ve.Reason)
			} else {
				fmt.Printf("%-8q unexpected: %v\\n", slug, err)
			}
		}
	}
}
```

Never compare with `err == ErrNotFound` once wrapping is in play - `errors.Is`
is the one that still works after a caller adds context. And never compare error
*strings*: they are for humans, and they change.

## Adding context on the way up

```go
package main

import (
	"errors"
	"fmt"
)

var ErrNoConnection = errors.New("no connection")

func query() error        { return ErrNoConnection }
func loadCourse() error {
	if err := query(); err != nil {
		return fmt.Errorf("loading course: %w", err)
	}
	return nil
}
func handleRequest() error {
	if err := loadCourse(); err != nil {
		return fmt.Errorf("GET /courses/go: %w", err)
	}
	return nil
}

func main() {
	err := handleRequest()
	fmt.Println(err)
	fmt.Println("is it ErrNoConnection?", errors.Is(err, ErrNoConnection))

	// Unwrap one layer at a time, which is what errors.Is does internally.
	for err != nil {
		fmt.Printf("  %v\\n", err)
		err = errors.Unwrap(err)
	}
}
```

Each layer adds what *it* knows and nothing more. The result reads like a path
from the request to the cause, which is exactly what you want at 3am.

## Do not ignore errors, and do not check them twice

```go
package main

import (
	"fmt"
	"os"
	"strconv"
)

func main() {
	// The one legitimate ignore: _ says "I know, and I have decided".
	_, _ = fmt.Fprintln(os.Stdout, "writing to stdout basically cannot fail")

	// Everything else gets checked, immediately, next to the call.
	if n, err := strconv.Atoi("42"); err == nil {
		fmt.Println(n * 2)
	}

	// A helper that returns (T, error) keeps the caller''s code flat.
	if total, err := sum([]string{"1", "2", "3"}); err == nil {
		fmt.Println("total", total)
	}

	if _, err := sum([]string{"1", "x"}); err != nil {
		fmt.Println("as expected:", err)
	}
}

func sum(texts []string) (int, error) {
	total := 0
	for i, text := range texts {
		n, err := strconv.Atoi(text)
		if err != nil {
			return 0, fmt.Errorf("element %d: %w", i, err)
		}
		total += n
	}
	return total, nil
}
```

## panic and recover are not exceptions

`panic` unwinds the stack and crashes the program. It is for a bug - an
impossible state, a broken invariant - not for an expected failure. `recover`
stops that unwinding, and belongs in exactly two places: the top of a server
goroutine that must not take the process down, and a package that converts a
panic back into an error at its own boundary.

```go
package main

import "fmt"

func main() {
	fmt.Println(safeDivide(10, 2))
	fmt.Println(safeDivide(10, 0))
	fmt.Println("still running")

	// Where recover really belongs: at a boundary, so one bad request does not
	// take down the whole server.
	handle(func() { panic("a bug in a handler") })
	handle(func() { fmt.Println("  a handler that behaves") })
	fmt.Println("the server is still up")
}

func safeDivide(a, b int) (result int, err error) {
	// Named results, so the deferred function can set them.
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("recovered: %v", r)
		}
	}()
	return a / b, nil
}

func handle(f func()) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("  handler panicked, recovered:", r)
		}
	}()
	f()
}
```

A library that panics on bad input is a library that is hard to use. Return an
error and let the caller decide.

## What to take away

- `error` is an ordinary interface value returned as the last result.
- Wrap with `%w` to add context; `errors.Is` and `errors.As` see through it.
- Sentinel errors for identity, typed errors for detail - never compare strings.
- Each layer adds only what it knows, which makes the final message a path.
- Check every error next to the call; `_` only where you have genuinely decided.
- `panic` is for bugs; `recover` belongs at a boundary, not in ordinary control flow.
',
   'Wrapping with %w, errors.Is and errors.As, and why panic is only for bugs.',
   5, 979,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Goroutines and Channels
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b7',
   'Goroutines and Channels',
   'markdown',
   '# Goroutines and Channels

A goroutine is a function running concurrently, managed by Go''s runtime rather
than the operating system. Starting one costs a couple of kilobytes, so a
program can have hundreds of thousands - which is why Go code blocks freely
instead of contorting itself around callbacks.

```go
package main

import (
	"fmt"
	"sync"
	"time"
)

func main() {
	start := time.Now()

	// A WaitGroup counts outstanding work. Add before starting, Done when
	// finished, Wait until the count reaches zero.
	var wg sync.WaitGroup
	for i := 1; i <= 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			time.Sleep(100 * time.Millisecond)   // pretend this is I/O
			fmt.Printf("  worker %d finished\\n", i)
		}()
	}
	wg.Wait()

	fmt.Printf("four 100ms jobs in about 100ms: %t\\n", time.Since(start) < 350*time.Millisecond)
}
```

Without the `Wait`, `main` returns and the program exits - taking every
goroutine with it, finished or not. Nothing waits for a goroutine automatically.

## Channels: typed pipes between goroutines

```go
package main

import "fmt"

func main() {
	// Unbuffered: a send blocks until a receive is ready, and vice versa.
	// That is a synchronisation point, not just a queue.
	messages := make(chan string)
	go func() { messages <- "from the goroutine" }()
	fmt.Println(<-messages)

	// Buffered: a send blocks only when the buffer is full.
	buffered := make(chan int, 3)
	buffered <- 1
	buffered <- 2
	fmt.Println(len(buffered), cap(buffered))
	fmt.Println(<-buffered, <-buffered)

	// Closing says "no more values". Ranging over a channel ends when it closes.
	work := make(chan int, 5)
	go func() {
		defer close(work)                    // the sender closes, never the receiver
		for i := 1; i <= 5; i++ {
			work <- i * i
		}
	}()

	total := 0
	for value := range work {
		total += value
	}
	fmt.Println("total", total)

	// Receiving from a closed channel gives the zero value immediately; the
	// comma-ok form tells you which.
	if v, ok := <-work; !ok {
		fmt.Printf("closed, got the zero value %d\\n", v)
	}
}
```

## The deadlocks you will actually hit

```go
package main

import (
	"fmt"
	"sync"
	"time"
)

func main() {
	// 1. Sending on an unbuffered channel with no receiver ready.
	//    ch := make(chan int); ch <- 1     // fatal error: all goroutines are asleep
	//    The fix is a receiver, or a buffer.
	ch := make(chan int, 1)
	ch <- 1
	fmt.Println("buffered send did not block:", <-ch)

	// 2. Ranging over a channel nobody closes - the loop waits forever.
	//    The fix is close() in the sender, usually with defer.
	done := make(chan int, 3)
	go func() {
		defer close(done)
		for i := 0; i < 3; i++ {
			done <- i
		}
	}()
	for range done {
	}
	fmt.Println("range ended because the sender closed")

	// 3. Forgetting wg.Done, so Wait never returns. defer is the fix.
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()                       // even if this panics
		time.Sleep(10 * time.Millisecond)
	}()
	wg.Wait()
	fmt.Println("Wait returned because Done was deferred")

	// 4. Sending to a channel whose reader has gone away. Select with a
	//    default, or a done channel, is the escape.
	orphan := make(chan int)
	select {
	case orphan <- 1:
		fmt.Println("sent")
	default:
		fmt.Println("nobody listening, and we did not block")
	}
}
```

## select: waiting on several channels

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fast := make(chan string)
	slow := make(chan string)

	go func() { time.Sleep(20 * time.Millisecond); fast <- "fast" }()
	go func() { time.Sleep(80 * time.Millisecond); slow <- "slow" }()

	// select takes whichever is ready first.
	for received := 0; received < 2; received++ {
		select {
		case msg := <-fast:
			fmt.Println("got", msg)
		case msg := <-slow:
			fmt.Println("got", msg)
		}
	}

	// A timeout is just another case.
	quiet := make(chan string)
	select {
	case msg := <-quiet:
		fmt.Println(msg)
	case <-time.After(50 * time.Millisecond):
		fmt.Println("gave up after 50ms")
	}

	// A default makes the whole select non-blocking.
	select {
	case msg := <-quiet:
		fmt.Println(msg)
	default:
		fmt.Println("nothing ready, carrying on")
	}
}
```

## Channels are for handing over, mutexes are for protecting

Both are correct tools. The rule of thumb: use a channel when a value moves from
one goroutine to another; use a `sync.Mutex` when several goroutines share one
piece of state.

```go
package main

import (
	"fmt"
	"sync"
)

type Counter struct {
	mu sync.Mutex
	n  int
}

func (c *Counter) Increment() {
	c.mu.Lock()
	defer c.mu.Unlock()          // unlocked even if the body panics
	c.n++
}

func (c *Counter) Value() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.n
}

func main() {
	counter := &Counter{}

	var wg sync.WaitGroup
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for n := 0; n < 100; n++ {
				counter.Increment()
			}
		}()
	}
	wg.Wait()

	fmt.Println("counter:", counter.Value(), "- exactly 10000, every time")

	// Without the mutex this is a data race: run it under `go run -race` and
	// the detector will say so. Use -race in CI; it catches what tests miss.
}
```

## What to take away

- A goroutine is cheap; nothing waits for one unless you make it.
- `sync.WaitGroup`: `Add` before starting, `defer Done`, `Wait` at the end.
- An unbuffered channel is a synchronisation point, not merely a queue.
- The sender closes a channel, never the receiver; `range` ends when it closes.
- `select` waits on several channels; `time.After` is a timeout, `default` is non-blocking.
- Channels hand values over, mutexes protect shared state - and `-race` finds the rest.
',
   'WaitGroups, unbuffered channels as synchronisation, select, and the four deadlocks.',
   5, 911,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Context, Pipelines and Worker Pools
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b8',
   'Context, Pipelines and Worker Pools',
   'markdown',
   '# Context, Pipelines and Worker Pools

`context.Context` is how a Go program carries cancellation, deadlines and
request-scoped values across API boundaries. Every standard-library call that
can block takes one, and yours should too - as the first parameter, by
convention, named `ctx`.

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"time"
)

func main() {
	// A context with a deadline. The cancel function must always be called -
	// defer it on the next line, every time, or you leak the timer.
	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
	defer cancel()

	if err := slowWork(ctx, 200*time.Millisecond); err != nil {
		fmt.Println("first:", err, "| deadline exceeded:", errors.Is(err, context.DeadlineExceeded))
	}

	// Enough time this time.
	ctx2, cancel2 := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel2()
	fmt.Println("second:", slowWork(ctx2, 20*time.Millisecond))

	// Cancellation by hand, which is what a user closing a connection looks like.
	ctx3, cancel3 := context.WithCancel(context.Background())
	go func() {
		time.Sleep(20 * time.Millisecond)
		cancel3()
	}()
	fmt.Println("third:", slowWork(ctx3, time.Second))
}

func slowWork(ctx context.Context, duration time.Duration) error {
	select {
	case <-time.After(duration):
		return nil
	case <-ctx.Done():
		return ctx.Err()          // DeadlineExceeded or Canceled
	}
}
```

Pass the context down; never store one in a struct, and never pass `nil` -
`context.Background()` is the root, `context.TODO()` the placeholder while you
work out where the real one comes from.

## A worker pool

```go
package main

import (
	"fmt"
	"sync"
	"time"
)

type result struct {
	job   int
	value int
}

func main() {
	jobs := make(chan int)
	results := make(chan result)

	const workers = 4
	var wg sync.WaitGroup

	for w := 1; w <= workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobs {              // ends when jobs is closed
				time.Sleep(10 * time.Millisecond)
				results <- result{job: job, value: job * job}
			}
		}()
	}

	// The sender closes jobs when there is no more work.
	go func() {
		defer close(jobs)
		for i := 1; i <= 12; i++ {
			jobs <- i
		}
	}()

	// A separate goroutine closes results once every worker has finished, which
	// is what lets the range below terminate.
	go func() {
		wg.Wait()
		close(results)
	}()

	total := 0
	for r := range results {
		total += r.value
	}
	fmt.Println("sum of squares 1..12 =", total)
}
```

Three channel rules are doing the work: the producer closes `jobs`, each worker
ranges until it is closed, and a closer goroutine waits for all of them before
closing `results`. Get one wrong and the program either deadlocks or panics on a
send to a closed channel.

## A pipeline

Each stage is a function that takes a channel and returns one, so stages compose
and each runs concurrently with the others.

```go
package main

import "fmt"

func main() {
	for value := range square(filterEven(generate(1, 10))) {
		fmt.Print(value, " ")
	}
	fmt.Println()
}

func generate(from, to int) <-chan int {
	out := make(chan int)
	go func() {
		defer close(out)
		for i := from; i <= to; i++ {
			out <- i
		}
	}()
	return out
}

func filterEven(in <-chan int) <-chan int {
	out := make(chan int)
	go func() {
		defer close(out)
		for n := range in {
			if n%2 == 0 {
				out <- n
			}
		}
	}()
	return out
}

func square(in <-chan int) <-chan int {
	out := make(chan int)
	go func() {
		defer close(out)
		for n := range in {
			out <- n * n
		}
	}()
	return out
}
```

`<-chan int` in the return type is a receive-only channel: the caller can read
but not send or close. Directional channel types are free documentation the
compiler enforces.

## errgroup, for when any failure should cancel the rest

The standard library''s `sync.WaitGroup` has no error handling. The common
pattern - and what `golang.org/x/sync/errgroup` packages up - is a group that
collects the first error and cancels a shared context.

```go
package main

import (
	"context"
	"fmt"
	"sync"
	"time"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	var (
		wg    sync.WaitGroup
		once  sync.Once
		first error
	)

	fail := func(err error) {
		once.Do(func() {           // only the FIRST error is kept
			first = err
			cancel()               // and everyone else is told to stop
		})
	}

	for i := 1; i <= 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := task(ctx, i); err != nil {
				fail(err)
			}
		}()
	}
	wg.Wait()

	fmt.Println("first error:", first)
	fmt.Println("ctx cancelled:", ctx.Err())
}

func task(ctx context.Context, id int) error {
	select {
	case <-time.After(time.Duration(id*20) * time.Millisecond):
		if id == 2 {
			return fmt.Errorf("task %d failed", id)
		}
		fmt.Printf("  task %d done\\n", id)
		return nil
	case <-ctx.Done():
		fmt.Printf("  task %d cancelled\\n", id)
		return ctx.Err()
	}
}
```

## Goroutine leaks

A goroutine blocked forever on a channel is never collected, and its stack and
everything it references stay in memory. This is Go''s characteristic leak.

```go
package main

import (
	"context"
	"fmt"
	"runtime"
	"time"
)

func main() {
	before := runtime.NumGoroutine()

	// Leaks: nobody ever receives, so this goroutine blocks forever.
	leak := make(chan int)
	go func() { leak <- 1 }()

	time.Sleep(20 * time.Millisecond)
	fmt.Printf("goroutines: %d -> %d (one leaked)\\n", before, runtime.NumGoroutine())

	// The fix: give every goroutine a way to be told to stop.
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		select {
		case <-ctx.Done():
			return
		case leak <- 1:
		}
	}()
	cancel()
	time.Sleep(20 * time.Millisecond)
	fmt.Println("goroutines after cancelling the second:", runtime.NumGoroutine())
}
```

Rule: whoever starts a goroutine is responsible for how it ends. A context, a
done channel, or a closed input - but always something.

## What to take away

- `ctx` first, always passed down, never stored in a struct; `defer cancel()` every time.
- `ctx.Done()` in a `select` is how a goroutine notices cancellation.
- Worker pool: producer closes the jobs channel, a closer goroutine waits then closes results.
- Pipelines compose stages that each own and close their output channel.
- `<-chan T` and `chan<- T` document direction and are checked by the compiler.
- Whoever starts a goroutine must arrange for it to finish, or it leaks.
',
   'ctx.Done(), worker pools, pipelines, and the goroutine leak that never gets collected.',
   5, 994,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- The Standard Library You Will Actually Use
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000b9',
   'The Standard Library You Will Actually Use',
   'markdown',
   '# The Standard Library You Will Actually Use

Go''s standard library is unusually complete, and leaning on it is idiomatic
rather than lazy. This lesson covers the packages that turn up in almost every
program.

## encoding/json

```go
package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

type Course struct {
	Slug      string   `json:"slug"`
	Title     string   `json:"title"`
	Lessons   int      `json:"lessons"`
	Tags      []string `json:"tags,omitempty"`
	Published bool     `json:"-"`             // never serialised
}

func main() {
	course := Course{Slug: "go", Title: "Go", Lessons: 12, Published: true}

	encoded, err := json.Marshal(course)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(encoded))

	var decoded Course
	if err := json.Unmarshal(encoded, &decoded); err != nil {
		panic(err)
	}
	fmt.Printf("%+v\\n", decoded)

	// Unknown fields are ignored by default; DisallowUnknownFields is how you
	// catch a typo in a config file instead of silently using the zero value.
	strict := json.NewDecoder(strings.NewReader(`{"slug":"go","lessonz":12}`))
	strict.DisallowUnknownFields()
	var target Course
	fmt.Println("strict decode:", strict.Decode(&target))

	// Decoding into a map when the shape is not known ahead of time.
	var loose map[string]any
	_ = json.Unmarshal([]byte(`{"a":1,"b":["x","y"]}`), &loose)
	fmt.Printf("%T for a number, %T for an array\\n", loose["a"], loose["b"])
}
```

Note the types in that last line: every JSON number decodes into `float64` and
every array into `[]any`. That is the price of `map[string]any`, and the reason
a struct is almost always better.

## time

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	// A fixed instant, so this lesson prints the same thing every run.
	launch := time.Date(2026, time.March, 14, 9, 30, 0, 0, time.UTC)

	fmt.Println(launch.Format(time.RFC3339))
	fmt.Println(launch.Format("Mon 2 Jan 2006 at 15:04"))   // the reference layout

	later := launch.Add(90 * time.Minute)
	fmt.Println(later.Sub(launch), later.After(launch))

	deadline := launch.AddDate(0, 1, 0)
	fmt.Println("a month later:", deadline.Format(time.DateOnly))

	parsed, err := time.Parse(time.RFC3339, "2026-03-14T09:30:00Z")
	fmt.Println(parsed.Equal(launch), err)

	// Durations are typed, which stops the "was that seconds or milliseconds?"
	// class of bug entirely.
	timeout := 250 * time.Millisecond
	fmt.Println(timeout, timeout.Seconds())

	start := time.Now()
	time.Sleep(10 * time.Millisecond)
	fmt.Println("elapsed at least 10ms:", time.Since(start) >= 10*time.Millisecond)
}
```

That layout string is Go''s one real oddity: the reference time is
`Mon Jan 2 15:04:05 MST 2006` - 01/02 03:04:05PM ''06 -0700 - and you write the
format by example rather than with `%Y`.

## strings, strconv and bytes

```go
package main

import (
	"fmt"
	"strconv"
	"strings"
)

func main() {
	s := "  Go: From Basics to Expert  "

	fmt.Printf("%q\\n", strings.TrimSpace(s))
	fmt.Println(strings.Contains(s, "Basics"), strings.HasPrefix(strings.TrimSpace(s), "Go"))
	fmt.Println(strings.Split("a,b,c", ","))
	fmt.Println(strings.Join([]string{"a", "b", "c"}, " -> "))
	fmt.Println(strings.ReplaceAll("one one one", "one", "1"))
	fmt.Println(strings.Fields("  several   spaced   words  "))
	fmt.Println(strings.EqualFold("GoLang", "golang"))       // ASCII-insensitive

	// strconv converts; it never guesses.
	n, err := strconv.Atoi("42")
	fmt.Println(n, err)

	_, err = strconv.Atoi("42x")
	fmt.Println("error:", err)

	fmt.Println(strconv.Itoa(42) + "!")
	fmt.Println(strconv.FormatFloat(3.14159, ''f'', 2, 64))
	fmt.Println(strconv.Quote("needs \\"escaping\\""))

	b, _ := strconv.ParseBool("true")
	fmt.Println(b)
}
```

## io, and why it composes

```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"
)

func main() {
	// Anything that reads is an io.Reader; anything that writes is an io.Writer.
	// A file, a socket, a buffer and a string all are, so code written against
	// them works with all four.
	reader := strings.NewReader("first line\\nsecond line\\nthird line\\n")

	scanner := bufio.NewScanner(reader)
	count := 0
	for scanner.Scan() {
		count++
		fmt.Printf("  %d: %s\\n", count, scanner.Text())
	}
	if err := scanner.Err(); err != nil {
		panic(err)
	}

	// io.Copy moves bytes from any reader to any writer without a buffer of
	// your own - here from a string straight to stdout.
	if _, err := io.Copy(os.Stdout, strings.NewReader("copied directly\\n")); err != nil {
		panic(err)
	}

	// A writer that counts, in six lines, usable anywhere an io.Writer is.
	counting := &countingWriter{}
	fmt.Fprintf(io.MultiWriter(os.Stdout, counting), "written to two places\\n")
	fmt.Println("bytes counted:", counting.n)
}

type countingWriter struct{ n int }

func (w *countingWriter) Write(p []byte) (int, error) {
	w.n += len(p)
	return len(p), nil
}
```

## sort, slices and maps

```go
package main

import (
	"fmt"
	"maps"
	"slices"
	"strings"
)

type Learner struct {
	Name  string
	Score int
}

func main() {
	learners := []Learner{{"Ada", 95}, {"Grace", 88}, {"Alan", 95}}

	// slices.SortFunc (Go 1.21+) replaces most uses of the old sort package.
	slices.SortFunc(learners, func(a, b Learner) int {
		if c := b.Score - a.Score; c != 0 {
			return c                        // descending by score
		}
		return strings.Compare(a.Name, b.Name)
	})
	fmt.Println(learners)

	numbers := []int{5, 2, 9, 1}
	slices.Sort(numbers)
	fmt.Println(numbers, slices.Contains(numbers, 9), slices.Index(numbers, 5))
	fmt.Println(slices.Max(numbers), slices.Min(numbers))
	reversed := slices.Clone(numbers)      // Clone, so the original is untouched
	slices.Reverse(reversed)
	fmt.Println(reversed, numbers)

	stock := map[string]int{"pears": 2, "apples": 5, "cherries": 9}
	keys := slices.Sorted(maps.Keys(stock))     // map iteration is random; sort it
	fmt.Println(keys)

	// maps.Keys and maps.Values return iterators (Go 1.23+), so they are ranged
	// over directly rather than returning a slice.
	total := 0
	for v := range maps.Values(stock) {
		total += v
	}
	fmt.Println("total", total)
}
```

## What to take away

- `encoding/json` reads struct tags, and only exported fields; unknown fields are ignored unless you forbid them.
- A JSON number in a `map[string]any` is a `float64` - prefer a struct.
- Go''s time layouts are written by example, using the reference `2006-01-02 15:04:05`.
- `time.Duration` is a type, which removes a whole class of unit bug.
- `io.Reader`/`io.Writer` compose: `bufio`, `io.Copy` and `io.MultiWriter` work with anything.
- `slices` and `maps` (Go 1.21+) replace most hand-written sorting and key extraction.
',
   'encoding/json and its struct tags, time layouts by example, io composition, slices and maps.',
   4, 860,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Memory, Escape Analysis and the Collector
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000ba',
   'Memory, Escape Analysis and the Collector',
   'markdown',
   '# Memory, Escape Analysis and the Collector

Go has a garbage collector and pointers, and no `new`/`delete` distinction to
worry about: you take an address and the compiler works out whether the value
can live on the stack or must go on the heap. That decision is called **escape
analysis**, and it is the one piece of Go memory behaviour worth understanding.

```go
package main

import "fmt"

type Point struct{ X, Y int }

// Does not escape: the value is copied into the return, so it can live in the
// frame and disappear when the function returns.
func stackPoint() Point {
	p := Point{1, 2}
	return p
}

// Escapes: the caller gets a pointer, so the value must outlive this frame.
func heapPoint() *Point {
	p := Point{1, 2}
	return &p            // legal in Go, unlike C - the compiler moves it to the heap
}

func main() {
	a := stackPoint()
	b := heapPoint()
	fmt.Println(a, *b)

	// `go build -gcflags=-m` prints the decisions:
	//   ./main.go:14:9: &p escapes to heap
	// which is how you find an allocation you did not expect.
	fmt.Println("build with -gcflags=-m to see what escapes")
}
```

Returning a pointer to a local is safe in Go - the compiler notices and
allocates accordingly. That removes a whole class of C bug, at the cost of an
allocation you might not have intended.

## What keeps memory alive

An object lives while something can reach it. Go''s characteristic leaks are a
slice that holds a much larger array, and a goroutine that never finishes.

```go
package main

import (
	"fmt"
	"runtime"
)

func main() {
	var stats runtime.MemStats

	// A small slice of a big array keeps the WHOLE array alive.
	big := make([]byte, 10_000_000)
	for i := range big {
		big[i] = byte(i)
	}
	small := big[:10]
	big = nil                          // the variable is gone; the array is not

	runtime.GC()
	runtime.ReadMemStats(&stats)
	fmt.Printf("holding %d bytes through a 10-byte slice: heap %dMB\\n",
		cap(small), stats.HeapAlloc/1_000_000)

	// copy() breaks the link, and the 10MB becomes collectable.
	independent := make([]byte, len(small))
	copy(independent, small)
	small = nil

	runtime.GC()
	runtime.ReadMemStats(&stats)
	fmt.Printf("after copying out: heap %dMB\\n", stats.HeapAlloc/1_000_000)
	fmt.Println(len(independent))
}
```

The other one - a goroutine blocked forever on a channel - was the last lesson''s
subject, and it is worth repeating here: a leaked goroutine holds its stack and
everything its closure references.

## Value or pointer: the decision you make constantly

```go
package main

import "fmt"

type Small struct{ A, B int }
type Large struct{ Data [1024]int }

// A small struct is cheaper to copy than to chase a pointer for.
func sumSmall(s Small) int { return s.A + s.B }

// A large one is not - and a pointer also avoids a copy per call.
func sumLarge(l *Large) int {
	total := 0
	for _, v := range l.Data {
		total += v
	}
	return total
}

func main() {
	small := Small{1, 2}
	large := &Large{}
	large.Data[0] = 42

	fmt.Println(sumSmall(small), sumLarge(large))

	// The rules of thumb, in order of importance:
	//   1. Use a pointer if the method must modify the receiver.
	//   2. Use a pointer if the struct contains a sync.Mutex or similar - a
	//      copy of a mutex is a different mutex, and a silent bug.
	//   3. Use a pointer for large structs; a value for small immutable ones.
	//   4. Be consistent within a type: mixing receivers confuses everyone.
	fmt.Println("copying a struct with a mutex is the one that bites silently")
}
```

## The collector, and what it asks of you

Go''s collector is concurrent and non-generational: it runs alongside your
program and aims for sub-millisecond pauses, at the cost of doing more total
work than a generational collector would.

```go
package main

import (
	"fmt"
	"runtime"
)

func main() {
	var before, after runtime.MemStats
	runtime.ReadMemStats(&before)

	// Allocating in a loop. This is the cheap case - the collector is built
	// for it - but it is not free, and it is the first thing to look at when
	// a Go program is slower than it should be.
	total := 0
	for i := 0; i < 1_000_000; i++ {
		s := fmt.Sprintf("item-%d", i)     // one allocation per iteration
		total += len(s)
	}

	runtime.ReadMemStats(&after)
	fmt.Println("total length", total)
	fmt.Printf("allocations: %d, total allocated: %dMB, GC cycles: %d\\n",
		after.Mallocs-before.Mallocs,
		(after.TotalAlloc-before.TotalAlloc)/1_000_000,
		after.NumGC-before.NumGC)

	fmt.Println("GOGC (default 100) trades heap size against CPU;")
	fmt.Println("GOMEMLIMIT (1.19+) puts a soft ceiling on the heap.")
}
```

Do not call `runtime.GC()` in application code - it is a hint at best and a
pause you asked for at worst. The two knobs that matter in production are
`GOGC` and `GOMEMLIMIT`, and both belong in deployment configuration rather
than in the program.

## sync.Pool, for the allocation you genuinely cannot avoid

```go
package main

import (
	"bytes"
	"fmt"
	"sync"
)

var buffers = sync.Pool{
	New: func() any { return new(bytes.Buffer) },
}

func render(name string) string {
	buf := buffers.Get().(*bytes.Buffer)
	defer func() {
		buf.Reset()            // always reset before putting it back
		buffers.Put(buf)
	}()

	buf.WriteString("hello, ")
	buf.WriteString(name)
	return buf.String()
}

func main() {
	var wg sync.WaitGroup
	results := make([]string, 4)
	for i := 0; i < 4; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			results[i] = render(fmt.Sprintf("worker %d", i))
		}()
	}
	wg.Wait()

	for _, r := range results {
		fmt.Println(r)
	}
	fmt.Println("a pool is for hot paths with measurable allocation - not a default")
}
```

## What to take away

- Escape analysis decides stack or heap; returning a pointer to a local is safe here.
- `go build -gcflags=-m` tells you what escaped, and why.
- A slice of a large array keeps the whole array alive - `copy` breaks the link.
- Pointer receiver to modify, for large structs, and always when a mutex is involved.
- The collector is concurrent and non-generational; tune with `GOGC`/`GOMEMLIMIT`, not `runtime.GC()`.
- `sync.Pool` is for a measured hot path, and always `Reset` before `Put`.
',
   'Escape analysis, the slice that holds a megabyte alive, and when to use a pointer.',
   5, 989,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Where Go Spends Its Time
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000bb',
   'Where Go Spends Its Time',
   'markdown',
   '# Where Go Spends Its Time

Go programs are usually fast by default, and the three things that make them
slow are the same three every time: building strings in a loop, growing a slice
or map that could have been preallocated, and allocating inside a hot path.

```go
package main

import (
	"fmt"
	"strings"
	"time"
)

func main() {
	const n = 50_000
	checksum := 0                        // used, so neither loop is removable

	start := time.Now()
	concatenated := ""
	for i := 0; i < n; i++ {
		concatenated += "x"              // a new string every time
	}
	plusEquals := time.Since(start)
	checksum += len(concatenated)

	start = time.Now()
	var b strings.Builder
	b.Grow(n)                            // one allocation, the right size
	for i := 0; i < n; i++ {
		b.WriteByte(''x'')
	}
	built := b.String()
	builder := time.Since(start)
	checksum += len(built)

	fmt.Println("+=             ", plusEquals)
	fmt.Println("strings.Builder", builder)
	fmt.Println("builder is faster:", builder < plusEquals)
	fmt.Println("both built", checksum/2, "characters")
}
```

## Preallocate when you know the size

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	const n = 5_000_000

	start := time.Now()
	grown := []int{}                     // starts at capacity 0 and keeps copying
	for i := 0; i < n; i++ {
		grown = append(grown, i)
	}
	growing := time.Since(start)

	start = time.Now()
	sized := make([]int, 0, n)           // one allocation, and no copying at all
	for i := 0; i < n; i++ {
		sized = append(sized, i)
	}
	presized := time.Since(start)

	fmt.Println("growing ", growing)
	fmt.Println("presized", presized)
	fmt.Println("same result:", len(grown) == len(sized))

	// The same applies to maps.
	start = time.Now()
	m1 := map[int]int{}
	for i := 0; i < 1_000_000; i++ {
		m1[i] = i
	}
	unsized := time.Since(start)

	start = time.Now()
	m2 := make(map[int]int, 1_000_000)
	for i := 0; i < 1_000_000; i++ {
		m2[i] = i
	}
	fmt.Println("map unsized", unsized, "presized", time.Since(start))
}
```

`append` doubles the backing array when it runs out, so growing to a million
elements copies about two million. `make([]T, 0, n)` does none of it.

## The structure is the algorithm

```go
package main

import (
	"fmt"
	"slices"
	"time"
)

func main() {
	const n = 20_000
	haystack := make([]int, n)
	for i := range haystack {
		haystack[i] = i
	}

	start := time.Now()
	foundByScan := 0
	for i := 0; i < n; i++ {
		if slices.Contains(haystack, i) {
			foundByScan++
		}
	}
	scan := time.Since(start)

	set := make(map[int]struct{}, n)     // struct{} is a zero-byte value
	for _, v := range haystack {
		set[v] = struct{}{}
	}

	start = time.Now()
	foundByMap := 0
	for i := 0; i < n; i++ {
		if _, ok := set[i]; ok {
			foundByMap++
		}
	}

	fmt.Println("slices.Contains", scan)
	fmt.Println("map lookup     ", time.Since(start))
	fmt.Println("same answer:", foundByScan == foundByMap)
	fmt.Println("map[T]struct{} is Go''s set: the value takes no space at all")
}
```

## Benchmarks belong in the testing package

`time.Now()` is fine for showing a difference in a lesson. For a number you will
act on, write a real benchmark: `go test -bench` runs the loop enough times to
be meaningful, and `-benchmem` reports allocations, which is usually the number
that matters.

```go
package main

import "fmt"

func main() {
	fmt.Println(`A benchmark lives in a _test.go file and looks like this:

    func BenchmarkJoin(b *testing.B) {
        parts := []string{"a", "b", "c", "d"}
        b.ResetTimer()
        for i := 0; i < b.N; i++ {
            _ = strings.Join(parts, ",")
        }
    }

Run it with:

    go test -bench=. -benchmem ./...

and read the last two columns - B/op and allocs/op. A change that removes an
allocation is usually worth more than one that shaves a nanosecond, because
allocation is what makes the collector work.`)

	fmt.Println(`
Two rules for any benchmark:
  - assign the result to something package-level or use b.Keep, or the compiler
    may delete the work entirely;
  - call b.ResetTimer() after setup, so you measure the loop and not the fixture.`)
}
```

## Profile before you optimise

```go
package main

import "fmt"

func main() {
	fmt.Println(`The standard tooling, in the order you would reach for it:

  go test -bench=. -benchmem     which function, and how many allocations
  go test -cpuprofile cpu.out    a CPU profile of the benchmark
  go tool pprof cpu.out          top, list <func>, web - where the time went
  go build -gcflags=-m           what escaped to the heap, and why
  go test -race                  data races, which no benchmark will show you
  GODEBUG=gctrace=1 ./program    every GC cycle, live, in production

Most "slow Go" turns out to be one of four things: an N+1 query, a mutex
everything queues behind, a goroutine leak, or an algorithm that is quadratic
in the size of the input. None of them are found by staring at the code, and
none are fixed by micro-tuning a loop.`)
}
```

## What to take away

- `strings.Builder` with `Grow` for text; `+=` in a loop is quadratic.
- `make([]T, 0, n)` and `make(map[K]V, n)` when the size is known - append copies.
- `map[T]struct{}` is Go''s set, and `struct{}` occupies no memory.
- Use `go test -bench -benchmem`; allocations per operation is usually the number that matters.
- `b.ResetTimer()` after setup, and make sure the result is used.
- Profile with pprof before optimising: it is usually a query, a lock, a leak, or the algorithm.
',
   'strings.Builder, preallocation, map[T]struct{}, and benchmarks that mean something.',
   4, 866,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

-- ---------------------------------------------------------------------------
-- Arranging a Go Application
-- ---------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000bc',
   'Arranging a Go Application',
   'markdown',
   '# Arranging a Go Application

Go''s conventions push you towards an architecture whether you plan one or not:
packages are the unit of privacy, imports may not form a cycle, and interfaces
are satisfied implicitly. Working with those three rather than against them is
most of what "good Go structure" means.

## The layout the tooling expects

```go
package main

import "fmt"

func main() {
	fmt.Println(`A typical service:

  cmd/
    api/main.go              the composition root: builds everything, starts it
  internal/
    catalogue/               the domain: rules and the interfaces they need
      course.go
      service.go
    storage/
      mysql.go               an adapter that satisfies catalogue''s interface
    http/
      handler.go             another adapter, on the other side
  go.mod

internal/ is enforced by the compiler: nothing outside this module can import
anything under it. That single directory name gives you a public API of exactly
what you chose to put elsewhere, and no accidental dependencies on your
internals.

cmd/<name>/main.go is the convention for a binary; "go build ./cmd/api" builds
it. A module can have several.`)
}
```

## The interface belongs to the consumer

This is the single biggest difference from Java or C#. Because satisfaction is
implicit, the *caller* declares the interface it needs, next to where it is
used - and the implementation package does not import it at all.

```go
package main

import (
	"errors"
	"fmt"
)

// --- the domain package would contain this -------------------------------
type Course struct {
	Slug  string
	Title string
}

var ErrNotFound = errors.New("course not found")

// The interface is declared HERE, by the code that needs it, and is as small
// as that need. The storage package never imports this one.
type CourseFinder interface {
	FindBySlug(slug string) (Course, error)
}

type Service struct {
	courses CourseFinder
}

func NewService(courses CourseFinder) *Service {
	return &Service{courses: courses}
}

func (s *Service) Describe(slug string) string {
	course, err := s.courses.FindBySlug(slug)
	if errors.Is(err, ErrNotFound) {
		return fmt.Sprintf("no course called %q", slug)
	}
	if err != nil {
		return fmt.Sprintf("could not load %q: %v", slug, err)
	}
	return "found " + course.Title
}

// --- the storage package would contain this ------------------------------
// It has no idea CourseFinder exists. It just has the method.
type InMemory struct {
	rows map[string]Course
}

func (m InMemory) FindBySlug(slug string) (Course, error) {
	course, ok := m.rows[slug]
	if !ok {
		return Course{}, fmt.Errorf("%q: %w", slug, ErrNotFound)
	}
	return course, nil
}

func main() {
	service := NewService(InMemory{rows: map[string]Course{
		"go": {Slug: "go", Title: "Go: From Basics to Expert"},
	}})

	fmt.Println(service.Describe("go"))
	fmt.Println(service.Describe("cobol"))
}
```

"Accept interfaces, return structs" is the slogan, and it follows from this: a
constructor returning a concrete type gives the caller everything, while a
parameter of interface type asks for only what is used.

## Dependencies are passed in, not reached for

```go
package main

import (
	"fmt"
	"time"
)

type Clock interface{ Now() time.Time }
type Mailer interface{ Send(to, subject string) error }

type Notifier struct {
	clock  Clock
	mailer Mailer
}

func NewNotifier(clock Clock, mailer Mailer) *Notifier {
	return &Notifier{clock: clock, mailer: mailer}
}

func (n *Notifier) Welcome(address string) error {
	return n.mailer.Send(address, "Welcome, at "+n.clock.Now().Format(time.RFC3339))
}

// Test doubles are four lines each, and need no mocking library.
type fixedClock struct{ t time.Time }

func (c fixedClock) Now() time.Time { return c.t }

type recordingMailer struct{ sent []string }

func (m *recordingMailer) Send(to, subject string) error {
	m.sent = append(m.sent, to+": "+subject)
	return nil
}

func main() {
	clock := fixedClock{t: time.Date(2026, 3, 14, 9, 30, 0, 0, time.UTC)}
	mailer := &recordingMailer{}

	if err := NewNotifier(clock, mailer).Welcome("ada@example.com"); err != nil {
		panic(err)
	}

	for _, line := range mailer.sent {
		fmt.Println(line)
	}
	fmt.Println("no framework, no mocks, no container - just a parameter")
}
```

A package that calls `time.Now()` or opens its own database connection cannot be
tested without one. A package that takes them as parameters can be tested with
four lines.

## Errors at the boundary

Each layer adds what it knows and passes the rest up; the boundary - an HTTP
handler, a CLI - is where an error becomes a status code or an exit code.

```go
package main

import (
	"errors"
	"fmt"
)

var (
	ErrNotFound   = errors.New("not found")
	ErrValidation = errors.New("invalid")
)

func handle(slug string) (status int, body string) {
	course, err := describe(slug)
	switch {
	case errors.Is(err, ErrNotFound):
		return 404, "no such course"
	case errors.Is(err, ErrValidation):
		return 400, err.Error()
	case err != nil:
		// Unexpected: log the detail, return something generic. Never leak an
		// internal message to a client.
		fmt.Println("  [log]", err)
		return 500, "internal error"
	default:
		return 200, course
	}
}

func describe(slug string) (string, error) {
	if slug == "" {
		return "", fmt.Errorf("slug: %w", ErrValidation)
	}
	if slug != "go" {
		return "", fmt.Errorf("describe %q: %w", slug, ErrNotFound)
	}
	return "Go: From Basics to Expert", nil
}

func main() {
	for _, slug := range []string{"go", "cobol", ""} {
		status, body := handle(slug)
		fmt.Printf("%-8q %d %s\\n", slug, status, body)
	}
}
```

## Table-driven tests are the house style

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	// A real test file uses testing.T; the shape is this, and it is worth
	// copying because adding a case is one line rather than one function.
	cases := []struct {
		name string
		in   int
		want string
	}{
		{"negative", -1, "negative"},
		{"zero", 0, "zero"},
		{"small", 5, "small"},
		{"large", 500, "large"},
	}

	failures := 0
	for _, c := range cases {
		if got := categorise(c.in); got != c.want {
			fmt.Printf("  %s: got %q, want %q\\n", c.name, got, c.want)
			failures++
		}
	}
	fmt.Printf("%d cases, %d failures\\n", len(cases), failures)

	// Written out with os.Stdout rather than fmt.Println, because go vet warns
	// about a Println argument containing what looks like a format directive -
	// and it is right to, which is the lesson.
	os.Stdout.WriteString(`
In a _test.go file that loop is:

    for _, c := range cases {
        t.Run(c.name, func(t *testing.T) {
            if got := categorise(c.in); got != c.want {
                t.Errorf("got %q, want %q", got, c.want)
            }
        })
    }

t.Run gives each case its own name in the output, and lets you run one with
go test -run ''TestCategorise/zero''.
`)
}

func categorise(n int) string {
	switch {
	case n < 0:
		return "negative"
	case n == 0:
		return "zero"
	case n < 100:
		return "small"
	default:
		return "large"
	}
}
```

## What the tooling should enforce

`gofmt` ends formatting arguments - there is one layout and the tool applies it.
`go vet` catches the mistakes the compiler allows. `golangci-lint` bundles the
rest. Run all three in CI along with `go test -race`, and spend review on the
design instead.

## What to take away

- `internal/` is compiler-enforced privacy; `cmd/<name>/main.go` is the binary.
- The consumer declares the interface, as small as its need - the implementer never imports it.
- Accept interfaces, return structs.
- Pass dependencies in; a package that reaches for a clock or a database cannot be tested.
- Wrap errors on the way up, and translate them to status codes at the boundary.
- Table-driven tests with `t.Run`, and `gofmt`, `go vet` and `-race` in CI.
',
   'internal/ as real privacy, consumer-declared interfaces, and table-driven tests.',
   6, 1177,
   '55555555-5555-4555-8555-555555555555',
   'published', DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 1 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-00000000000e');
CALL search_reindex_all();
