-- =========================================================================
-- Seed 31 : Python for Data Science
--
-- The first course in the Data Science track. It assumes you can write
-- ordinary Python and teaches the part that is specific to working with
-- data: arrays, dataframes, and the habits that make an analysis
-- reproducible.
--
-- Part of the Data Science track. Generated by the shared builder, so all
-- five courses in the track have the same shape and the same guarantees.
-- =========================================================================

INSERT INTO catalog_categories (id, slug, name, description, `position`) VALUES
  ('aaaaaaa1-0000-4000-8000-000000000004', 'data-science', 'Data Science',
   'Python, analytics, machine learning, deep learning and generative AI - the whole path from a dataframe to a model in production.', 4)
ON DUPLICATE KEY UPDATE name = VALUES(name), description = VALUES(description),
  `position` = VALUES(`position`);

INSERT INTO catalog_tags (id, slug, name) VALUES
  ('bbbbbbb1-0000-4000-8000-000000000019', 'data-science', 'Data Science'),
  ('bbbbbbb1-0000-4000-8000-00000000001a', 'python-data', 'Python for Data'),
  ('bbbbbbb1-0000-4000-8000-00000000001b', 'pandas', 'pandas'),
  ('bbbbbbb1-0000-4000-8000-00000000001c', 'numpy', 'NumPy')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO catalog_courses
  (id, slug, title, subtitle, overview, description, category_id, instructor_id,
   level, status, thumbnail_url, price_cents, learning_outcomes, requirements,
   published_at)
VALUES
  ('c0000001-0000-4000-8000-000000000010',
   'python-for-data-science',
   'Python for Data Science',
   'Four levels, twelve lessons, from an array to a pipeline',
   'Python is the language data science actually runs on, and the reason is not the language itself - it is NumPy, pandas, scikit-learn and the hundred libraries built on top of them. Learning Python for data work means learning that stack and the way of thinking it rewards.

That way of thinking is the real content of this course. Ordinary Python code loops over items one at a time; array code describes an operation on a whole column and lets a C library run it. The same calculation can differ by a factor of fifty between the two, and the faster one is usually shorter to write.

This is the foundation of the rest of the Data Science track. Analytics, machine learning, deep learning and generative AI all assume you can load a messy file, clean it, reshape it and look at it without reaching for a spreadsheet - which is exactly what the twelve lessons here are about.',
   'A complete path through the data side of Python in four levels. Level 1 covers the scientific stack and the two objects everything else is built on: the NumPy array and the pandas DataFrame. Level 2 is loading real data from CSV, JSON, SQL and Excel, and the cleaning that always follows it. Level 3 is the analysis itself - grouping, joining, time series and plots. Level 4 is what separates an analysis that runs once from one somebody else can run: memory, dtypes, reproducibility, and the point at which pandas is the wrong tool.

This course assumes you can already write Python: functions, loops, lists and dictionaries. If you cannot, take Python: From Basics to Expert first - it is on this site, it is free, and Level 1 and 2 of it are all you need before coming back here.

Every level is three lessons and a Level Check quiz, with an Expert Exam at the end. The examples use small datasets written into the code rather than files you have to download, so every one of them runs as it stands.

By the end you will be able to take a file somebody sends you, work out what is wrong with it, reshape it into the form your question needs, answer that question, and hand the whole thing to a colleague in a state where it runs for them too.',
   'aaaaaaa1-0000-4000-8000-000000000004',
   '55555555-5555-4555-8555-555555555555',
   'beginner', 'published',
   'https://images.example-cdn.test/courses/python-for-data-science.jpg', 0,
   JSON_ARRAY('Replace loops with vectorised array operations, and know why that matters',
              'Load data from CSV, JSON, SQL and Excel, including the broken ones',
              'Find and fix missing values, wrong dtypes and duplicate rows',
              'Group, join and reshape a DataFrame to answer a specific question',
              'Work with dates and time zones without silently shifting your data',
              'Make an analysis somebody else can run and get the same numbers'),
   JSON_ARRAY('Python basics: functions, loops, lists and dictionaries', 'No statistics or maths beyond arithmetic'),
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), subtitle = VALUES(subtitle), overview = VALUES(overview),
  description = VALUES(description), category_id = VALUES(category_id),
  learning_outcomes = VALUES(learning_outcomes), requirements = VALUES(requirements);

INSERT INTO catalog_course_tags (course_id, tag_id) VALUES
  ('c0000001-0000-4000-8000-000000000010', 'bbbbbbb1-0000-4000-8000-000000000019'),
  ('c0000001-0000-4000-8000-000000000010', 'bbbbbbb1-0000-4000-8000-00000000001a'),
  ('c0000001-0000-4000-8000-000000000010', 'bbbbbbb1-0000-4000-8000-00000000001b'),
  ('c0000001-0000-4000-8000-000000000010', 'bbbbbbb1-0000-4000-8000-00000000001c')
ON DUPLICATE KEY UPDATE course_id = VALUES(course_id);

-- -------------------------------------------------------------------------
-- The four levels
-- -------------------------------------------------------------------------
INSERT INTO catalog_modules (id, course_id, title, summary, `position`) VALUES
  ('d0000001-0000-4000-8000-000000000038', 'c0000001-0000-4000-8000-000000000010',
   'Level 1 - Basic',
   'The scientific stack, and the two objects the rest of data work in Python is built from. The NumPy array comes first because pandas is built on it: one typed block of memory that you operate on as a whole rather than one item at a time. Then the DataFrame, which is what you will actually hold data in - a set of named, typed columns sharing an index.', 1),
  ('d0000001-0000-4000-8000-000000000039', 'c0000001-0000-4000-8000-000000000010',
   'Level 2 - Intermediate',
   'Real data arrives broken. This level is about getting it in - from CSV, JSON, SQL and Excel, including the files with the wrong encoding and the header three rows down - and then about the cleaning that always follows: missing values that are not always NaN, numbers that arrived as strings, and duplicates that are only duplicates on some columns.', 2),
  ('d0000001-0000-4000-8000-00000000003a', 'c0000001-0000-4000-8000-000000000010',
   'Level 3 - Advanced',
   'The analysis itself. Group-by goes beyond one aggregate per group into transforms and window calculations; dates turn out to be the part of data work most likely to be quietly wrong, especially across time zones; and plotting is treated as a way of finding out what is in the data rather than as the last step before a slide.', 3),
  ('d0000001-0000-4000-8000-00000000003b', 'c0000001-0000-4000-8000-000000000010',
   'Level 4 - Expert',
   'The difference between an analysis that ran once on your laptop and one somebody else can run next quarter and get the same numbers. Memory and dtypes, because the first serious dataset will not fit; reproducibility, because a notebook that only runs in the order you happened to press the keys is not a result; and the move from a notebook to something that runs on a schedule.', 4)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary);

INSERT INTO catalog_lessons
  (id, module_id, course_id, slug, title, summary, kind, status, `position`,
   duration_seconds, is_free_preview)
VALUES
  ('e0000001-0000-4000-8000-0000000000d1', 'd0000001-0000-4000-8000-000000000038', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-stack', 'The Scientific Stack and Where to Run It',
   'What NumPy, pandas, Matplotlib and scikit-learn each do, how they fit together, and why an isolated environment is the first thing to set up rather than the last.',
   'article', 'published', 1, 480, 1),
  ('e0000001-0000-4000-8000-0000000000d2', 'd0000001-0000-4000-8000-000000000038', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-numpy', 'NumPy: Arrays and Vectorised Thinking',
   'One typed block of memory instead of a million Python objects, and the habit of describing an operation on a whole array rather than looping over it. This is the idea the entire stack is built on.',
   'article', 'published', 2, 660, 1),
  ('e0000001-0000-4000-8000-0000000000d3', 'd0000001-0000-4000-8000-000000000038', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-pandas', 'Pandas: Series and DataFrames',
   'The DataFrame is the object you will spend the rest of your career in: named, typed columns sharing an index. This lesson covers how to make one, how to select from it, and the one distinction - loc against iloc - that causes most early confusion.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000d4', 'd0000001-0000-4000-8000-000000000038', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-level-1-check', 'Level 1 Check: Arrays and DataFrames',
   'Vectorised thinking, axis arguments, dtypes, and the difference between loc and iloc. Everything here is settled by running the snippet rather than by remembering.',
   'quiz', 'published', 4, 600, 0),
  ('e0000001-0000-4000-8000-0000000000d5', 'd0000001-0000-4000-8000-000000000039', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-loading', 'Reading Real Data: CSV, JSON, SQL and Excel',
   'read_csv has about fifty parameters and you will need six of them regularly. This lesson covers those six, the equivalents for JSON, SQL and Excel, and what to do when a file will not parse at all.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-0000000000d6', 'd0000001-0000-4000-8000-000000000039', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-cleaning', 'Missing Values, Types and Duplicates',
   'Missing is not one thing: a gap can mean unknown, not applicable, or zero recorded badly, and the right fix differs for each. This lesson also covers dtypes that arrived wrong and duplicates that are only duplicates on the columns that identify a row.',
   'article', 'published', 2, 720, 0),
  ('e0000001-0000-4000-8000-0000000000d7', 'd0000001-0000-4000-8000-000000000039', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-reshaping', 'Filtering, Grouping and Joining',
   'Three operations answer most questions: narrow the rows, collapse them into groups, and bring in a column from somewhere else. This lesson covers all three, and the merge that silently multiplies your row count.',
   'article', 'published', 3, 720, 0),
  ('e0000001-0000-4000-8000-0000000000d8', 'd0000001-0000-4000-8000-000000000039', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-level-2-check', 'Level 2 Check: Loading, Cleaning and Reshaping',
   'Reading awkward files, deciding what a missing value means, and the join that doubles your row count. These are the mistakes that produce a confident wrong answer rather than an error.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-0000000000d9', 'd0000001-0000-4000-8000-00000000003a', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-aggregation', 'Group-By in Depth and Window Calculations',
   'Beyond one number per group: transforms that put a group statistic back on every row, ranking inside a group, and cumulative calculations. This is the pandas equivalent of SQL window functions, and it removes most remaining loops.',
   'article', 'published', 1, 720, 0),
  ('e0000001-0000-4000-8000-0000000000da', 'd0000001-0000-4000-8000-00000000003a', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-timeseries', 'Dates, Time Zones and Resampling',
   'Dates are the part of data work most likely to be quietly wrong. A DatetimeIndex unlocks resampling and partial-string selection; time zones decide whether your daily totals are actually daily, and whether last March has 31 days or 30 and an hour.',
   'article', 'published', 2, 720, 0),
  ('e0000001-0000-4000-8000-0000000000db', 'd0000001-0000-4000-8000-00000000003a', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-plotting', 'Plotting to Find Things Out',
   'A chart is a tool for seeing what is in the data, not just the last step before a slide. Four plot types answer most questions, and knowing which one answers which saves you from the decorated bar chart that shows nothing.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000dc', 'd0000001-0000-4000-8000-00000000003a', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-level-3-check', 'Level 3 Check: Grouping, Time and Charts',
   'Transform against agg, what resample does to a missing day, which direction tz_localize goes, and which chart answers which question.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-0000000000dd', 'd0000001-0000-4000-8000-00000000003b', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-performance', 'Memory, dtypes and When Pandas Is Wrong',
   'A DataFrame can use ten times the memory it needs, and the fix is usually one line of dtypes. This lesson covers measuring it, chunked reading for files larger than RAM, and the honest point at which the answer is a database or a different library.',
   'article', 'published', 1, 720, 0),
  ('e0000001-0000-4000-8000-0000000000de', 'd0000001-0000-4000-8000-00000000003b', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-reproducible', 'Analysis Somebody Else Can Run',
   'An analysis that only runs on your laptop, in the order you happened to press the keys, is not a result - it is an anecdote. Pinned versions, a fixed seed, no hidden state, and a notebook that runs top to bottom from a clean kernel.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-0000000000df', 'd0000001-0000-4000-8000-00000000003b', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-pipeline', 'From Notebook to Pipeline',
   'The notebook was for finding the answer. Getting the same answer every Monday without you means functions, a defined input and output, idempotence and a loud failure - the few things that separate a script from a scheduled job.',
   'article', 'published', 3, 720, 0),
  ('e0000001-0000-4000-8000-0000000000e0', 'd0000001-0000-4000-8000-00000000003b', 'c0000001-0000-4000-8000-000000000010',
   'py-ds-expert-exam', 'Expert Exam: Python for Data Science',
   'Memory and dtypes, the four reasons an analysis will not reproduce, idempotence, and the point where the right answer is a database rather than a bigger machine.',
   'quiz', 'published', 4, 1500, 0)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), summary = VALUES(summary), kind = VALUES(kind),
  duration_seconds = VALUES(duration_seconds), is_free_preview = VALUES(is_free_preview);

-- -------------------------------------------------------------------------
-- The diagram the course opens with
-- -------------------------------------------------------------------------
INSERT INTO content_lesson_diagrams (lesson_id, title, alt, caption, spec, `position`) VALUES
  ('e0000001-0000-4000-8000-0000000000d1',
   'How an analysis flows',
   'Raw data is loaded into a DataFrame, cleaned so its types and missing values are right, reshaped by grouping and joining into the form the question needs, and finally summarised as a number or a plot.',
   'Four steps, in this order, every time. Most of the work is in the second one.',
   '{"nodes": [{"label": "Raw data", "note": "A CSV, an API response, a database table"}, {"label": "DataFrame", "note": "Loaded into pandas - rows and typed columns"}, {"label": "Cleaned and reshaped", "note": "Types fixed, gaps handled, grouped and joined"}, {"label": "An answer", "note": "A number, a table, or a plot"}], "edges": [{"label": "read into"}, {"label": "prepared as"}, {"label": "summarised to"}]}', 1)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), alt = VALUES(alt), caption = VALUES(caption), spec = VALUES(spec);

-- -------------------------------------------------------------------------
-- The lessons themselves
-- -------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000d1',
   'The Scientific Stack and Where to Run It',
   'markdown',
   'Python on its own is not especially good at numbers. A list of a million floats is a million separate objects, each with its own type information, scattered across memory. Adding two such lists means a million interpreter steps.

The scientific stack exists to fix exactly that, and it is worth knowing which library does what before you start using them interchangeably.

## The four you will actually use

- **NumPy** is the foundation. One array is one typed block of memory, and an operation on it runs in compiled C over the whole block. Everything below is built on this.
- **pandas** adds labels. A DataFrame is a set of NumPy arrays with column names, an index, and the operations you want for tabular data: join, group, pivot, resample.
- **Matplotlib** draws. It is old and its API shows it, but it is what everything else wraps, so it is the one worth knowing.
- **scikit-learn** is the machine learning course further down this track, and it takes NumPy arrays and DataFrames as its input. That is the main reason to learn these two properly first.

## Environments, before anything else

Install everything into one global Python and two projects will eventually need different versions of the same library. The fix costs thirty seconds:

```python
# In a terminal, once per project:
#   python -m venv .venv
#   source .venv/bin/activate      (Windows: .venv/Scripts/activate)
#   pip install numpy pandas matplotlib scikit-learn
#   pip freeze > requirements.txt

import sys
print(sys.executable)      # which Python is actually running
```

That last line is worth running whenever something is "not installed" despite having been installed. Nine times out of ten the answer is that pip and the interpreter are not the same environment.

## Notebooks, honestly

A notebook is a good place to look at data and a bad place to keep code. Cells run in whatever order you pressed shift-enter, which means a notebook that works on your screen may not work from a clean start - and that is not a hypothetical, it is the single most common reason an analysis cannot be reproduced.

Use one, and use it with a rule: before you share anything, restart the kernel and run every cell from the top. If that fails, the notebook was lying to you. Level 4 comes back to this.

## The versions this course uses

```python
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)
```

`np` and `pd` are not arbitrary. They are near-universal, every example you find online uses them, and deviating costs your reader a translation on every line.',
   'What NumPy, pandas, Matplotlib and scikit-learn each do, how they fit together, and why an isolated environment is the first thing to set up rather than the last.',
   8, 432, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000d2',
   'NumPy: Arrays and Vectorised Thinking',
   'markdown',
   'A NumPy array is a block of memory with one type and a shape. That single sentence explains both its speed and its restrictions.

```python
import numpy as np

prices = np.array([12.5, 19.0, 7.25, 31.0])
print(prices.dtype)     # float64
print(prices.shape)     # (4,)
```

Every element is a float64, laid out one after another. There is no per-item type tag and no pointer chasing, so an operation over the array is a tight loop in compiled code.

## Vectorised, not looped

The habit to build is describing the operation on the whole array:

```python
# Not this:
with_tax = []
for p in prices:
    with_tax.append(p * 1.2)

# This:
with_tax = prices * 1.2
```

The second version is shorter, harder to get wrong, and on a million elements it is roughly fifty times faster - the arithmetic happens in C, with no interpreter in the loop.

The same applies to comparisons, which produce an array of booleans you can use to select:

```python
expensive = prices > 15          # array([False,  True, False,  True])
print(prices[expensive])         # array([19., 31.])
print(prices[prices > 15].sum()) # 50.0
```

That pattern - build a boolean mask, index with it - is the one you will use most often, and it carries over to pandas unchanged.

## Shape is the thing that bites

```python
grid = np.arange(12).reshape(3, 4)
print(grid.sum())          # 66   - everything
print(grid.sum(axis=0))    # [12 15 18 21]  - down the columns
print(grid.sum(axis=1))    # [ 6 22 38]     - across the rows
```

`axis` is the axis that disappears. `axis=0` collapses the rows and leaves one value per column. People remember it as "0 is columns", which works until it does not; "the axis that goes away" always works.

## Broadcasting

An operation between arrays of different shapes stretches the smaller one, if it can:

```python
grid = np.arange(12).reshape(3, 4)
offsets = np.array([10, 20, 30, 40])
print(grid + offsets)      # offsets applied to every row
```

It works when the shapes match from the right, with 1 or absent counting as a match. It is extremely convenient and it is also how a bug hides: two arrays you expected to be the same length can broadcast into something plausible rather than raising. Print the shape when the numbers look wrong.

## Where NumPy stops

An array has one type. The moment you want a column of names next to a column of prices, with labels and a meaningful index, you want pandas - which is the next lesson, and which is NumPy underneath.',
   'One typed block of memory instead of a million Python objects, and the habit of describing an operation on a whole array rather than looping over it. This is the idea the entire stack is built on.',
   11, 416, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000d3',
   'Pandas: Series and DataFrames',
   'markdown',
   'A Series is a labelled array. A DataFrame is a dictionary of Series that share an index. Everything in pandas follows from those two sentences.

```python
import pandas as pd

sales = pd.DataFrame({
    ''region'': [''North'', ''South'', ''North'', ''East''],
    ''units'':  [120, 95, 143, 60],
    ''price'':  [12.5, 12.5, 11.0, 14.0],
})
print(sales)
print(sales.dtypes)
```

Each column is one dtype. The index - here 0 to 3, because nobody chose one - is how rows are addressed, and it is worth setting deliberately when you have a natural key.

## Selecting: the part to get right early

```python
sales[''units'']            # one column, as a Series
sales[[''region'', ''units'']] # two columns, as a DataFrame
sales[sales[''units''] > 100]  # rows where the mask is True
```

Then the pair that confuses everybody:

```python
sales.loc[0]        # by LABEL - the row whose index value is 0
sales.iloc[0]       # by POSITION - the first row
```

With a default index those two agree, which is why the difference goes unnoticed until the day you sort or filter and the labels stop matching the positions. Use `loc` when you mean a label and `iloc` when you mean a position, and say which you meant.

## Adding and transforming columns

```python
sales[''revenue''] = sales[''units''] * sales[''price'']
sales[''big''] = sales[''units''] > 100
```

Vectorised, exactly as in NumPy. If you find yourself writing `for i in range(len(df))`, stop: there is nearly always a column operation that does it, and it will be both faster and clearer.

## Looking at it

```python
sales.head()        # first five rows
sales.info()        # dtypes, non-null counts, memory
sales.describe()    # count, mean, std, quartiles for numeric columns
```

`info()` is the first thing to run on any new data. It tells you in one screen how many rows you have, which columns have missing values and - crucially - whether a column you expect to be a number has arrived as an object, which is pandas saying "these are strings".

## The copy warning

```python
subset = sales[sales[''units''] > 100]
subset[''units''] = 0      # SettingWithCopyWarning
```

pandas is warning that `subset` may be a view onto `sales` rather than a copy, so it cannot tell you whether the assignment will reach the original. Be explicit:

```python
subset = sales[sales[''units''] > 100].copy()
subset[''units''] = 0                        # unambiguous

sales.loc[sales[''units''] > 100, ''units''] = 0   # or change the original on purpose
```

Treat that warning as an error. It is the pandas equivalent of an uninitialised variable: the code appears to work until the day it does not.',
   'The DataFrame is the object you will spend the rest of your career in: named, typed columns sharing an index. This lesson covers how to make one, how to select from it, and the one distinction - loc against iloc - that causes most early confusion.',
   11, 420, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000d5',
   'Reading Real Data: CSV, JSON, SQL and Excel',
   'markdown',
   'Getting data in is where an analysis actually starts, and it is rarely one line.

## CSV, and the arguments worth knowing

```python
import pandas as pd
from io import StringIO

raw = StringIO("""date,region,units,note
2026-01-04,North,120,ok
2026-01-05,South,,missing count
2026-01-06,North,143,ok
""")

df = pd.read_csv(
    raw,
    parse_dates=[''date''],       # dates as datetimes, not strings
    dtype={''region'': ''category''},  # a repeated string is a category
)
print(df.dtypes)
```

Six parameters cover most of what goes wrong:

- **`sep`** when it is not a comma. European exports are often semicolon separated because the comma is the decimal point.
- **`encoding`** when the file came from Windows. `utf-8` fails, `latin-1` or `cp1252` usually works, and the giveaway is a UnicodeDecodeError naming a byte position.
- **`parse_dates`** so a date is a date. Without it every comparison is string comparison, which sorts 2026-10-01 before 2026-9-01.
- **`skiprows` / `header`** for files with a title and a blank line above the actual header - which is every file exported from a reporting tool.
- **`na_values`** for the placeholders a system used instead of leaving the field empty: `[''NA'', ''N/A'', ''-'', ''missing'', ''9999'']`.
- **`usecols`** when the file has eighty columns and you need four. It is also the simplest way to make a large file fit in memory.

## JSON

```python
import json
payload = json.loads(''{"results": [{"id": 1, "score": 9}, {"id": 2, "score": 7}]}'')
df = pd.json_normalize(payload[''results''])
```

`json_normalize` is the one to know: it flattens nested objects into columns like `user.name`, which is what you want from an API response. `pd.read_json` is for a file that is already a flat table.

## SQL

```python
# with a DB-API connection or a SQLAlchemy engine
# df = pd.read_sql("SELECT region, units FROM sales WHERE date >= %s", conn, params=[''2026-01-01''])
```

Two rules. Filter in SQL, not in pandas - a WHERE clause the database can serve with an index beats loading ten million rows and dropping nine. And parameterise; `params` exists for the same reason it does everywhere else.

## Excel

```python
# df = pd.read_excel(''report.xlsx'', sheet_name=''Q1'', skiprows=3)
```

Expect merged cells, a title row, numbers stored as text, and a footer with a total in it. `skiprows` and `usecols` handle most of it; the total row usually has to be dropped by hand, and it is worth asserting the row count afterwards so it fails loudly if the layout changes.

## Check what you got

```python
print(df.shape)
print(df.dtypes)
print(df.isna().sum())
```

Three lines, every time, before any analysis. Most bad results trace back to a column that silently loaded as `object` and was never looked at.',
   'read_csv has about fifty parameters and you will need six of them regularly. This lesson covers those six, the equivalents for JSON, SQL and Excel, and what to do when a file will not parse at all.',
   11, 425, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000d6',
   'Missing Values, Types and Duplicates',
   'markdown',
   'Cleaning is most of the work. It is also where the decisions that change your answer get made, usually without being written down.

## Missing is not one thing

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({
    ''region'': [''North'', ''South'', ''North'', None],
    ''units'':  [120, np.nan, 143, 60],
    ''note'':   [''ok'', ''N/A'', '''', ''ok''],
})
print(df.isna().sum())
```

Before deciding what to do, decide what the gap means:

- **Unknown.** The value exists and was not recorded. Dropping the row loses information; filling it invents some.
- **Not applicable.** A discount column on a non-discounted order. Zero may well be the honest value.
- **Recorded badly.** `''N/A''`, `''''`, `-1`, `9999`. These are not missing to pandas until you say so, which is what `na_values` is for at read time, or:

```python
df = df.replace({''N/A'': np.nan, '''': np.nan})
```

That third category is dangerous precisely because it does not show up in `isna()`. A `9999` left in a numeric column does not look missing; it looks like a very large order, and it moves your mean.

## Then choose, and say so

```python
df.dropna(subset=[''units''])              # rows without the thing being measured
df[''units''].fillna(0)                     # when absent genuinely means none
df[''units''].fillna(df[''units''].median())  # a defensible placeholder
df[''units''].ffill()                        # time series: carry the last reading
```

There is no default right answer. The one unacceptable choice is making it silently - write the reason in a comment next to the line, because the person asking why the total changed will be you, in March.

## Dtypes that arrived wrong

```python
df[''units''] = pd.to_numeric(df[''units''], errors=''coerce'')
df[''date''] = pd.to_datetime(df[''date''], errors=''coerce'')
df[''region''] = df[''region''].astype(''category'')
```

`errors=''coerce''` turns anything unparseable into NaT or NaN instead of raising - which is what you want, followed immediately by counting how many it produced:

```python
print(df[''units''].isna().sum(), ''values would not parse'')
```

A column that is `object` when it should be numeric is the single most common cause of a wrong answer, because `sum()` on strings concatenates rather than failing.

## Duplicates

```python
df.duplicated().sum()                         # identical rows
df.duplicated(subset=[''order_id'']).sum()      # rows that claim to be the same thing
df = df.drop_duplicates(subset=[''order_id''], keep=''last'')
```

Whole-row duplicates are usually a loading mistake - the same file appended twice. Key duplicates are a data problem, and `keep=''last''` versus `keep=''first''` is a real decision: the latest record is usually the corrected one, but not if your export is sorted alphabetically.

## Strings

```python
df[''region''] = df[''region''].str.strip().str.title()
```

Trailing whitespace is invisible and breaks every join and group-by you will do later. Normalise case and whitespace on anything you intend to group by, as soon as it is loaded.',
   'Missing is not one thing: a gap can mean unknown, not applicable, or zero recorded badly, and the right fix differs for each. This lesson also covers dtypes that arrived wrong and duplicates that are only duplicates on the columns that identify a row.',
   12, 431, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000d7',
   'Filtering, Grouping and Joining',
   'markdown',
   'Most questions are answered by narrowing rows, collapsing them into groups, or bringing in a column from another table. The rest is presentation.

## Filtering

```python
import pandas as pd

sales = pd.DataFrame({
    ''region'': [''North'', ''South'', ''North'', ''East'', ''South''],
    ''rep'':    [''ana'', ''bo'', ''ana'', ''cai'', ''bo''],
    ''units'':  [120, 95, 143, 60, 210],
})

north = sales[sales[''region''] == ''North'']
busy = sales[(sales[''units''] > 100) & (sales[''region''] != ''East'')]
```

Two things catch people. Conditions need brackets, because `&` binds tighter than `>`. And it is `&` and `|`, not `and` and `or` - the Python keywords want a single true or false, and a Series of booleans is neither.

```python
sales.query(''units > 100 and region != "East"'')
```

`query` is often easier to read, and it avoids both traps.

## Grouping

```python
sales.groupby(''region'')[''units''].sum()

sales.groupby(''region'').agg(
    total=(''units'', ''sum''),
    orders=(''units'', ''size''),
    best=(''units'', ''max''),
)
```

Split, apply, combine: the rows are split by the key, a function is applied to each group, and the results are stitched back together. The named form of `agg` is worth defaulting to - it produces columns called `total` and `orders` rather than a multi-level index you then have to flatten.

To keep the grouping key as a column rather than an index:

```python
sales.groupby(''region'', as_index=False)[''units''].sum()
```

## Joining

```python
targets = pd.DataFrame({''region'': [''North'', ''South'', ''West''], ''target'': [200, 300, 150]})

sales.merge(targets, on=''region'', how=''left'')
```

`how` is the whole decision:

- **`left`** keeps every sales row, filling `target` with NaN where there is no match. Usually what you want.
- **`inner`** keeps only matching rows, and silently drops the rest.
- **`outer`** keeps everything from both.

## The merge that multiplies

If the right-hand side has two rows per key, every left row matching that key becomes two rows. Nobody notices until a total is exactly double.

```python
before = len(sales)
joined = sales.merge(targets, on=''region'', how=''left'', validate=''many_to_one'')
assert len(joined) == before
```

`validate` raises if the relationship is not what you said, and the assertion catches the rest. Both cost one line and have each saved an afternoon.

## Reshaping between wide and long

```python
wide = sales.pivot_table(index=''rep'', columns=''region'', values=''units'', aggfunc=''sum'')
long = wide.reset_index().melt(id_vars=''rep'', value_name=''units'')
```

Long is better for computing and for most plotting libraries; wide is better for reading. Knowing which one a tool expects saves a lot of fighting with it.',
   'Three operations answer most questions: narrow the rows, collapse them into groups, and bring in a column from somewhere else. This lesson covers all three, and the merge that silently multiplies your row count.',
   12, 383, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000d9',
   'Group-By in Depth and Window Calculations',
   'markdown',
   '`groupby().sum()` collapses each group to one row. Often what you want is a group statistic attached to every row - each sale next to its region total, each score next to its cohort mean. That is `transform`, and it is the tool most people are missing.

```python
import pandas as pd

sales = pd.DataFrame({
    ''region'': [''North'', ''South'', ''North'', ''East'', ''South'', ''North''],
    ''rep'':    [''ana'', ''bo'', ''ana'', ''cai'', ''bo'', ''dee''],
    ''units'':  [120, 95, 143, 60, 210, 80],
})

sales[''region_total''] = sales.groupby(''region'')[''units''].transform(''sum'')
sales[''share''] = sales[''units''] / sales[''region_total'']
```

`transform` returns a Series the same length as the input, aligned to the original index. `agg` returns one row per group. That single difference is most of what there is to learn.

## Ranking inside a group

```python
sales[''rank_in_region''] = (
    sales.groupby(''region'')[''units''].rank(method=''dense'', ascending=False)
)
```

`method` matters when there are ties: `dense` gives 1, 2, 2, 3; `min` gives 1, 2, 2, 4. Pick on purpose, because a report that ranks differently from last quarter for no visible reason is a long conversation.

## Top n per group

```python
top = (sales.sort_values(''units'', ascending=False)
            .groupby(''region'')
            .head(1))
```

Sort, then take the head of each group. It reads oddly the first time and it is the idiomatic answer.

## Cumulative and rolling

```python
daily = pd.DataFrame({
    ''day'':   pd.date_range(''2026-01-01'', periods=7, freq=''D''),
    ''units'': [10, 14, 9, 21, 17, 25, 13],
})

daily[''running''] = daily[''units''].cumsum()
daily[''avg_3d''] = daily[''units''].rolling(window=3).mean()
daily[''vs_yesterday''] = daily[''units''].diff()
```

The first two values of `avg_3d` are NaN, which is correct rather than broken: a three-day average needs three days. `min_periods=1` will fill them if you would rather have a partial answer, and that is a judgement about what the number is for.

## Filtering whole groups

```python
busy = sales.groupby(''region'').filter(lambda g: g[''units''].sum() > 150)
```

Keeps every row of the groups that pass. Different from filtering rows, and the right tool for "show me everything from the regions that hit target".

## Apply, and why it is last

`apply` with a Python function works for anything and runs at Python speed - a loop with extra steps. Reach for `agg`, `transform` and the built-in methods first; use `apply` when the operation genuinely has no vectorised form, and expect it to be the slow line in your notebook.',
   'Beyond one number per group: transforms that put a group statistic back on every row, ranking inside a group, and cumulative calculations. This is the pandas equivalent of SQL window functions, and it removes most remaining loops.',
   12, 370, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000da',
   'Dates, Time Zones and Resampling',
   'markdown',
   'Dates look simple and are not. Most silent errors in reporting are a date doing something reasonable that nobody specified.

## Get them parsed, then indexed

```python
import pandas as pd

df = pd.DataFrame({
    ''ts'': [''2026-01-01 09:15'', ''2026-01-01 17:40'', ''2026-01-02 08:05''],
    ''units'': [12, 30, 7],
})
df[''ts''] = pd.to_datetime(df[''ts''])
df = df.set_index(''ts'').sort_index()
```

With a DatetimeIndex you get selection by partial string, which is the feature worth the setup:

```python
df.loc[''2026-01'']        # the whole month
df.loc[''2026-01-01'']     # one day
df.loc[''2026-01-01 09'':''2026-01-01 12'']
```

## Resampling

```python
df.resample(''D'')[''units''].sum()      # daily totals
df.resample(''W'')[''units''].mean()     # weekly average
df.resample(''ME'')[''units''].sum()     # month end
```

`resample` is `groupby` for time, and it fills in the gaps: a day with no rows appears with 0 or NaN rather than vanishing. That is usually what you want in a chart, and always what you want in a total.

## Time zones

This is where money gets lost.

```python
utc = df.tz_localize(''UTC'')               # these timestamps ARE UTC
local = utc.tz_convert(''Europe/London'')   # same instants, London clock
```

`tz_localize` attaches a zone to naive timestamps - it asserts what they always meant. `tz_convert` moves an aware timestamp to another zone. Using the first when you meant the second shifts every value by the offset, and nothing raises.

The practical rule: store and compute in UTC, convert once at the edge when a human will read it. A "daily total" is only meaningful once you have said whose day, and in a business with customers in two countries those two answers differ.

The clock changes make it concrete. On the last Sunday in March a London day has 23 hours; in October, 25. A daily sum over local time therefore has an hour missing or an hour counted twice, once a year, and it is usually blamed on the data.

## Gaps and alignment

```python
daily = df.resample(''D'')[''units''].sum()
daily = daily.asfreq(''D'').fillna(0)
```

`asfreq` makes the index regular. Without it, a chart draws a straight line across a missing week and a reader sees a trend that is really an absence.

## The two conversions worth memorising

```python
pd.to_datetime(1767225600, unit=''s'')     # a Unix timestamp
df[''ts''].dt.tz_convert(''UTC'').dt.date    # a date, in a stated zone
```

Everything else can be looked up. These two come up constantly and are easy to get subtly wrong.',
   'Dates are the part of data work most likely to be quietly wrong. A DatetimeIndex unlocks resampling and partial-string selection; time zones decide whether your daily totals are actually daily, and whether last March has 31 days or 30 and an hour.',
   12, 378, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000db',
   'Plotting to Find Things Out',
   'markdown',
   'Plot early and plot roughly. A chart you draw in ten seconds to see the shape of a column is worth more than the polished one at the end, because it is the one that changes what you do next.

## The four that answer most questions

```python
import pandas as pd
import matplotlib.pyplot as plt

daily = pd.DataFrame({
    ''day'': pd.date_range(''2026-01-01'', periods=14, freq=''D''),
    ''units'': [10, 14, 9, 21, 17, 25, 13, 11, 19, 24, 8, 30, 22, 16],
})

# 1. A line, for something over time
daily.plot(x=''day'', y=''units'', figsize=(8, 3))

# 2. A histogram, for the shape of one column
daily[''units''].plot(kind=''hist'', bins=7)

# 3. A bar, for a count or total per category
daily.assign(week=daily[''day''].dt.isocalendar().week)      .groupby(''week'')[''units''].sum().plot(kind=''bar'')

# 4. A scatter, for whether two numbers move together
daily.plot(kind=''scatter'', x=''units'', y=daily[''units''].cumsum())

plt.show()
```

Line for time. Histogram for distribution. Bar for comparison between categories. Scatter for relationship. Picking the wrong one is why so many dashboards are unreadable: a bar chart of a time series throws away the one thing you wanted to see.

## What a histogram tells you that describe() does not

```python
print(daily[''units''].describe())
daily[''units''].plot(kind=''hist'', bins=20)
```

A mean of 17 is consistent with every value being 17, with half being 4 and half being 30, and with a hundred values near 10 and three near 400. Those are completely different situations and they want completely different decisions. The histogram distinguishes them in one glance; the summary statistics do not.

## Enough Matplotlib to be dangerous

```python
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(daily[''day''], daily[''units''], marker=''o'')
ax.set_title(''Daily units, January'')
ax.set_ylabel(''units'')
ax.grid(alpha=0.3)
fig.autofmt_xdate()
```

`fig, ax = plt.subplots()` then methods on `ax` is the form worth learning. The alternative - `plt.plot` and friends drawing on a hidden current figure - works until you want two charts, at which point it stops working in a way that is hard to debug.

## One rule about axes

A truncated y-axis makes a 2% change look like a collapse. Sometimes that is the honest choice, because the variation is genuinely what matters. It is never the accidental choice: if your axis does not start at zero, you should be able to say why in a sentence.',
   'A chart is a tool for seeing what is in the data, not just the last step before a slide. Four plot types answer most questions, and knowing which one answers which saves you from the decorated bar chart that shows nothing.',
   11, 361, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000dd',
   'Memory, dtypes and When Pandas Is Wrong',
   'markdown',
   'The first dataset that does not fit in memory arrives sooner than people expect, and the first response - buy a bigger machine - is usually unnecessary.

## Measure before optimising

```python
import pandas as pd

df = pd.DataFrame({
    ''region'': [''North'', ''South'', ''East'', ''West''] * 25_000,
    ''units'': range(100_000),
    ''flag'': [True, False] * 50_000,
})
print(df.memory_usage(deep=True).sum() / 1e6, ''MB'')
print(df.dtypes)
```

`deep=True` matters: without it, object columns report the size of the pointers rather than of the strings they point at, which is the opposite of useful.

## The dtypes that cost you

- **Repeated strings as `object`.** Four distinct regions over 100,000 rows is four strings and 100,000 pointers. As a `category` it is four strings and 100,000 small integers.
- **int64 where int32 or int16 would do.** Ages do not need 64 bits.
- **float64 for something that is really a flag.**

```python
df[''region''] = df[''region''].astype(''category'')
df[''units''] = pd.to_numeric(df[''units''], downcast=''integer'')
print(df.memory_usage(deep=True).sum() / 1e6, ''MB'')
```

An order of magnitude is normal for a wide table with repeated strings. That is often the whole problem solved.

## Reading more than fits

```python
total = 0
for chunk in pd.read_csv(''big.csv'', chunksize=100_000, usecols=[''units'']):
    total += chunk[''units''].sum()
```

Two ideas: `usecols` so you never load the columns you do not need, and `chunksize` so you hold one piece at a time. Any aggregation that can be computed incrementally - sums, counts, min, max - works this way. A median does not, which is a useful thing to know about medians.

## Where pandas stops

Be honest about this rather than fighting it:

- **The data lives in a database and you are loading all of it to filter it.** Push the filter and the group-by into SQL. The database has indexes and was built for this.
- **It does not fit on one machine.** Polars will take you a long way further on one machine; Dask and Spark distribute. Each costs learning and operational complexity, which is why they are the third answer, not the first.
- **You are looping over rows.** That is not a scale problem, it is a vectorisation problem, and the fix is in Level 1.

## One habit

Time the slow cell before changing it:

```python
# In a notebook:
#   %%timeit
#   df.groupby(''region'')[''units''].sum()
```

Most guesses about which line is slow are wrong, and an optimisation applied to the wrong line is pure cost.',
   'A DataFrame can use ten times the memory it needs, and the fix is usually one line of dtypes. This lesson covers measuring it, chunked reading for files larger than RAM, and the honest point at which the answer is a database or a different library.',
   12, 397, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000de',
   'Analysis Somebody Else Can Run',
   'markdown',
   'The test is simple and uncomfortable: a colleague clones your work, runs it, and gets your numbers. Most analyses fail that test, and almost always for one of four reasons.

## 1. The environment is not written down

```python
# pip freeze > requirements.txt
# or, better, a pyproject.toml with pinned versions
```

"It worked last month" usually means a library changed a default. pandas has changed the default of more than one argument between versions; an unpinned analysis is one that produces different numbers over time for reasons unrelated to the data.

## 2. Nothing fixed the randomness

```python
import numpy as np

rng = np.random.default_rng(seed=20260104)
sample = rng.choice(1000, size=10, replace=False)
```

Any sampling, shuffling, train/test split or model initialisation needs a seed, and the seed belongs in the code rather than in your head. `default_rng` is the modern form; the old `np.random.seed` sets global state, which means one library can change another library''s results.

## 3. The notebook has hidden state

A cell you edited and did not re-run, a variable from a cell you deleted, a file you created by hand in cell 4 and then rewrote in cell 12. The notebook on your screen is not the notebook in the file.

The rule is the whole of the fix: **restart the kernel and run all cells, before sharing anything**. If it fails, it was always broken; you just had not noticed.

## 4. The inputs can change underneath

```python
import hashlib, pathlib

path = pathlib.Path(''sales.csv'')
print(path.stat().st_size, hashlib.sha256(path.read_bytes()).hexdigest()[:12])
```

Recording the size and a hash of the input costs nothing and settles the question of whether the file changed - which is otherwise an argument rather than a fact.

## Asserts are documentation that runs

```python
assert df[''order_id''].is_unique, ''order_id should identify a row''
assert df[''units''].ge(0).all(), ''negative units means a return, not a sale''
assert len(df) == before, ''the join changed the row count''
```

Each one states a thing you believe about the data. When the next export breaks that belief, you get a line number instead of a wrong chart.

## Write down the decisions

Every `fillna`, every dropped row, every outlier excluded is a judgement that changes the answer. A short Markdown cell saying what you did and why is the difference between a number somebody can defend and one they can only repeat.',
   'An analysis that only runs on your laptop, in the order you happened to press the keys, is not a result - it is an anecdote. Pinned versions, a fixed seed, no hidden state, and a notebook that runs top to bottom from a clean kernel.',
   11, 389, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000df',
   'From Notebook to Pipeline',
   'markdown',
   'A notebook is for discovering something. Once it has to run again next Monday, it needs to become something else - and the gap is smaller than people think.

## Functions with inputs and outputs

```python
import pandas as pd

def load(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=[''date''])
    assert not df.empty, f''no rows in {path}''
    return df

def clean(df: pd.DataFrame) -> pd.DataFrame:
    df = df.drop_duplicates(subset=[''order_id''], keep=''last'').copy()
    df[''region''] = df[''region''].str.strip().str.title()
    df[''units''] = pd.to_numeric(df[''units''], errors=''coerce'').fillna(0)
    return df

def summarise(df: pd.DataFrame) -> pd.DataFrame:
    return (df.groupby([''region'', pd.Grouper(key=''date'', freq=''W'')], as_index=False)
              [''units''].sum())
```

Three functions, each taking a DataFrame and returning one. No globals, nothing reading a variable defined in a cell above. Each is testable on five rows you write by hand, which is the thing a notebook can never give you.

## One entry point

```python
def main(source: str, destination: str) -> None:
    summary = summarise(clean(load(source)))
    summary.to_parquet(destination, index=False)
    print(f''wrote {len(summary)} rows to {destination}'')

# if __name__ == ''__main__'':
#     main(sys.argv[1], sys.argv[2])
```

Paths come in as arguments. A path hard-coded to your Downloads folder is the most common reason a pipeline runs on one machine only.

## Idempotent, or you will regret it

Running it twice must produce the same result as running it once. That means writing to a file that gets replaced, or upserting on a key - never appending. Jobs get retried, by a scheduler that does not tell you, and an appending job silently doubles a month.

## Fail loudly, in the right place

```python
try:
    main(source, destination)
except Exception:
    # A scheduler needs a non-zero exit code to notice.
    raise
```

A pipeline that catches everything and logs a warning is a pipeline that quietly stops producing data, and nobody finds out until someone asks why the dashboard stopped moving. Let it crash, and make sure the crash reaches a person.

## Parquet over CSV for anything downstream

```python
summary.to_parquet(''weekly.parquet'', index=False)
```

Parquet keeps dtypes, compresses several times smaller and reads columns selectively. CSV loses every type you worked out during cleaning - which means the next script re-infers them, possibly differently.

## What stays in the notebook

The exploration, the charts, the dead ends. Keep it; it is the record of how you got here. It is just no longer the thing that runs.',
   'The notebook was for finding the answer. Getting the same answer every Monday without you means functions, a defined input and output, idempotence and a loud failure - the few things that separate a script from a scheduled job.',
   12, 377, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-000000000010');
CALL search_reindex_all_quiet();
