-- =========================================================================
-- Seed 33 : Data Analytics
--
-- The second course in the Data Science track. It is about turning a
-- question somebody asked into a number somebody can act on, and about the
-- several ways that number can be confidently wrong.
--
-- Part of the Data Science track. Generated by the shared builder, so all
-- five courses in the track have the same shape and the same guarantees.
-- =========================================================================

INSERT INTO catalog_tags (id, slug, name) VALUES
  ('bbbbbbb1-0000-4000-8000-000000000019', 'data-science', 'Data Science'),
  ('bbbbbbb1-0000-4000-8000-00000000001d', 'analytics', 'Analytics'),
  ('bbbbbbb1-0000-4000-8000-00000000001e', 'statistics', 'Statistics'),
  ('bbbbbbb1-0000-4000-8000-000000000004', 'sql', 'SQL')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO catalog_courses
  (id, slug, title, subtitle, overview, description, category_id, instructor_id,
   level, status, thumbnail_url, price_cents, learning_outcomes, requirements,
   published_at)
VALUES
  ('c0000001-0000-4000-8000-000000000011',
   'data-analytics',
   'Data Analytics',
   'Four levels, twelve lessons, from a vague question to a defensible number',
   'Analytics is the work between a question and a decision. Somebody asks why signups dropped, or whether the new checkout is better, or which customers are worth keeping - and the job is to turn that into something measurable, measure it honestly, and say what it means plainly enough to act on.

Most of the difficulty is not technical. Pulling the numbers is usually the quick part; deciding what to count, noticing that the drop is a tracking change rather than a behaviour change, and recognising when a difference is too small to be real - that is the work, and it is where analyses go wrong.

So this course spends its time on judgement rather than tools. The SQL and the statistics here are the small subset you will use constantly, taught alongside the mistakes that make a number look solid when it is not.',
   'A complete path through analytics in four levels. Level 1 is the workflow and the descriptive statistics everyone uses and many people misread. Level 2 is metric design: defining something precisely enough that two people compute the same number, and the cohort and segmentation work that stops an average hiding the thing you were looking for. Level 3 is comparison - A/B tests, confidence intervals, and the difference between correlation and a cause. Level 4 is the operating side: dashboards people actually use, definitions that drift, and forecasts that are honest about uncertainty.

It assumes you can write basic SQL - SELECT, WHERE, GROUP BY - and no statistics at all. Everything statistical is built up from scratch, in words first.

Every level is three lessons and a Level Check quiz, with an Expert Exam at the end. The examples are small tables you can read in your head rather than datasets to download, because the point is the reasoning rather than the arithmetic.

By the end you will be able to take a question like "is the new onboarding working", turn it into a metric you can defend, work out whether the difference you see is real, and present it in a form that survives someone disagreeing with it.',
   'aaaaaaa1-0000-4000-8000-000000000004',
   '55555555-5555-4555-8555-555555555555',
   'beginner', 'published',
   'https://images.example-cdn.test/courses/data-analytics.jpg', 0,
   JSON_ARRAY('Turn a vague business question into a metric with a precise definition',
              'Read a distribution rather than trusting an average',
              'Build cohorts and retention curves, and read what they are saying',
              'Judge whether a difference between two groups is real or noise',
              'Tell correlation from causation, and name the likely confounder',
              'Build a dashboard somebody keeps using after the first week'),
   JSON_ARRAY('Basic SQL: SELECT, WHERE, GROUP BY', 'No statistics assumed'),
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), subtitle = VALUES(subtitle), overview = VALUES(overview),
  description = VALUES(description), category_id = VALUES(category_id),
  learning_outcomes = VALUES(learning_outcomes), requirements = VALUES(requirements);

INSERT INTO catalog_course_tags (course_id, tag_id) VALUES
  ('c0000001-0000-4000-8000-000000000011', 'bbbbbbb1-0000-4000-8000-000000000019'),
  ('c0000001-0000-4000-8000-000000000011', 'bbbbbbb1-0000-4000-8000-00000000001d'),
  ('c0000001-0000-4000-8000-000000000011', 'bbbbbbb1-0000-4000-8000-00000000001e'),
  ('c0000001-0000-4000-8000-000000000011', 'bbbbbbb1-0000-4000-8000-000000000004')
ON DUPLICATE KEY UPDATE course_id = VALUES(course_id);

-- -------------------------------------------------------------------------
-- The four levels
-- -------------------------------------------------------------------------
INSERT INTO catalog_modules (id, course_id, title, summary, `position`) VALUES
  ('d0000001-0000-4000-8000-00000000003c', 'c0000001-0000-4000-8000-000000000011',
   'Level 1 - Basic',
   'The shape of the work, and the statistics everybody already uses. The workflow first - what a question has to become before it can be answered - then the descriptive statistics that are reported daily and misread almost as often, and the handful of SQL that produces nearly every analytical answer.', 1),
  ('d0000001-0000-4000-8000-00000000003d', 'c0000001-0000-4000-8000-000000000011',
   'Level 2 - Intermediate',
   'Metrics, and the ways an average hides what you were looking for. Defining a metric precisely enough that two analysts compute the same number is harder than it sounds and worth doing properly. Then cohorts, which separate what changed from who changed, and segmentation, including the case where every segment moves one way and the total moves the other.', 2),
  ('d0000001-0000-4000-8000-00000000003e', 'c0000001-0000-4000-8000-000000000011',
   'Level 3 - Advanced',
   'Comparison, which is where confident wrong answers come from. Whether a difference between two groups is real, how big a sample has to be before the question can even be asked, and the gap between two things moving together and one causing the other - including how to name the confounder rather than gesture at it.', 3),
  ('d0000001-0000-4000-8000-00000000003f', 'c0000001-0000-4000-8000-000000000011',
   'Level 4 - Expert',
   'The operating side, which decides whether any of the earlier work keeps being useful. Dashboards that are still open in a month, definitions that drift without anyone noticing, and forecasts that are honest about what they do not know. Every one of these is a maintenance problem dressed as an analysis problem.', 4)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary);

INSERT INTO catalog_lessons
  (id, module_id, course_id, slug, title, summary, kind, status, `position`,
   duration_seconds, is_free_preview)
VALUES
  ('e0000001-0000-4000-8000-0000000000e1', 'd0000001-0000-4000-8000-00000000003c', 'c0000001-0000-4000-8000-000000000011',
   'an-workflow', 'From a Question to Something You Can Measure',
   'Nobody asks an answerable question first time. This lesson is about the translation: what "are users engaged" has to become before anybody can compute it, and the four questions to ask before touching any data.',
   'article', 'published', 1, 540, 1),
  ('e0000001-0000-4000-8000-0000000000e2', 'd0000001-0000-4000-8000-00000000003c', 'c0000001-0000-4000-8000-000000000011',
   'an-descriptive', 'Averages, Medians and the Shape Underneath',
   'The mean is the most reported and most misleading statistic in business. This lesson covers when it lies, what the median and the percentiles tell you instead, and why the distribution is the thing to look at first.',
   'article', 'published', 2, 600, 1),
  ('e0000001-0000-4000-8000-0000000000e3', 'd0000001-0000-4000-8000-00000000003c', 'c0000001-0000-4000-8000-000000000011',
   'an-sql', 'The SQL an Analyst Actually Uses',
   'Five clauses and three patterns answer most analytical questions. This lesson covers them, the difference between WHERE and HAVING, why a LEFT JOIN can silently drop rows, and the window functions that replace most self-joins.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000e4', 'd0000001-0000-4000-8000-00000000003c', 'c0000001-0000-4000-8000-000000000011',
   'an-level-1-check', 'Level 1 Check: Questions, Distributions and SQL',
   'Translating a question into a metric, when a mean misleads, and the LEFT JOIN that silently becomes an INNER JOIN.',
   'quiz', 'published', 4, 600, 0),
  ('e0000001-0000-4000-8000-0000000000e5', 'd0000001-0000-4000-8000-00000000003d', 'c0000001-0000-4000-8000-000000000011',
   'an-metrics', 'Defining a Metric That Survives Scrutiny',
   'Two analysts computing active users from the same database routinely get different numbers, and both are right. This lesson is about writing a definition precise enough that they cannot, and about the properties that separate a useful metric from a vanity one.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-0000000000e6', 'd0000001-0000-4000-8000-00000000003d', 'c0000001-0000-4000-8000-000000000011',
   'an-cohorts', 'Cohorts and Retention',
   'A total hides whether you are keeping people or replacing them. A cohort follows one group of users forward in time, which is the only way to see retention, and the shape of the curve says more than any single number.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-0000000000e7', 'd0000001-0000-4000-8000-00000000003d', 'c0000001-0000-4000-8000-000000000011',
   'an-segmentation', 'Segmentation, and Simpson Paradox',
   'An average over a mixed population describes nobody. Splitting it is the most reliable way to find something - and occasionally the split reverses the conclusion entirely, which is a real effect with a name and a straightforward explanation.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000e8', 'd0000001-0000-4000-8000-00000000003d', 'c0000001-0000-4000-8000-000000000011',
   'an-level-2-check', 'Level 2 Check: Metrics, Cohorts and Segments',
   'What a metric definition has to pin down, how to read a retention curve, the incomplete-cohort trap, and the reversal that happens when the mix changes.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-0000000000e9', 'd0000001-0000-4000-8000-00000000003e', 'c0000001-0000-4000-8000-000000000011',
   'an-ab-tests', 'Comparing Two Groups Honestly',
   'Checkout B converted at 4.4% against 4.1%. Whether that is a win, noise, or an artefact of when you stopped looking is the entire question, and the answer depends on decisions made before the test started.',
   'article', 'published', 1, 720, 0),
  ('e0000001-0000-4000-8000-0000000000ea', 'd0000001-0000-4000-8000-00000000003e', 'c0000001-0000-4000-8000-000000000011',
   'an-uncertainty', 'Confidence, Sample Size and Noise',
   'Every number computed from a sample has a range around it, and ignoring that range is how a dashboard produces a weekly meeting about nothing. How big that range is, how to shrink it, and when a difference is too small to discuss.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-0000000000eb', 'd0000001-0000-4000-8000-00000000003e', 'c0000001-0000-4000-8000-000000000011',
   'an-causation', 'Correlation, Causation and the Missing Variable',
   'Two things moving together is the beginning of a question, not the end of one. This lesson covers the three alternatives to causation, how to name the confounder in a specific case, and what evidence actually supports a causal claim.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000ec', 'd0000001-0000-4000-8000-00000000003e', 'c0000001-0000-4000-8000-000000000011',
   'an-level-3-check', 'Level 3 Check: Comparison and Inference',
   'What a p-value does and does not say, why peeking breaks a test, how sample size and uncertainty relate, and the three alternatives to a causal explanation.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-0000000000ed', 'd0000001-0000-4000-8000-00000000003f', 'c0000001-0000-4000-8000-000000000011',
   'an-dashboards', 'Dashboards People Actually Use',
   'Most dashboards are opened twice. The ones that survive answer a specific recurring question, show change rather than level, and make it obvious when a number is broken rather than merely low.',
   'article', 'published', 1, 600, 0),
  ('e0000001-0000-4000-8000-0000000000ee', 'd0000001-0000-4000-8000-00000000003f', 'c0000001-0000-4000-8000-000000000011',
   'an-data-quality', 'Definitions Drift, and Data Breaks Quietly',
   'The hardest failures in analytics are the silent ones: a tracking change, a renamed column, a filter somebody added. This lesson is about tests on data, the checks worth running every day, and what to do when the numbers were wrong for a month.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-0000000000ef', 'd0000001-0000-4000-8000-00000000003f', 'c0000001-0000-4000-8000-000000000011',
   'an-forecasting', 'Forecasting Without Pretending',
   'A forecast is a range with a story, not a line. Trend and seasonality, why a confidence band is the point rather than a decoration, and the small number of honest checks that stop a forecast being an extrapolation of last Tuesday.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000f0', 'd0000001-0000-4000-8000-00000000003f', 'c0000001-0000-4000-8000-000000000011',
   'an-expert-exam', 'Expert Exam: Data Analytics',
   'Dashboards, silent data failures, forecasting baselines, and the judgement running through all of it: what makes a number defensible rather than merely available.',
   'quiz', 'published', 4, 1500, 0)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), summary = VALUES(summary), kind = VALUES(kind),
  duration_seconds = VALUES(duration_seconds), is_free_preview = VALUES(is_free_preview);

-- -------------------------------------------------------------------------
-- The diagram the course opens with
-- -------------------------------------------------------------------------
INSERT INTO content_lesson_diagrams (lesson_id, title, alt, caption, spec, `position`) VALUES
  ('e0000001-0000-4000-8000-0000000000e1',
   'From question to decision',
   'A business question is turned into a precisely defined metric, the metric is computed from data, the result is checked for whether the difference is real, and only then does it become a decision.',
   'The second box is where most analyses go wrong, and the only one nobody schedules time for.',
   '{"nodes": [{"label": "A question", "note": "Why did signups drop? Is checkout B better?"}, {"label": "A metric", "note": "Defined precisely enough to compute twice the same way"}, {"label": "A number", "note": "Computed from data you have checked"}, {"label": "A decision", "note": "With the uncertainty stated, not hidden"}], "edges": [{"label": "defined as"}, {"label": "measured as"}, {"label": "read as"}]}', 1)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), alt = VALUES(alt), caption = VALUES(caption), spec = VALUES(spec);

-- -------------------------------------------------------------------------
-- The lessons themselves
-- -------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000e1',
   'From a Question to Something You Can Measure',
   'markdown',
   '"Are users engaged?" is not a question you can answer. It is a question you have to translate, and the translation is the analysis.

## The four questions, before any SQL

**1. What decision follows from this?** If the answer changes nothing, the analysis is not worth doing, and saying so is a legitimate output. If the answer is "we would change the onboarding", that tells you what the metric has to be sensitive to.

**2. Which population?** All users, or users who signed up this quarter, or paying users excluding the free trial? Every one of those gives a different number and all of them are defensible. The analysis that does not say which it used cannot be reproduced.

**3. Over what period, and compared to what?** A number alone is rarely useful. 4.2% is meaningless; 4.2% against 3.9% last month, on the same definition, is a finding.

**4. What would make this wrong?** Ask it before you compute, while you can still be honest. A tracking change, a seasonal effect, a marketing campaign, a bot.

## A worked translation

- Question: *Are users engaged?*
- Decision: whether to invest in a weekly digest email.
- Metric: proportion of accounts active in at least 3 distinct days in a rolling 28-day window.
- Population: accounts created more than 28 days ago, excluding internal and test accounts.
- Comparison: this 28-day window against the same window a quarter ago.
- Threats: the mobile app started sending a heartbeat in March, which would raise "active" without anyone doing anything.

That takes ten minutes and is most of the work. The query is twenty lines.

## Write the definition down before you compute

Not after. The pressure to adjust a definition once you have seen the number is enormous and usually invisible to the person doing it - you try a variant, it looks more sensible, you keep it. That is how an analysis ends up measuring the analyst''s expectations.

If you do change it, say so and show both.

## The output is a sentence

Not a table. "Engagement is flat at 4.2% quarter on quarter, and the mobile heartbeat added about 0.3 points in March, so the underlying number is slightly down." A table supports that sentence; it does not replace it.',
   'Nobody asks an answerable question first time. This lesson is about the translation: what "are users engaged" has to become before anybody can compute it, and the four questions to ask before touching any data.',
   9, 382, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000e2',
   'Averages, Medians and the Shape Underneath',
   'markdown',
   'The mean is the first statistic everyone learns and the one that misleads most often, because it assumes something about the data that business data rarely satisfies.

## When the mean is fine, and when it is not

The mean is a good summary when the data is roughly symmetric and has no extreme values. Heights are like this. Almost nothing in a business is.

Revenue per customer, session length, time to first purchase, support tickets per account - all of these are skewed: most values small, a few enormous. One customer spending 50,000 moves the mean for everybody and tells you nothing about a typical customer.

```
Spend per customer: 10, 12, 15, 18, 20, 22, 25, 30, 35, 50000
mean   = 5018.7
median = 21
```

The mean here describes nobody. The median describes the middle customer, which is what "typical" meant.

## Percentiles say more than either

```
p50 = 21     half of customers spend less than this
p90 = 50     the busiest tenth start here
p99 = 50000  and this is the one distorting your mean
```

For anything about time - page load, response time, delivery - the percentile is the only honest summary, because the average user experience is not the experience of the average. A mean response time of 200ms with a p99 of 8 seconds means one request in a hundred is unusable, and the mean conceals exactly that.

## Look at the distribution first

A histogram takes ten seconds and answers questions a summary cannot:

- Is it **bimodal**? Two humps usually means two populations stuck together - trial and paid, mobile and desktop - and the right move is to split them, not to average them.
- Is there a **spike at zero**? Very common, and it usually means "never did the thing", which is a different question from "how much did they do".
- Are there **impossible values**? Negative ages, orders in 1970, a thousand sessions in a day. Those are data problems, and the mean quietly absorbs them.

## Variation matters as much as level

Two teams both average 100 tickets a week. One does 95-105; the other does 20-250. Those are completely different operations and the average is identical. Report a spread - standard deviation if the data is symmetric, the interquartile range if it is not - or you have told half the story.

## The practical rule

Report the median and a couple of percentiles for anything skewed, say which you used, and keep the distribution to hand. Reporting a mean is not wrong; reporting only a mean, for data you have not looked at, usually is.',
   'The mean is the most reported and most misleading statistic in business. This lesson covers when it lies, what the median and the percentiles tell you instead, and why the distribution is the thing to look at first.',
   10, 442, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000e3',
   'The SQL an Analyst Actually Uses',
   'markdown',
   'Analytical SQL is a small language. Five clauses, three patterns, and a handful of functions cover most questions.

## The shape

```sql
SELECT   region, COUNT(*) AS orders, SUM(amount) AS revenue
FROM     orders
WHERE    created_at >= ''2026-01-01''
GROUP BY region
HAVING   COUNT(*) > 10
ORDER BY revenue DESC;
```

WHERE filters rows before grouping; HAVING filters groups after. Putting an aggregate in WHERE is an error, and putting a row condition in HAVING is slow rather than wrong - the database had to build groups it then threw away.

## Counting things carefully

```sql
COUNT(*)              -- rows
COUNT(user_id)        -- rows where user_id is not null
COUNT(DISTINCT user_id)  -- distinct users
```

Three different numbers, confused constantly. "How many customers ordered" is nearly always `COUNT(DISTINCT user_id)`, and reporting `COUNT(*)` instead silently counts your repeat buyers several times.

## The LEFT JOIN that becomes an INNER JOIN

```sql
-- Wrong: the WHERE clause drops the unmatched rows the LEFT JOIN kept
SELECT u.id, o.amount
FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE o.created_at >= ''2026-01-01'';

-- Right: the condition belongs in the join
SELECT u.id, o.amount
FROM users u
LEFT JOIN orders o ON o.user_id = u.id AND o.created_at >= ''2026-01-01'';
```

In the first query, a user with no orders has a NULL `created_at`, the WHERE rejects NULL, and the user disappears - so "users and their recent orders" quietly becomes "users who ordered recently". This is the most common bug in analytical SQL and it produces a plausible answer.

## Window functions

```sql
SELECT
  region,
  order_id,
  amount,
  SUM(amount)  OVER (PARTITION BY region)                AS region_total,
  RANK()       OVER (PARTITION BY region ORDER BY amount DESC) AS rank_in_region,
  LAG(amount)  OVER (PARTITION BY region ORDER BY created_at)  AS previous_order
FROM orders;
```

A window function computes across a set of rows without collapsing them - the same idea as `transform` in pandas. It replaces most self-joins, and `LAG` in particular turns "compared to the previous period" from a fiddly join into one line.

## Dates, carefully

```sql
WHERE created_at >= ''2026-01-01'' AND created_at < ''2026-02-01''
```

Half-open ranges. `BETWEEN ''2026-01-01'' AND ''2026-01-31''` excludes everything that happened on the 31st after midnight, which is most of the 31st - and the error is invisible because the number still looks reasonable.

## Common table expressions, for readability

```sql
WITH recent AS (
  SELECT * FROM orders WHERE created_at >= ''2026-01-01''
),
per_user AS (
  SELECT user_id, SUM(amount) AS spend FROM recent GROUP BY user_id
)
SELECT AVG(spend), COUNT(*) FROM per_user;
```

Each step is named and can be inspected on its own. A query written as one nested block is a query nobody will check.',
   'Five clauses and three patterns answer most analytical questions. This lesson covers them, the difference between WHERE and HAVING, why a LEFT JOIN can silently drop rows, and the window functions that replace most self-joins.',
   11, 442, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000e5',
   'Defining a Metric That Survives Scrutiny',
   'markdown',
   '"Monthly active users" sounds unambiguous. It is not, and two analysts given that brief will produce different numbers from the same database - both correctly.

## What has to be nailed down

- **Active doing what?** Logged in? Performed a meaningful action? Received an automated sync from a mobile app that was never opened?
- **Which accounts?** Internal, test, bot, deleted, duplicate.
- **What window?** Calendar month, or rolling 28 days? Calendar months differ in length and in weekend count, so January looks worse than March for no reason. Rolling 28 days has a constant number of each weekday and is almost always the better choice.
- **Which time zone?** A day boundary in UTC splits an Australian evening in half.
- **Counted how?** Distinct accounts, or distinct humans - two people sharing a login, one person with three accounts.

A definition that answers those five is a definition two people can implement identically. One that does not is a source of meetings.

## Properties of a metric worth having

**It moves when the thing moves.** If a metric cannot distinguish a good month from a bad one, it is decoration.

**It is hard to game accidentally.** Page views goes up when navigation gets worse. Tickets closed goes up when tickets are closed badly. Choose metrics whose easiest way to improve is the thing you actually want.

**It is one number, with a stated denominator.** "Conversion" is meaningless until you say conversion of what to what over what period.

**Somebody owns it.** Metrics without an owner drift: a column changes meaning, a filter is added, and nobody notices for a quarter.

## Ratios need their denominator watched

A conversion rate can rise because more people converted or because fewer people arrived. Those call for opposite responses. Always report the numerator and denominator alongside the ratio - it costs two columns and prevents the most common misreading in analytics.

## Leading and lagging

Revenue is a lagging metric: by the time it moves, the thing that caused it happened weeks ago. Trial-to-paid conversion in week one is leading: it moves early and predicts revenue later.

You need both. Lagging metrics tell you whether the business worked; leading metrics tell you in time to do something.

## Write it in a shared place

```
weekly_active_account:
  numerator: distinct account_id with >= 1 qualifying_event in the last 7 days
  qualifying_event: any of lesson_view, quiz_start, playground_run
  excludes: account.is_internal, account.deleted_at IS NOT NULL
  timezone: UTC
  owner: analytics
  changed: 2026-03-02 added playground_run
```

That block, in a document everybody can see, ends more arguments than any dashboard.',
   'Two analysts computing active users from the same database routinely get different numbers, and both are right. This lesson is about writing a definition precise enough that they cannot, and about the properties that separate a useful metric from a vanity one.',
   11, 430, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000e6',
   'Cohorts and Retention',
   'markdown',
   'Total active users can be flat while you lose every user you had and replace them with new ones. The total cannot tell you which is happening. A cohort can.

## What a cohort is

A group of users who share a starting point - usually the month or week they signed up - followed forward in time. You are asking: of the people who joined in January, how many were still here in month 1, month 2, month 3?

```
Cohort     Size   M0     M1     M2     M3
Jan        1200   100%   42%    31%    28%
Feb        1450   100%   45%    33%    30%
Mar        1600   100%   38%    24%    -
```

Three things are visible here that no total would show.

## Reading the curve

**It should flatten.** A retention curve that drops and then levels off means you have found a group the product works for. One that keeps falling at a constant rate means there is no such group yet, and growth is a leaky bucket.

**The first interval is the biggest drop, always.** M0 to M1 is where most of the loss is. Improving it is usually the highest-leverage work available, and it is about onboarding rather than about the product''s depth.

**Compare cohorts, not months.** March looks worse at M1 than February. That is a real signal: something changed for people who joined in March. A total active number would have shown this as a mild dip two months later, by which time the cause is hard to find.

## The SQL shape

```sql
WITH first_seen AS (
  SELECT user_id, DATE_FORMAT(MIN(created_at), ''%Y-%m-01'') AS cohort
  FROM events GROUP BY user_id
),
activity AS (
  SELECT DISTINCT user_id, DATE_FORMAT(created_at, ''%Y-%m-01'') AS active_month
  FROM events
)
SELECT f.cohort,
       TIMESTAMPDIFF(MONTH, f.cohort, a.active_month) AS month_number,
       COUNT(DISTINCT a.user_id) AS users
FROM first_seen f
JOIN activity a ON a.user_id = f.user_id
GROUP BY f.cohort, month_number
ORDER BY f.cohort, month_number;
```

Divide each row by its cohort size to get the percentages.

## Two traps

**The newest cohort is incomplete.** March has no M3 because March was two months ago. Showing it as 0 rather than blank makes a healthy cohort look like a collapse, and somebody will act on it.

**Cohorts are not only signup month.** Cohort by acquisition channel, by plan, by first action taken. "Users who completed onboarding" against "users who did not" is often the most informative split anybody has run.',
   'A total hides whether you are keeping people or replacing them. A cohort follows one group of users forward in time, which is the only way to see retention, and the shape of the curve says more than any single number.',
   11, 396, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000e7',
   'Segmentation, and Simpson Paradox',
   'markdown',
   'An average over a mixed population usually describes nobody in it. Segmentation is splitting that population into groups that behave differently, and it is the most reliable way to turn a flat number into a finding.

## Where to split

- **By acquisition.** Paid search, organic, referral. These almost always retain differently, and a blended number is a weighted average of two unrelated businesses.
- **By platform.** Mobile and desktop behave differently enough that a combined funnel is usually meaningless.
- **By tenure.** New and long-standing users want different things and fail at different steps.
- **By geography**, which is often a proxy for language, payment method and time zone all at once.

Start with the split you would act on differently. If you would do the same thing either way, it is not a useful segmentation.

## The reversal that has a name

```
                 Treatment A        Treatment B
Mobile           10/100   = 10%     40/400  = 10%
Desktop          80/400   = 20%     30/150  = 20%
Overall          90/500   = 18%     70/550  = 12.7%
```

A and B perform identically in every segment. Overall, A looks far better. Nothing is wrong with the arithmetic: A happened to get more desktop users, and desktop converts better regardless of treatment.

That is Simpson''s paradox, and it is not a curiosity - it appears whenever the mix differs between the groups being compared. If someone shows you a difference between two periods, two channels or two experiment arms, the first question is whether the mix changed.

## The practical defence

**Check the mix before believing the difference.** If the proportion of mobile users changed between the periods, compare within platform first.

**Prefer a weighted comparison.** Compute the metric per segment and then combine using a fixed reference mix, so a change in composition cannot move the headline on its own.

**Be suspicious of a metric that moved without any segment moving.** That is the signature.

## Do not split until it is noise

Segment far enough and every group has twelve people in it and a dramatic-looking rate. A segment that small cannot distinguish a real effect from a coin flip, and the most extreme-looking segments in any analysis are almost always the smallest ones. Show the count beside every rate, and treat anything under a few hundred as a hypothesis rather than a finding.',
   'An average over a mixed population describes nobody. Splitting it is the most reliable way to find something - and occasionally the split reverses the conclusion entirely, which is a real effect with a name and a straightforward explanation.',
   11, 388, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000e9',
   'Comparing Two Groups Honestly',
   'markdown',
   'Variant B converted at 4.4%, A at 4.1%. Is B better?

The honest answer is that you cannot tell from those two numbers, and most of what determines the answer was decided before the test ran.

## Why a difference is not a result

Flip two fair coins a hundred times each and they will not both land on fifty. Random variation produces differences; the question is whether this difference is larger than variation alone would usually produce.

That is all a p-value is: the probability of seeing a difference at least this large if there were really no difference at all. A small p-value means the result would be surprising under "no effect". It does **not** mean the effect is large, or important, or that you have a 95% chance of being right.

## Decide the sample size first

A test that runs until it looks good is not a test. Looking repeatedly and stopping at the first significant moment ("peeking") inflates the false positive rate badly - run it long enough and almost any A/A test will cross the line at some point.

Before starting, fix:

- the **metric**, exactly one, defined as in Level 2;
- the **minimum effect worth detecting** - 0.1 percentage points may be real and still not worth shipping;
- the **sample size**, computed from that effect and your baseline rate;
- the **stopping date**, and then stop then.

As a rough shape: detecting small relative changes on a 4% baseline takes tens of thousands of users per arm. If you have hundreds, you are not going to detect a 5% improvement, and running the test anyway produces a number rather than knowledge.

## Confidence intervals say more than p-values

"B is better, p = 0.03" tells you almost nothing about size. "B is 0.3 points higher, 95% interval from 0.05 to 0.55" tells you it is probably real and probably small. The interval answers the question people actually have.

A wide interval that crosses zero is not "no effect" - it is "this test could not tell", which is a different and more useful statement.

## The practical failures, in order of frequency

1. **Peeking and stopping early.** Overwhelmingly the most common.
2. **Testing many metrics and reporting the one that moved.** Twenty metrics at a 5% threshold means one false positive on average, every time.
3. **Broken randomisation.** Users assigned by a bucketing that correlates with something - signup date, device - are not two comparable groups.
4. **Novelty.** A change performs well for a week because it is new. Run long enough to see it settle.
5. **Ignoring the segments.** An overall wash can hide a large gain on mobile and a loss on desktop.

## When you cannot run a test

Plenty of changes cannot be A/B tested: pricing, brand, anything affecting everyone at once. Then you are comparing before and after, and you have to argue away everything else that changed - seasonality, a campaign, a release. Say that explicitly rather than presenting it as if it were a test.',
   'Checkout B converted at 4.4% against 4.1%. Whether that is a win, noise, or an artefact of when you stopped looking is the entire question, and the answer depends on decisions made before the test started.',
   12, 512, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000ea',
   'Confidence, Sample Size and Noise',
   'markdown',
   'Every number computed from a sample is an estimate. It has a range around it, and that range is usually wider than people expect.

## Where the range comes from

If 40 out of 1,000 visitors converted, the rate is 4%. Run the same week again with the same product and you would get 3.7%, or 4.3%. Nothing changed; the visitors are a sample.

The width of that range depends almost entirely on the count of the thing you are measuring, not on the size of the population. For a proportion, a reasonable mental model is that the uncertainty shrinks with the square root of the number of events - so to halve the range you need four times the data.

```
40 conversions out of 1,000   -> 4%, roughly plus or minus 1.2 points
400 out of 10,000             -> 4%, roughly plus or minus 0.4 points
4,000 out of 100,000          -> 4%, roughly plus or minus 0.12 points
```

That table is the whole lesson. With a thousand visitors, a move from 4% to 4.5% is invisible. With a hundred thousand, it is obvious.

## The weekly dashboard problem

A metric with a plus or minus 1.2 point range, reported weekly without that range, will appear to move every week. Teams then explain each movement - a campaign, a release, the weather - and the explanations are fiction, because nothing moved.

Two fixes, both cheap:

- **Put the interval on the chart.** A band rather than a line changes the conversation from "why is it down" to "it is not down".
- **Use a longer window.** A 28-day rolling figure has four times the data of a 7-day one and roughly half the noise.

## Small segments are mostly noise

The most extreme-looking rows of any segmented table are almost always the smallest ones, because small samples vary more. Sort a table by conversion rate and the top is populated by segments with eleven users.

Always show the denominator next to the rate. A reader who can see `11 users` will discount it automatically; one who sees only `63%` will not.

## Rounding and false precision

Reporting 4.17% from 1,000 visitors claims a precision you do not have. Round to the precision your sample supports - here, one decimal at most - because an extra digit is a claim about certainty.

## The question to ask of any difference

"How many events is this based on, and how big is the range?" If that cannot be answered, the difference is not yet a finding. It is an observation worth checking with more data.',
   'Every number computed from a sample has a range around it, and ignoring that range is how a dashboard produces a weekly meeting about nothing. How big that range is, how to shrink it, and when a difference is too small to discuss.',
   11, 434, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000eb',
   'Correlation, Causation and the Missing Variable',
   'markdown',
   'Users who use feature X retain better. The temptation is to build more of feature X. Before that, there are three other explanations, and one of them is usually right.

## The three alternatives

**1. Reverse causation.** Engaged users use more features. The feature did not cause the engagement; the engagement caused the feature use. This is extremely common with anything optional.

**2. A confounder.** Something causes both. Teams on the enterprise plan use feature X and also retain better - because they are enterprise teams with a contract and an administrator, not because of the feature.

**3. Selection.** The people who chose the feature differ systematically from those who did not, in ways you did not measure. Self-selection is a confounder you cannot see.

## Naming it, in the specific case

The useful discipline is not "correlation is not causation" - everyone knows that and it stops no one. It is to say out loud what the confounder would be, concretely:

> Accounts that enabled single sign-on retain 30 points better. The confounder is company size: SSO is an enterprise feature, enterprise accounts have annual contracts, and an annual contract retains by definition.

Once stated, it can be checked. Compare within company size and see whether the gap survives.

## Evidence that does support a causal claim

In descending order of strength:

1. **A randomised experiment.** Assignment is random, so the groups differ only by chance. This is why A/B tests matter: randomisation handles confounders you never thought of.
2. **A natural experiment.** Something assigned the groups for reasons unrelated to the outcome - a staged rollout by region, a bug that disabled a feature for some users.
3. **Comparison within strata.** If the effect holds in every company size, the confounder has been accounted for - but only that one, and only if measured well.
4. **A plausible mechanism plus timing.** The weakest. Useful for forming a hypothesis, not for concluding.

## The time-ordering check

Does the behaviour precede the outcome? If users show the retention difference before they adopt the feature, the feature is a marker rather than a cause. This is a cheap check and it kills a surprising number of claims.

## How to say it

Not "feature X drives retention". Instead: "accounts using X retain 30 points better; this is largely explained by plan size, and within the enterprise plan the gap is 4 points, which we have not tested causally."

That sentence is longer and less satisfying, and it is the one that will not have to be retracted.',
   'Two things moving together is the beginning of a question, not the end of one. This lesson covers the three alternatives to causation, how to name the confounder in a specific case, and what evidence actually supports a causal claim.',
   11, 426, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000ed',
   'Dashboards People Actually Use',
   'markdown',
   'Most dashboards are built, shown once, and never opened again. The ones that survive have a few things in common, and none of them are chart types.

## Build it for one recurring question

"Everything about sales" is not a question, and a dashboard that answers it has forty charts and no reader. "Did anything change this week that I should look into?" is a question, and it supports maybe six.

If you cannot say who opens it, how often, and what they do differently as a result, it is a report rather than a dashboard, and a report is better as a document that goes to them.

## Show change, not level

A number on its own cannot be interpreted. Every metric needs a comparison baked into the view: against last week, against the same week last year, against target. The most useful dashboards show a sparkline and a delta and almost nothing else.

## Make broken look different from bad

The most important failure mode is a pipeline that stops. A chart that flatlines at zero because the job failed looks exactly like a catastrophic business week, and the reaction is wrong in both directions.

- Show the **data freshness** - "last updated 14 minutes ago" - on every page.
- Draw **no data** differently from **zero**. A gap in the line, not a point at the bottom.
- Add a **row count** panel. A sudden drop in rows processed is the earliest signal of a broken upstream.

## Keep the definitions attached

Every metric on a dashboard should link to its definition - the block from Level 2. Without it, the dashboard becomes the definition, and the definition is then whatever the SQL happens to do after six people have edited it.

## Fewer numbers, chosen

Six good charts are read; forty are scanned. If something has not been looked at in a month, delete it. A dashboard that has grown continuously for two years is a dashboard nobody trusts, because nobody can say which parts are still correct.

## Let people leave with the data

An export button, or the query behind each chart. Analysts will need to go further than any dashboard allows, and hiding the query means they rebuild it - slightly differently - and now there are two definitions.',
   'Most dashboards are opened twice. The ones that survive answer a specific recurring question, show change rather than level, and make it obvious when a number is broken rather than merely low.',
   10, 386, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000ee',
   'Definitions Drift, and Data Breaks Quietly',
   'markdown',
   'The loud failures are easy: a job crashes and somebody gets paged. The expensive ones are silent - a number that is wrong but plausible, for weeks.

## How numbers go wrong quietly

- **A tracking change.** The mobile app starts firing an event on launch rather than on interaction. Active users rises 8%, everyone celebrates, nothing happened.
- **A schema change.** A column goes from NOT NULL to nullable. Rows that used to be counted now have a NULL that a filter rejects.
- **A backfill.** Someone reloads six months of history with slightly different logic, and your dashboard changes retrospectively.
- **A definition edit.** A filter is added to a shared query to fix one report, and every other report using it moves.

None of these produce an error. All produce a number.

## Tests that catch them

Treat data like code, with assertions that run on every refresh:

```sql
-- Volume: today should look like recent days
SELECT COUNT(*) FROM events WHERE day = CURRENT_DATE;   -- alert if < 50% of the 7-day median

-- Uniqueness: the key is actually a key
SELECT COUNT(*) - COUNT(DISTINCT order_id) FROM orders;  -- must be 0

-- Range: values that cannot be
SELECT COUNT(*) FROM orders WHERE amount < 0 OR amount > 100000;

-- Freshness: is the newest row recent
SELECT TIMESTAMPDIFF(HOUR, MAX(created_at), NOW()) FROM events;  -- alert over 6

-- Referential: orphans
SELECT COUNT(*) FROM orders o LEFT JOIN users u ON u.id = o.user_id WHERE u.id IS NULL;
```

Five checks, each one line, each catching a class of failure that otherwise reaches a slide.

## Version the definitions

Metric definitions belong in version control with the rest of the code, so a change is a reviewed diff with a date on it. When a metric moves, the first question is "what changed in the definition", and a git log answers it in seconds.

## Annotate the charts

Mark the deploy, the tracking change, the backfill on the timeline. A step change with no annotation gets explained as behaviour for ever afterwards.

## When you find out it was wrong

Say so quickly, in plain terms: what was wrong, which period, which direction, what the corrected number is, and what will stop it recurring. Quietly fixing a dashboard is worse than the original error - someone made a decision on the old number and nobody told them.

The credibility cost of announcing an error is small and recoverable. The cost of someone else finding it is not.',
   'The hardest failures in analytics are the silent ones: a tracking change, a renamed column, a filter somebody added. This lesson is about tests on data, the checks worth running every day, and what to do when the numbers were wrong for a month.',
   11, 420, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY)),

  ('e0000001-0000-4000-8000-0000000000ef',
   'Forecasting Without Pretending',
   'markdown',
   'A forecast is a range. A forecast presented as a single line is a forecast that will be wrong in a way nobody planned for.

## The three parts of most business series

**Trend** - the slow direction. **Seasonality** - the repeating pattern, usually weekly and yearly. **Noise** - the rest.

Separating them is most of forecasting:

- A weekly pattern is almost always there in anything consumer-facing. Comparing Monday to Sunday and calling it a decline is the single most common mistake.
- A yearly pattern needs at least two years of history to see at all, and three to trust.
- What is left after removing both is the part worth explaining.

## Start with the dumb baselines

Before any model, compute these:

```
naive:        tomorrow = today
seasonal:     next Monday = last Monday
drift:        extend the straight line through the last 8 weeks
```

A model that cannot beat "the same day last week" is not earning its complexity, and a surprising number cannot. Always report your model''s error alongside the baselines''; a forecast without that comparison has no scale.

## Measure the error on data the model has not seen

Fit on everything up to a cut-off, predict the period after it, compare. Measuring error on the data you fitted tells you how well the model memorised, which is not the question.

For business series, mean absolute error in the units people think in ("out by about 40 orders a day") communicates better than a percentage, which explodes when the actual value is near zero.

## The band is the output

```
Next week: 1,240 orders expected, likely between 1,080 and 1,400.
```

The range is what makes the forecast usable - it is what tells somebody whether to staff for 1,100 or 1,400. A point estimate alone invites a conversation about why the actual was not exactly that.

And the range should widen with distance. A forecast six months out with the same band as next week is not a forecast; it is a straight line with error bars drawn on.

## When not to forecast

If the series is driven by events rather than momentum - launches, campaigns, contracts - a statistical forecast will extrapolate the past through a future that does not resemble it. Say that, and forecast the known events instead.

The honest version is often: "the baseline continues at about 1,200 a week; the question is entirely whether the March campaign repeats, which is a decision rather than a prediction."',
   'A forecast is a range with a story, not a line. Trend and seasonality, why a confidence band is the point rather than a decoration, and the small number of honest checks that stop a forecast being an extrapolation of last Tuesday.',
   11, 419, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 3 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-000000000011');
CALL search_reindex_all_quiet();
