-- =========================================================================
-- Seed 35 : Machine Learning
--
-- The third course in the Data Science track. It teaches supervised learning
-- with scikit-learn, and spends as much time on the ways a model can look
-- good and be useless as on fitting one.
--
-- Part of the Data Science track. Generated by the shared builder, so all
-- five courses in the track have the same shape and the same guarantees.
-- =========================================================================

INSERT INTO catalog_tags (id, slug, name) VALUES
  ('bbbbbbb1-0000-4000-8000-000000000019', 'data-science', 'Data Science'),
  ('bbbbbbb1-0000-4000-8000-00000000001f', 'machine-learning', 'Machine Learning'),
  ('bbbbbbb1-0000-4000-8000-000000000020', 'scikit-learn', 'scikit-learn'),
  ('bbbbbbb1-0000-4000-8000-00000000001e', 'statistics', 'Statistics')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO catalog_courses
  (id, slug, title, subtitle, overview, description, category_id, instructor_id,
   level, status, thumbnail_url, price_cents, learning_outcomes, requirements,
   published_at)
VALUES
  ('c0000001-0000-4000-8000-000000000012',
   'machine-learning',
   'Machine Learning',
   'Four levels, twelve lessons, from a first model to one you can defend',
   'Machine learning is fitting a function to examples. You show a program thousands of cases where you know the answer, it finds a rule that reproduces them, and you then apply that rule to cases where you do not know the answer. There is no understanding involved, and treating it as if there were is the source of most disappointment with it.

The fitting is the easy part. Four lines of scikit-learn will train a model on anything you hand it, and it will produce a number that looks like success. The hard part - and the content of this course - is knowing whether that number means anything: whether the model has learned the pattern or memorised the examples, whether a column quietly contains the answer, and whether 95% accuracy is excellent or worse than guessing.

It is the point in this track where the earlier courses pay off. Everything here assumes you can load and clean data in pandas and that you know why a difference might be noise.',
   'A complete path through practical machine learning in four levels. Level 1 is what a model is, the vocabulary - features, labels, supervised and unsupervised - and a first model trained, evaluated and interpreted end to end. Level 2 is why that first model is usually wrong: overfitting, cross-validation, the feature engineering that helps and the leakage that fakes a result. Level 3 covers the models worth actually knowing, from linear and logistic regression through to gradient boosting, plus clustering. Level 4 is production: pipelines, tuning, drift, monitoring, and what to say when a model''s decision has to be explained to the person it affected.

It assumes Python and pandas - the first course in this track is enough - and no mathematics beyond arithmetic. Where a method needs an idea from statistics, the idea is explained in words where it is used.

Every level is three lessons and a Level Check quiz, with an Expert Exam at the end. Examples use scikit-learn with small built-in datasets, so every one runs without a download.

By the end you will be able to frame a problem as a learning task, build a model that does not fool you, measure it with a metric that matches the cost of being wrong, and say honestly what it will and will not do once it is live.',
   'aaaaaaa1-0000-4000-8000-000000000004',
   '55555555-5555-4555-8555-555555555555',
   'intermediate', 'published',
   'https://images.example-cdn.test/courses/machine-learning.jpg', 0,
   JSON_ARRAY('Frame a business problem as a supervised learning task, or rule out that it is one',
              'Split data so your evaluation means something, including for time series',
              'Recognise overfitting and leakage before they reach a slide',
              'Choose a metric that matches the real cost of each kind of error',
              'Pick between linear models, forests and boosting for a reason you can state',
              'Put a model behind a pipeline and monitor it for drift once it is live'),
   JSON_ARRAY('Python and pandas - the first course in this track is enough', 'No mathematics beyond arithmetic'),
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), subtitle = VALUES(subtitle), overview = VALUES(overview),
  description = VALUES(description), category_id = VALUES(category_id),
  learning_outcomes = VALUES(learning_outcomes), requirements = VALUES(requirements);

INSERT INTO catalog_course_tags (course_id, tag_id) VALUES
  ('c0000001-0000-4000-8000-000000000012', 'bbbbbbb1-0000-4000-8000-000000000019'),
  ('c0000001-0000-4000-8000-000000000012', 'bbbbbbb1-0000-4000-8000-00000000001f'),
  ('c0000001-0000-4000-8000-000000000012', 'bbbbbbb1-0000-4000-8000-000000000020'),
  ('c0000001-0000-4000-8000-000000000012', 'bbbbbbb1-0000-4000-8000-00000000001e')
ON DUPLICATE KEY UPDATE course_id = VALUES(course_id);

-- -------------------------------------------------------------------------
-- The four levels
-- -------------------------------------------------------------------------
INSERT INTO catalog_modules (id, course_id, title, summary, `position`) VALUES
  ('d0000001-0000-4000-8000-000000000040', 'c0000001-0000-4000-8000-000000000012',
   'Level 1 - Basic',
   'What a model actually is, and a first one built properly. The vocabulary comes first because it is used imprecisely everywhere: features, labels, supervised and unsupervised, classification and regression. Then the train/test split, which is the one idea that makes evaluation meaningful, and a complete first model with its score interpreted rather than just reported.', 1),
  ('d0000001-0000-4000-8000-000000000041', 'c0000001-0000-4000-8000-000000000012',
   'Level 2 - Intermediate',
   'Why a first model is usually wrong, and how to find out before anybody else does. Overfitting and the cross-validation that measures it, feature engineering and the leakage that masquerades as brilliance, and the evaluation metrics that matter once accuracy has been exposed as a poor summary.', 2),
  ('d0000001-0000-4000-8000-000000000042', 'c0000001-0000-4000-8000-000000000012',
   'Level 3 - Advanced',
   'The models worth knowing, and when each is the right answer. Linear and logistic regression first, because they are interpretable and frequently sufficient; then trees, forests and gradient boosting, which win most competitions on tabular data; then the unsupervised pair - clustering and dimensionality reduction - with an honest account of how to tell a real cluster from an arbitrary one.', 3),
  ('d0000001-0000-4000-8000-000000000043', 'c0000001-0000-4000-8000-000000000012',
   'Level 4 - Expert',
   'Everything between a good notebook and a model that keeps working. Pipelines and tuning done so the result is reproducible rather than lucky; drift, which is the reason a model that was fine in March is wrong in September; and the obligations that arrive the moment a model makes a decision about a person.', 4)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary);

INSERT INTO catalog_lessons
  (id, module_id, course_id, slug, title, summary, kind, status, `position`,
   duration_seconds, is_free_preview)
VALUES
  ('e0000001-0000-4000-8000-0000000000f1', 'd0000001-0000-4000-8000-000000000040', 'c0000001-0000-4000-8000-000000000012',
   'ml-what-it-is', 'What a Model Is, and What It Is Not',
   'A model is a function fitted to examples. This lesson covers the vocabulary used loosely everywhere, the difference between supervised and unsupervised learning, and the kinds of problem machine learning is the wrong answer to.',
   'article', 'published', 1, 540, 1),
  ('e0000001-0000-4000-8000-0000000000f2', 'd0000001-0000-4000-8000-000000000040', 'c0000001-0000-4000-8000-000000000012',
   'ml-split', 'Features, Labels and the Split That Makes It Honest',
   'A model scored on the data it was fitted to tells you how well it memorised. The train/test split is the fix, and getting it right - including for time series and grouped data - decides whether every number after it is meaningful.',
   'article', 'published', 2, 600, 1),
  ('e0000001-0000-4000-8000-0000000000f3', 'd0000001-0000-4000-8000-000000000040', 'c0000001-0000-4000-8000-000000000012',
   'ml-first-model', 'A First Model, End to End',
   'Load, split, fit, predict, score - and then the part people skip, which is working out whether the score is good. A model that is 95% accurate on data that is 95% one class has learned nothing at all.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000f4', 'd0000001-0000-4000-8000-000000000040', 'c0000001-0000-4000-8000-000000000012',
   'ml-level-1-check', 'Level 1 Check: Models, Splits and First Scores',
   'What a model is and is not, why the split comes first, when random splitting is wrong, and why an accuracy figure means nothing without a baseline.',
   'quiz', 'published', 4, 600, 0),
  ('e0000001-0000-4000-8000-0000000000f5', 'd0000001-0000-4000-8000-000000000041', 'c0000001-0000-4000-8000-000000000012',
   'ml-overfitting', 'Overfitting, Underfitting and Cross-Validation',
   'Every model sits somewhere between memorising the training set and missing the pattern entirely. Cross-validation measures where, using the training data alone, so the test set stays untouched for the one number you report.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-0000000000f6', 'd0000001-0000-4000-8000-000000000041', 'c0000001-0000-4000-8000-000000000012',
   'ml-features', 'Feature Engineering, and the Leakage That Fakes a Result',
   'Features are where domain knowledge enters a model, and where the most embarrassing mistakes happen. A 0.99 score is almost never brilliance - it is a column that contains the answer, and this lesson is about finding it before a presentation does.',
   'article', 'published', 2, 720, 0),
  ('e0000001-0000-4000-8000-0000000000f7', 'd0000001-0000-4000-8000-000000000041', 'c0000001-0000-4000-8000-000000000012',
   'ml-evaluation', 'Choosing a Metric That Matches the Cost',
   'Accuracy is almost always the wrong metric. Precision, recall, the confusion matrix and the threshold you get to choose - and which of them to optimise depends entirely on what each kind of mistake actually costs.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000f8', 'd0000001-0000-4000-8000-000000000041', 'c0000001-0000-4000-8000-000000000012',
   'ml-level-2-check', 'Level 2 Check: Overfitting, Features and Metrics',
   'Reading a train-test gap, what cross-validation buys, spotting leakage from the score alone, and choosing between precision and recall for a stated cost.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-0000000000f9', 'd0000001-0000-4000-8000-000000000042', 'c0000001-0000-4000-8000-000000000012',
   'ml-linear', 'Linear and Logistic Regression',
   'The models to try first: fast, interpretable, hard to overfit when regularised, and often within a point or two of anything more elaborate. Also the only ones whose decisions you can explain in a sentence.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-0000000000fa', 'd0000001-0000-4000-8000-000000000042', 'c0000001-0000-4000-8000-000000000012',
   'ml-trees', 'Trees, Forests and Gradient Boosting',
   'A decision tree asks a sequence of yes-or-no questions. One is weak and interpretable; hundreds averaged are strong; hundreds built to correct each other are what wins on tabular data. This lesson covers all three and what each costs.',
   'article', 'published', 2, 720, 0),
  ('e0000001-0000-4000-8000-0000000000fb', 'd0000001-0000-4000-8000-000000000042', 'c0000001-0000-4000-8000-000000000012',
   'ml-unsupervised', 'Clustering and Dimensionality Reduction',
   'Learning without labels: finding groups that were not defined in advance, and compressing many columns into a few. Both are useful and both are easy to over-interpret, because an algorithm will always return an answer.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-0000000000fc', 'd0000001-0000-4000-8000-000000000042', 'c0000001-0000-4000-8000-000000000012',
   'ml-level-3-check', 'Level 3 Check: Models and What They Assume',
   'When a linear model is enough, what a forest and boosting each buy you, why permutation importance beats the built-in kind, and how to tell a real cluster from an arbitrary one.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-0000000000fd', 'd0000001-0000-4000-8000-000000000043', 'c0000001-0000-4000-8000-000000000012',
   'ml-pipelines', 'Pipelines, Tuning and Reproducibility',
   'Every preprocessing step must be fitted on training data only, every time, including inside each cross-validation fold. A pipeline makes that automatic, and it is also the only sane way to ship the same transformations to production.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-0000000000fe', 'd0000001-0000-4000-8000-000000000043', 'c0000001-0000-4000-8000-000000000012',
   'ml-drift', 'Drift, Monitoring and Knowing When to Retrain',
   'A model is fitted to a moment. The world moves, the inputs change shape, and the model degrades without any error being raised. What to monitor, how to tell input drift from a genuine fall in performance, and when retraining is the wrong answer.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-0000000000ff', 'd0000001-0000-4000-8000-000000000043', 'c0000001-0000-4000-8000-000000000012',
   'ml-responsibility', 'Explaining a Decision, and Its Limits',
   'The moment a model affects a person, accuracy stops being the only requirement. Why a proxy for a protected attribute is the usual mechanism, why group metrics cannot all be equal at once, and what an explanation has to contain to be worth anything.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-000000000100', 'd0000001-0000-4000-8000-000000000043', 'c0000001-0000-4000-8000-000000000012',
   'ml-expert-exam', 'Expert Exam: Machine Learning',
   'Pipelines and leakage, tuning honestly, the two kinds of drift, feedback loops, and what has to be true before a model decides something about a person.',
   'quiz', 'published', 4, 1500, 0)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), summary = VALUES(summary), kind = VALUES(kind),
  duration_seconds = VALUES(duration_seconds), is_free_preview = VALUES(is_free_preview);

-- -------------------------------------------------------------------------
-- The diagram the course opens with
-- -------------------------------------------------------------------------
INSERT INTO content_lesson_diagrams (lesson_id, title, alt, caption, spec, `position`) VALUES
  ('e0000001-0000-4000-8000-0000000000f1',
   'How a model is built and judged',
   'Labelled examples are split into a training set and a held-out test set, a model is fitted on the training set only, and it is then judged on the test set, which it has never seen. The gap between the two scores is what tells you whether it learned or memorised.',
   'The split comes first, before anything else touches the data. Everything that goes wrong in machine learning goes wrong here.',
   '{"nodes": [{"label": "Labelled examples", "note": "Rows where you already know the answer"}, {"label": "Split", "note": "Training set, and a test set set aside untouched"}, {"label": "A fitted model", "note": "A rule learned from the training set only"}, {"label": "An honest score", "note": "Measured on data the model has never seen"}], "edges": [{"label": "divided into"}, {"label": "fitted on"}, {"label": "judged by"}]}', 1)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), alt = VALUES(alt), caption = VALUES(caption), spec = VALUES(spec);

-- -------------------------------------------------------------------------
-- The lessons themselves
-- -------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-0000000000f1',
   'What a Model Is, and What It Is Not',
   'markdown',
   'A machine learning model is a function fitted to examples. You supply inputs and known outputs; an algorithm searches for a function that maps one to the other with as few mistakes as possible; you then apply that function to inputs whose output you do not know.

That is the whole idea. It is worth holding onto, because almost every disappointment with machine learning comes from expecting something more.

## The vocabulary, used precisely

- A **feature** is an input column. Age, price, country, number of logins last week.
- A **label** (or target) is the output column you want to predict.
- **Supervised** learning has labels. **Unsupervised** does not - it finds structure, such as clusters, without being told what is correct.
- **Classification** predicts a category: spam or not, which of five plans. **Regression** predicts a number: revenue, days until churn.
- **Training** is the fitting. **Inference** is using the fitted model on new data.

Most useful business machine learning is supervised, and most of that is classification.

## What it does not do

**It does not find causes.** A model that predicts churn from support tickets has not shown that tickets cause churn. It has found that they move together, which is where the analytics course left off.

**It does not work without examples.** If you have no labelled cases, you have no supervised problem, and acquiring labels is usually the real project.

**It does not extrapolate.** A model trained on last year''s prices knows nothing about a price range it has never seen. It will still return a confident number for it.

## When not to use it

- **A rule would do.** If the policy is "flag any transaction over 10,000 from a new account", write that. It is auditable, instant, and will not drift.
- **Being wrong is expensive and unexplainable.** Credit, hiring, medical triage - the bar is far higher than accuracy, and "the model said so" is not a defence.
- **The data does not contain the answer.** No algorithm recovers information that was never recorded. Predicting cancellation from a table with no behavioural columns is not a modelling problem; it is an instrumentation problem.

## The honest framing

"Given these columns, can we predict this one, well enough to be worth acting on, often enough to beat what we do now?" Every word matters. The baseline - what we do now - is what a model has to beat, and it is frequently a simple rule that nobody wrote down.',
   'A model is a function fitted to examples. This lesson covers the vocabulary used loosely everywhere, the difference between supervised and unsupervised learning, and the kinds of problem machine learning is the wrong answer to.',
   9, 419, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000f2',
   'Features, Labels and the Split That Makes It Honest',
   'markdown',
   'A model scored on the data it was trained on is not being tested. It is being asked to recall, and a complex enough model can recall perfectly while knowing nothing.

So the first thing you do, before exploring, before engineering a single feature, is set data aside.

```python
from sklearn.model_selection import train_test_split

X = df[[''tenure_days'', ''logins_last_week'', ''plan'']]
y = df[''churned'']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
```

Four arguments, three of which matter.

- **`test_size=0.2`** keeps a fifth back. With small data, 0.3; with millions of rows, 0.1 is plenty.
- **`random_state`** makes it reproducible. Without it, every run gives a different score and you will chase the variation.
- **`stratify=y`** keeps the class proportions the same in both halves. With an imbalanced label - 3% churn - a random split can easily give a test set with twice the churn rate of the training set, and then the score is about the split rather than the model.

## Random is not always right

**Time series.** If you are predicting the future, the test set must come after the training set. A random split lets the model learn from Thursday to predict Wednesday, which it will never be able to do in production. Split by date.

```python
cutoff = ''2026-03-01''
train = df[df[''date''] < cutoff]
test = df[df[''date''] >= cutoff]
```

**Grouped data.** If one customer has forty rows, a random split puts some in train and some in test, and the model recognises the customer rather than the pattern. Split by group - `GroupShuffleSplit` - so every row for a customer lands on one side.

## The test set is spent when you look at it

Each time you check the test score and change something in response, a little of it leaks into your decisions. Do that twenty times and the test set has become a second training set, and the score is optimistic again.

The discipline: use cross-validation on the training set for every decision, and touch the test set once, at the end, to report a number. If you must look more often, hold out a third set.

## The number worth watching

Not the test score on its own, but the gap between training and test:

```
train 0.99, test 0.71   -> memorised; the model is too complex for the data
train 0.72, test 0.70   -> learned something, and it generalises
train 0.61, test 0.60   -> underfitted; it has not found the pattern yet
```

That one comparison diagnoses most of what goes wrong, and the next level is about what to do in each case.',
   'A model scored on the data it was fitted to tells you how well it memorised. The train/test split is the fix, and getting it right - including for time series and grouped data - decides whether every number after it is meaningful.',
   10, 438, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000f3',
   'A First Model, End to End',
   'markdown',
   'Six lines train a model. The work is in the seventh.

```python
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

data = load_breast_cancer(as_frame=True)
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000))
model.fit(X_train, y_train)

print(''train'', model.score(X_train, y_train))
print(''test '', model.score(X_test, y_test))
```

`fit` then `predict` or `score` is the entire scikit-learn interface, and it is the same for every model in the library. Swapping LogisticRegression for RandomForestClassifier is a one-word change, which is why the library is worth learning rather than any one algorithm.

## The pipeline is not optional

`make_pipeline(StandardScaler(), LogisticRegression())` matters more than it looks. The scaler learns the mean and standard deviation of each column, and it must learn them from the training data only. Scaling the whole dataset first lets information from the test set into the training process - which is leakage, quietly, in the first three lines of nearly every tutorial.

Inside a pipeline, `fit` scales using training statistics and `predict` reuses them. It is correct by construction.

## Is the score good?

```python
from sklearn.dummy import DummyClassifier

baseline = DummyClassifier(strategy=''most_frequent'')
baseline.fit(X_train, y_train)
print(''baseline'', baseline.score(X_test, y_test))
```

Always. If 95% of your rows are one class, predicting that class for everything scores 95%, and a model at 96% has added almost nothing. The baseline turns an impressive-sounding number into a comparison.

## What the model learned

```python
import pandas as pd

coefficients = pd.Series(
    model[-1].coef_[0], index=X.columns
).sort_values()
print(coefficients.head(3))
print(coefficients.tail(3))
```

For a linear model on scaled inputs, the coefficients are comparable: the largest absolute values are the features doing the work. If something nonsensical is at the top - an id column, a timestamp - you have found a bug, and finding it now is much cheaper than finding it after launch.

## The order to work in

Split, baseline, simplest model that could work, look at what it learned, and only then reach for something more complicated. Most projects that go wrong skipped to the end.',
   'Load, split, fit, predict, score - and then the part people skip, which is working out whether the score is good. A model that is 95% accurate on data that is 95% one class has learned nothing at all.',
   11, 347, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000f5',
   'Overfitting, Underfitting and Cross-Validation',
   'markdown',
   'A model that is too simple misses the pattern. A model that is too complex memorises the noise. Everything in between is a choice, and cross-validation is how you make it with evidence.

## The two failures

**Underfitting**: poor on training data and poor on test data. The model cannot represent the relationship - a straight line through a curve. Fix by adding capacity or better features.

**Overfitting**: excellent on training data, poor on test data. The model has learned the specific rows, including their noise. Fix by simplifying, regularising, or getting more data.

```
train 0.99, test 0.71   overfitted
train 0.61, test 0.60   underfitted
train 0.74, test 0.72   about right
```

## Cross-validation

A single train/validation split wastes data and gives a score that depends on which rows happened to land where. K-fold cross-validation splits the training data into k parts, fits k times - each time holding out a different part - and averages.

```python
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train, y_train, cv=5, scoring=''roc_auc'')
print(scores.mean().round(3), ''+/-'', scores.std().round(3))
```

The standard deviation is as informative as the mean. A model scoring 0.80 plus or minus 0.02 is a different proposition from one scoring 0.80 plus or minus 0.11 - the second is unstable, and on a different sample it might be 0.69.

Use `StratifiedKFold` for imbalanced classes, `TimeSeriesSplit` when order matters, `GroupKFold` when rows share an entity.

## The learning curve

```python
from sklearn.model_selection import learning_curve
```

Plot the training and validation scores against the amount of data used. The shape tells you what to do next:

- Both low, converged: **underfitting**. More data will not help. Better features or a stronger model will.
- Large gap, validation still rising: **overfitting**, and more data probably will help.
- Both converged and acceptable: you are done; spend the effort elsewhere.

This is worth running before deciding to collect more data, because collecting more data is usually the most expensive option available.

## Regularisation, in one paragraph

Regularisation penalises complexity: the fit is scored on accuracy minus a penalty for large coefficients. It is the dial between the two failures, exposed as `C` in scikit-learn''s linear models (smaller is more regularised) and as depth and leaf limits in trees. Tuning it is most of what hyperparameter search does.',
   'Every model sits somewhere between memorising the training set and missing the pattern entirely. Cross-validation measures where, using the training data alone, so the test set stays untouched for the one number you report.',
   11, 379, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000f6',
   'Feature Engineering, and the Leakage That Fakes a Result',
   'markdown',
   'Most of the lift in a modelling project comes from features rather than from algorithms. And so does the most common catastrophic error.

## Useful features

**Ratios and rates.** Logins per day since signup is usually more predictive than logins, because it is not confounded with tenure.

**Recency.** Days since last activity is one of the strongest single predictors of churn in most products.

**Aggregates with a window.** Orders in the last 7, 30 and 90 days, together, carry a trend that any one of them alone does not.

**Categorical encoding, chosen deliberately.** One-hot for a handful of categories; for high-cardinality columns such as postcode, one-hot creates thousands of columns and target encoding is the usual answer - computed inside the cross-validation fold, for the reason below.

```python
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

prep = ColumnTransformer([
    (''num'', StandardScaler(), [''tenure_days'', ''logins_per_day'']),
    (''cat'', OneHotEncoder(handle_unknown=''ignore''), [''plan'', ''country'']),
])
```

`handle_unknown=''ignore''` matters: production will send a category that was not in your training data, and the default is to raise.

## Leakage

Leakage is any information in your features that would not be available at prediction time. It produces excellent scores and a model that fails completely in production.

The classic cases:

- **A column that is a consequence of the label.** Predicting churn with `cancellation_reason`. It is only populated for churners.
- **An aggregate computed over the whole dataset.** A customer average that includes rows from the test period.
- **Timestamps.** Predicting fraud with `investigated_at`, which only exists because fraud was suspected.
- **Scaling or imputing before the split.** The scaler saw the test set. Small, real, and the reason to use pipelines.

## How to find it

**Be suspicious of a very high score.** On a messy business problem, 0.99 means leakage until proven otherwise. Nothing is that predictable.

**Look at feature importance.** A column at the top that you did not expect is the first place to check.

**Ask of every feature: would I know this at the moment I need the prediction?** If the answer is no, or "only for some rows", it leaks.

**Drop it and see.** If removing one column collapses the score from 0.98 to 0.71, that column was the answer in disguise.

## The 0.99 rule

A model that scores 0.99 on a real business problem is wrong roughly every time. It is worth saying so plainly, before it reaches a slide: the fastest way to lose credibility is to present a leaked model and have somebody else find the column.',
   'Features are where domain knowledge enters a model, and where the most embarrassing mistakes happen. A 0.99 score is almost never brilliance - it is a column that contains the answer, and this lesson is about finding it before a presentation does.',
   12, 419, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000f7',
   'Choosing a Metric That Matches the Cost',
   'markdown',
   'A fraud model that flags nothing is 99.8% accurate. Accuracy is the default metric and almost always the wrong one.

## The confusion matrix

```python
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, model.predict(X_test)))
print(classification_report(y_test, model.predict(X_test)))
```

Four numbers: true positives, false positives, true negatives, false negatives. Every other metric is a summary of them, and the four are worth looking at directly because they are what the business feels.

- **Precision** - of the cases we flagged, how many were real. Low precision means wasted effort and annoyed customers.
- **Recall** - of the real cases, how many we caught. Low recall means the thing you were trying to catch got through.

These trade off. You can always have more of one by accepting less of the other, which is why the question "is this model good" cannot be answered without knowing what the errors cost.

## Which to favour

- **Screening for a serious condition**: recall. A missed case is far worse than a second test.
- **Sending an expensive intervention**: precision. Every false positive is money spent on somebody who was fine.
- **Both matter roughly equally**: F1, their harmonic mean - but say so deliberately rather than reaching for it by default.

## The threshold is yours to pick

```python
probabilities = model.predict_proba(X_test)[:, 1]
flagged = probabilities > 0.3     # not 0.5
```

`predict` uses 0.5, which has no special meaning. Lowering the threshold catches more and flags more; raising it does the opposite. Choosing it is a business decision, and it is one of the few dials you can turn after training with no retraining at all.

## ROC AUC, and when it misleads

ROC AUC measures ranking quality across every threshold - the probability that a random positive is ranked above a random negative. It is threshold-free, which makes it good for comparing models.

With heavy class imbalance it flatters: a model can have excellent AUC and still be useless at any threshold you would actually use, because the metric gives credit for discriminating among the vast negative class. For rare positives, use average precision (the area under the precision-recall curve) instead.

## For regression

```python
from sklearn.metrics import mean_absolute_error, mean_squared_error
```

MAE is in the units people think in and treats all errors alike. RMSE punishes large errors more, which is right when one big miss is worse than several small ones. R-squared says how much variance you explained and is easy to misread as a grade - 0.3 can be excellent or terrible depending on the domain.

Pick before you model. Choosing the metric after seeing the results is how a model gets reported as a success.',
   'Accuracy is almost always the wrong metric. Precision, recall, the confusion matrix and the threshold you get to choose - and which of them to optimise depends entirely on what each kind of mistake actually costs.',
   11, 443, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000f9',
   'Linear and Logistic Regression',
   'markdown',
   'Linear models predict a weighted sum of the inputs. That is their limitation and the reason to start with them.

## Linear regression

```python
from sklearn.linear_model import Ridge

model = make_pipeline(StandardScaler(), Ridge(alpha=1.0))
model.fit(X_train, y_train)
```

Each feature gets a coefficient; the prediction is the sum. With scaled inputs the coefficients are directly comparable, and "a one standard deviation increase in recency reduces the prediction by 0.4" is a sentence you can put in front of anybody.

`Ridge` rather than plain `LinearRegression` as a default: the `alpha` penalty on large coefficients is what stops correlated features producing enormous opposing weights that fit the training noise.

## Logistic regression

For classification. It predicts a probability by passing the same weighted sum through a function that squashes it into 0 to 1.

```python
from sklearn.linear_model import LogisticRegression

model = make_pipeline(StandardScaler(), LogisticRegression(C=1.0, max_iter=2000))
model.fit(X_train, y_train)
proba = model.predict_proba(X_test)[:, 1]
```

`C` is the inverse of regularisation strength: smaller C, simpler model. It is the first thing to tune.

Despite the name it is a classifier, and it is the workhorse of credit scoring, medical risk and anywhere a decision has to be explained - because the contribution of each feature is visible.

## Why start here

- **Fast.** Seconds on millions of rows, which means you can iterate on features rather than waiting.
- **Interpretable.** You can say why it decided what it decided.
- **Hard to overfit** when regularised, so the gap between training and test is usually small.
- **A real baseline.** If gradient boosting beats it by half a point, the extra complexity may not be worth operating.

## What they cannot do

They fit a straight relationship. If the effect of price is to increase sales up to a point and then reduce them, a linear model will average the two into nothing.

You can help by hand - add a squared term, bucket the variable, cross two features - and that is often enough. When it is not, the answer is the next lesson: trees find interactions and non-linearity without being told.

## Lasso, for feature selection

```python
from sklearn.linear_model import LassoCV
```

L1 regularisation drives some coefficients to exactly zero, which selects features as a side effect of fitting. Useful when you have four hundred columns and want to know which forty matter.',
   'The models to try first: fast, interpretable, hard to overfit when regularised, and often within a point or two of anything more elaborate. Also the only ones whose decisions you can explain in a sentence.',
   11, 385, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000fa',
   'Trees, Forests and Gradient Boosting',
   'markdown',
   'A decision tree splits the data on one feature at a time, choosing the split that best separates the outcome, and repeats. The result is a flowchart.

## One tree

```python
from sklearn.tree import DecisionTreeClassifier, export_text

tree = DecisionTreeClassifier(max_depth=3, random_state=42)
tree.fit(X_train, y_train)
print(export_text(tree, feature_names=list(X.columns)))
```

Readable, and that is its main virtue - you can print the rules and show them to someone. Grown without a depth limit it will memorise the training set perfectly and generalise badly, which is overfitting in its purest form.

Trees need no scaling, handle non-linearity naturally, and find interactions without being told. Those three properties carry over to everything built from them.

## Random forest

```python
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(
    n_estimators=300, max_depth=None, min_samples_leaf=2,
    n_jobs=-1, random_state=42,
)
forest.fit(X_train, y_train)
```

Hundreds of trees, each fitted on a random sample of rows and offered a random subset of features at each split, then averaged. The randomness makes the trees disagree, and averaging disagreeing models cancels much of their individual overfitting.

Strong out of the box, hard to misuse, and the sensible default when you want something better than linear without tuning.

## Gradient boosting

```python
from sklearn.ensemble import HistGradientBoostingClassifier

boosted = HistGradientBoostingClassifier(
    max_iter=300, learning_rate=0.1, max_depth=None, random_state=42,
)
boosted.fit(X_train, y_train)
```

Trees built in sequence, each fitted on the errors the previous ones are still making. More accurate than a forest on most tabular problems, and the thing that wins competitions - XGBoost and LightGBM are the same idea with better engineering.

The cost is that it will overfit if you let it. `learning_rate` and `max_iter` trade against each other: lower rate, more iterations, better results, longer training. Use early stopping on a validation set rather than guessing.

## Feature importance, carefully

```python
from sklearn.inspection import permutation_importance

result = permutation_importance(forest, X_test, y_test, n_repeats=10, random_state=42)
```

The built-in `feature_importances_` is biased towards high-cardinality features and is computed on the training data. Permutation importance - shuffle a column and see how much the score drops - is slower, measured on held-out data, and far more trustworthy.

Either way, importance is not causation. A feature can be important because it proxies for something you cannot measure.

## Choosing

Start linear. If the relationship is clearly non-linear or interactions matter, go to a forest. If you need the last two points of accuracy and can afford the tuning and the slower inference, boost. For tabular data, deep learning is usually not the answer - that is the next course, and it is for a different kind of input.',
   'A decision tree asks a sequence of yes-or-no questions. One is weak and interpretable; hundreds averaged are strong; hundreds built to correct each other are what wins on tabular data. This lesson covers all three and what each costs.',
   12, 420, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000fb',
   'Clustering and Dimensionality Reduction',
   'markdown',
   'Unsupervised learning has no labels. You are asking what structure exists, not whether a prediction is right - which means there is no score to check, and that is the danger.

## k-means

```python
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

scaled = StandardScaler().fit_transform(X)
km = KMeans(n_clusters=4, n_init=10, random_state=42)
labels = km.fit_predict(scaled)
```

It finds k groups by minimising the distance from each point to its group centre. Three things to know:

- **Scaling is mandatory.** k-means measures distance, so a column in thousands dominates a column in fractions entirely.
- **You choose k**, and the algorithm will happily produce whatever number you ask for, including on data with no groups at all.
- **It assumes round, similar-sized clusters.** Elongated or nested structures come out wrong, and DBSCAN handles those better.

## Choosing k, and being honest

```python
from sklearn.metrics import silhouette_score

for k in range(2, 8):
    labels = KMeans(n_clusters=k, n_init=10, random_state=42).fit_predict(scaled)
    print(k, round(silhouette_score(scaled, labels), 3))
```

The silhouette score measures how much better each point fits its own cluster than the next nearest. A clear peak suggests real structure; a flat curve means the data does not cluster, and the right response is to say so rather than to pick the largest number.

The real test is different: do the clusters differ on something you did not cluster on? If segment 3 also has twice the churn and half the spend, you have found something. If the only thing distinguishing them is the variables you fed in, you have drawn arbitrary lines through a cloud.

## PCA

```python
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
coordinates = pca.fit_transform(scaled)
print(pca.explained_variance_ratio_)
```

Principal component analysis finds the directions along which the data varies most and projects onto them. Two uses: plotting fifty dimensions in two, and compressing correlated columns before another model.

`explained_variance_ratio_` is the honest part - if two components capture 35% of the variance, your plot is showing a third of the picture, and clusters that appear in it may not exist in the full space.

## The warning

An algorithm always returns clusters. Naming them - "these are our power users" - is an interpretation, and it is yours rather than the model''s. Validate it against something external before anybody builds a campaign on it.',
   'Learning without labels: finding groups that were not defined in advance, and compressing many columns into a few. Both are useful and both are easy to over-interpret, because an algorithm will always return an answer.',
   11, 378, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000fd',
   'Pipelines, Tuning and Reproducibility',
   'markdown',
   'A model is the last step of a sequence: impute, scale, encode, then fit. If any of those steps learns from the test data, the evaluation is wrong - and the only reliable way to prevent that is to make the whole sequence one object.

```python
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import HistGradientBoostingClassifier

numeric = [''tenure_days'', ''logins_per_day'']
categorical = [''plan'', ''country'']

prep = ColumnTransformer([
    (''num'', Pipeline([(''impute'', SimpleImputer(strategy=''median'')),
                      (''scale'', StandardScaler())]), numeric),
    (''cat'', Pipeline([(''impute'', SimpleImputer(strategy=''most_frequent'')),
                      (''encode'', OneHotEncoder(handle_unknown=''ignore''))]), categorical),
])

model = Pipeline([(''prep'', prep), (''clf'', HistGradientBoostingClassifier(random_state=42))])
```

Now `model.fit(X_train, y_train)` fits every step on training data only, and `model.predict(X_new)` applies the same learned transformations. Inside cross-validation, it is refitted per fold, which is what makes those scores honest.

It is also one object to serialise, which means production runs exactly the transformations that were evaluated - the single most common source of a model that scored well and performs badly live.

## Tuning

```python
from sklearn.model_selection import RandomizedSearchCV

search = RandomizedSearchCV(
    model,
    {''clf__learning_rate'': [0.03, 0.05, 0.1, 0.2],
     ''clf__max_leaf_nodes'': [15, 31, 63],
     ''clf__min_samples_leaf'': [10, 20, 50]},
    n_iter=20, cv=5, scoring=''average_precision'',
    random_state=42, n_jobs=-1,
)
search.fit(X_train, y_train)
print(search.best_params_, round(search.best_score_, 3))
```

Randomised search beats exhaustive grid search for the same budget: most hyperparameters barely matter, and random sampling spends its evaluations across the ones that do. Note `scoring` - tune for the metric you chose in Level 2, not for accuracy by default.

## The number you report

`best_score_` is optimistic. It is the best of twenty attempts on the same folds, so some of it is luck. Report the test-set score, measured once, after the search is finished.

## Reproducibility

- `random_state` on every component that has one.
- Pin library versions. scikit-learn changes defaults between releases.
- Record the training data: a row count and a hash, or a snapshot.
- Save the fitted pipeline with `joblib`, alongside the version of scikit-learn that wrote it.

```python
import joblib, sklearn
joblib.dump({''model'': search.best_estimator_, ''sklearn'': sklearn.__version__}, ''model.joblib'')
```

A model file without its library version is a model you may not be able to load in a year.',
   'Every preprocessing step must be fitted on training data only, every time, including inside each cross-validation fold. A pipeline makes that automatic, and it is also the only sane way to ship the same transformations to production.',
   11, 354, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000fe',
   'Drift, Monitoring and Knowing When to Retrain',
   'markdown',
   'A model is a fitted description of a particular period. The world keeps moving, and the model does not.

## The two kinds of drift

**Data drift**: the inputs change distribution. A new marketing channel brings different users, a country launches, a competitor changes the mix. The relationship may still hold, but the model is now extrapolating.

**Concept drift**: the relationship itself changes. Behaviour that predicted churn before a pricing change no longer does. This is the serious one, and no amount of input monitoring detects it directly.

## What to monitor, in order of usefulness

1. **The prediction distribution.** The cheapest and most informative signal. If the share of positive predictions moves from 4% to 11% in a week, something changed, and you know before anybody complains.
2. **Input distributions**, per feature. Mean, missing rate, and the set of categories seen. A new category arriving - a country code you never trained on - is a concrete, fixable event.
3. **Actual outcomes, when they arrive.** The real measure, and usually delayed: churn is only known a month later. Log every prediction with its inputs so the comparison is possible when the label lands.
4. **Latency and error rates.** A model that times out is also a model that is wrong.

```python
# Log one row per prediction. Without this, nothing above is possible.
record = {
    ''ts'': now, ''model_version'': ''2026-03-01-a'', ''request_id'': rid,
    ''features'': feature_dict, ''score'': float(score), ''threshold'': 0.3,
    ''decision'': bool(score > 0.3),
}
```

## Retraining is not always the answer

If inputs have shifted but the relationship holds, retraining on fresh data helps. If the relationship has changed, retraining on data that spans both regimes gives you a model that fits neither - and the right move may be to retrain on the recent period only, or to rebuild the features.

If a product change caused it, no retraining fixes the fact that the old behaviour no longer exists. Say so.

## Retrain on a schedule, deploy on evidence

Retraining automatically is fine. Deploying automatically is not: a retrained model should be compared against the live one on held-out recent data before replacing it, because a bad data week produces a bad model silently.

Keep the previous version loadable. The fastest fix for a bad deployment is the old model, not a debugging session.

## The feedback loop

A model that chooses who gets an intervention also shapes the data it will next be trained on. Fraud flagged and blocked never produces a confirmed fraud label; customers given a retention offer do not churn. Train on that naively and the model learns that its own interventions prevent the outcome - which they may, but you cannot tell from this data. Holding out a small random control group, permanently, is the standard answer and it is worth the cost.',
   'A model is fitted to a moment. The world moves, the inputs change shape, and the model degrades without any error being raised. What to monitor, how to tell input drift from a genuine fall in performance, and when retraining is the wrong answer.',
   11, 470, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-0000000000ff',
   'Explaining a Decision, and Its Limits',
   'markdown',
   'A model that affects people - who gets credit, an interview, a higher price, extra scrutiny - carries obligations that a sales forecast does not.

## Unfairness arrives through proxies

Nobody puts ethnicity in a model. The model finds it anyway, through postcode, through device, through the name of a school. Removing the protected attribute does not remove the effect; it removes your ability to measure it.

So measure it. Compute the model''s error rates per group and look at them:

```python
for group, rows in test.groupby(''group''):
    predictions = model.predict(rows[features])
    print(group, len(rows),
          recall_score(rows[''label''], predictions).round(3),
          precision_score(rows[''label''], predictions).round(3))
```

Equal accuracy across groups is not the same as equal false positive rates, which is not the same as equal selection rates. These are different definitions of fairness and - this is a mathematical result, not an opinion - they generally cannot all hold at once when base rates differ. Pick which one matters for this decision, state it, and defend it.

## Explanation

```python
from sklearn.inspection import permutation_importance, PartialDependenceDisplay
```

Global explanation says which features matter overall. Local explanation says why this person got this decision, which is what somebody affected actually wants. SHAP values are the common tool; a per-feature contribution for a single prediction.

Three things an explanation must be:

- **True to the model.** A plausible story that is not what the model did is worse than no explanation.
- **Actionable.** "Your application was declined because of your credit utilisation" tells someone what to change. "Because of 47 factors" does not.
- **Stable.** If two near-identical cases get different explanations, the explanation is noise.

## The practical obligations

**Document the training data.** Where it came from, what period, who is in it and who is not. A model trained only on one country''s customers should say so.

**Keep a human path.** Anybody materially affected should be able to get a review by a person. This is law in several places and good practice everywhere.

**Record the decision.** The inputs, the score, the threshold, the model version. Six months later somebody will ask why, and "we retrained since then" is not an answer.

**Know the failure mode.** Every model is wrong sometimes. Know which direction hurts most and set the threshold accordingly - and be able to say what happens to the people on the wrong side of it.

## The question worth asking first

Not "can we predict this" but "should a prediction decide this". Sometimes the honest answer is that the model informs a person who decides, and that is a better system than either alone.',
   'The moment a model affects a person, accuracy stops being the only requirement. Why a proxy for a protected attribute is the usual mechanism, why group metrics cannot all be equal at once, and what an explanation has to contain to be worth anything.',
   11, 428, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-000000000012');
CALL search_reindex_all_quiet();
