-- =========================================================================
-- Seed 36 : quizzes for Machine Learning
--
-- One per level, the last one an exam over the whole course. Generated by
-- the shared builder, which refuses to emit a single_choice without exactly
-- one correct option, or a multiple_choice with fewer than two.
-- =========================================================================

INSERT INTO assessment_quizzes
  (id, course_id, lesson_id, title, description, pass_percent, time_limit_seconds,
   max_attempts, shuffle_questions, shuffle_options, show_answers, status)
VALUES
  ('f0000001-0000-4000-8000-00000000003c',
   'c0000001-0000-4000-8000-000000000012', 'e0000001-0000-4000-8000-0000000000f4',
   'Level 1 Check: Models, Splits and First Scores',
   'What a model is, why the split comes first, and why accuracy means nothing without a baseline.',
   60, 600, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-00000000003d',
   'c0000001-0000-4000-8000-000000000012', 'e0000001-0000-4000-8000-0000000000f8',
   'Level 2 Check: Overfitting, Features and Metrics',
   'Reading a train-test gap, what cross-validation buys, spotting leakage, and choosing a metric by cost.',
   60, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-00000000003e',
   'c0000001-0000-4000-8000-000000000012', 'e0000001-0000-4000-8000-0000000000fc',
   'Level 3 Check: Models and What They Assume',
   'When linear is enough, what forests and boosting buy, importance done properly, and honest clustering.',
   70, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-00000000003f',
   'c0000001-0000-4000-8000-000000000012', 'e0000001-0000-4000-8000-000000000100',
   'Expert Exam: Machine Learning',
   'Pipelines, honest tuning, drift, feedback loops, and models that make decisions about people.',
   70, 1500, 3, 1, 1, 1, 'published')
ON DUPLICATE KEY UPDATE
  title = VALUES(title), description = VALUES(description),
  pass_percent = VALUES(pass_percent), status = VALUES(status);

INSERT INTO assessment_questions
  (id, quiz_id, kind, prompt, explanation, points, `position`, correct_text)
VALUES
  -- Level 1 Check: Models, Splits and First Scores
  ('a1000001-0000-4000-8000-000000000361', 'f0000001-0000-4000-8000-00000000003c', 'single_choice',
   'A model predicts churn accurately from support ticket counts. What has it established?',
   'That the two move together. A model fits a function to examples; it has no mechanism for distinguishing a cause from a correlate, and the tickets may be a symptom of the same dissatisfaction that causes the churn.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-000000000362', 'f0000001-0000-4000-8000-00000000003c', 'single_choice',
   'You are predicting next month revenue from this month data. Why is a random train/test split wrong?',
   'It lets the model train on future rows and predict past ones, which it can never do in production. The test set must come after the training set in time, so the evaluation matches the real task.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-000000000363', 'f0000001-0000-4000-8000-00000000003c', 'single_choice',
   'Your classifier is 95% accurate and 95% of rows are the negative class. What do you know?',
   'Nothing yet. Predicting the majority class for everything scores the same, which is why a DummyClassifier baseline is the first thing to compute - it converts an impressive number into a comparison.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-000000000364', 'f0000001-0000-4000-8000-00000000003c', 'single_choice',
   'Why scale inside a pipeline rather than scaling the whole dataset first?',
   'A scaler fitted on everything has learned the mean and standard deviation of the test set, so information from it has entered the training process. Inside a pipeline the scaler is fitted on the training fold only, which is correct by construction.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-000000000365', 'f0000001-0000-4000-8000-00000000003c', 'multiple_choice',
   'Which situations mean machine learning is the wrong tool? Select all that apply.',
   'A written rule is better when one exists: auditable, instant, no drift. No labels means no supervised problem. And no algorithm recovers information that was never recorded - that is an instrumentation problem wearing a modelling costume.',
   2, 5, NULL),

  -- Level 2 Check: Overfitting, Features and Metrics
  ('a1000001-0000-4000-8000-000000000366', 'f0000001-0000-4000-8000-00000000003d', 'single_choice',
   'Training score 0.99, test score 0.71. What is happening?',
   'Overfitting: the model has memorised the training rows, including their noise. The responses are to simplify it, regularise harder, or get more data - not to add capacity.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-000000000367', 'f0000001-0000-4000-8000-00000000003d', 'single_choice',
   'Cross-validation returns 0.80 with a standard deviation of 0.11. What does that tell you?',
   'The model is unstable across folds: on a different sample it might score 0.69. The spread is as informative as the mean, and a wide one usually means too little data or too much model.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-000000000368', 'f0000001-0000-4000-8000-00000000003d', 'single_choice',
   'A churn model scores 0.985 AUC on the first try. What should you do?',
   'Look for leakage. On a real business problem that number almost always means a feature contains the answer - a cancellation reason, a flag only set after the fact, or an aggregate computed across the test period.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-000000000369', 'f0000001-0000-4000-8000-00000000003d', 'single_choice',
   'Flagged accounts get an expensive manual review. Which metric should you favour?',
   'Precision. Every false positive costs a review of somebody who was fine. Recall would matter more if the cost of a missed case dominated - which metric to favour follows from what each error actually costs.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-00000000036a', 'f0000001-0000-4000-8000-00000000003d', 'single_choice',
   'Why does lowering the decision threshold from 0.5 to 0.3 not require retraining?',
   'The model outputs a probability; the threshold is just where you cut it. Moving it trades precision for recall with no change to the fitted model, which makes it the cheapest dial available after training.',
   2, 5, NULL),

  -- Level 3 Check: Models and What They Assume
  ('a1000001-0000-4000-8000-00000000036b', 'f0000001-0000-4000-8000-00000000003e', 'multiple_choice',
   'Why start with a regularised linear model? Select all that apply.',
   'Fast to fit so you can iterate on features, interpretable so a decision can be explained, and hard to overfit when regularised. It also sets the bar: if boosting beats it by half a point, the extra operational cost may not be worth paying.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-00000000036c', 'f0000001-0000-4000-8000-00000000003e', 'single_choice',
   'What distinguishes gradient boosting from a random forest?',
   'A forest fits many trees independently on random samples and averages them. Boosting fits trees in sequence, each one on the errors the previous ones still make - more accurate on tabular data, and more willing to overfit if you do not stop it.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-00000000036d', 'f0000001-0000-4000-8000-00000000003e', 'single_choice',
   'Why prefer permutation importance over the built-in feature_importances_?',
   'The built-in measure is computed on training data and is biased towards high-cardinality features. Permutation importance shuffles a column and measures the drop on held-out data, which is slower and much harder to fool.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-00000000036e', 'f0000001-0000-4000-8000-00000000003e', 'single_choice',
   'k-means has returned four clusters. What would best suggest they are real?',
   'That they differ on something you did not cluster on - churn, spend, support volume. The algorithm will always return k groups; external validation is the only way to tell structure from arbitrary lines through a cloud.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-00000000036f', 'f0000001-0000-4000-8000-00000000003e', 'single_choice',
   'Why must features be scaled before k-means?',
   'It assigns points to the nearest centre by distance, so a column measured in thousands contributes far more than one measured in fractions. The clusters would then be determined by the choice of units.',
   2, 5, NULL),

  -- Expert Exam: Machine Learning
  ('a1000001-0000-4000-8000-000000000370', 'f0000001-0000-4000-8000-00000000003f', 'single_choice',
   'Why is RandomizedSearchCV usually a better use of a fixed budget than GridSearchCV?',
   'Most hyperparameters barely matter. A grid spends the same number of evaluations on every axis; random sampling covers more distinct values of the ones that do matter for the same number of fits.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-000000000371', 'f0000001-0000-4000-8000-00000000003f', 'single_choice',
   'Why is best_score_ from a hyperparameter search an optimistic estimate?',
   'It is the best of many attempts measured on the same folds, so part of it is luck in those folds. The number to report is the test-set score, measured once after the search is finished.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-000000000372', 'f0000001-0000-4000-8000-00000000003f', 'single_choice',
   'The share of positive predictions jumps from 4% to 11% in a week, with no new model deployed. What is the most likely explanation?',
   'The inputs have changed - a new channel, a new country, a broken upstream field. The prediction distribution is the cheapest drift signal because it moves immediately, long before outcome labels arrive.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-000000000373', 'f0000001-0000-4000-8000-00000000003f', 'single_choice',
   'Your model blocks suspected fraud, and blocked cases never produce a confirmed-fraud label. Why is that a problem for the next model?',
   'The intervention removed the outcome it was predicting, so the training data no longer contains the cases the model caught. Trained naively on that, the next model learns that those patterns are safe. A small permanent random control group is the usual defence.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-000000000374', 'f0000001-0000-4000-8000-00000000003f', 'single_choice',
   'Removing a protected attribute from the features has what effect on fairness?',
   'Little, except that you can no longer measure it. The model reconstructs the attribute from proxies - postcode, device, name - so the effect survives while the ability to detect it does not.',
   2, 5, NULL),

  ('a1000001-0000-4000-8000-000000000375', 'f0000001-0000-4000-8000-00000000003f', 'single_choice',
   'Why can a model not satisfy every definition of fairness at once?',
   'When base rates differ between groups, equal false positive rates, equal recall and equal selection rates are mathematically incompatible. You have to choose which matters for this decision and defend the choice.',
   2, 6, NULL)
ON DUPLICATE KEY UPDATE
  prompt = VALUES(prompt), explanation = VALUES(explanation), points = VALUES(points);

-- Options are inserted rather than replaced, for the reason seed 14 gives:
-- deleting and re-inserting them would orphan every answer already recorded
-- against them, and a graded attempt whose answers point at nothing is a
-- review that resolves nothing.
INSERT INTO assessment_question_options (question_id, body, is_correct, `position`)
SELECT v.question_id, v.body, v.is_correct, v.pos
  FROM (
    SELECT 'a1000001-0000-4000-8000-000000000361' AS question_id, 'That tickets and churn are associated in this data' AS body, 1 AS is_correct, 1 AS pos
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000361', 'That tickets cause churn', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000361', 'That reducing tickets would reduce churn', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000361', 'That ticket volume is the most important business metric', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000362', 'It trains on the future to predict the past', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000362', 'Random splits cannot preserve class balance', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000362', 'Time series need more test data than 20%', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000362', 'It is not wrong, as long as random_state is set', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000363', 'Nothing until you compare it against a majority-class baseline', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000363', 'The model is performing well', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000363', 'The model has overfitted', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000363', 'The classes need rebalancing before training', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000364', 'Scaling first lets the test set influence the training statistics', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000364', 'It is faster, because the pipeline caches the transformation', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000364', 'Some models require scaling and others do not', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000364', 'The pipeline rescales automatically at prediction time anyway', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000365', 'A clear written rule already captures the decision', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000365', 'There are no labelled examples and no way to get them', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000365', 'The data contains nothing related to the outcome', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000365', 'The dataset has more than a million rows', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000366', 'Overfitting - the model memorised rather than generalised', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000366', 'Underfitting - the model is too simple', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000366', 'The test set is too small to be reliable', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000366', 'The split was not stratified', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000367', 'The result is unstable and could be much worse on new data', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000367', 'The model is well calibrated', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000367', 'Five folds were too many for this dataset', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000367', 'The mean is reliable because the folds averaged out', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000368', 'Look for a feature that would not exist at prediction time', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000368', 'Ship it, since the evaluation was on held-out data', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000368', 'Add more features to push it higher', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000368', 'Reduce regularisation to confirm the result', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000369', 'Precision', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000369', 'Recall', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000369', 'Accuracy', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000369', 'ROC AUC', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036a', 'The threshold is applied to the output, not learned by the model', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036a', 'scikit-learn retrains lazily when the threshold changes', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036a', '0.5 is only a default for balanced classes', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036a', 'It does require retraining to stay calibrated', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036b', 'It trains fast, so you iterate on features instead of waiting', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036b', 'Its coefficients explain the decision', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036b', 'It is a real baseline for anything more complex', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036b', 'It handles non-linear relationships automatically', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036c', 'Boosting fits trees in sequence on the previous errors; a forest averages independent trees', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036c', 'Boosting uses deeper trees and a forest uses shallower ones', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036c', 'A forest requires scaling and boosting does not', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036c', 'Boosting cannot overfit because of the learning rate', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036d', 'It is measured on held-out data and is not biased by cardinality', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036d', 'It is faster on large models', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036d', 'It works for linear models, where the built-in does not', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036d', 'It reports causal effect rather than association', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036e', 'They differ on a variable that was not used to build them', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036e', 'The silhouette score is positive', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036e', 'They are roughly equal in size', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036e', 'They look separated in a two-component PCA plot', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036f', 'It clusters by distance, so unscaled columns dominate by their units', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036f', 'Because k-means assumes normally distributed features', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036f', 'To make the silhouette score interpretable', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000036f', 'It is not required; k-means scales internally', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000370', 'It spends its evaluations across the parameters that actually matter', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000370', 'It is guaranteed to find the global optimum', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000370', 'It does not require cross-validation', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000370', 'It avoids overfitting the validation folds entirely', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000371', 'It is the maximum over many attempts on the same folds', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000371', 'It is computed on training data', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000371', 'It uses a different metric from the final evaluation', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000371', 'It excludes the preprocessing steps', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000372', 'The input data has shifted', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000372', 'The model has overfitted', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000372', 'The threshold has drifted on its own', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000372', 'The metric was computed incorrectly', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000373', 'The intervention removes the outcome, so future training data is biased by the current model', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000373', 'Blocked cases are logged with the wrong timestamp', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000373', 'Fraud rates are too low for supervised learning', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000373', 'It is not a problem, because blocked cases can be treated as positives', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000374', 'The model can still learn it through proxies, and you lose the ability to measure it', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000374', 'It removes the effect entirely, which is why it is standard practice', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000374', 'It makes the model fairer but less accurate', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000374', 'It has no effect either way', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000375', 'When base rates differ between groups, the definitions are mathematically incompatible', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000375', 'Because fairness metrics are not computable on held-out data', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000375', 'Because any fairness constraint destroys accuracy', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000375', 'It can, with enough regularisation', 0, 4
  ) v
ON DUPLICATE KEY UPDATE
  body = VALUES(body), is_correct = VALUES(is_correct);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-000000000012');
CALL search_reindex_all_quiet();
