-- =========================================================================
-- Seed 37 : Deep Learning
--
-- The fourth course in the Data Science track. Neural networks from a single
-- neuron up to the transformer, with an honest account of when a deep model
-- is the right answer and when gradient boosting already was.
--
-- Part of the Data Science track. Generated by the shared builder, so all
-- five courses in the track have the same shape and the same guarantees.
-- =========================================================================

INSERT INTO catalog_tags (id, slug, name) VALUES
  ('bbbbbbb1-0000-4000-8000-000000000019', 'data-science', 'Data Science'),
  ('bbbbbbb1-0000-4000-8000-000000000021', 'deep-learning', 'Deep Learning'),
  ('bbbbbbb1-0000-4000-8000-000000000022', 'neural-networks', 'Neural Networks'),
  ('bbbbbbb1-0000-4000-8000-00000000001f', 'machine-learning', 'Machine Learning')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO catalog_courses
  (id, slug, title, subtitle, overview, description, category_id, instructor_id,
   level, status, thumbnail_url, price_cents, learning_outcomes, requirements,
   published_at)
VALUES
  ('c0000001-0000-4000-8000-000000000013',
   'deep-learning',
   'Deep Learning',
   'Four levels, twelve lessons, from one neuron to a transformer',
   'Deep learning is machine learning with models that learn their own features. A traditional model needs you to tell it that recency matters and that price divided by tenure is informative; a neural network, given enough examples, works out its own intermediate representations from raw input.

That is why it took over the problems where features are impossible to write down by hand. Nobody can specify the rule that distinguishes a cat from a dog in pixel values, or what makes a sentence sarcastic. Images, audio and language are where deep learning is not just better but the only thing that works.

It is also why it is the wrong tool for a spreadsheet. On tabular data, gradient boosting usually matches or beats a neural network with a fraction of the data, the tuning and the hardware - and this course says so early, because the most expensive mistake in this field is using it where it was never needed.',
   'A complete path through neural networks in four levels. Level 1 builds the idea from one neuron: what a layer is, what an activation function does, and how gradient descent and backpropagation actually train anything. Level 2 is making training work - loss functions, optimisers, batches and epochs, and the regularisation that stops a network memorising. Level 3 covers the architectures: convolutional networks for images, recurrent models and their limits, and the attention mechanism that replaced them. Level 4 is practice: transfer learning, which is how almost everybody really trains a model, the engineering of getting one into production, and the costs - compute, data, carbon and failure modes - stated plainly.

It assumes the machine learning course in this track: train/test splits, overfitting, metrics. It does not assume calculus. Gradient descent is explained as an idea, with the mathematics described rather than derived.

Every level is three lessons and a Level Check quiz, with an Expert Exam at the end. The code is PyTorch-shaped and kept small enough to read; this is a course about understanding what you are running, not a library tour.

By the end you will be able to say what architecture suits a problem, train a model without the usual silent failures, recognise why a network is not learning, and judge whether a deep model is worth its cost at all.',
   'aaaaaaa1-0000-4000-8000-000000000004',
   '55555555-5555-4555-8555-555555555555',
   'advanced', 'published',
   'https://images.example-cdn.test/courses/deep-learning.jpg', 0,
   JSON_ARRAY('Explain what a neuron, a layer and an activation function actually do',
              'Describe how gradient descent and backpropagation train a network',
              'Choose a loss and an optimiser that match the task',
              'Diagnose a network that will not learn, or that has memorised',
              'Pick between convolution, recurrence and attention for a given input',
              'Fine-tune a pretrained model instead of training from scratch'),
   JSON_ARRAY('The Machine Learning course in this track, or equivalent experience', 'Python and NumPy', 'No calculus required'),
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), subtitle = VALUES(subtitle), overview = VALUES(overview),
  description = VALUES(description), category_id = VALUES(category_id),
  learning_outcomes = VALUES(learning_outcomes), requirements = VALUES(requirements);

INSERT INTO catalog_course_tags (course_id, tag_id) VALUES
  ('c0000001-0000-4000-8000-000000000013', 'bbbbbbb1-0000-4000-8000-000000000019'),
  ('c0000001-0000-4000-8000-000000000013', 'bbbbbbb1-0000-4000-8000-000000000021'),
  ('c0000001-0000-4000-8000-000000000013', 'bbbbbbb1-0000-4000-8000-000000000022'),
  ('c0000001-0000-4000-8000-000000000013', 'bbbbbbb1-0000-4000-8000-00000000001f')
ON DUPLICATE KEY UPDATE course_id = VALUES(course_id);

-- -------------------------------------------------------------------------
-- The four levels
-- -------------------------------------------------------------------------
INSERT INTO catalog_modules (id, course_id, title, summary, `position`) VALUES
  ('d0000001-0000-4000-8000-000000000044', 'c0000001-0000-4000-8000-000000000013',
   'Level 1 - Basic',
   'The machinery, built from the smallest piece. One neuron is a weighted sum and a function; a layer is many of them; a network is layers stacked so that each learns from the output of the last. Then the two ideas that make training possible at all: gradient descent, which is how a model improves, and backpropagation, which is how it knows which weight to blame.', 1),
  ('d0000001-0000-4000-8000-000000000045', 'c0000001-0000-4000-8000-000000000013',
   'Level 2 - Intermediate',
   'Making training actually work, which is mostly a matter of five decisions and the ability to read a loss curve. Loss functions and optimisers chosen for the task rather than by habit, batches and epochs and what each controls, and the regularisation that decides whether a network generalises or memorises its training set exactly.', 2),
  ('d0000001-0000-4000-8000-000000000046', 'c0000001-0000-4000-8000-000000000013',
   'Level 3 - Advanced',
   'Architectures, and the structure each one assumes about its input. Convolution assumes that a pattern means the same thing wherever it appears, which is what makes it right for images; recurrence assumes order and processes it one step at a time, which is what eventually limited it; attention lets every position look at every other, which is why transformers replaced both.', 3),
  ('d0000001-0000-4000-8000-000000000047', 'c0000001-0000-4000-8000-000000000013',
   'Level 4 - Expert',
   'How deep learning is actually practised, which is mostly not training from scratch. Transfer learning and fine-tuning, the engineering of serving a model at a sensible cost and latency, and an honest accounting of what these models cost in compute, data and failure - including the failures that only appear once real users are involved.', 4)
ON DUPLICATE KEY UPDATE title = VALUES(title), summary = VALUES(summary);

INSERT INTO catalog_lessons
  (id, module_id, course_id, slug, title, summary, kind, status, `position`,
   duration_seconds, is_free_preview)
VALUES
  ('e0000001-0000-4000-8000-000000000101', 'd0000001-0000-4000-8000-000000000044', 'c0000001-0000-4000-8000-000000000013',
   'dl-neuron', 'From One Neuron to a Network',
   'A neuron is a weighted sum passed through a function. That one sentence, repeated and stacked, is the whole architecture - and the non-linear function in the middle is what makes depth worth anything at all.',
   'article', 'published', 1, 600, 1),
  ('e0000001-0000-4000-8000-000000000102', 'd0000001-0000-4000-8000-000000000044', 'c0000001-0000-4000-8000-000000000013',
   'dl-training', 'Gradient Descent and Backpropagation',
   'Training is a loop: predict, measure the error, work out how much each weight contributed, and nudge every one of them downhill. This lesson explains both halves without calculus, and the learning rate that decides whether any of it works.',
   'article', 'published', 2, 660, 1),
  ('e0000001-0000-4000-8000-000000000103', 'd0000001-0000-4000-8000-000000000044', 'c0000001-0000-4000-8000-000000000013',
   'dl-when', 'When a Neural Network Is the Wrong Answer',
   'Deep learning dominates images, audio and language, and loses to gradient boosting on the spreadsheet most businesses actually have. Knowing which situation you are in before starting is worth more than any architecture choice.',
   'article', 'published', 3, 600, 0),
  ('e0000001-0000-4000-8000-000000000104', 'd0000001-0000-4000-8000-000000000044', 'c0000001-0000-4000-8000-000000000013',
   'dl-level-1-check', 'Level 1 Check: Neurons, Gradients and Fit',
   'Five questions on what the activation function is actually for, how the training loop fits together, what the learning rate controls and what happens at both extremes, and when a neural network is the wrong tool for the data you have.',
   'quiz', 'published', 4, 600, 0),
  ('e0000001-0000-4000-8000-000000000105', 'd0000001-0000-4000-8000-000000000045', 'c0000001-0000-4000-8000-000000000013',
   'dl-loss', 'Loss Functions and Optimisers',
   'The loss defines what the network is trying to do, so choosing it wrongly means optimising the wrong thing perfectly. The optimiser decides how it gets there. There are sensible defaults for both, and reasons to depart from them.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-000000000106', 'd0000001-0000-4000-8000-000000000045', 'c0000001-0000-4000-8000-000000000013',
   'dl-batches', 'Batches, Epochs and Normalisation',
   'Three knobs that decide whether training is fast, stable and finishes in the right place - plus the input normalisation that is the most common reason a network does not learn at all.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-000000000107', 'd0000001-0000-4000-8000-000000000045', 'c0000001-0000-4000-8000-000000000013',
   'dl-regularisation', 'Stopping a Network Memorising',
   'A model with a million parameters can memorise ten thousand examples perfectly. Dropout, weight decay, augmentation and early stopping are the four tools that prevent it, and they work in different ways and combine.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-000000000108', 'd0000001-0000-4000-8000-000000000045', 'c0000001-0000-4000-8000-000000000013',
   'dl-level-2-check', 'Level 2 Check: Training That Works',
   'Five questions on reading a loss curve and knowing when to stop, choosing a loss and an optimiser that match the task, what batch size trades against what, and why forgetting model.eval() quietly changes every prediction you make.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-000000000109', 'd0000001-0000-4000-8000-000000000046', 'c0000001-0000-4000-8000-000000000013',
   'dl-cnn', 'Convolutional Networks, and Why They Suit Images',
   'A convolution slides a small learned filter across an image, which builds in two assumptions: that a pattern means the same thing anywhere, and that nearby pixels are related. Those assumptions are why a convolutional network needs far less data than a fully connected one.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-00000000010a', 'd0000001-0000-4000-8000-000000000046', 'c0000001-0000-4000-8000-000000000013',
   'dl-sequences', 'Sequences: Recurrence and Its Limits',
   'Text, speech and time series have order. Recurrent networks process them one step at a time, carrying a hidden state - an elegant idea with two fatal problems that explain exactly why the field moved to attention.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-00000000010b', 'd0000001-0000-4000-8000-000000000046', 'c0000001-0000-4000-8000-000000000013',
   'dl-attention', 'Attention and the Transformer',
   'Attention lets every position look directly at every other and decide what matters, with no sequential bottleneck. It is the idea behind every large language model, and it is simpler than its reputation.',
   'article', 'published', 3, 720, 0),
  ('e0000001-0000-4000-8000-00000000010c', 'd0000001-0000-4000-8000-000000000046', 'c0000001-0000-4000-8000-000000000013',
   'dl-level-3-check', 'Level 3 Check: Architectures',
   'What convolution assumes about its input, the two problems that ended recurrence, what attention computes, and why positional encoding is needed at all.',
   'quiz', 'published', 4, 720, 0),
  ('e0000001-0000-4000-8000-00000000010d', 'd0000001-0000-4000-8000-000000000047', 'c0000001-0000-4000-8000-000000000013',
   'dl-transfer', 'Transfer Learning: How Models Are Really Trained',
   'Almost nobody trains from scratch. You take a model that has already learned general representations from an enormous dataset and adapt it to your task with a fraction of the data - and which layers you unfreeze is the main decision.',
   'article', 'published', 1, 660, 0),
  ('e0000001-0000-4000-8000-00000000010e', 'd0000001-0000-4000-8000-000000000047', 'c0000001-0000-4000-8000-000000000013',
   'dl-production', 'Serving a Model Without Setting Money on Fire',
   'Training is a project; serving is a service. Latency, batching, quantisation, versioning and the monitoring that tells you the model has quietly started receiving inputs it has never seen.',
   'article', 'published', 2, 660, 0),
  ('e0000001-0000-4000-8000-00000000010f', 'd0000001-0000-4000-8000-000000000047', 'c0000001-0000-4000-8000-000000000013',
   'dl-costs', 'What Deep Learning Actually Costs',
   'Compute, data, carbon and the failures that only appear with real users. Stating these before a project starts is the difference between a considered decision and a sunk cost nobody wants to admit to.',
   'article', 'published', 3, 660, 0),
  ('e0000001-0000-4000-8000-000000000110', 'd0000001-0000-4000-8000-000000000047', 'c0000001-0000-4000-8000-000000000013',
   'dl-expert-exam', 'Expert Exam: Deep Learning',
   'Transfer learning, catastrophic forgetting, serving costs, confident nonsense outside the training distribution, and the five questions to answer before a project starts.',
   'quiz', 'published', 4, 1500, 0)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), summary = VALUES(summary), kind = VALUES(kind),
  duration_seconds = VALUES(duration_seconds), is_free_preview = VALUES(is_free_preview);

-- -------------------------------------------------------------------------
-- The diagram the course opens with
-- -------------------------------------------------------------------------
INSERT INTO content_lesson_diagrams (lesson_id, title, alt, caption, spec, `position`) VALUES
  ('e0000001-0000-4000-8000-000000000101',
   'How a network learns',
   'Input passes forward through layers to produce a prediction, a loss function measures how wrong that prediction is against the known answer, backpropagation computes how much each weight contributed to the error, and the optimiser adjusts every weight a small step in the direction that reduces it. The cycle repeats.',
   'One loop, repeated millions of times. Everything else in deep learning is a variation on it.',
   '{"nodes": [{"label": "Input", "note": "Pixels, tokens, or a row of numbers"}, {"label": "Forward pass", "note": "Through the layers, producing a prediction"}, {"label": "Loss", "note": "How wrong that prediction was"}, {"label": "Update", "note": "Every weight nudged to make the loss smaller"}], "edges": [{"label": "passed through"}, {"label": "scored by"}, {"label": "backpropagated into"}]}', 1)
ON DUPLICATE KEY UPDATE
  title = VALUES(title), alt = VALUES(alt), caption = VALUES(caption), spec = VALUES(spec);

-- -------------------------------------------------------------------------
-- The lessons themselves
-- -------------------------------------------------------------------------
INSERT INTO content_articles
  (lesson_id, title, format, body, excerpt, reading_time_minutes, word_count,
   author_id, status, published_at)
VALUES
  ('e0000001-0000-4000-8000-000000000101',
   'From One Neuron to a Network',
   'markdown',
   'A neuron computes a weighted sum of its inputs, adds a bias, and passes the result through a function.

```
output = activation(w1*x1 + w2*x2 + ... + wn*xn + b)
```

That is it. A layer is many neurons computing in parallel from the same inputs. A network is layers stacked, each taking the previous layer''s outputs as its inputs.

## Why the activation function matters

Without it, a neuron is a weighted sum, and a stack of weighted sums is still a weighted sum - a hundred-layer network would be exactly equivalent to one linear layer. The non-linearity is what makes depth mean anything.

- **ReLU** - `max(0, x)` - is the default. Cheap, and it does not saturate for large positive values, which keeps gradients flowing.
- **Sigmoid** squashes to 0-1. Used on an output for binary probability; poor in hidden layers because its gradient vanishes at both ends.
- **Softmax** on the output layer turns scores into probabilities that sum to one, for multi-class problems.

A dead ReLU - one whose input is always negative, so it outputs zero and receives no gradient - is a real failure mode, and it is the reason variants like LeakyReLU exist.

## What depth buys

Each layer builds on the representation beneath it. In an image network the first layer learns edges, the next corners and textures, the next shapes, the next objects. Nobody specified that hierarchy; it emerges because it is an efficient way to reduce the loss.

That is the central claim of deep learning: the features are learned rather than designed. It is also why it needs so much data - it is learning the representation as well as the task.

## A small network, concretely

```python
import torch
from torch import nn

model = nn.Sequential(
    nn.Linear(10, 64),   # 10 inputs -> 64 neurons
    nn.ReLU(),
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 1),    # one output
)

print(sum(p.numel() for p in model.parameters()), ''parameters'')
```

Roughly 2,800 numbers, all learned. A modern language model has hundreds of billions, and the idea is identical.

## Width, depth and the cost

More neurons per layer means more capacity to fit. More layers means more abstraction. Both increase the data needed and the ways training can fail, which is why "make it bigger" is a late answer rather than a first one.',
   'A neuron is a weighted sum passed through a function. That one sentence, repeated and stacked, is the whole architecture - and the non-linear function in the middle is what makes depth worth anything at all.',
   10, 389, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-000000000102',
   'Gradient Descent and Backpropagation',
   'markdown',
   'Training a network means finding weights that make the loss small. There are millions of weights, so you cannot search; you have to descend.

## Gradient descent, as an idea

Imagine the loss as a landscape, with one dimension per weight and height being how wrong the model is. You are standing somewhere in it, in fog, and want to get lower.

The gradient tells you which way is downhill, and how steep. Take a small step that way. Repeat.

```
weight = weight - learning_rate * gradient
```

That single line is the whole optimiser. Everything else is refinement.

## The learning rate

The most important number in deep learning and the first thing to tune.

- **Too large**: steps overshoot the valley; the loss bounces or goes to NaN.
- **Too small**: it moves, barely; training takes a week to reach what it could have reached in an hour.
- **About right**: the loss falls quickly and then flattens.

A rate that produces NaN within a few batches is almost always too high. Divide it by ten and try again - that single habit resolves most "my model will not train" problems.

## Backpropagation

The gradient has to be computed for every weight, including ones deep inside the network whose effect on the loss is indirect.

Backpropagation is the chain rule applied efficiently: start at the loss, work backwards layer by layer, and at each step multiply by how much that layer''s output affected the next. One backward pass computes the gradient for every weight at roughly the cost of one forward pass - which is why training is feasible at all.

In practice a framework does it:

```python
for batch_x, batch_y in loader:
    optimizer.zero_grad()          # gradients accumulate; clear them first
    predictions = model(batch_x)   # forward
    loss = loss_fn(predictions, batch_y)
    loss.backward()                # backward: fills in every gradient
    optimizer.step()               # apply them
```

Five lines, and every training loop you will ever write is this. Forgetting `zero_grad()` is the classic bug: gradients from previous batches add up, the steps become enormous, and the loss diverges.

## Vanishing and exploding gradients

Multiply many small numbers and you get something near zero: early layers stop learning. Multiply many large ones and it explodes to NaN. This is why very deep networks were impractical for years, and the fixes - ReLU rather than sigmoid, careful initialisation, normalisation layers, residual connections - are each a direct response to it.

## What it does not guarantee

Gradient descent finds a local minimum, not the best possible one. In practice, in very high dimensions, this matters far less than you would expect - most local minima turn out to be about as good as each other. It is one of the things that works better than the theory suggested it should.',
   'Training is a loop: predict, measure the error, work out how much each weight contributed, and nudge every one of them downhill. This lesson explains both halves without calculus, and the learning rate that decides whether any of it works.',
   11, 466, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-000000000103',
   'When a Neural Network Is the Wrong Answer',
   'markdown',
   'Deep learning is extraordinary at some problems and a poor trade on others. The dividing line is clear enough to decide before you start.

## Where it wins, and why

Images, audio, text and video. These share a property: the raw input has structure that nobody can write down as features.

You cannot specify in pixel values what makes a face. You cannot list the rules that make a sentence sarcastic. Deep models learn those representations from examples, which is the one thing nothing else does.

They also win where there is a very great deal of data. Capacity is only useful if there is enough signal to fill it.

## Where it loses

**Tabular data.** This is the common case in business - a table of customers, transactions, sensor readings - and gradient boosting usually matches or beats a neural network on it, trains in seconds rather than hours, needs no GPU and no tuning marathon.

The reason is that tabular columns are already features. Somebody already decided that `days_since_last_order` is a column. The representation learning that makes deep models powerful has little left to do.

**Small data.** A few thousand rows cannot fit a model with a million parameters. Transfer learning changes this for images and text; for a bespoke tabular problem it generally does not.

**When you must explain the decision.** A boosted tree is hard enough to explain. A deep network, substantially harder, and "the model said so" is not acceptable for credit or hiring.

## The honest comparison

| | Gradient boosting | Neural network |
| --- | --- | --- |
| Tabular data | Usually wins | Usually loses |
| Images, audio, text | Not applicable | Only option |
| Data needed | Thousands of rows | Tens of thousands upward |
| Training | Seconds to minutes, on a laptop | Hours, usually on a GPU |
| Tuning | A handful of parameters | Many, interacting |
| Explaining a decision | Hard | Harder |

## The practical sequence

1. Baseline - majority class, or a simple rule.
2. Regularised linear model.
3. Gradient boosting.
4. Only then, if the input is images, audio or text, or if 3 is clearly leaving something on the table, a neural network.

Most projects should stop at 3 and most of this field''s disappointment comes from starting at 4.

## The exception worth naming

If your tabular problem includes a free-text column - support tickets, product descriptions, reviews - a sentence embedding from a pretrained language model as extra features into a boosted tree is frequently the best of both. That is a deep model doing the part it is good at, feeding the model that is good at the rest.',
   'Deep learning dominates images, audio and language, and loses to gradient boosting on the spreadsheet most businesses actually have. Knowing which situation you are in before starting is worth more than any architecture choice.',
   10, 461, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-000000000105',
   'Loss Functions and Optimisers',
   'markdown',
   'The loss function is the definition of the task. The network will minimise exactly what you write down, including the parts you did not mean.

## Choosing a loss

- **Regression**: mean squared error by default. It punishes large errors quadratically, which is right when one big miss is worse than several small ones - and wrong when your data has outliers, because the model will distort itself to accommodate them. Huber loss is the compromise.
- **Binary classification**: binary cross-entropy. It measures the distance between the predicted probability and the truth, and penalises confident mistakes heavily.
- **Multi-class**: cross-entropy over a softmax output.
- **Imbalanced classes**: weight the loss so the rare class contributes more, or the network will reach a low loss by predicting the majority for everything.

```python
import torch
from torch import nn

loss_fn = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([9.0]))
```

`BCEWithLogitsLoss` rather than a sigmoid followed by `BCELoss`: combining them is numerically stable, and separating them is a known source of NaN.

## Optimisers

- **SGD with momentum** - the classic. Momentum carries speed through flat regions and damps oscillation. Often the best final result for vision, with tuning.
- **Adam** - adapts the step size per parameter. It is the right default: it works reasonably without tuning, which is why nearly everything starts here.
- **AdamW** - Adam with weight decay applied correctly. Prefer it to Adam for anything substantial.

```python
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=0.01)
```

`3e-4` is the folk default for Adam and a reasonable place to start. For SGD, `1e-2` is the equivalent. These differ by two orders of magnitude, so carrying a learning rate across a change of optimiser is a reliable way to break training.

## Schedules

The learning rate should fall as training proceeds: large steps to get near, small steps to settle.

```python
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
```

Cosine annealing is a good default. Warmup - starting small for a few hundred steps and rising - matters for transformers, where early large steps destabilise training.

## Reading the loss curve

- **Falls then flattens, validation tracking it**: working.
- **Falls to NaN**: learning rate too high, or a numerically unstable loss.
- **Flat from the start**: learning rate too low, data not normalised, labels misaligned, or the output layer wrong for the loss.
- **Training falls while validation rises**: overfitting; stop at the turn.
- **Jagged**: batch too small, or learning rate slightly too high.

Plot it every time. Training without looking at the loss curve is guessing.',
   'The loss defines what the network is trying to do, so choosing it wrongly means optimising the wrong thing perfectly. The optimiser decides how it gets there. There are sensible defaults for both, and reasons to depart from them.',
   11, 417, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-000000000106',
   'Batches, Epochs and Normalisation',
   'markdown',
   'A few mechanical choices determine whether training works, and they are easy to get wrong in ways that look like a modelling problem.

## Batch size

The number of examples processed before each weight update.

- **Small batches** (8-64): noisier gradients, which acts as regularisation and often generalises better. Slower per epoch.
- **Large batches** (256-4096): smoother gradients, far better GPU utilisation, and a tendency to converge to sharper minima that generalise slightly worse. Usually needs a higher learning rate to compensate.

In practice: use the largest batch that fits in memory, then tune the learning rate for it. If you double the batch size, scale the learning rate up as a starting point.

## Epochs, and stopping

An epoch is one pass through the training data. The right number is not a number you pick - it is where validation loss stops improving.

```python
best, patience, waited = float(''inf''), 5, 0
for epoch in range(200):
    train_one_epoch(model, train_loader)
    val_loss = evaluate(model, val_loader)
    if val_loss < best:
        best, waited = val_loss, 0
        torch.save(model.state_dict(), ''best.pt'')
    else:
        waited += 1
        if waited >= patience:
            break
```

Early stopping with checkpointing: keep the weights from the best epoch, not the last. Training past the turn does not just waste time, it actively makes the model worse, and the final weights are the worst ones you kept.

## Normalise the input

Neural networks expect inputs on a similar scale. A column in the thousands next to one in fractions makes the loss surface a ravine, and gradient descent oscillates across it instead of travelling along it.

```python
# Fit on training data only, exactly as in the machine learning course.
mean, std = X_train.mean(0), X_train.std(0) + 1e-8
X_train = (X_train - mean) / std
X_val = (X_val - mean) / std
```

For images, divide by 255 and then normalise by the channel statistics of the dataset the model was pretrained on. Skipping this is the single most common reason a network fails to learn, and it produces a flat loss curve that looks like a bug anywhere else.

## Normalisation layers

**Batch normalisation** normalises activations using statistics from the batch. It made deep networks trainable and is still standard in convolutional models. It behaves differently in training and evaluation, which is why forgetting `model.eval()` changes your results.

**Layer normalisation** normalises across features within each example, independent of batch size. It is what transformers use, and it is the better choice for sequences and for small batches.

## Shuffle, and check the labels

```python
loader = DataLoader(dataset, batch_size=64, shuffle=True)
```

Unshuffled data sorted by class means a batch of all-one-class, which produces nonsense gradients. And print one batch of inputs with their labels before training anything - misaligned labels are far more common than anybody admits, and they look exactly like a model that will not learn.',
   'Three knobs that decide whether training is fast, stable and finishes in the right place - plus the input normalisation that is the most common reason a network does not learn at all.',
   11, 472, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-000000000107',
   'Stopping a Network Memorising',
   'markdown',
   'A network with more parameters than training examples can memorise them exactly. It will reach zero training loss and be useless on anything new.

## The signal

```
epoch 10   train 0.42   val 0.45
epoch 30   train 0.18   val 0.31
epoch 60   train 0.03   val 0.48   <- the turn was around epoch 30
```

Validation loss falling then rising while training loss keeps falling. That turn is the moment the model stopped generalising and started memorising.

## Dropout

```python
model = nn.Sequential(
    nn.Linear(100, 256), nn.ReLU(), nn.Dropout(0.3),
    nn.Linear(256, 64),  nn.ReLU(), nn.Dropout(0.3),
    nn.Linear(64, 1),
)
```

During training, each neuron is zeroed with probability p for each example. The network cannot rely on any single neuron, so it spreads the representation - an averaging effect over many thinned networks.

0.1 to 0.5 is the usual range. It is disabled automatically at evaluation time, which is what `model.eval()` does, and forgetting that call gives you randomly worse predictions in production.

## Weight decay

```python
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=0.01)
```

A penalty on large weights, which is the same regularisation idea as ridge regression. Cheap, nearly always helpful, and the first thing to turn up when a model overfits.

## Data augmentation

The most effective regulariser when it applies: generate more training data by transforming what you have.

For images, random crops, flips and colour jitter. For audio, time shifts and noise. For text, it is harder and often harmful - a synonym substitution can invert the meaning of a sentence.

Augmentation must preserve the label. Flipping a photograph of a dog horizontally still shows a dog; flipping a photograph of the digit 2 does not show a 2.

## Early stopping

Already covered, and it is the one you should never skip. It is free and it directly targets the symptom.

## More data

Worth saying plainly: more real data beats every technique above. When the choice is between a week of tuning regularisation and a week of labelling, labelling usually wins.

## The order to apply them

1. Early stopping - always, from the first run.
2. Weight decay - cheap, nearly always helps.
3. Augmentation - if your data type supports it.
4. Dropout - tune the rate.
5. A smaller model - frequently overlooked, and if the dataset is small it is the honest answer.',
   'A model with a million parameters can memorise ten thousand examples perfectly. Dropout, weight decay, augmentation and early stopping are the four tools that prevent it, and they work in different ways and combine.',
   11, 386, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-000000000109',
   'Convolutional Networks, and Why They Suit Images',
   'markdown',
   'A fully connected layer on a 224x224 colour image would need about 150,000 weights per neuron, and it would have to learn separately what an edge looks like in every position. Convolution fixes both problems with one idea.

## What a convolution does

A small filter - typically 3x3 - slides across the image. At each position it computes a weighted sum of the pixels under it. The same weights are used at every position.

Two consequences, and they are the whole reason this works:

- **Parameter sharing.** One 3x3 filter is 9 weights that detect their pattern anywhere in the image, instead of relearning it per location.
- **Locality.** Each output depends only on a small neighbourhood, which matches how images are actually structured - nearby pixels are related, distant ones usually are not.

```python
from torch import nn

model = nn.Sequential(
    nn.Conv2d(3, 32, kernel_size=3, padding=1), nn.ReLU(),
    nn.MaxPool2d(2),
    nn.Conv2d(32, 64, kernel_size=3, padding=1), nn.ReLU(),
    nn.MaxPool2d(2),
    nn.Flatten(),
    nn.Linear(64 * 56 * 56, 10),
)
```

## The hierarchy

Stacked convolutions build up abstraction, and this is visible if you look at the learned filters: the first layer finds edges and colour gradients, the second corners and textures, the third parts of objects, the fourth objects.

Pooling reduces the spatial size as you go, which widens the area each later neuron sees while keeping the computation manageable.

## The pieces you will see

- **Padding** keeps the output the same size as the input, so stacking does not shrink everything to nothing.
- **Stride** moves the filter more than one pixel at a time, downsampling as it convolves.
- **Channels** are the number of filters in a layer - 32 filters means 32 different patterns detected.
- **Residual connections** add a layer''s input to its output, which lets gradients flow directly through very deep stacks. This is what made 50- and 100-layer networks trainable, and it is the central idea in ResNet.

## Where else convolution applies

Anywhere the input has a grid structure and translation invariance: spectrograms for audio, one-dimensional convolution over time series, and board positions in game playing.

It does not apply to tabular data, where column 3 and column 4 have no spatial relationship at all - which is one concrete reason neural networks underperform on spreadsheets.

## In practice, you will not train one from scratch

For almost any image task, a pretrained backbone fine-tuned on your data beats a network trained from scratch, by a wide margin, with a fraction of the data. That is Level 4, and it is how this is actually done.',
   'A convolution slides a small learned filter across an image, which builds in two assumptions: that a pattern means the same thing anywhere, and that nearby pixels are related. Those assumptions are why a convolutional network needs far less data than a fully connected one.',
   11, 429, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-00000000010a',
   'Sequences: Recurrence and Its Limits',
   'markdown',
   'A sequence has order and variable length. A fixed-size input layer cannot represent that, so recurrent networks process one element at a time, carrying a hidden state forward.

```
hidden = f(hidden, input_t)
```

The same weights at every step. The hidden state is the model''s memory of everything so far.

## LSTM and GRU

A plain recurrent network forgets quickly: the gradient has to flow back through every step, and multiplying small numbers many times drives it to zero. Information from thirty steps ago has no path to influence the update.

LSTMs added gates - learned decisions about what to keep, what to forget and what to output - giving gradients a more direct route backwards. GRUs are a simpler variant with similar performance. Both were the standard for sequence work for years, and both are still reasonable for modest-length series.

## The two problems that ended their dominance

**1. They cannot be parallelised across time.** Step 50 needs the hidden state from step 49. Training is inherently sequential, which does not use a GPU well and puts a hard ceiling on how much data you can train on.

**2. Long-range dependencies remain hard.** Gates help, but a word 500 tokens back still has to survive 500 updates to a fixed-size state. In practice information fades.

Both were tolerated until an architecture appeared without either, which is the next lesson.

## Where recurrence is still fine

Short sequences, small models, and settings where you want streaming inference - a recurrent model consumes one step at a time naturally, where a transformer wants the window. For a sensor time series of a few hundred steps, a GRU is small, fast and entirely adequate.

## Sequence tasks have shapes

- **Many to one**: a sentence to a sentiment. Take the final hidden state.
- **Many to many, aligned**: tag every word. One output per step.
- **Many to many, unaligned**: translation. Encoder, then decoder - and the bottleneck between them is exactly what attention was invented to fix.

## Teacher forcing, and the gap it creates

When training a model that generates a sequence, you feed it the true previous token rather than its own prediction, which makes training stable. At inference it has to consume its own output, so one early mistake compounds - the model has never practised recovering from its own errors. This exposure gap is still a live issue in generation, including in the models in the next course.',
   'Text, speech and time series have order. Recurrent networks process them one step at a time, carrying a hidden state - an elegant idea with two fatal problems that explain exactly why the field moved to attention.',
   11, 412, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-00000000010b',
   'Attention and the Transformer',
   'markdown',
   'Attention answers one question: when processing this element, which other elements matter, and how much?

## The mechanism, in words

Every position produces three vectors - a query, a key and a value. To compute the output at one position, compare its query against every key to get a score, turn the scores into weights with softmax, and take the weighted sum of the values.

```
attention(Q, K, V) = softmax(Q Kt / sqrt(d)) V
```

The scaling by the square root of the dimension stops the scores growing so large that softmax saturates into a one-hot vector with no useful gradient.

That is the whole mechanism. Everything else in a transformer is plumbing around it.

## Why it replaced recurrence

**Every position reaches every other in one step.** The distance between two words is irrelevant - 500 tokens apart costs the same as adjacent.

**It parallelises.** Every position is computed at once, which uses a GPU properly. This is the practical reason transformers scaled and recurrent models did not.

The cost is that attention is quadratic in sequence length: double the context, quadruple the computation. That is why context windows were small for years and why so much research targets exactly this.

## The rest of a transformer block

- **Multi-head attention** - several attention operations in parallel with different learned projections, so one head can track syntax while another tracks reference.
- **Positional encoding** - attention is order-blind on its own, so position information is added to the inputs. Without it, a sentence and its shuffle are identical to the model.
- **A feed-forward network** per position, applied identically everywhere.
- **Residual connections and layer normalisation** around each sub-layer, for the same reason as in deep convolutional networks.

Stack that block N times and you have a transformer.

## The three shapes

- **Encoder only** (BERT-style): sees the whole input at once. For classification, retrieval and embeddings.
- **Decoder only** (GPT-style): each position attends only to earlier ones, so it can be trained to predict the next token. Every large language model you have used.
- **Encoder-decoder** (T5-style): for translation and summarisation, where input and output are different sequences.

## Why this is the last architecture lesson

The same block works for text, images (as patches), audio and video. A single architecture absorbed fields that each had their own specialised models, and scaling it up turned out to keep working - which is the entire premise of the generative AI course that follows this one.',
   'Attention lets every position look directly at every other and decide what matters, with no sequential bottleneck. It is the idea behind every large language model, and it is simpler than its reputation.',
   12, 417, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-00000000010d',
   'Transfer Learning: How Models Are Really Trained',
   'markdown',
   'Training from scratch needs an enormous dataset and a lot of compute. Almost nobody does it, and you should not either.

## The idea

A model trained on millions of images has learned edges, textures, shapes and parts. Those are useful for almost any image task. Only the last layers are specific to the original classes.

So: take the pretrained model, replace the final layer with one for your classes, and train on your data.

```python
import torch
from torchvision import models

model = models.resnet50(weights=''IMAGENET1K_V2'')

for param in model.parameters():
    param.requires_grad = False        # freeze the learned representation

model.fc = torch.nn.Linear(model.fc.in_features, num_classes)  # a new head
# only model.fc has requires_grad=True now
```

With a few hundred labelled images this will beat anything you could train from scratch with ten thousand.

## Freeze, or fine-tune

**Freeze everything but the head** when your data is small or very similar to the original training data. Fast, little risk of overfitting, works surprisingly often.

**Unfreeze the later layers too** when your domain differs - medical scans, satellite imagery, industrial defects. The early layers still transfer; the later, more specific ones need to change.

**Fine-tune everything** with a very small learning rate when you have substantial data. Use a rate roughly ten times smaller than you would for a new model: large steps will destroy the pretrained weights before they adapt, which is called catastrophic forgetting and looks like a model that was fine and then suddenly was not.

## Discriminative learning rates

```python
optimizer = torch.optim.AdamW([
    {''params'': model.layer4.parameters(), ''lr'': 1e-4},
    {''params'': model.fc.parameters(),     ''lr'': 1e-3},
])
```

Later layers learn faster, earlier ones barely move. This is the standard recipe and it is better than one rate for everything.

## For text

The same pattern with a pretrained language model: load it, add a classification head, fine-tune on a few thousand labelled examples. Parameter-efficient methods such as LoRA go further - freeze the whole model and train a small number of additional parameters - which is how fine-tuning a very large model becomes possible on one GPU.

## The practical warning

Check what the pretrained model was trained on. It carries that data''s biases, its blind spots and its licence. A model trained on web images reproduces what is over- and under-represented there, and you inherit all of it along with the useful features.',
   'Almost nobody trains from scratch. You take a model that has already learned general representations from an enormous dataset and adapt it to your task with a fraction of the data - and which layers you unfreeze is the main decision.',
   11, 389, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-00000000010e',
   'Serving a Model Without Setting Money on Fire',
   'markdown',
   'Training happens once a month. Inference happens on every request, and that is where the cost and the failures live.

## Make it smaller before you make it faster

- **Quantisation**: store weights in 8-bit integers rather than 32-bit floats. Roughly four times smaller, substantially faster, usually a fraction of a point of accuracy. Nearly always worth it.
- **Distillation**: train a small model to reproduce the large one''s outputs. More work, and it can be dramatically smaller.
- **Pruning**: remove weights near zero. Most effective with structure, so the hardware can actually skip them.

Start with quantisation. It is a few lines and it often removes the need for everything else.

## Batching, and the latency it costs

A GPU is far more efficient on 32 requests at once than on one. Dynamic batching - wait a few milliseconds to collect a batch - multiplies throughput several times over.

The cost is latency for the first request in each batch. That is the trade: pick the window from the latency budget, not from the throughput target.

## Export rather than ship Python

```python
scripted = torch.jit.trace(model.eval(), example_input)
scripted.save(''model.pt'')
```

Or export to ONNX. Either gives you an artefact that runs without your training code, in a runtime designed for serving. It also freezes the preprocessing, which is the usual source of a mismatch between evaluation and production.

## Version everything together

A model artefact is useless without the exact preprocessing that produced its inputs. Ship them as one versioned unit - model weights, preprocessing, label mapping, framework version - and record the version with every prediction.

## Monitor the inputs, not just the outputs

The failure that matters is receiving inputs unlike anything in training: a new camera, a different microphone, a language the model never saw. The prediction confidence usually drops, so track the distribution of maximum softmax probability over time. A shift there is the earliest warning you get.

## Keep a path back

```
model_version: 2026-03-01-a   (previous: 2026-02-01-c, still loadable)
```

Roll back before debugging. A deployment that cannot be reversed in one step is a deployment that will be live while you investigate.

## The question to ask first

Does this need a GPU in the request path at all? Precomputing predictions nightly, caching embeddings, or running a small model on CPU solves a surprising number of problems at a fraction of the cost. GPU inference is the expensive answer and it should be the second thing you try.',
   'Training is a project; serving is a service. Latency, batching, quantisation, versioning and the monitoring that tells you the model has quietly started receiving inputs it has never seen.',
   11, 414, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY)),

  ('e0000001-0000-4000-8000-00000000010f',
   'What Deep Learning Actually Costs',
   'markdown',
   'The costs of a deep learning project are real, usually underestimated, and worth writing down before the project starts rather than after.

## Compute

Training a large model from scratch costs serious money and takes days to weeks on multiple GPUs. Fine-tuning costs orders of magnitude less, which is one more reason it is the default.

Inference is the cost that recurs. A model answering a million requests a day costs more over a year than training it did, and that cost is proportional to traffic - so a successful product makes it worse.

## Data, which is the real expense

Labelling is almost always the largest cost in a supervised project, and it is the one nobody budgets. Ten thousand labelled examples at thirty seconds each is 80 hours of someone''s attention, and that assumes the labels are unambiguous.

Label quality sets a ceiling on model quality. Two annotators who disagree 15% of the time have defined a task the model cannot exceed 85% on, and measuring that agreement before training is one of the highest-value hours available.

## Carbon

Training large models uses a lot of electricity. It is worth knowing the number, choosing a region with cleaner power when you have the choice, and not retraining on a schedule when nothing changed.

The honest framing: a fine-tuned small model that is good enough has a tiny fraction of the footprint of training something large to be slightly better.

## Failure modes that only appear with users

**Adversarial inputs.** Small, deliberate perturbations change a prediction completely. Mostly relevant where someone has an incentive - fraud, moderation, access.

**Distribution shift that is a person, not an accident.** Users adapt to a model. Spam adapts to a spam filter.

**Confident nonsense.** A neural network is confident outside its training distribution and has no mechanism for saying "I have not seen anything like this". That property is dangerous wherever the output is acted on automatically, and it is the single most important thing to design around.

**Feedback loops.** A recommender trained on what it recommended narrows over time, and the data stops being a sample of what people like and becomes a record of what they were shown.

## The decision to write down

Before starting:

- what it costs to build, including labelling;
- what it costs per month to serve at expected traffic;
- what the baseline already achieves;
- what happens when it is wrong, and who it happens to;
- how you will know it has stopped working.

A project that cannot answer those five is not ready to start, and answering them honestly cancels some projects - which is the point.',
   'Compute, data, carbon and the failures that only appear with real users. Stating these before a project starts is the difference between a considered decision and a sunk cost nobody wants to admit to.',
   11, 445, '55555555-5555-4555-8555-555555555555', 'published',
   DATE_SUB(UTC_TIMESTAMP(3), INTERVAL 2 DAY))
ON DUPLICATE KEY UPDATE
  title = VALUES(title), body = VALUES(body), excerpt = VALUES(excerpt),
  reading_time_minutes = VALUES(reading_time_minutes), word_count = VALUES(word_count),
  status = VALUES(status);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-000000000013');
CALL search_reindex_all_quiet();
