-- =========================================================================
-- Seed 38 : quizzes for Deep Learning
--
-- One per level, the last one an exam over the whole course. Generated by
-- the shared builder, which refuses to emit a single_choice without exactly
-- one correct option, or a multiple_choice with fewer than two.
-- =========================================================================

INSERT INTO assessment_quizzes
  (id, course_id, lesson_id, title, description, pass_percent, time_limit_seconds,
   max_attempts, shuffle_questions, shuffle_options, show_answers, status)
VALUES
  ('f0000001-0000-4000-8000-000000000040',
   'c0000001-0000-4000-8000-000000000013', 'e0000001-0000-4000-8000-000000000104',
   'Level 1 Check: Neurons, Gradients and Fit',
   'Activation functions, the training loop, the learning rate, and when not to use a neural network.',
   60, 600, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000041',
   'c0000001-0000-4000-8000-000000000013', 'e0000001-0000-4000-8000-000000000108',
   'Level 2 Check: Training That Works',
   'Losses and optimisers, batch size, normalisation, and reading the curve.',
   60, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000042',
   'c0000001-0000-4000-8000-000000000013', 'e0000001-0000-4000-8000-00000000010c',
   'Level 3 Check: Architectures',
   'Convolution, recurrence, attention, and the assumptions each one makes about its input.',
   70, 720, NULL, 0, 1, 1, 'published'),

  ('f0000001-0000-4000-8000-000000000043',
   'c0000001-0000-4000-8000-000000000013', 'e0000001-0000-4000-8000-000000000110',
   'Expert Exam: Deep Learning',
   'Transfer learning, serving cost, confident nonsense, and what to answer before starting.',
   70, 1500, 3, 1, 1, 1, 'published')
ON DUPLICATE KEY UPDATE
  title = VALUES(title), description = VALUES(description),
  pass_percent = VALUES(pass_percent), status = VALUES(status);

INSERT INTO assessment_questions
  (id, quiz_id, kind, prompt, explanation, points, `position`, correct_text)
VALUES
  -- Level 1 Check: Neurons, Gradients and Fit
  ('a1000001-0000-4000-8000-000000000391', 'f0000001-0000-4000-8000-000000000040', 'single_choice',
   'Why does a network need a non-linear activation function between layers?',
   'Without one, every layer is a weighted sum, and a stack of weighted sums collapses algebraically into a single weighted sum. A hundred layers would be exactly equivalent to one, so depth would buy nothing.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-000000000392', 'f0000001-0000-4000-8000-000000000040', 'single_choice',
   'Your loss becomes NaN after a few batches. What is the first thing to try?',
   'Lower the learning rate, typically by a factor of ten. Steps that overshoot produce exploding values; it is the most common cause by a wide margin, and the cheapest to test.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-000000000393', 'f0000001-0000-4000-8000-000000000040', 'single_choice',
   'What goes wrong if you forget optimizer.zero_grad() in a PyTorch training loop?',
   'Gradients accumulate across batches rather than being replaced, so each step is based on the sum of all previous batches. The updates grow and training diverges - a bug that looks like an unstable model.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-000000000394', 'f0000001-0000-4000-8000-000000000040', 'single_choice',
   'You have 50,000 rows of customer data in a table and want to predict churn. What should you try before a neural network?',
   'Gradient boosting. On tabular data it usually matches or beats a neural network, trains in seconds on a laptop, needs no GPU and far less tuning. The columns are already features, so there is little representation left to learn.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-000000000395', 'f0000001-0000-4000-8000-000000000040', 'multiple_choice',
   'Which inputs are deep learning genuinely the right tool for? Select all that apply.',
   'Images, audio and text all have structure nobody can write down as features, which is exactly what representation learning provides. A table of numeric columns already has its features chosen by whoever designed the schema.',
   2, 5, NULL),

  -- Level 2 Check: Training That Works
  ('a1000001-0000-4000-8000-000000000396', 'f0000001-0000-4000-8000-000000000041', 'single_choice',
   'Training loss keeps falling while validation loss has been rising for ten epochs. What should you do?',
   'Stop, and use the weights from the epoch where validation loss was lowest. Training past the turn actively makes the model worse, and the final weights are the worst ones you have kept.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-000000000397', 'f0000001-0000-4000-8000-000000000041', 'single_choice',
   'Your loss is completely flat from the first epoch. Which cause is most likely?',
   'Unnormalised inputs, a learning rate far too low, or labels that do not line up with the inputs. A flat curve from the start means no learning signal is reaching the weights at all - check that one batch of inputs matches its labels before anything else.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-000000000398', 'f0000001-0000-4000-8000-000000000041', 'single_choice',
   'Why use BCEWithLogitsLoss rather than a sigmoid followed by BCELoss?',
   'Combining them is numerically stable. Applying sigmoid separately and then taking a logarithm can underflow for confident predictions, which produces NaN - a well-known and entirely avoidable source of failed training runs.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-000000000399', 'f0000001-0000-4000-8000-000000000041', 'single_choice',
   'What does forgetting model.eval() before inference change?',
   'Dropout stays active and batch normalisation keeps using batch statistics instead of the running averages, so predictions become random and batch-dependent. The model has not changed; the mode has.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-00000000039a', 'f0000001-0000-4000-8000-000000000041', 'multiple_choice',
   'Which of these reduce overfitting? Select all that apply.',
   'Dropout, weight decay, augmentation and early stopping all work, by different mechanisms. Increasing model capacity does the opposite - a larger model memorises a small dataset more easily.',
   2, 5, NULL),

  -- Level 3 Check: Architectures
  ('a1000001-0000-4000-8000-00000000039b', 'f0000001-0000-4000-8000-000000000042', 'single_choice',
   'What does parameter sharing in a convolution buy you?',
   'One filter detects its pattern anywhere in the image, instead of the network having to learn the same edge detector separately at every position. That is why a convolutional network needs far fewer parameters and far less data than a fully connected one on images.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-00000000039c', 'f0000001-0000-4000-8000-000000000042', 'multiple_choice',
   'Which problems with recurrent networks did the transformer solve? Select all that apply.',
   'Recurrence is sequential, so it cannot be parallelised across time, and information from far back has to survive many updates to a fixed-size state. Attention connects every position to every other in one step and computes them all at once.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-00000000039d', 'f0000001-0000-4000-8000-000000000042', 'single_choice',
   'Why does a transformer need positional encoding?',
   'Attention computes weighted sums over all positions with no notion of order, so without position information a sentence and any shuffle of it are identical to the model. The encoding is added to the inputs to restore it.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-00000000039e', 'f0000001-0000-4000-8000-000000000042', 'single_choice',
   'What is the main computational cost of self-attention?',
   'It is quadratic in sequence length: every position attends to every other, so doubling the context quadruples the work. This is why context windows were limited for years and why so much research targets exactly this.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-00000000039f', 'f0000001-0000-4000-8000-000000000042', 'single_choice',
   'Which architecture shape suits producing a sentence embedding for search?',
   'Encoder only, such as BERT. It sees the whole input at once in both directions, which is what you want for representing a complete text. Decoder-only models are trained to predict the next token, which is a different objective.',
   2, 5, NULL),

  -- Expert Exam: Deep Learning
  ('a1000001-0000-4000-8000-0000000003a0', 'f0000001-0000-4000-8000-000000000043', 'single_choice',
   'Why fine-tune a pretrained model with a much smaller learning rate than you would use to train from scratch?',
   'Large steps overwrite the pretrained representation before it can adapt - catastrophic forgetting. A rate around ten times smaller lets the weights adjust while keeping what they already encode.',
   2, 1, NULL),

  ('a1000001-0000-4000-8000-0000000003a1', 'f0000001-0000-4000-8000-000000000043', 'single_choice',
   'You have 400 labelled images of an industrial defect. What is the right approach?',
   'Fine-tune a pretrained backbone. Four hundred images cannot train a network from scratch, but the early layers of a model trained on millions of images already encode edges and textures that transfer directly.',
   2, 2, NULL),

  ('a1000001-0000-4000-8000-0000000003a2', 'f0000001-0000-4000-8000-000000000043', 'single_choice',
   'Which cost usually dominates a successful deployed model over a year?',
   'Inference. It recurs on every request and scales with traffic, so success makes it worse. Training is a one-off and labelling, while often the largest build cost, does not repeat in the same way.',
   2, 3, NULL),

  ('a1000001-0000-4000-8000-0000000003a3', 'f0000001-0000-4000-8000-000000000043', 'single_choice',
   'Why is a neural network dangerous when it receives an input unlike anything in its training data?',
   'It produces a confident output anyway. There is no built-in mechanism for abstaining, so a prediction acted on automatically is acted on with no signal that the model is outside what it knows.',
   2, 4, NULL),

  ('a1000001-0000-4000-8000-0000000003a4', 'f0000001-0000-4000-8000-000000000043', 'single_choice',
   'Two annotators disagree on 15% of your labels. What does that imply?',
   'The task as defined has a ceiling around 85%, because the labels themselves do not agree. Measuring annotator agreement before training is one of the highest-value hours in a supervised project, and it often sends you back to the definition.',
   2, 5, NULL),

  ('a1000001-0000-4000-8000-0000000003a5', 'f0000001-0000-4000-8000-000000000043', 'single_choice',
   'What does quantising a model to 8-bit integers typically achieve?',
   'Roughly four times smaller and substantially faster, for a fraction of a point of accuracy. It is a few lines of code and is usually the first optimisation worth making - often removing the need for distillation or pruning entirely.',
   2, 6, NULL)
ON DUPLICATE KEY UPDATE
  prompt = VALUES(prompt), explanation = VALUES(explanation), points = VALUES(points);

-- Options are inserted rather than replaced, for the reason seed 14 gives:
-- deleting and re-inserting them would orphan every answer already recorded
-- against them, and a graded attempt whose answers point at nothing is a
-- review that resolves nothing.
INSERT INTO assessment_question_options (question_id, body, is_correct, `position`)
SELECT v.question_id, v.body, v.is_correct, v.pos
  FROM (
    SELECT 'a1000001-0000-4000-8000-000000000391' AS question_id, 'Without it, stacked layers collapse into one linear layer' AS body, 1 AS is_correct, 1 AS pos
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000391', 'It keeps the outputs between 0 and 1', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000391', 'It speeds up backpropagation', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000391', 'It prevents the weights becoming negative', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000392', 'Reduce the learning rate', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000392', 'Increase the batch size', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000392', 'Add more layers', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000392', 'Train for more epochs', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000393', 'Gradients accumulate across batches and the updates grow', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000393', 'The model trains on the same batch repeatedly', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000393', 'The learning rate is ignored', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000393', 'Nothing; it is called automatically by step()', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000394', 'Gradient boosting', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000394', 'A deeper network with more layers', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000394', 'A convolutional network over the columns', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000394', 'A transformer with the rows as a sequence', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000395', 'Images', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000395', 'Raw audio', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000395', 'Natural language text', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000395', 'A spreadsheet of numeric business metrics', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000396', 'Stop and restore the checkpoint from the best validation epoch', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000396', 'Train longer, since training loss is still improving', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000396', 'Increase the learning rate to escape the local minimum', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000396', 'Add more layers', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000397', 'Inputs were not normalised, or the labels are misaligned', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000397', 'The model is overfitting immediately', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000397', 'The batch size is too large', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000397', 'Dropout is set too low', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000398', 'Combining them is numerically stable and avoids NaN', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000398', 'It is faster because it fuses two operations', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000398', 'BCELoss does not support class weighting', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000398', 'It applies softmax rather than sigmoid', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000399', 'Dropout stays on and batch norm uses batch statistics', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000399', 'Gradients are computed, which is only slower', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000399', 'The weights are reinitialised', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-000000000399', 'Nothing, unless the model has no dropout', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039a', 'Dropout', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039a', 'Weight decay', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039a', 'Data augmentation', 1, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039a', 'Adding more layers and neurons', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039b', 'The same pattern is detected anywhere, with one set of weights', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039b', 'It guarantees the network cannot overfit', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039b', 'It removes the need for an activation function', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039b', 'It makes the network invariant to colour', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039c', 'Training cannot be parallelised across the sequence', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039c', 'Long-range dependencies fade through many update steps', 1, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039c', 'They cannot handle variable-length input', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039c', 'They require the input to be normalised', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039d', 'Attention is order-blind, so position must be supplied explicitly', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039d', 'To keep the attention scores from saturating', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039d', 'To reduce the quadratic cost of attention', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039d', 'Because layer normalisation removes positional information', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039e', 'It is quadratic in the sequence length', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039e', 'It is linear in the number of layers', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039e', 'It cannot be computed on a GPU', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039e', 'It requires storing every previous hidden state', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039f', 'Encoder only', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039f', 'Decoder only', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039f', 'Encoder-decoder', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-00000000039f', 'A recurrent network with attention', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a0', 'Large steps destroy the pretrained weights before they adapt', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a0', 'Pretrained models converge faster, so less movement is needed', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a0', 'Smaller rates prevent overfitting entirely', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a0', 'The optimiser requires it after loading saved weights', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a1', 'Fine-tune a pretrained model, freezing most of it', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a1', 'Train a convolutional network from scratch with heavy augmentation', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a1', 'Use a transformer, which needs less data', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a1', 'Collect 400 more images and then train from scratch', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a2', 'Serving the model at production traffic', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a2', 'The original training run', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a2', 'Storing the model artefacts', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a2', 'Hyperparameter search', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a3', 'It is confidently wrong, with no mechanism to abstain', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a3', 'It raises an error that must be handled', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a3', 'It falls back to the majority class', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a3', 'Its latency increases noticeably', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a4', 'Model accuracy is capped near 85% until the task is defined better', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a4', 'The model should be trained on the majority label and will exceed 85%', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a4', 'The dataset is too small', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a4', 'Agreement does not affect achievable accuracy', 0, 4
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a5', 'About four times smaller and faster, for a small accuracy cost', 1, 1
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a5', 'The same size but faster, with no accuracy change', 0, 2
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a5', 'Smaller, but only usable on a GPU', 0, 3
    UNION ALL SELECT 'a1000001-0000-4000-8000-0000000003a5', 'Better accuracy through implicit regularisation', 0, 4
  ) v
ON DUPLICATE KEY UPDATE
  body = VALUES(body), is_correct = VALUES(is_correct);

CALL catalog_refresh_course_rollup('c0000001-0000-4000-8000-000000000013');
CALL search_reindex_all_quiet();
