#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Builds dist/install.sql - every migration and seed concatenated in order,
# for hosts where you import a file through a control panel instead of running
# scripts/migrate.sh over SSH.
#
# The output is generated, not committed: it would go stale the moment a
# migration or seed changed. Run this, import the result, throw it away.
#
#   ./scripts/build-install-sql.sh
#
# It deliberately does NOT create the database. On shared hosting you make that
# in the control panel and import into it, which is the whole reason the schema
# stopped naming it.
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="dist/install.sql"
mkdir -p dist

{
  cat <<'HEADER'
-- ===========================================================================
-- learning_db : complete install
--
-- Every migration then every seed, in the order scripts/migrate.sh and
-- scripts/seed.sh would apply them. Generated by scripts/build-install-sql.sh
-- - do not edit this file, edit the sources and regenerate.
--
-- HOW TO IMPORT
--
--   Create the database first, in your host's control panel. This file does
--   not create one, because shared hosting does not let it: the database
--   arrives with an account prefix (yourcpaneluser_learning) and the name
--   belongs in your connection string, nowhere else.
--
--   phpMyAdmin : select the database, Import, choose this file, Go.
--   SSH        : mysql -u USER -p DATABASE < install.sql
--
--   If phpMyAdmin rejects the file for size, use SSH, or ask your host to
--   raise upload_max_filesize. Splitting this file by hand will break it -
--   the stored routines below span many lines between DELIMITER markers.
--
-- WHAT YOU GET
--
--   The whole schema, and every course in seeds/, plus one demo learner.
--
--   There used to be exact counts here - "10 courses, 227 searchable
--   documents". They were written by hand and were five courses out of date
--   by the time anyone noticed. A count that cannot be derived from the
--   sources does not belong in a generated file; the seed list below is the
--   answer, and it cannot go stale.
--
--   The last statements record every migration as applied, so running
--   scripts/migrate.sh later against this database is correctly a no-op
--   rather than an attempt to create everything twice.
--
-- RE-IMPORTING, AND WHAT THIS FILE DELETES
--
--   This file makes the database BE the learning platform, whatever state it
--   was in before. It drops every table, view, routine and trigger it is
--   about to create, then creates them, then seeds them. So an import that
--   failed halfway - which leaves a database full of half-made tables - is
--   fixed by importing this file again. Nothing has to be dropped by hand.
--
--   That also means it DELETES whatever those tables held. Enrolments, quiz
--   attempts, progress, registered accounts: gone, replaced by the seeds.
--
--   To ADD COURSES to a database you are keeping, this is the wrong file.
--   Use content.sql - it inserts and updates only, and never drops anything.
--
--   One thing stops this file: an account that did not come from the seeds.
--   Every seeded account is @learning.test, so a single real registration is
--   enough for the check at the top to refuse the import and leave the
--   database untouched, saying so in words.
--
-- A NOTE ON PHPMYADMIN'S "STATIC ANALYSIS" WARNINGS
--
--   phpMyAdmin reports "Unrecognized statement type (near DECLARE)" for every
--   stored routine in this file. Its parser does not follow DELIMITER into a
--   BEGIN ... END body. The warnings are advisory - it hands the statements to
--   MySQL anyway, and MySQL parses them correctly. Ignore them; only messages
--   prefixed "MySQL said" are real.
-- ===========================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET sql_mode = 'STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

HEADER

  # Stop, in words, if a real person has an account in this database.
  #
  # The older version of this check refused any database that still had
  # tables. It was well meant and it was wrong: the state somebody is most
  # often in when they import this file is "the last import failed and left a
  # mess", and refusing that made the file unable to fix the one problem it
  # was most needed for. The drops below deal with the mess; this check is
  # left to do the only thing that actually matters, which is to not delete a
  # database that has real learners in it.
  #
  # Every account the seeds create is @learning.test. One address that is not
  # is somebody who registered through the site, and that is a database this
  # file must not touch.
  #
  # MESSAGE_TEXT is capped at 128 characters. MySQL 8 rejects a longer one
  # outright - "ERROR 1648: Data too long for condition item 'MESSAGE_TEXT'" -
  # while MariaDB takes it, so this is a limit you can pass locally and fail on
  # the server. Asserted here rather than trusted, because the whole point of
  # the message is to be read by somebody whose import just stopped.
  refusal='install.sql REPLACES this database and it has real accounts in it. To add courses, import content.sql instead.'
  if [ "${#refusal}" -gt 128 ]; then
    echo "error: the refusal message is ${#refusal} characters; SIGNAL allows 128" >&2
    exit 1
  fi

  # Quoted heredoc, and the message substituted afterwards. An unquoted one
  # would expand the DELIMITER $$ markers below into the shell's PID, which
  # produces a file that looks right until MySQL refuses the whole routine.
  cat <<'PRECHECK' | sed "s|__REFUSAL__|$refusal|"

-- ###########################################################################
-- Refuse to run against a database that has real accounts in it.
--
-- If this stops your import, somebody has registered on this site and this
-- file would delete them. To add courses to a database you are keeping,
-- import content.sql instead - it only inserts and updates.
--
-- Nothing has been changed when this message appears: this is the first
-- statement in the file, and it stops everything after it.
-- ###########################################################################

DROP PROCEDURE IF EXISTS install_precheck;

-- identity_users does not exist in an empty database, and a procedure naming
-- a table that is not there fails when it is called - "#1146 table doesn't
-- exist" - rather than passing. So: make sure there is something to look at.
--
-- On any database that has been installed before, this does nothing at all
-- (MySQL answers CREATE TABLE IF NOT EXISTS with a warning and leaves the real
-- table alone). On an empty one it makes a two-column stand-in, which the DROP
-- TABLE block below removes a moment later, before the migrations create the
-- real thing.
--
-- The alternative was a prepared statement inside the procedure. This is
-- duller, and duller is what you want in the first statement of a file that
-- has to run on somebody else's shared hosting.
CREATE TABLE IF NOT EXISTS identity_users (
  id CHAR(36) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELIMITER $$

CREATE PROCEDURE install_precheck()
BEGIN
  DECLARE v_strangers INT DEFAULT 0;

  SELECT COUNT(*) INTO v_strangers
    FROM identity_users
   WHERE email NOT LIKE '%@learning.test';

  -- The long version is the comment above this block: MESSAGE_TEXT stops at
  -- 128 characters, so the detail lives where there is room for it.
  IF v_strangers > 0 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '__REFUSAL__';
  END IF;
END$$

DELIMITER ;

CALL install_precheck();
DROP PROCEDURE install_precheck;
PRECHECK

  # Everything the migrations below create, dropped first, so that importing
  # this file works from any starting state: an empty database, a database
  # this file already installed, or the half-made wreckage of an import that
  # stopped in the middle.
  #
  # All of it is read out of the migrations rather than listed here, because a
  # list written by hand is one object behind the first time somebody adds
  # one. Names are deduplicated: 0011 replaces a procedure 0008 created, so it
  # appears twice.
  #
  # Routines, views and triggers come first and are plain statements, emitted
  # before the first DELIMITER block, so there is no delimiter juggling to get
  # wrong. Triggers die with their tables anyway; they are dropped here too
  # rather than relying on that.
  printf '\n-- ###########################################################################\n'
  printf -- '-- Clear anything already here. See "WHAT THIS FILE DELETES" above.\n'
  printf -- '-- ###########################################################################\n\n'

  grep -hoE '^CREATE PROCEDURE [a-z_]+' migrations/*.sql | awk '{print $3}' | sort -u \
    | while IFS= read -r name; do printf 'DROP PROCEDURE IF EXISTS %s;\n' "$name"; done
  grep -hoE '^CREATE FUNCTION [a-z_]+' migrations/*.sql | awk '{print $3}' | sort -u \
    | while IFS= read -r name; do printf 'DROP FUNCTION IF EXISTS %s;\n' "$name"; done
  grep -hoE '^CREATE TRIGGER [a-z_]+' migrations/*.sql | awk '{print $3}' | sort -u \
    | while IFS= read -r name; do printf 'DROP TRIGGER IF EXISTS %s;\n' "$name"; done
  grep -hoE '^CREATE OR REPLACE .*VIEW [a-z_]+' migrations/*.sql | awk '{print $NF}' | sort -u \
    | while IFS= read -r name; do printf 'DROP VIEW IF EXISTS %s;\n' "$name"; done

  # The tables. FOREIGN_KEY_CHECKS is off around them so the order does not
  # matter - with 32 tables and foreign keys in both directions between the
  # catalogue and progress, any hand-chosen order is a bug waiting for the
  # next migration. It is switched back on immediately afterwards, before a
  # single row is inserted, so every seed below is still checked.
  tables="$(grep -hoE '^CREATE TABLE( IF NOT EXISTS)? [a-z_]+' migrations/*.sql \
    | awk '{print $NF}' | sort -u)"

  if [ -z "$tables" ]; then
    echo "error: no CREATE TABLE found in migrations/ - refusing to write a file that drops nothing" >&2
    exit 1
  fi

  printf '\nSET FOREIGN_KEY_CHECKS = 0;\n'
  printf '%s\n' "$tables" | while IFS= read -r name; do
    printf 'DROP TABLE IF EXISTS %s;\n' "$name"
  done
  printf 'SET FOREIGN_KEY_CHECKS = 1;\n'

  for file in migrations/*.sql; do
    printf '\n-- ###########################################################################\n'
    printf -- '-- migration: %s\n' "$(basename "$file")"
    printf -- '-- ###########################################################################\n\n'
    cat "$file"
  done

  for file in seeds/*.sql; do
    printf '\n-- ###########################################################################\n'
    printf -- '-- seed: %s\n' "$(basename "$file")"
    printf -- '-- ###########################################################################\n\n'
    cat "$file"
  done

  # The ledger migrate.sh keeps. Without these rows a later migrate.sh would
  # try to apply all eleven files again against a database that already has
  # them, and fail partway through on the first CREATE TABLE.
  printf '\n-- ###########################################################################\n'
  printf -- '-- Record the migrations as applied, so scripts/migrate.sh is a no-op here.\n'
  printf -- '-- ###########################################################################\n\n'
  printf 'INSERT INTO platform_schema_migrations (filename, checksum) VALUES\n'
  first=1
  for file in migrations/*.sql; do
    name="$(basename "$file")"
    sum="$(sha256sum "$file" | cut -d' ' -f1)"
    [ $first -eq 1 ] && first=0 || printf ',\n'
    printf "  ('%s', '%s')" "$name" "$sum"
  done
  printf '\nON DUPLICATE KEY UPDATE checksum = VALUES(checksum);\n'
} > "$OUT"

lines=$(wc -l < "$OUT")
bytes=$(wc -c < "$OUT")
printf 'wrote %s - %s lines, %.1f KB\n' "$OUT" "$lines" "$(echo "$bytes" | awk '{print $1/1024}')"
