#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Builds dist/install.sql - every migration and seed concatenated in order,
# for hosts where you import a file through a control panel instead of running
# scripts/migrate.sh over SSH.
#
# The output is generated, not committed: it would go stale the moment a
# migration or seed changed. Run this, import the result, throw it away.
#
#   ./scripts/build-install-sql.sh
#
# It deliberately does NOT create the database. On shared hosting you make that
# in the control panel and import into it, which is the whole reason the schema
# stopped naming it.
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="dist/install.sql"
mkdir -p dist

{
  cat <<'HEADER'
-- ===========================================================================
-- learning_db : complete install
--
-- Every migration then every seed, in the order scripts/migrate.sh and
-- scripts/seed.sh would apply them. Generated by scripts/build-install-sql.sh
-- - do not edit this file, edit the sources and regenerate.
--
-- HOW TO IMPORT
--
--   Create the database first, in your host's control panel. This file does
--   not create one, because shared hosting does not let it: the database
--   arrives with an account prefix (yourcpaneluser_learning) and the name
--   belongs in your connection string, nowhere else.
--
--   phpMyAdmin : select the database, Import, choose this file, Go.
--   SSH        : mysql -u USER -p DATABASE < install.sql
--
--   If phpMyAdmin rejects the file for size, use SSH, or ask your host to
--   raise upload_max_filesize. Splitting this file by hand will break it -
--   the stored routines below span many lines between DELIMITER markers.
--
-- WHAT YOU GET
--
--   32 tables, 3 views, 11 stored routines, 13 triggers, and the demo
--   content: 10 courses, 227 searchable documents, one demo learner.
--
--   The last statements record every migration as applied, so running
--   scripts/migrate.sh later against this database is correctly a no-op
--   rather than an attempt to create everything twice.
-- ===========================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET sql_mode = 'STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

HEADER

  for file in migrations/*.sql; do
    printf '\n-- ###########################################################################\n'
    printf -- '-- migration: %s\n' "$(basename "$file")"
    printf -- '-- ###########################################################################\n\n'
    cat "$file"
  done

  for file in seeds/*.sql; do
    printf '\n-- ###########################################################################\n'
    printf -- '-- seed: %s\n' "$(basename "$file")"
    printf -- '-- ###########################################################################\n\n'
    cat "$file"
  done

  # The ledger migrate.sh keeps. Without these rows a later migrate.sh would
  # try to apply all eleven files again against a database that already has
  # them, and fail partway through on the first CREATE TABLE.
  printf '\n-- ###########################################################################\n'
  printf -- '-- Record the migrations as applied, so scripts/migrate.sh is a no-op here.\n'
  printf -- '-- ###########################################################################\n\n'
  printf 'INSERT INTO platform_schema_migrations (filename, checksum) VALUES\n'
  first=1
  for file in migrations/*.sql; do
    name="$(basename "$file")"
    sum="$(sha256sum "$file" | cut -d' ' -f1)"
    [ $first -eq 1 ] && first=0 || printf ',\n'
    printf "  ('%s', '%s')" "$name" "$sum"
  done
  printf '\nON DUPLICATE KEY UPDATE checksum = VALUES(checksum);\n'
} > "$OUT"

lines=$(wc -l < "$OUT")
bytes=$(wc -c < "$OUT")
printf 'wrote %s - %s lines, %.1f KB\n' "$OUT" "$lines" "$(echo "$bytes" | awk '{print $1/1024}')"
